elastic/docs

conf.yaml
Related to https://github.com/elastic/elasticsearch/issues/46718 and https://github.com/elastic/docs/pull/1662
This PR moves the Stack Overview to the "legacy documentation" section of the landing page and sets "noindex" to 1.
=> Moves Stack Overview to legacy documentation

integtest/spec/all_books_spec.rb, lib/ES/Book.pm
If a book is not `live` and is "older" than the current book this
defaults its header to an "end of life" style message.
=> Default to "non-live" header on non-live old books

conf.yaml
This commit updates the Azure Marketplace docs to version 7.5
=> Update Azure Marketplace docs to 7.5

shared/attributes62.asciidoc
There is at least one page where the API reference shared attributes are failing in 6.2 documentation:
https://www.elastic.co/guide/en/elasticsearch/reference/6.2/ml-close-job.html
This PR copies those attributes from https://github.com/elastic/docs/blob/master/shared/attributes.asciidoc to https://github.com/elastic/docs/blob/master/shared/attributes62.asciidoc
=> Adds API reference attributes to older versions

README.asciidoc, resources/web/docs_js/__tests__/prettify/lang-asciidoc.test.js, resources/web/docs_js/index.js, resources/web/docs_js/prettify/lang-asciidoc.js
The syntax highlighter has been doing a terrible job on asciidoc code
for a long time and it ha bothered me. This teaches it to do a little
better. Not perfect at all, but better.
=> Improve prettifier for asciidoc

README.asciidoc, integtest/spec/all_books_spec.rb, package.json, resources/asciidoctor/lib/docbook_compat/convert_example.rb, resources/asciidoctor/spec/docbook_compat_spec.rb, resources/web/docs.js.licenses, resources/web/docs_js/index.js, yarn.lock
This adds support for collapsible examples to our docs. It turns out
that asciidoctor just uses `<details>` and `<summary>` which isn't
supported by all browsers, but we've got a polyfill.
Closes #1279
=> Add support for "collapsible" examples

conf.yaml
This PR updates the conf.yaml such that the Elasticsearch Reference, Installation and Upgrade Guide, and X-Pack Reference are shown as having a dependency on the attributes62.asciidoc file in certain branches.
=> Add attributes62.asciidoc dependency to appropriate books

integtest/spec/single_book_spec.rb, lib/ES/Util.pm
Some of our `index.asciidoc` files are actually `index.x.asciidoc` for
historical reasons. The `.x` filse should always have the same
`-extra-title-page` content so this strips the `.x` from the check for
`-extra-title-page`.
Closes #1689
=> Make extra-title-page ignore `.x` in index

conf.yaml
This PR updates the conf.yaml since the Stack Overview no longer pulls content from the elasticsearch repo.
=> Removes elasticsearch repo from Stack Overview dependencies

conf.yaml
This PR adds the Rust client to the Elasticsearch Clients documentation.
Per Rust crate idioms, the core documentation is hosted on docs.rs, which for the Rust client package is
at https://docs.rs/elasticsearch. The inclusion of the Rust client in the Clients documentation is to provide representation in the official docs and an overview of the client.
=> Add rust client to Elasticsearch clients docs

conf.yaml
**Only for review, please do not merge**
This PR makes the 1.0 branch the current one.
=> Promote ECK 1.0 branch to "current"

shared/api-ref-ex.asciidoc
elastic/elasticsearch#46180 added support for `[source,console]` and `[source,console-result]`, replacing several older 'magic comments' for snippets.
This updates the API Reference template for the new code block attributes.
=> [DOCS] Update snippets in API Reference template

conf.yaml
This PR updates the code examples folder for PHP. Changed in https://github.com/elastic/elasticsearch-php/pull/987.
=> Updated the code examples folder for PHP

shared/versions/stack/7.5.asciidoc
Related to https://github.com/elastic/dev/issues/1353
#DO NOT MERGE UNTIL RELEASE DAY#
=> Doc version bumps for 7.5.2

conf.yaml
Related PR: https://github.com/elastic/stack-docs/pull/807.
Closes https://github.com/elastic/stack-docs/issues/495.
=> Make Google Cloud's Anthos docs legacy

README.asciidoc, resources/asciidoctor/lib/care_admonition/extension.rb, resources/asciidoctor/spec/care_admonition_spec.rb
We add the `experimental::[]` and `beta::[]` macros to document features that are not yet ready for GA. However, these tags don't currently indicate what steps are needed to get a feature to GA.
With these changes, users can include a GitHub issue for the feature in the `experimental::[]` or `beta::[]`. When provided, a concise sentence and link is generated for the issue.
Relates to https://github.com/elastic/elasticsearch/issues/51250
http://test__care-admon-links.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/_beta_experimental_macro_examples.html
=> Add Github link support to beta and experimental macros

shared/attributes.asciidoc
This PR adds two new attributes to `attributes.asciidoc`.
:lang-ident-cap: --> Language identification
:lang-ident:         --> language identification
=> Adds language identification related attributes

README.asciidoc
The old docs for branches were quite out of date. This changes them to
reflect how they work now.
=> Rewrite README about branches

shared/attributes.asciidoc
Adds an attribute for the EQL query guide: https://eql.readthedocs.io/en/latest/index.html
This will be helpful as I add content for https://github.com/elastic/elasticsearch/issues/51057
=> [DOCS] Add attribute for EQL guide

README.asciidoc
There is a known problem when addition or deprecation text includes commas.  This PR updates the readme so that the work-around is easy to find.
=> Describes work-around for deprecation with commas

integtest/spec/helper/console_alternative_examples.rb, resources/asciidoctor/lib/alternative_language_lookup/converter.rb, resources/asciidoctor/lib/alternative_language_lookup/extension.rb, resources/asciidoctor/lib/alternative_language_lookup/listing.rb, resources/asciidoctor/lib/extensions.rb, resources/asciidoctor/spec/alternative_language_lookup_spec.rb
This adds an `<a>` tag above every example listing that could
potentially have alternative languages with `id` set to the hash of the
example. This is useful for the folks writing the alternative language
examples so they can easily see the examples in context.
Closes #1709
=> Add anchor with hash of example

conf.yaml
Updating the conf yaml in preparation for adding docs about the Elastic Logging Plugin for Docker.
PR is here: https://github.com/elastic/beats/pull/15799
Do not merge until after the docs are merged and the CI is clean.
=> Add elastic logging plugin docs

conf.yaml
To be merged after #1704. (Will need to rebase.)
=> Only publish current and older versions for Workplace search.

conf.yaml
The generator and the generated examples have been merged into the `master` branch of the go-elasticsearch client, so this patch removes the extra branch mapping.
=> Update conf.yml for go-elasticsearch

shared/versions55.asciidoc, shared/versions56.asciidoc, shared/versions60.asciidoc, shared/versions61.asciidoc, shared/versions62.asciidoc, shared/versions63.asciidoc, shared/versions64.asciidoc, shared/versions65.asciidoc, shared/versions66.asciidoc, shared/versions67.asciidoc, shared/versions68.asciidoc, shared/versions70.asciidoc, shared/versions71.asciidoc, shared/versions72.asciidoc, shared/versions73.asciidoc, shared/versions74.asciidoc, shared/versions75.asciidoc, shared/versions76.asciidoc
Related to https://github.com/elastic/docs/issues/804
This PR removes old shared version attribute files that are no longer required.
=> Removes old shared files

conf.yaml
This removes the 7.5 branch from the list of "live" Stack release branches in our docs.
With the release of 7.6.0, the 7.5.x versions passed their maintenance date: https://www.elastic.co/support/eol
=> [DOCS] Remove 7.5 from maintained release branches

conf.yaml, doc_build_aliases.sh
This PR fixes the language selector dropdown for the Elasticsearch Service docs. Previously, no selector was shown at all. With a small fix to conf.yaml, the selector now appears as expected:
Before this is ready for review: 
* With the selector enabled, none of the language examples can be found. Need to investigate further to see what's amiss. ~~Possibly related to us needing to map to the `master` branch in the clients-team repo?~~ EDIT: After investigating further, I think this might be because of how the examples in the elastic/cloud repo are written, which will require a separate PR to fix. 
* Added the `master` branch to the ESS doc build for testing; need to remove before merging
Also added an alias for `docbldess`. Unrelated but helpful, since `docbldec` is dates back to the …
=> Fix console selector for ESS client docs

resources/web/style/base_styles.pcss
elastic/docs#1213 added the bootstrap CSS to our built docs. This
inadvertently increased the font size of block quotes by 25%.
This adds a new rule to return the block quote font size to its previous
size.
This was initially raised by @astefan while reviewing https://www.elastic.co/guide/en/elasticsearch/reference/current/sql-client-apps-dbeaver.html
Here's how that page would look after these changes:
http://docs_1735.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/sql-client-apps-dbeaver.html
=> Reduce font size of blockquotes

conf.yaml
I renamed the version branches of `elasticsearch-php` in `7.x`, `6.x`, `5.x`, `2.x` and `1.x`. This to be compliant with the naming convention used by Elasticsearch client.
I didn't remove the old branch names for backward compatibility (e.g. `7.4`, `7.2`, etc). I'll remove these branches when this PR will be merged.
=> Renamed the elasticsearch-php doc branches

shared/attributes.asciidoc
Related to https://github.com/elastic/stack-docs/pull/843
This PR adds shared attributes for the APM agent names.
=> Adds APM agent shared attributes

conf.yaml
Within the docs index page, Enterprise Search (formerly Swiftype)
books are presented under two separate headings (Swiftype and
Enterprise Search). This is misaligned with Elastic's marketing of
these products, which all fall under Enterprise Search now.
Consolidate all Enterprise Search books under the "Enterprise Search"
heading.
Also:
* Re-order the (formerly) Swiftype books
* Update the Workplace Search link text to match the book title
* Remove errant dash in config file
* Remove trailing whitespace in config file
Closes #1739
=> Consolidate Enterprise Search books within index

shared/attributes.asciidoc
We'd like to start collecting some metrics for ESS trial sign-ups from the docs, for which we need a standard attribute. 
Relates to https://github.com/elastic/marketing-ops/issues/7367.
=> Add standard ESS trial attribute

conf.yaml, doc_build_aliases.sh
Update Cloud Docs builds for SaaS to include cloud-assets repo.
=> Add cloud-assets repo to Cloud ESS docs build

conf.yaml, doc_build_aliases.sh
Reverts elastic/docs#1745
We decided against sourcing the regions list in the cloud-assets repo, so this undoes the changes to make that happen.
=> Revert "Add cloud-assets repo to Cloud ESS docs build"

resources/web/style/heading.pcss
Fixes a typo in the CSS that breaks the font-size for h5 headings.
=> Correct CSS for h5 headings

conf.yaml
As we are adding support for more products such as APM, App Search, and in the future Workplace Search as well, a more suitable title seems to be the "Elasticsearch Service - Hosted Elastic Stack"
=> Updated the title of ESS to "Hosted Elastic Stack"

conf.yaml
Adds path for new processors under `x-pack/libbeat/processors/`
=> Add path for new beats processor

conf.yaml
Removes 7.x from the processor exclude.
=> Remove 7.x from libbeat processor exclude

conf.yaml
Alternative example docs are in a new location.
Depends on https://github.com/elastic/elasticsearch-py/pull/1122 landing first.
=> Update elasticsearch-py document path

README.asciidoc
The `rebuild` command doesn't work without the comma.
=> Update rebuild command

conf.yaml
We want to move the folder containing the doc examples for Elastic Cloud in the [clients-team](https://github.com/elastic/clients-team) from the root level to a semantic more appropriated level under [docs](https://github.com/elastic/clients-team/tree/master/docs/examples).
Once we have this change merged, we will remove the old folder to avoid breaking the docs build.
=> Moved the Cloud Doc Examples folder

resources/web/style/admonishment.pcss
PR #1761 set the bottom margin for paragraphs inside admonitions to
zero. This "squishes" all paragraphs within admonitions into a
semi-paragraph.
This tweak sets a zero bottom margin only on the _last_ paragraph
within an admonition. This eliminates unneeded grey space within the
admin without squishing paragraphs.
=> Improve styling for multi-paragraph admonitions

doc_build_aliases.sh
This PR removes a link from the doc_build_aliases.sh to a private repo. The information pertained to the layout of private X-Pack repos and is (1) not pertinent to current releases, and (2) not accessible externally.  Therefore I have removed it.
=> Removes outdated link from doc_build_aliases.sh

shared/attributes.asciidoc
This PR adds the eland docs URL to the shared/attributes.asciidoc file.
=> Adds eland docs URL to shared/attributes

conf.yaml, doc_build_aliases.sh
This PR adds a new repository (`eland-docs`) to the conf.yaml file and a build alias to the `doc_build_alias.sh` file.
Depends on https://github.com/elastic/elasticsearch-eland-docs/pull/4. Please merge that PR first
=> Adds eland-docs repo to conf.yaml and alias to doc_build_aliases.sh 

shared/attributes.asciidoc
Adds an attribute for the 7.x version of the Elasticsearch Reference docs
=> Add attribute for 7.x ES ref docs

README.asciidoc
Updates an example in the README to avoid the `deprecated[...]` syntax.
While it technically works due to some docs build conversions, this syntax
isn't supported in Asciidoctor. We should avoid using it going forward.
=> [DOCS] Fix inconsistent deprecated tag in README

conf.yaml
We changed the path for the example docs in the Ruby client.
=> Changed the path to Ruby doc examples

shared/versions/stack/7.7.asciidoc
This PR adds a shared attribute file to reflect version details in the 7.7 and 7.x branches.
=> Add 7.7 shared versions file

resources/web/style/child_attributes.pcss, resources/web/styles.pcss
This PR creates a stylesheet with a border around collapsed sections (detail/summary objects). It's intended for use in nested objects on API reference pages.
=> [DOCS] Adds child_attributes CSS role

shared/attributes.asciidoc, shared/fn-ref-ex.asciidoc
Adds a reference template for function documentation.
I ended up needing this while documenting functions for
EQL in the Elasticsearch docs. Even within the Elasticsearch
docs, we have several conventions for documenting functions.
The goal of this template is to standardize the way Elastic
documents functions. Inspiration was taken from the Kibana docs:
https://www.elastic.co/guide/en/kibana/master/canvas-function-reference.html
Any and all feedback welcome!
=> [DOCS] Add function reference template

resources/web/style/child_attributes.pcss
IMO, the background color for `child_attributes` makes it difficult to differentiate between inline code and regular text inside of collapsed sections. @lcawl also pointed out that admonition blocks don't seem to be showing up, as they probably use the same grey. **This PR explores some alternative background colors.**
Here's an example of the current background color:
And here's an enlarged comparison:
Some of these are just terrible, but I took screenshots, so I might as well share them. I like `#ebf7fa` the best, but I'm also not in love with it. Open to any and all suggestions.
---
cc @jrodewig / @KOTungseth
=> docs: update child_attributes background color

shared/versions/stack/5.5.asciidoc, shared/versions/stack/5.6.asciidoc, shared/versions/stack/6.0.asciidoc, shared/versions/stack/6.1.asciidoc, shared/versions/stack/6.2.asciidoc, shared/versions/stack/6.3.asciidoc, shared/versions/stack/6.4.asciidoc, shared/versions/stack/6.5.asciidoc, shared/versions/stack/6.6.asciidoc, shared/versions/stack/6.7.asciidoc, shared/versions/stack/6.8.asciidoc, shared/versions/stack/7.0.asciidoc, shared/versions/stack/7.1.asciidoc, shared/versions/stack/7.2.asciidoc, shared/versions/stack/7.3.asciidoc, shared/versions/stack/7.4.asciidoc, shared/versions/stack/7.5.asciidoc, shared/versions/stack/7.6.asciidoc, shared/versions/stack/7.7.asciidoc, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
Adds a `minor-version` attribute to the `versions/stack` attribute
files.
Writers can use this attribute to reference the minor version of a
release _without_ the bug release. In many cases, this is the same as
the branch, but not always (e.g. `master`, `7.x`).
=> [DOCS] Add `minor-version` attribute

shared/versions/stack/5.5.asciidoc, shared/versions/stack/5.6.asciidoc
Fixes a copy/paste error from #1797. Thanks for spotting @gtback!
=> [DOCS] Correct `minor-version` attribute for 5.5 and 5.6

resources/web/style/code.pcss
Updates the fallback front for code snippets from `sans-serif` to
`monospace`.
Closes #1802
=> Correct fallback font for code snippets

README.asciidoc
Hello,
I suggest modifying explanation for build_aliases.sh file in `README.asciidoc`.
>Some documentation books require more complex build commands, ...
this  explanation is too broad and  ambiguous, as in most cases the additional options provided in `doc_build_aliases.sh` file are needed to build document.
For the first-time builders like me, we don't know our document build process is whether complex one or not. For example, I tried to build a part of elasticsearch document using the simple command and I encountered this errors:
```
...
INFO:build_docs:Error executing: asciidoctor -v --trace -r /docs_build/resources/asciidoctor/lib/extensions.rb -b html5 -d book -a showcomments=1 -a lang=en -a source_branch=master -a compat-mode=legacy -a …
```
=> [DOCS] Modify explanation to use doc_build_aliases.sh file in README.asciidoc.

conf.yaml
Adds ECK 1.1 to the dropdown. Will followup with a PR in the future to make it the current branch.
It wasn't clear to me if I should also add it to the excludes array just below it that includes the 1.0 branch. It was added here https://github.com/elastic/docs/pull/1297
=> Add ECK 1.1

conf.yaml
We need to add the `2.5` branch to our doc builds and switch `current` in time for the March 31 GA date.
@elastic/cloud-delivery or @elastic/cloud-writers could I get an LGTM for this PR, please?
=> Doc build changes for ECE 2.5 - MERGE ON APRIL 14, 2020

shared/attributes.asciidoc
These attributes are defined in the obs docs, but they need to be defined in the shared file so all projects can use them.
@gchaps Let me know what else you want in this list, or feel free to push commits to my fork, if you want to list other app names.
=> Add kibana observability app names to shared attribute list

resources/web/style/base_styles.pcss
Adds a bottom margin for the `<details>` tag.
Otherwise, collapsible sections are too close when stacked.
*Before*
*After*
=> Update `details` style for stacked collapsible sections

conf.yaml
This PR adds a doc build for beta2 of ecctl and sets that doc build to be the current (default) docs you get. The docs out of `master` remain available but you will have to select them from the version drop-down to see them.
The beta2 build uses the new https://github.com/elastic/ecctl/tree/v1.0.0-beta2 
branch in the ecctl repo that I created off the `v1.0.0-beta2` tag:
=> Add beta2 doc builds for ecctl and make them current

shared/attributes.asciidoc
This PR is in addition to https://github.com/elastic/docs/pull/1737 and adds standard attributes to track logins for:
* links to the ESS product page https://www.elastic.co/cloud/elasticsearch-service
* links to the cloud sign-in page https://cloud.elastic.co
* an ESS baymax-only attribute for variants of these pages (e.g. `https://www.elastic.co/cloud/elasticsearch-service/pricing`)
We discussed whether we want to start tracking these links recently and the consensus was that we should. Ergo, this PR.
=> Add attributes for ESS login and product pages

resources/web/template.html
Updates default RTP content for docs sidebar.
Ref: https://github.com/elastic/website-www.elastic.co/issues/5984
=> GH5984 - Docs default RTP: swap out ES Trial with Getting Started

conf.yaml
We missed the docker logging driver docs when the conf.yaml was updated to include 7.7 branches.
=> Build logging driver docs for 7.7

conf.yaml
- Add .git suffix to repo URLs for consistency
- Add quotes around section titles that contain colons
- reuse rather than redefine `mapCloudSaasToClientsTeam` variable.
The last two changes are needed to make Python's YAML library able to
load the file.
=> Clean up conf.yaml

shared/attributes.asciidoc, shared/fn-ref-ex.asciidoc
The `{multi-arg}` attribute is used in the function reference template
to add footnotes for parameters can be passed multiple times.
However, using this attribute multiple times on the same page results
in duplicated footnotes:
This updates the `{multi-arg}` attribute to use the `footnoteref`
syntax. This gives the footnote a single, reusable ID. This means only one
footnote is generated:
This also adds a new attribute, `{multi-arg-ref}`, which can be used for
the subsequent occurrences of the footnote.
This also updates guidance on usage of the `{multi-arg}` attribute
in the function reference template.
=> [DOCS] Update attributes for multi arg footnotes

conf.yaml, doc_build_aliases.sh
With the combination of App Search and Workplace Search into an Enterprise Search binary comes 7.7, our team need a solution-level book that allows us to communicate solution level documentation, such as the Enterprise Search Home experience, as well as common installation procedures. 
This book only applies to version 7.7 and above, so I wasn't sure what to put in the config for `version` and `current`. @debadair: you may be able to guide me here.
@zumwalt @chriscressman @goodroot This adds the book to the `docs` repo.
=>   [7.7 Release] Adding an Enterprise Search Book to the Elastic Documentation

conf.yaml
This will apply to the 7.7 and 7.x branches.
=> Add new location of transport client documentation examples

conf.yaml
This PR removes `master` from the list of ecctl branches.
=> Removed master from the list of ecctl branches

README.asciidoc, resources/asciidoctor/lib/care_admonition/extension.rb, resources/asciidoctor/lib/elastic_compat_preprocessor/extension.rb, resources/asciidoctor/spec/care_admonition_spec.rb, resources/asciidoctor/spec/elastic_compat_preprocessor_spec.rb, resources/web/style/toc.pcss
Adds a new `dev` care admonition, similar to the existing `beta`
and `experimental` admonitions. Also cleans up some outdated/redundant
docs regarding care admonitions in the README.
The ES team has started developing more features under feature flags.
Previously, we've indicated that in the feature's docs using the
`experimental` care admonition.
However, we also use the `experimental` admonition for experimental
features. Unlike feature flag development, experimental features _are_
released as part of ES distributions.
Reusing the admonition could confuse users and our internal support
team. Creating a new admonition lets us set a reusable default text
that's easy for contributors to use.
=> Add `dev` care admonition

conf.yaml
For the Milestone 36 release, we need to switch our ESS and Heroku doc builds over. 
@elastic/cloud-writers, can I get an LGTM for this PR, please?
=> Switch to MS 36

conf.yaml, doc_build_aliases.sh, shared/versions/stack/7.7.asciidoc, shared/versions/stack/current.asciidoc
DO NOT MERGE THIS PR UNTIL RELEASE DAY
Changes:
* Adds the `Enterprise Search Guide` docbook and makes several Enterprise Search changes from #1790
* Adds `&stackcurrent` variable for the current Stack docs branch
* Sets the `&stackcurrent` variable as `7.7`
* Removes the `7.6` branch from `&stacklive`
Closes #1396
http://docs_1822.docs-preview.app.elstc.co/guide/index.html
=> Updates for 7.7 release

conf.yaml
Move the "title" key onto the line with the '-' to make it easier to
browse through the sections and books in editors which support code
folding.
=> Reformat conf.yaml titles.

shared/api-ref-ex.asciidoc
Adds the `[role="child_attributes"]` role attribute to the API reference
template.
This attribute allows us to nicely display nested parameters.
Since the attribute does nothing if a collapsible section isn't present,
we should include it by default. This'll make things easier for
non-writer contributors.
=> [DOCS] Add `child_attributes` attribute to API reference template

shared/versions/stack/7.8.asciidoc, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
This PR adds a `short-version` attribute to the `versions/stack` attribute files for `master`, `7.x`, and `7.8` .
=> [DOCS] Add short-version attribute

README.asciidoc
Adds a tip to help doc contributors use topic titles and IDs that improve SEO.
@AnneB-SEO I'm trying to keep this guideline simple, but let me know if you think I should say more.
=> Add naming guideline for topic titles and IDs

shared/cloud/ess-getting-started.asciidoc
This PR removes two hidden characters from the shared Cloud getting started file. They were visible when the page was built directly via Asciidoctor:
=> Removes special characters from shared file

README.asciidoc, build_docs
Python 2 (annoyingly) doesn't include the name of the missing file, but
we assume that it's `docker`, since other files passed as arguments
should get logged by Perl in the Docker container, not by Python on the
host.
See https://github.com/elastic/docs/issues/1379.
Python 2:
```
$ ./build_docs --doc README.asciidoc --open
[Errno 2] No such file or directory
Are you sure Docker is installed?
```
Python 3:
```
$ ./build_docs --doc README.asciidoc --open
[Errno 2] No such file or directory: 'docker'
Are you sure Docker is installed?
```
=> Show better error when Docker missing.

conf.yaml
This PR removes the branches with `v` in the name from our ecctl doc builds. These branches match tags in the ecctl repo and we'd like to remove to simplify life. 
Relates to https://github.com/elastic/docs/pull/1840
Depends on https://github.com/elastic/website-www.elastic.co/issues/6128.
=> Remove `v` branches from ecctl docs — DO NOT MERGE YET

conf.yaml, doc_build_aliases.sh
This updates the ECE book chunking level from `1` to `2`.  This will enable the structure that Arianna has planned for the ECE install section.  
Also, I notice in at least one spot it improves our existing structure by adding a few new links in our ToC.  Improved navigation is always a win. :-)
Chunk level set to `1`:
Chunk level set to `2`:
=> Change ECE book chunking level

README.asciidoc
This PR adds a new "Shared attributes" section to the readme (moving some existing content out of the linking section and augmenting it with details about the special *-root attributes).
=> Adds shared attributes section to README

conf.yaml
@KOTungseth pointed out that our solution docs are hidden away at the bottom of our current documentation landing page. To better 3+1ify the page, this PR moves our solution documentation above the Logstash and Beats reference. The page still isn't perfect, but in its current structure, it will never be.
@dedemorton asked if I could also update the order the Beats documentation while I was working with the file. Beats are now sorted alphabetically, with the Beats platform reference at the top of the list, and the Beats developer reference at the bottom.
=> docs: Guide order

shared/attributes.asciidoc
Adds attributes (variables) for names related to new ingest management capabilities. 
@mostlyjason Can you verify the names here? Not sure if I got these right, although I did read through 3 different issue.  I couldn't figure out the final decision on a couple names, like the package registry. :-) 
@skh After we merge this PR, please use these attributes in place of names in the ingest management docs. For example, instead of Elastic Agent, use `{agent}`.
The Kibana Reference already includes the file. To include the file in new docs, use:
`include::{docs-root}/shared/versions/stack/{source_branch}.asciidoc[]`
=> Add attributes for ingest management

shared/attributes.asciidoc
Our style guide will say to use Ingest Manager when describing the UI. However, we need to use ingest management generically, and I can already see folks alphabetizing it all over the place.
So let's have an attribute!
=> Add an attribute for ingest management

conf.yaml, doc_build_aliases.sh
Initial PR to add ingest management docs.
Draft until we get the initial files in place.
Open issues:
- Put under Elastic Stack
- Put under Observability: APM, Logs, Metrics, and Uptime
- Rename "Beats: Collect, Parse, and Ship" to "Collect, Parse, and Ship" and put under there.
UPDATE: Decision was to put under Beats for now because this feature is experimental.
=> Get Ingest Management docs building

conf.yaml
With the release of milestone 39﻿to happen soon, we should get a PR ready to change our doc builds to use the new milestone for ESS and Heroku. 
@elastic/cloud-writers could one of you approve this PR, please?
=> Change current for ESS to MS 39

shared/attributes.asciidoc
The Kibana and Elasticsearch documentation use "{pull}" and "{issue}" attributes with different values (e.g. https://raw.githubusercontent.com/elastic/kibana/master/docs/index.asciidoc and https://raw.githubusercontent.com/elastic/elasticsearch/master/docs/Versions.asciidoc), which can cause problems when the content is used in a shared context (such as the Installation and Upgrade Guide). 
This PR defines repo-specific attributes in the shared attributes file to solve the problem.
=> Adds shared attributes for release doc PR URLs

shared/attributes.asciidoc
APM doesn't build the 7.x branch, so we need to set the URL to master to avoid breaking the build.
=> Sets apm branches for 7.x to master

shared/attributes.asciidoc
Missed this one in https://github.com/elastic/docs/pull/1873
=> Set branch for apm-get-started-ref attribute

conf.yaml, doc_build_aliases.sh
Related to https://github.com/elastic/kibana/pull/69721
This PR adds the kibana repo as a resource for the Glossary so that it can pull tagged sections from that repo.
=> Add kibana dependency to Glossary

conf.yaml
This commit adds the 7.8 Azure Marketplace docs and sets 7.8 as the default.
=> Add 7.8 Azure Marketplace docs

conf.yaml, doc_build_aliases.sh, shared/attributes.asciidoc
This PR is to add the forthcoming Observability docs. The PR includes:
- Observability docs added to config file
- Doc build alias for Observability docs
- Observability docs added to shared attributes file
Related Issue:
=> [WIP] Add Observability docs

conf.yaml
The content in the Stack Overview was moved elsewhere and it doesn't contain any useful information after 6.3. Redirects were created, so there doesn't seem to be any point to having 7.x or later branches in that book.
=> [DOCS] Remove branches from Stack Overview

shared/attributes.asciidoc
This PR adds a shared attribute for a URL that we reference in several license-related pages.
=> Adds shared attribute for trial URL

conf.yaml
This PR adds the beats and APM server docs as dependencies to the Observability docs.
=> Add dependencies to observability docs

conf.yaml, doc_build_aliases.sh
This PR updates the source and doc build alias for the Uptime Monitoring Guide.
The Uptime monitoring content is in the process of being moved from the Kibana repo to the [Observability docs repo](https://github.com/elastic/observability-docs).
=> [WIP] Update uptime sources and build alias

conf.yaml
Adding the `release-ms-41` branch to the ESS build, per the [release CSR](https://github.com/elastic/cloud/issues/60156).
=> Adding ESS MS 41 branch

shared/versions/stack/7.9.asciidoc, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
The current ECS version is incorrectly listed as 1.4 on the 7.9, 7.x, and master branches.
This PR fixes that.
=> [DOCS] Correct current ECS version for several branches

conf.yaml
This adds the ECK 1.2 branch to the build list. ECK 1.2.0 is planned for release on July 21. 
I followed #1799 and added 1.2 to the exclude list for `7.x`. I hope that is still the correct thing to do as 1.2 also uses `current.asciidoc` (https://raw.githubusercontent.com/elastic/cloud-on-k8s/1.2/docs/index.asciidoc)
=> Add ECK 1.2 

shared/attributes.asciidoc
This PR adds the root attribute for the Beats URL. This is required for including the tab-widgets, from the Beats repo, into the Observability docs. 
Related PR: https://github.com/elastic/observability-docs/pull/16
=> [DOCS] [WIP] Add Beats root attribute

conf.yaml
A place for technical writers to coordinate the docs configuration changes that should be applied shortly after the 7.9.0 feature freeze.
=> Add 7.9 branches to all applicable books

shared/attributes.asciidoc
I need this attribute to resolve links in the Beats documentation that point to the ECK docs.
=> Add attribute for eck html path

conf.yaml
This PR sets the ECK 1.2 branch as the `current` version. 
I am submitting this early to get approval. It should only be merged on July 21 after ECK 1.2 is released.
=> Promote ECK 1.2 branch to current

conf.yaml
Removes the dependency on `shared/versions/stack/7.x.asciidoc` from the ECK configuration. 
ECK 0.8 and 0.9 docs have a reference to `shared/versions/stack/7.x.asciidoc` but none of the attributes are used anywhere so we don't require the docs to be rebuilt whenever that file changes. Removing this dependency simplifies adding future versions to the build as they all rely on `shared/versions/stack/current.asciidoc` and don't have to be explicitly added to the `exclude_branches` list of 7.x.
Related to https://github.com/elastic/cloud-on-k8s/issues/3448
=> Remove ECK dependency on 7.x attributes

doc_build_aliases.sh
Additional resources need to be specified to use the build alias to build the observability guide.
=> Add resources required for obs doc alias

Dockerfile, Makefile, lib/ES/Book.pm, schema.yaml
schema.yaml lists the keys and their expected values, along with
comments to describe many of the settings in conf.yaml.
This is incorporated into `make check`.
=> Add yamale to enforce (and document) a schema for conf.yaml

doc_build_aliases.sh
Changes the `docbldsec` alias to point to the new Security docs repo.
FYI - @lcawl @karenzone
=> [Doc] Updates sec docs alias

shared/versions/stack/7.8.asciidoc
This PR updates the shared version attributes for the latest 7.8 documentation release.
=> Updates 7.8 version attributes

shared/versions/stack/6.8.asciidoc
This PR updates the shared version attributes for the latest 6.8 documentation release.
=> Updates 6.8 version attributes

conf.yaml
related https://github.com/elastic/elasticsearch/pull/60026
----
Note - I am not 100% this is correct, however in https://github.com/elastic/elasticsearch/pull/60026 I am moving this from test to internalClusterTest. The 7.x PR is failing https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+build-docs/6444/console ... i _think_ this will fix that ? I suppose that I will need to merge these two PRs fairly close to each other to prevent alot of failures. 
```
14:14:54 INFO:build_docs: -                                 Java API: Merging the subbed dir for [elasticsearch][7.x][modules/reindex/src/test/java/org/elasticsearch/client/documentation] into the last successful build.
14:14:56 INFO:build_docs: -                                 Java API: Merged the subbed dir for …
```
=> move location of re-index java-api

integtest/spec/all_books_sub_dir_spec.rb, lib/ES/BaseRepo.pm
These were added in 69e747baa8653201b3589869bb2ab9c9dc2e7b87, and are
necessary to detect all the right files, but we don't want to pass that
flag in the sparse-checkout file.
Related to #1917
=> Fix issue with `:(glob)` in sparse-checkout files

README.asciidoc, integtest/spec/all_books_change_detection_spec.rb, integtest/spec/all_books_spec.rb, integtest/spec/helper/dsl/convert_all.rb, lib/ES/Book.pm, schema.yaml, shared/legacy-attrs.asciidoc
There's an existing method to give each "branch" a "title". The title corresponds to the "name" of the version, in cases where it doesn't match the name of the branch itself, and the "title" already appears in the version dropdown. This change extends that to use the version name ("title") in the URL.
Future work will better distinguish between "branches" and "versions" in cases where they aren't the same.
---
To use this, put a `{ branch-name: version-name }` into the `branches` list of a book in conf.yaml. All other places where you would put a branch (like `live` and `current`) should continue to use the branch name (not the version name), but I plan to make further enhancements to make this more straighforward.
---
Related to https://github.com/elastic/docs/issues/1850
=> Use the "version" rather than "branch" in file paths

integtest/spec/all_books_spec.rb, integtest/spec/helper/source.rb, lib/ES/Book.pm
- Use the version name in all output rather than the branch name.
- Update the test DSL to replace spaces in book titles.
Related to #1928
=> Remove other places that branch names are used

conf.yaml
This PR changes current to MS 43 for ESS for the new release and removed the older MS 41 release. 
@elastic/cloud-writers could I get approval for this please?
=> Change current to MS 43 for ESS

shared/attributes.asciidoc
Added the following attributes:
:kibana-issue: {kib-issue}
:kibana-pull:  {kib-pull}
=> Adds Kibana pull and issue attributes

integtest/spec/single_book_spec.rb, lib/ES/Util.pm
Having a file named `<index>-extra-title-page.html` allows adding extra
content to a title page. This allows replacing the content entirely with
`<index>-custom-title-page.html`.
Ref: #1892
=> Allow replacing a book's default title page

integtest/spec/all_books_spec.rb, lib/ES/Book.pm, lib/ES/Util.pm
In #1909, we added the ability to replace the title page of a book with
completely custom content. For multi-branch builds, we previously
assumed the index.html file would always contain the TOC, which caused
errors in Kibana builds when removing a non-existant TOC.
Also, we previously customized the title page and then tried to extract the
TOC. Now, we extract the TOC first, since it may not exist if the title
page has been customized.
=> Don't fail when trying to remove TOC from custom title page

conf.yaml
This PR adds a few ECS branches to the version selector for ECS. We are not changing the "current" version yet, however, and this is intentional.
* ECS 1.6 release is coming, the branch has been cut
* ECS' main branch will now target ECS 2.0, and we have therefore added
an 1.x branch to track the upcoming minor releases before 2.0.
This can be merged as soon as it's approved.
https://docs_1936.docs-preview.app.elstc.co/guide/en/ecs/1.6/index.html
https://docs_1936.docs-preview.app.elstc.co/guide/en/ecs/1.x/index.html
=> Add 2 new branches in the ECS version selector

shared/attributes.asciidoc
Elastic Agent is defined twice. I'll fix the duplication later. This PR is mainly to get the logging attribute added.
=> Add docker logging attributes

conf.yaml
Updates the current branch to `1.0`, adds `1.0` in the branches array,
and updates the title to include Elasticsearch Service.
=> Update ecctl doc branches and title

conf.yaml
This PR adds the conf.yaml doc build changes required for ECE 2.6. 
Depends on https://github.com/elastic/docs/pull/1918 to be able to build versions rather than branches. 
Ran a docbld --all and it looks like we have a broken doc link:
```
INFO:build_docs:Bad cross-document links:
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud-enterprise/2.6/ece-add-capacity.html:
INFO:build_docs:   - en/cloud-enterprise/current//Platform_-_Allocators.html#set-allocator-settings
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/cloud-enterprise/current/ece-add-capacity.html:
INFO:build_docs:   - en/cloud-enterprise/current//Platform_-_Allocators.html#set-allocator-settings
```
@elastic/cloud-writers can one of you help Aran by tracking down and fixing this broken doc link for tomorrow?
=> Make ECE 2.6 doc build changes

conf.yaml, doc_build_aliases.sh
This PR adds the `chunk: 1` attribute to the Ruby API book attribute list in the conf.yml and adds `--chunk 1` to the Ruby book alias in `doc_buil_aliases.sh`.
These changes are required because of upcoming structural changes in the Ruby client book.
**Do not** merge this PR before https://github.com/elastic/elasticsearch-ruby/pull/998.
=> Adds chunk attribute to Ruby API book

conf.yaml
This removes the 7.8 branch from the list of "live" Stack release branches in our docs.
With the release of 7.9.0, the 7.8.x versions passed their maintenance window: https://www.elastic.co/support/eol
=> [DOCS] Drop 7.8 from stack live

README.asciidoc
Adds a note about what "slow" means to the full build documentation. I didn't realize it meant more than an hour 😅
=> docs: add timing note to full build docs

integtest/spec/all_books_spec.rb, lib/ES/Book.pm, schema.yaml
Previously, there was some complex analysis of the string values of each branch. Instead, we just require the "branches" list in conf.yaml to be in the correct order, and use list position to decide which branches are newer or older than the "current" branch.
See #1899
I went through a lot of complex calculations to compare branch versions, but kept running into edge cases, so just decided this approach was easier. conf.yaml already appears to have the right rules (the ones that didn't were the "versions" fixed by #1918, so this fixes that too).
~I also fixed a warning (using `==` rather than `eq`).~ Turns out this is actually related to a separate bug (#1930) so I removed this.
=> Use branch list to decide if branch is new or old

shared/versions/stack/7.10.asciidoc, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
ECS 1.6.0 released today (2020-0825)!  This PR updates our shared version files for 7.10, 7.x, and master.
=> Update ECS versions

conf.yaml, doc_build_aliases.sh, shared/attributes.asciidoc, shared/versions/stack/7.10.asciidoc, shared/versions/stack/7.9.asciidoc, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
This PR adds the APM PHP agent to the documentation build.
~Do not merge until https://github.com/elastic/apm-agent-php/pull/167 has been merged.~
=> docs: add APM PHP agent to doc build

conf.yaml
This PR switches our ESS and Heroku doc builds over to MS 44.
=> Make doc build changes for MS 44

build_docs.pl
In the newest branches of the kibana repo, the file is in a new location.
After merging, it should be fine to undo elastic/kibana#76354.
cc: @pgayvallet
=> Add another location to check for Kibana links

shared/versions/stack/7.9.asciidoc
This PR updates the shared version attributes for the latest 7.9 documentation release.
=> Updates 7.9 version atts

conf.yaml
This commit adds 7.9 branch Azure Marketplace docs, and makes them the current version
=> Add Azure Marketplace 7.9 docs and make current

conf.yaml
This adds "(deprecated)" to the title in the doc landing page, and moves the book down to the bottom of the clients list.
=> Make it more obvious that the Java API is deprecated.

conf.yaml
This patch updates the `conf.yml` file for the new location of go-elasticsearch documentation.
Related: https://github.com/elastic/elasticsearch/pull/62634
=> Update conf.yml for go-elasticsearch documentation

.ci/publish_air_gapped_docs.sh
We don't push to push.docker.elastic.co anymore.
=> Fix air-gapped build

conf.yaml
Depends on https://github.com/elastic/elasticsearch-py/pull/1380 and the resulting backport to 7.x
=> Migrate Python documentation to elasticsearch-py

conf.yaml, doc_build_aliases.sh
This PR adds the `chunk: 1` attribute to the attribute list of the GO API book in the conf.yml and adds `--chunk 1` to the GO API book alias in `doc_build_aliases.sh`.
These changes are required because of upcoming structural changes in the GO client book.
=> Adds chunk attribute to GO API book

conf.yaml
Some very old client versions are appearing high in the search results. For example:
This PR adds the "live" option to the client docs in the conf.yaml so that their active branches are prioritized. In a couple of cases there is only one branch, but I didn't think it hurt to add it there either in case more branches are added in the near future.
=> Add live branches for client docs

conf.yaml, doc_build_aliases.sh
This PR adds the `chunk: 1` attribute to the attribute list of the JavaScript API book in the conf.yml and adds `--chunk 1` to the JavaScript API book alias in `doc_build_aliases.sh`.
These changes are required because of upcoming structural changes in the JavaScript client book.
**Do not merge this PR before https://github.com/elastic/elasticsearch-js/pull/1316 and re-generating the API reference docs.**
=> Adds chunk attribute to JavaScript API book

shared/cloud/ess-getting-started-obs.asciidoc, shared/cloud/ess-getting-started.asciidoc
@EamonnTP pointed out in https://github.com/elastic/observability-docs/issues/144 that the ESS shared docs content is outdated. This PR updates it.
In addition, this PR adds a new getting started snippet for Observability. I'm not sure if the best approach here is to have two different files, or to pepper a bunch of `ifdef::[]` and `ifndef::[]` statements into one cloud getting started snippet. Thoughts?
Closes https://github.com/elastic/observability-docs/issues/144.
=> docs: update shared cloud docs

conf.yaml, shared/versions/stack/7.x.asciidoc
This PR:
* adds the new unreleased 1.7 branch to the version selector.
* maps the next stack release (7.x) to this new ECS version
The "current" version is not changing, as the ECS release is in a few weeks.
=> Add ECS 1.7 branch in preparation for release

conf.yaml
Related to https://github.com/elastic/docs/pull/1972#discussion_r500628265
This PR uses the "stacklive" attribute in the conf.yaml for the Ingest Management content.
=> Add stacklive to conf.yaml for Ingest Management Guide

conf.yaml, doc_build_aliases.sh
This PR adds the `chunk: 1` attribute to the attribute list of the Python, Rust, and eland client books in the conf.yml and adds `--chunk 1` to the respective book aliases in `doc_build_aliases.sh`.
These changes are required because of upcoming structural changes in the above-mentioned client books. This PR covers the last bits of infrastructural changes required to the Clients docs restructuring.
**Merge only the following PRs are merged:**
* py: https://github.com/elastic/elasticsearch-py/pull/1393
* eland: https://github.com/elastic/elasticsearch-eland-docs/pull/9
* rust: https://github.com/elastic/elasticsearch-rs/pull/150
=> [DOCS] Adds chunking to Py, Rust, and eland client books

conf.yaml
This PR adds new 7.10 branches to the appropriate books.
NOTE: These build checks will fail until all the branches exist.
=> Add 7.10 branches to conf.yaml

conf.yaml, doc_build_aliases.sh
Updating the ECS book chunking config from `1` to `2`. This change will enable adding additional usage sub-sections per fieldset in the ECS field reference.
Example:
The full details of these ECS documentation changes are captured in https://github.com/elastic/ecs/issues/943.
=> Change ECS chunking level

shared/attributes.asciidoc
Adds `:observability-guide-all:` and `:user-experience:`
For https://github.com/elastic/observability-docs/pull/187.
=> Add new Observability attributes

conf.yaml
How do sources work for documentation books? We have files in `apm-server`'s `doc` folder that the Observability guide needs to access. Is the fix as simple as removing the `/guide` from the source?
For the failures in https://github.com/elastic/observability-docs/pull/188:
```
08:57:19 INFO:build_docs:
08:57:19 INFO:build_docs:asciidoctor: ERROR: instrument-apps.asciidoc: line 22: include file not found: /tmp/docsbuild/qaSsMmfBdn/apm-server/docs/tab-widgets/install-agents-widget.asciidoc
08:57:19 INFO:build_docs:asciidoctor: ERROR: instrument-apps.asciidoc: line 36: include file not found: /tmp/docsbuild/qaSsMmfBdn/apm-server/docs/tab-widgets/configure-agent-widget.asciidoc
08:57:19 INFO:build_docs:asciidoctor: ERROR: instrument-apps.asciidoc: line 43: include file not found: …
```
=> Update Observability sources

shared/versions/stack/6.8.asciidoc
Updates the shared version attributes to 6.8.13.
NOTE: Do not merge until release day.
=> 6.8.13 release

shared/versions/stack/7.9.asciidoc
Updates the shared version attributes to 7.9.3.
NOTE: Do not merge until release day.
=> 7.9.3 release

conf.yaml
This PR depends on https://github.com/elastic/eland/pull/304
After this is merged can delete the repository at: https://github.com/elastic/elasticsearch-eland-docs
=> Migrate Eland documentation to elastic/eland

conf.yaml
Updates `current` and branches to point to MS-47 Cloud docs.
=> Update Cloud to MS47

conf.yaml, doc_build_aliases.sh
This PR adds the `chunk: 1` attribute to the attribute list of the Perl API book in the conf.yml and adds `--chunk 1` to the Perl API book alias in `doc_build_aliases.sh`.
These changes are required because of upcoming structural changes in the Perl client book.
**Do not merge before https://github.com/elastic/elasticsearch-perl/pull/195!**
=> Adds chunk attribute to Perl API book

conf.yaml
This PR adds observability-docs as a source to the stack-docs repo. This will allow Observability "What's new" content to be included in the installation and upgrade guide.
https://github.com/elastic/observability-docs/pull/216
=> Add Observability repo source to stack docs

conf.yaml
This adds the ECK 1.3 branch to the build list. ECK 1.3.0 is planned for release on November 10th.
=> Add ECK 1.3

doc_build_aliases.sh
The following resource is needed to support changes to the tagged regions in the highlights section:
`--resource=$GIT_HOME/observability-docs/docs/en/observability`
=> Add observability docs resource to the doc build aliases

conf.yaml
This PR sets the ECK 1.3 branch as the current version.
I am submitting this early to get approval. It should only be merged on November 10th after https://github.com/elastic/docs/pull/1996 is merged and ECK 1.3 is released.
=> Promote ECK 1.3 branch to current

conf.yaml, shared/versions/stack/7.10.asciidoc, shared/versions/stack/current.asciidoc
--DO NOT MERGE THIS PR UNTIL RELEASE DAY --
Updates "current" from 7.9 to 7.10 and the release state from "unreleased" to "released".
=> Update current version for 7.10

conf.yaml
Removes the 7.9 branch from the list of "live" Stack release branches in our docs.
With the release of 7.10.0, the 7.9.x versions passed their maintenance window: https://www.elastic.co/support/eol
=> [DOCS] Drop 7.9 from stack live

conf.yaml
Closes https://github.com/elastic/observability-docs/issues/128
TODO after merging:
=> Get Fleet User Guide building

conf.yaml
Removes the Ingest Management Guide and updates the shared path attribute to use fleet.
=> Get all branches building in Fleet User Guide

conf.yaml, shared/versions/stack/master.asciidoc
=> Make ECS 1.7 the current release

conf.yaml
The Ingest Management Guide has been renamed to the Fleet User Guide in all versions of the docs. This PR removes the guide permanently from the Beats section.
**Do not merge until after the global redirects are in place**: https://github.com/elastic/website-www.elastic.co/issues/7066
=> Remove Ingest Management Guide from Beats section

conf.yaml, doc_build_aliases.sh, shared/attributes.asciidoc, shared/versions/stack/7.10.asciidoc, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
This PR adds the [ECS Logging Java Reference](https://github.com/elastic/ecs-logging-java) to the elastic.co documentation build.
* For https://github.com/elastic/ecs-logging-java/pull/112
=> Add ECS Logging Java Reference to doc build

conf.yaml, shared/versions/stack/7.10.asciidoc, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
This PR updates `current` to `0.x` for `ecs-logging-java`. This PR should only be merged after the `0.x` branch has been added to the repository.
cc @felixbarny 
This is a follow-up PR to https://github.com/elastic/docs/pull/2010.
=> docs: Update ECS logging current

shared/versions/stack/7.10.asciidoc
Updates the shared version attributes to 7.10.1.
NOTE: Do not merge until release day.
=> 7.10.1 release

conf.yaml
These were added to the cached worker images used for CI, and will soon be needed by docs builds. I have a periodic job that keeps these two lists in sync, so I'm adding them in here, even though they aren't used by any published docs yet.
=> Add ecs-logging and ecs-dotnet repos

conf.yaml
__IMPORTANT: Do not merge until ECE 2.7.1 release__
Updates the current branch to 1.1, adds 1.1 in the branches array,
=> Update ecctl branch to 1.1

conf.yaml, doc_build_aliases.sh, shared/attributes.asciidoc, shared/versions/stack/7.10.asciidoc, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
This PR adds the `ecs-logging` repository as a source repo for the `ecs-logging-java` documentation. It also maps the `master` branch of `ecs-logging` to both the `1.x` and `0.x` branches of `ecs-logging-java`.
Blocked by:
~https://github.com/elastic/ecs-logging-java/pull/117.~
=> docs: add ecs-logging

shared/attributes.asciidoc
Fixes ECS logging link
For https://github.com/elastic/ecs-logging-java/pull/117.
=> docs: fix ecs-logging link

doc_build_aliases.sh
Fixes doc build alias for Filebeat so that local build does not fail.
@gtback The Beats aliases were defined before we made the file structure of the books more complex. Should we try to sync up the aliases with all potential resource paths defined in the conf.yaml, or just deal with them when they break? I'm inclined to wait until they break.
=> Add missing resource to filebeat build alias

conf.yaml
Removes the `beta` suffixed branches from the doc building.
=> ecctl: Remove beta suffixed branches from listing

conf.yaml, doc_build_aliases.sh
This PR adds:
* A new `tpec` entry in conf.yaml for the Elastic Cloud Terraform provider book
* A new build alias for building the docs locally (try `docbldtpec --open` once you have the PR mentioned below locally)
Depends on the new docs content in https://github.com/elastic/terraform-provider-ec/pull/163. 
In terms of placement, this is where the new docs will appear:
=> Add Cloud Terraform provider docs to builds

conf.yaml, doc_build_aliases.sh, shared/attributes.asciidoc, shared/versions/stack/7.10.asciidoc, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
This PR adds ECS Logging .NET documentation to our build system. It sets `master` as the `current` branch and sets up the required include parameters for including content from `ecs-logging`.
Blocked by:
=> Add ECS .NET & Ruby documentation

conf.yaml, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
* Adds a new unreleased 1.8 branch to the version selector.
* Updates the stack version mappings to this new version.
`current` version will be updated when ECS 1.8 releases.
=> Add ECS 1.8 branch in prep for release

conf.yaml
Updates conf.yaml to add 7.11 to doc build
This PR must be merged after ~https://github.com/elastic/docs/pull/2025~ and ~https://github.com/elastic/docs/pull/2024~. Both merged!
=> Add 7.11 branch to doc build

conf.yaml
We're currently moving all source for the Elastic Agent + Fleet documentation to a single location in the observability-docs repo. 
When that work is complete, the x-pack/elastic-agent/docs directory will no longer exist.
DO NOT MERGE until the work is complete and all open PRs are merged.
=> Remove Beats repo dependency

conf.yaml
Add `x-pack/libbeat/docs` as a dependency to the Functionbeat reference.
For https://github.com/elastic/beats/pull/23344
=> Add libbeat/docs to Functionbeat reference

shared/versions/stack/7.10.asciidoc
Updates the shared version attributes to 7.10.2.
**NOTE**: Do not merge until release day.
=> 7.10.2 release

conf.yaml, doc_build_aliases.sh, shared/attributes.asciidoc, shared/versions/stack/7.10.asciidoc, shared/versions/stack/7.11.asciidoc, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
Adds `ecs-logging-python` to the build.
Blocked by https://github.com/elastic/ecs-logging-python/pull/29.
For https://github.com/elastic/ecs-logging-python/issues/27.
=> Add ecs-logging-python to the build

conf.yaml, doc_build_aliases.sh, shared/attributes.asciidoc, shared/versions/stack/7.10.asciidoc, shared/versions/stack/7.11.asciidoc, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
Adds `ecs-logging-go-zap` to the build.
For https://github.com/elastic/ecs-logging-go-zap/issues/20.
=> Add ecs-logging-go-zap to the build

conf.yaml
This commit adds the 7.10 version to the Azure Marketplace documentation, and sets it as the current version.
=> Add version 7.10 to Azure Marketplace docs

conf.yaml
This PR updates our docs to use MS 51 as `current` for ESS and the Heroku docs built partially off the same source.
=> Change current to MS 51

shared/versions/stack/7.10.asciidoc, shared/versions/stack/7.11.asciidoc, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
This PR proposes the addition of a new shared attribute, `is-current-version`. `is-current-version` will be set to `true` in the currently released stack version, and `false` in all other versions.
At each minor and major release, a two-line update will be required. The previously current version will need to be set to `false`, and the newly current version will need to be set to `true`.
For example, in the 7.11 release, `shared/versions/stack/7.10.asciidoc` will set `:is-current-version:` to `false` and `shared/versions/stack/7.11.asciidoc:` will set `:is-current-version:` to `true`.
If Greg and Lisa are cool with this, I'll update the release documentation as well.
Required for https://github.com/elastic/observability-docs/pull/350.
=> Add is-current-version attribute

conf.yaml, doc_build_aliases.sh, shared/attributes.asciidoc, shared/versions/stack/7.10.asciidoc, shared/versions/stack/7.11.asciidoc, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
This PR adds `ecs-logging-go-logrus` to the build. It also renames the ECS zap book.
For https://github.com/elastic/ecs-logging-go-logrus/issues/5.
~**Merge after https://github.com/elastic/ecs-logging-go-logrus/pull/9.**~
=> Add ecs-logging-go-logrus to the build

conf.yaml, doc_build_aliases.sh, shared/attributes.asciidoc, shared/versions/stack/7.10.asciidoc, shared/versions/stack/7.11.asciidoc, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
This PR adds `ecs-logging-js` to the documentation build.
For https://github.com/elastic/ecs-logging-js/issues/20.
Note: CI is expected to fail until https://github.com/elastic/ecs-logging-js/pull/44 is merged.
=> add ecs-logging-nodejs to the docs repo

conf.yaml, doc_build_aliases.sh, shared/attributes.asciidoc, shared/versions/stack/7.10.asciidoc, shared/versions/stack/7.11.asciidoc, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
Adds [`ecs-logging-php`](https://github.com/elastic/ecs-logging-php) to the doc build.
For https://github.com/elastic/ecs-logging-php/issues/20.
~Blocked by https://github.com/elastic/ecs-logging-php/pull/18.~
=> Add ecs-logging-php to the build

conf.yaml
This PR updates our docs to use MS 52 as `current` for ESS and the Heroku docs.
=> Change current to MS 52 for ESS

conf.yaml, doc_build_aliases.sh
This PR adds the `chunk: 1` attribute to the PHP book attribute list in the conf.yml and adds `--chunk 1` to the PHP book alias in `doc_buil_aliases.sh`.
These changes are required because of upcoming structural changes in the PHP client book.
Do not merge until https://github.com/elastic/elasticsearch-php/pull/1099 is not merged.
=> Adds chunk attribute to PHP book

conf.yaml
=> Make ECS 1.8 the current release

conf.yaml
This value is used as the `DC.subject` meta value for the ML book. The search facets on www.elastic.co use the capitalized version of the name, so we should match that in order for results to appear.
cc: @laurent-qa @brianjolly
=> Capitalize subject for ML Book

conf.yaml
Part of the ecctl 1.2 release, accompanying ECE 2.8.0
Relates to https://github.com/elastic/ecctl/issues/436
=> Add new version of the docs for ecctl

conf.yaml, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
* Adds a new unreleased 1.9 branch to the version selector.
* Updates the stack version mappings to this new version.
`current` version will be updated when ECS 1.9 releases.
=> Add ECS 1.9 branch in prep for release

conf.yaml, shared/versions/stack/7.12.asciidoc
Adds a 7.12 branch to the docs.
CI is expected to fail until all repos have a 7.12 branch.
=> Add 7.12 branch

conf.yaml, shared/versions/stack/6.5.asciidoc, shared/versions/stack/6.6.asciidoc, shared/versions/stack/6.7.asciidoc, shared/versions/stack/6.8.asciidoc, shared/versions/stack/7.0.asciidoc, shared/versions/stack/7.1.asciidoc, shared/versions/stack/7.10.asciidoc, shared/versions/stack/7.11.asciidoc, shared/versions/stack/7.12.asciidoc, shared/versions/stack/7.2.asciidoc, shared/versions/stack/7.3.asciidoc, shared/versions/stack/7.4.asciidoc, shared/versions/stack/7.5.asciidoc, shared/versions/stack/7.6.asciidoc, shared/versions/stack/7.7.asciidoc, shared/versions/stack/7.8.asciidoc, shared/versions/stack/7.9.asciidoc, shared/versions/stack/7.x.asciidoc
This commit updates the configuration for the APM
.NET agent to include the 1.8 branch, and set it as
the current branch.
=> Add .NET APM agent 1.8 branch as current

conf.yaml, shared/versions/stack/master.asciidoc
To simplify their dev process, the APM .NET team wants to remove the `1.x` branch from their repository.
~`current` was swapped from `1.x` to `1.8` in https://github.com/elastic/docs/pull/2066, so I'm optimistic this will pass ci 🤞~ I jinxed myself.
=> Remove APM .NET agent 1.x branch from the doc build

conf.yaml
This commit adds 7.11 to the Azure Marketplace docs and sets as current
=> Update Azure Marketplace docs version

conf.yaml
As MS-53 has now been deployed in ESS production, this PR bumps the docs to use MS 53 as current for ESS and the Heroku docs
=> Change current to MS 53 for ESS

conf.yaml, doc_build_aliases.sh
This PR adds the `apm-server` repo as a dependency to the Fleet User Guide.
For https://github.com/elastic/observability-docs/pull/426.
=> Add new dependency to Fleet User Guide

doc_build_aliases.sh
On newer machines, it seems the default is zsh not bash, so the instructions in the doc_build_aliases can be misleading as-is. This PR adds a reference to .zshrc.
=> Add zshrc to doc_build_aliases instructions

conf.yaml
The Enterprise Search team is comfortable publishing the master branches for our docs.
We can merge this as soon as it builds successfully.
=> Publish the master branch for all Enterprise Search books

build_docs.pl
- Ignore links to web content that's outside the docs
- Ensure Elasticsearch Reference content is checked
Fixes #2081
Related: https://github.com/elastic/kibana/pull/94274, #1805
=> Improve link extraction for Kibana link checking

integtest/spec/all_books_broken_link_detection_spec.rb, integtest/spec/all_books_change_detection_spec.rb
When tested against a version of this repo prior to when #2085 was merged, it fails with these errors:
```
rspec './integtest/spec/all_books_broken_link_detection_spec.rb[1:2:5:1]' # building all books when broken link detection is enabled when there is a link in kibana to the website outside the guide logs that all the links are ok
rspec './integtest/spec/all_books_broken_link_detection_spec.rb[1:2:6:1]' # building all books when broken link detection is enabled when there is a broken Elasticsearch reference link in Kibana logs there are bad cross document links
rspec './integtest/spec/all_books_broken_link_detection_spec.rb[1:2:6:2]' # building all books when broken link detection is enabled when there is a broken Elasticsearch reference link in Kibana logs the bad link
```
This …
=> Add tests for the Kibana link checking changes in #2085

conf.yaml
Publish our 7.x docs, since we now have 7.x UIs within Kibana that link to those docs.
=> Publish the 7.x branch for all Enterprise Search books

conf.yaml
This adds the 1.5 release branch for the upcoming [ECK Operator](https://github.com/elastic/cloud-on-k8s) release.
=> Add ECK 1.5 branch to conf.yaml

conf.yaml
Based off of #2082. This promotes the ECK 1.5 release branch to current.
I am submitting this early to get approval. It should only be merged on March 23 after ECK 1.5 is released.
=> Promote ECK 1.5

conf.yaml, shared/versions/stack/7.11.asciidoc, shared/versions/stack/7.12.asciidoc, shared/versions/stack/current.asciidoc
--DO NOT MERGE THIS PR UNTIL RELEASE DAY --
Updates "current" from 7.11 to 7.12
Updates release state from "unreleased" to "released".
Removes 7.11 from live releases (branches displayed by default)
Sets is-current-version to false for 7.11 and true for 7.12
=> Update current version for 7.12

conf.yaml
As MS-54 has now been deployed in ESS production, this PR bumps the docs to use MS 54 as current for ESS and the Heroku docs
=> Change current to MS 54 for ESS

conf.yaml, shared/versions/stack/7.12.asciidoc, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
Adds the [apm-agent-php](https://github.com/elastic/apm-agent-php) `1.x` branch to the doc build and sets it as `current`.
=> docs: set 1.x as current for apm-agent-php

conf.yaml
=> Make ECS 1.9 the current release

conf.yaml, shared/versions/stack/7.12.asciidoc, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
Updates apm-agent-ruby `current` to `4.x`.
For https://github.com/elastic/apm-agent-ruby/issues/991.
=> docs: update ruby agent current

conf.yaml, doc_build_aliases.sh
DO NOT MERGE UNTIL ALL VERSIONS OF THE FLEET DOCS HAVE BEEN MODIFIED TO SUPPORT THIS CHANGE
This change is required in the current doc system to accommodate the large number of policy settings that will be documented in the agent docs. 
I know this goes contrary to the new design, but until we have the docs in the new docs system, having a flat structure is too overwhelming.
Incidentally, when we merge changes like this, we should let contributors know so they can pull down the latest aliases. We should also tell them when we add new build dependencies.
=> Change chunk level for Fleet User Guide

README.asciidoc, build_docs.pl, conf.yaml, integtest/spec/all_books_broken_link_detection_spec.rb
The ES docs team recently agreed to rename the `Elasticsearch Reference` docs to the `Elasticsearch Guide`.
This will help avoid the confusion and highlight that the ES docs contain more than reference material.
! This PR does **not** change the ES docs' URL structure or any links. !
Relates to https://github.com/elastic/elasticsearch/pull/71198
=> Rename ES Reference to ES Guide

shared/cloud/ess-getting-started.asciidoc
Tags the generic portion of our ESS getting started instructions for reuse. This lets me avoid Kibana-specific language in the ES docs. Also includes a minor edit.
=> [DOCS] Add tag for generic ESS getting started instructions

conf.yaml
Related to https://github.com/elastic/dev/issues/1659
As MS-55 has now been deployed in ESS production, this PR bumps the docs to use MS 55 as current for ESS and the Heroku docs
=> Change current to MS 55 for ESS

README.asciidoc, resources/web/docs_js/__tests__/docs.test.js, resources/web/docs_js/components/console_widget.jsx, resources/web/docs_js/localization.js
Super minor nit PR:
Per the [official site][0] and its [creator][1], the `curl` command-line tool should not be in camel case. This updates our `copy as curl` button accordingly.
Stumbled upon this when writing https://github.com/elastic/elasticsearch/pull/71331.
[0]: https://curl.se/
[1]: https://daniel.haxx.se/docs/curl-vs-libcurl.html
=> Fix capitalization for 'curl'

shared/attributes.asciidoc
Updated for new Fleet Server that will be added in 7.13.
=> Add Fleet Server to shared attributes list

conf.yaml, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
* Adds a new unreleased 1.10 branch to the version selector.
* Updates the stack version mappings to this new version.
`current` version will be updated when ECS 1.10 releases.
=> Add ECS 1.10 branch in prep for release

conf.yaml
We started releasing 6.x versions some time ago, but forgot about updating the docs.
I left 5.x as a live branch as it is the last version of the agent to support Python 2.7. 6.x+ only supports Python 3.
We added an item to our release checklist to avoid this from happening going forward. See https://github.com/elastic/apm-agent-python/pull/1109
=> added 6.x branch to elastic/apm-agent-python

conf.yaml, shared/versions/stack/7.13.asciidoc
Won't pass until all books publish a `7.13` branch.
- Adds 7.13 to include/exclude lists in central config file
- Adds shared attributes file for 7.13
- Changes 7.x shared attributes to reference 7.14
=> Add 7.13 branch

resources/web/air_gapped_template.html, resources/web/template.html
In the hosted docs, the copyright statement is in a footer injected via
JavaScript. This change makes sure the HTML output itself contains the
copyright statement as well.
cc: @AnneB-SEO @pchang7092
=> Add copyright notice to HTML templates

conf.yaml, doc_build_aliases.sh
Placeholder files in https://github.com/elastic/observability-docs/pull/603 must be merged before the CI will pass.
=> Get Fleet Developer Guide building

conf.yaml
This PR updates the version for our Terraform provider docs to be in step with https://github.com/elastic/terraform-provider-ec/blob/master/CHANGELOG.md. Need to do a full rebuild after the PR gets merged.
=> Change Cloud Terraform provider version

shared/attributes.asciidoc
This PR adds a shared attribute for terms "Elastic Maps Service" and "EMS" and for its URL https://maps.elastic.co/
Related to https://www.elastic.co/guide/en/kibana/master/maps-connect-to-ems.html
=> Adds shared URL for EMS

conf.yaml
Related to elastic/dev#1672
As MS-56 has now been deployed in ESS production, this PR bumps the docs to use MS 56 as current for ESS and the Heroku docs.
=> Update docs for ESS to ms-56 branch

conf.yaml
This adds the ECK 1.6 branch to the build list. ECK 1.6.0 is planned for release on May 25th.
=> Add ECK 1.6 to docs

doc_build_aliases.sh
Removes the `$GIT_HOME/beats/x-pack/elastic-agent/docs` resource because it no longer exists. The alias as previously written fails with errors.
=> Remove resource that no longer exists

conf.yaml
This PR promotes ECK 1.6 docs as current. Should be merged on May 25 after #2120  is merged and ECK 1.6 is released.
=> Promote ECK 1.6 to current

conf.yaml
This PR changes current to MS 57 for ESS for the new release and removed the older MS 56 release.
=> Update docs for ESS to ms-57 branch

shared/attributes.asciidoc
This PR copies the attribute hosted-ems from https://github.com/elastic/kibana/blob/master/docs/maps/index.asciidoc so that it can be used elsewhere too.
=> Adds shared attribute for Elastic Maps Server

conf.yaml, shared/versions/stack/7.13.asciidoc, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
We released v.1.10 of the .NET APM Agent.
This PR sets this version as current for the docs.
Full disclosure: I'm not 100% sure which files under `shared/versions/stack` we need to update - let me know if I need to change other files or revert some of the changes there.
=> Add .NET APM agent 1.10 branch as current 

conf.yaml
=> Make ECS 1.10 the current release

build_docs.pl, integtest/spec/all_books_broken_link_detection_spec.rb
Fixes https://github.com/elastic/docs/issues/2117
Adds both PLUGIN_DOCS and KIBANA_DOCS variables to align with https://github.com/elastic/kibana/blob/master/src/core/public/doc_links/doc_links_service.ts
=> Adds more variables to Kibana link checker

shared/attributes.asciidoc
Per https://github.com/elastic/kibana/pull/93597, in 7.13.0 and later releases, the Stack Management > "Alerts and Actions" app in Kibana is renamed to "Rules and Connectors". Since we cannot change the shared attribute "alerts-ui" across all the versions that use this file, I've added a new "rules-ui".
=> Add shared attribute for Rules and Connectors

build_docs.pl, integtest/spec/all_books_broken_link_detection_spec.rb
https://github.com/elastic/kibana/pull/102660 added a FLEET_DOCS variable to the documentation link service.
This PR makes changes similar to https://github.com/elastic/docs/pull/2132 so that this variable is handled properly in the doc build checks.
=> Adds FLEET_DOCS to Kibana link checker

conf.yaml
Updates the docs to point to the latest branch (`1.4.0`).
=> Update ecctl docs for 1.4 branch

conf.yaml
With https://github.com/elastic/stack-docs/pull/1722, we no longer need to include the ES glossary as a source.
Once this is merged, I'll remove the ES glossary with https://github.com/elastic/elasticsearch/pull/74579.
=> Remove ES glossary from Stack glossary dependencies

shared/attributes.asciidoc
Adding attributes for the time units & byte units sections that are cross-linked from outside of the ES guide.
=> Add attributes for units sections

conf.yaml, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
- Adds a new unreleased 1.11 branch to the version selector.
- Updates the stack version mappings to this new version.
- current version will be updated when ECS 1.11 releases.
=> Add ECS 1.11 branch in prep for release

shared/attributes.asciidoc
Now that the units sections are in the API conventions, these can point to the correct subsections.
=> Updated units attributes to point to correct anchors

resources/web/style/img.pcss
Link to preview: https://docs_2153.docs-preview.app.elstc.co/guide/index.html
About a year ago, a PR was merged that added padding around images. The change reduced the size of our images to 85% of the original size, resulting in many screen captures that are difficult to read. Most teams did not have an opportunity to review the PR and assess the impact on their published docs.
This PR proposes that we remove the extra padding to maximize the space available for screen captures. (Manipulating the viewport size to get a larger font size in the screen capture is not a good solution to this problem because it forces odd text wraps in the captured screen.)
I've requested a review from @gtback, but I'd like for all the writing teams to weigh in.
Here are some screens that show the difference. …
=> Remove extra padding around images

conf.yaml, doc_build_aliases.sh
Related to https://github.com/elastic/docs/pull/2141
With https://github.com/elastic/stack-docs/pull/1771, we no longer need to include the Kibana glossary as a source.
=> Remove Kibana glossary from Stack glossary dependencies

conf.yaml
This adds the ECK 1.7 branch to the build list. ECK 1.7.0 is planned for release on Tue, Aug 3 2021
=> Add ECK 1.7

conf.yaml
This PR promotes the ECK 1.7 release branch to current.
It depends on #2161, which should be merged first, I am submitting this early to get approval. It should only be merged on Tue, Aug 3 after ECK 1.7 is released.
=> Promote ECK 1.7 to current

shared/attributes.asciidoc
These attributes are useful in the What's New "other versions" links.
=> Add shared attributes for kibana-ref-all and security-guide-all

shared/attributes.asciidoc
The "index pattern management" feature is referenced from places like https://www.elastic.co/guide/en/kibana/master/index-patterns.html and https://www.elastic.co/guide/en/machine-learning/master/setup.html, so this pr adds an attribute as a shortcut
=> Add attribute for index pattern management

conf.yaml
This PR depends on https://github.com/elastic/docs/pull/2174
It cannot be merged until *after* a "main" branch is created in the stack-docs repo.
=> Add main branch in stack-docs repo to doc builds

conf.yaml
The master branch has been renamed to "main" in https://github.com/elastic/go-elasticsearch, which is resulting in the following docs build error:
> 09:06:59 INFO:build_docs:Error executing: git rev-parse master in GIT_DIR /docs_build/.repos/go-elasticsearch.git
09:06:59 INFO:build_docs
This PR makes the necessary changes to pull from main instead of master.
=> Adds main branch for go-elasticsearch repo

conf.yaml
This PR depends on https://github.com/elastic/docs/pull/2174
It cannot be merged until *after* a "main" branch is created in the stack-docs repo.
=> Add main branch in security-docs repo to doc builds

conf.yaml
The books that currently map "main" branches to a "master" output are currently still using "master" in their list of "live" branches, which causes that branch to disappear from the drop-down:
This PR updates the conf.yaml to include a "stacklivemain" attribute to address this problem.
=> Add list of live branches that includes main

conf.yaml, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
* Adds a new unreleased 1.12 branch to the ECS version selector.
* ~Remove 1.x branch; ECS 1.12 is the last planned ECS 1.x version.~ **Update:** Will address in separate PR
* Update the 7.x version mappings to point to ECS 1.12
* Update the master version mappings to point to ECS master
`current` version will be updated later when ECS 1.12 releases.
=> Add ECS 1.12 branch in prep for release

conf.yaml
Remove the ECS `1.x` branch from `conf.yaml` in the docs config.
=> Remove ECS 1.x branch

conf.yaml
This PR adds a main branch to the `elasticsearch-js` repo in the conf.yml file of the docs build system.
**It cannot be merged until _after_ a "main" branch is created in the elasticsearch-js repo.**
=> Add main branch to elasticsearch-js repo to docs build

conf.yaml
This PR adds a main branch to the `elasticsearch-py` repo in the conf.yml file of the docs build system.
**It cannot be merged until _after_ a "main" branch is created in the elasticsearch-py repo.**
=> Add main branch to elasticsearch-py repo to docs build

shared/attributes.asciidoc
Related to https://github.com/elastic/kibana/pull/109928 and https://github.com/elastic/kibana/pull/110283
This PR adds shared attributes for data views, so that the terminology can be used appropriately across the library.
This new terminology is specific to 8.0. For earlier branches,  we must either (a) not use the shared attributes, or (b) override them as was done in https://github.com/elastic/kibana/blob/7.x/docs/index.asciidoc
=> Adds data view shared attributes

conf.yaml
This PR adds a main branch to the `enterprise-search-python` repo in the conf.yml file of the docs build system.
**It cannot be merged until _after_ a "main" branch is created in the enterprise-search-python repo.**
=> Adds main branch to enterprise-search-python repo to docs build

.gitignore, conf.yaml, renderconf.py, schema.yaml
I also added a script that's used to test changes to ensure YAML refactors don't change the interpreted meaning. I used the script when making this change to ensure that the build would interpret conf.yaml the same way before and after this change.
=> Move shared variables in conf.yaml to the top

shared/attributes.asciidoc
Adds a shared attribute to use across docs that need to link to the externally published integrations doc.
=> Add shared attribute for external integrations documentation

conf.yaml
This PR adds a main branch to the `enterprise-search-ruby` repo in the conf.yml file of the docs build system.
**It cannot be merged until _after_ a "main" branch is created in the enterprise-search-ruby repo.**
=> Adds main branch to enterprise-search-ruby repo to docs build

conf.yaml
This PR adds the integrations developer guide to the documentation build.
~Blocked by https://github.com/elastic/observability-docs/pull/769.~
=> Add Integrations developer guide to build

conf.yaml
This PR adds a main branch to the `eland` repo in the conf.yml file of the docs build system.
**It cannot be merged until _after_ a "main" branch is created in the eland repo.**
=> Adds main branch to eland repo to docs build

build_docs.pl, integtest/spec/all_books_broken_link_detection_spec.rb
This PR adds `APM_DOCS` variable to align with https://github.com/elastic/kibana/blob/master/src/core/public/doc_links/doc_links_service.ts
Related to https://github.com/elastic/kibana/pull/110992
=> Adds apm_docs variable to Kibana link checker

conf.yaml
This changes "current" for the Cloud ESS docs to MS-62.
=> ESS - Change current to MS-62

integtest/spec/single_book_spec.rb, resources/asciidoctor/lib/docbook_compat/extension.rb, resources/asciidoctor/spec/docbook_compat_spec.rb, shared/versions/stack/7.11.asciidoc, shared/versions/stack/7.12.asciidoc, shared/versions/stack/7.13.asciidoc, shared/versions/stack/7.14.asciidoc, shared/versions/stack/7.15.asciidoc, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
Eventually, we'll want to remove the x-pack role from the Asciidoc for
all sections/headers that include it, but until then this will at least
hide the visual indicator and link. The `xpack` class will be included
on the surrounding divs, since this is the default Asciidoctor behavior
for "role" tags.
Fixes #2207.
=> Hide X-Pack tags on versions 7.11 and later

conf.yaml
This reverts commit 43369f0d818cd7943fd119129f0276d7243d0e40.
This revert is necessary since it seems that doc build PR checks (where the PR is opened against the master branch) are no longer able to correctly determine that there are differences in the docs (which are building from the main branch) and generate a preview. For example, a test PR (https://github.com/elastic/kibana/pull/112033) was incorrectly indicating that `There aren't any differences!`
=> Revert "Switch from master to main for kibana repo (#2211)"

shared/attributes.asciidoc
This PR adds a shared attribute for the plural form of Elastic Agents, since it's needed for pages like https://www.elastic.co/guide/en/fleet/current/elastic-agent-installation-configuration.html and https://github.com/elastic/kibana/pull/112138
=> Add shared attribute for Elastic Agents

conf.yaml
This PR renames the deprecated Java API book to Java Transport Client in `conf.yml`.
Related to https://github.com/elastic/elasticsearch/pull/77852
=> Renames deprecated Java API to Java Transport Client

conf.yaml
We are about to release ECK 1.8.0, this commit adds the 1.8 branch
to the list of branches to build docs for.
Note this should be merged slightly before the release.
=> Add ECK 1.8 to the list of ECK branches

conf.yaml
This sets up ECK 1.8 as the current ECK release.
Note this should not be merged before the release date.
https://github.com/elastic/docs/pull/2218 should be merged first so we have extra time to double-check everything is correct :) 
(I can handle both merges)
=> Set ECK 1.8 as the current docs branch

lib/ES/Book.pm
This code was looking in directories named after the branch, not the
version. As a result, we weren't getting version dropdowns in the TOCs
on the right side of the page when the version (directory) didn't match
the branch.
Fixes #1930
=> Fix building TOCs when version != branch

shared/attributes.asciidoc
Adds shared attributes for APM pull requests and issues.
The list of breaking changes in APM are re-used in the Installation and Upgrade Guide (https://www.elastic.co/guide/en/elastic-stack/current/apm-breaking-changes.html), but the generic "pull" attribute is misunderstood in that context.
=> Adds apm PR shared attributes

conf.yaml
**DO NOT MERGE BEFORE SEPTEMBER 21**
Updates the branches for: ECE, ecctl and the Terraform Provider for the
upcoming ECE 2.12.0 release.
**DO NOT MERGE BEFORE SEPTEMBER 21**
=> ece: Update branches for upcoming 2.12.0 release

conf.yaml
=> Make ECS 1.12 the current release

conf.yaml
This PR removes the `elasticsearc-java` repo from the sources of the Java REST Client book.
**DO NOT merge before https://github.com/elastic/elasticsearch/pull/78368** ✅
=> Removes es-java from Java REST Client book sources

doc_build_aliases.sh
As https://github.com/elastic/docs/pull/2231 removed the `elasticsearch-java` content from the Java REST Client book, it's no longer needed to have the repo as a resource in the doc build alias of the book. This PR removes the resource from the alias.
=> Removes es-java repo resource from Java REST Client doc build alias

conf.yaml
This PR creates a new book under **Elasticsearch Clients** called `Java API`. It contains the `elasticsearch-java` and `elasticsearch` repositories as sources.
**DO NOT merge before https://github.com/elastic/docs/pull/2231**
=> Adds new Java API book to Clients

conf.yaml
This PR adds the `client` folder of the elasticsearch repo to the source of the Java API book.
Related to: https://github.com/elastic/elasticsearch-java/pull/21
=> Adds ES client folder to Java API book sources

conf.yaml
This PR adds the whole `java-rest` folder to the source of the Java API book instead of `java-rest/low-level` as `java-rest` contains a license file that needs to be included.
Related to: https://github.com/elastic/elasticsearch-java/pull/21
It fixes the following build error:
```
INFO:build_docs:asciidoctor: ERROR: ../../elasticsearch/docs/java-rest/low-level/index.asciidoc: line 34: include file not found: /tmp/docsbuild/766KTRSny9/elasticsearch/docs/java-rest/license.asciidoc
```
=> Adds ES java-rest folder to Java API book sources

shared/attributes.asciidoc
This PR adds a new attribute to the `shared/attributes.asciidoc` file that substitutes the URL of the Java API Client guide.
=> Adds shared attribute for the new Java API Client

doc_build_aliases.sh
This PR adds a new docs build alias to `doc_build_aliases.sh` that generates the newly added Java API book.
=> Adds build alias for the new Java API book

conf.yaml
This PR stops publishing the `master` version of the Java REST Client book by updating the conf.yml file.
**Do NOT merge before the following PRs that provide redirects:**
* https://github.com/elastic/stack-docs/pull/1844
* https://github.com/elastic/elasticsearch-java/pull/29
* https://github.com/elastic/elasticsearch/pull/78613
=> Stops publishing master version of Java REST Client book

conf.yaml
Changes the name of the Fleet User Guide as described in https://github.com/elastic/observability-docs/issues/1104.
@gtback I think we should change the following settings, too, but TBH, I don't remember how these settings are used, so I'm unsure what settings make sense.
````
tags:       Fleet/Guide
subject:    Fleet
````
Maybe this?
````
tags:       Fleet/Elastic Agent/Guide
subject:    Fleet and Elastic Agent
````
=> Rename Fleet User Guide

conf.yaml
This changes "current" for the Cloud ESS docs to MS-64.
=> ESS - Change current to MS-64

conf.yaml, schema.yaml
This PR updates the conf.yaml to build from 7.16 branches instead of 7.x branches (with the exception of the client docs, which I'm presuming will continue to use 7.x).
=> Update conf.yaml for 7.16

shared/attributes.asciidoc
Fixes attribute that uses old path for Fleet docs. I should have changed this when we changed the path to all versions of the book.
After this PR is merged, we should be able to remove all the old files under https://github.com/elastic/built-docs/tree/master/html/en/ingest-management
=> Updates shared attributes to remove old path to fleet docs

conf.yaml
The APM breaking changes have moved from `docs/guide` to `docs/`.
I think this is why I keep seeing the following error in https://github.com/elastic/stack-docs/pull/1850
```
14:27:49 INFO:build_docs:ERROR building Installation and Upgrade Guide version master
14:27:49 INFO:build_docs:asciidoctor: ERROR: breaking.asciidoc: line 32: include file not found: /tmp/docsbuild/USkIJ27emi/apm-server/docs/apm-breaking.asciidoc
```
=> Change Installation and Upgrade Guide path to apm-server repo

conf.yaml
Based on the suggestion shared [here](https://github.com/elastic/docs/pull/2260#pullrequestreview-789637003), adding a `live` branch list for the ECS documentation.
=> Add live branches for ECS docs

.rubocop.yml, build_docs.pl, integtest/Makefile, integtest/spec/all_books_broken_link_detection_spec.rb, integtest/spec/all_books_change_detection_spec.rb, integtest/spec/helper/repo.rb
We need to look at the 'main' branch when checking links for 'master' in the output.
=> Fix Kibana link checking

conf.yaml
This PR removes the APM Server Reference and APM Overview from Elastic's documentation build.
```
17:17:25 INFO:build_docs:Bad cross-document links:
17:17:25 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/auditbeat/7.x/auditbeat-installation-configuration.html contains broken links to:
17:17:25 INFO:build_docs:   - en/apm/get-started/master/index.html
17:17:25 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/auditbeat/7.x/configuration-instrumentation.html contains broken links to:
17:17:25 INFO:build_docs:   - en/apm/server/master/api-key.html
17:17:25 INFO:build_docs:   - en/apm/server/master/getting-started-apm-server.html
17:17:25 INFO:build_docs:   - en/apm/server/master/secret-token.html
17:17:25 INFO:build_docs: …
```
=> Stop building APM Server and Overview books

Dockerfile, yarn.lock
When running the `build_docs` script on an ARM mac docker creates an ARM image, which requires additional deps in order to build native NPM modules installed in the container.
=> [docs] add build deps for installing native npm deps in ARM images

README.asciidoc, build_docs
=> Updated shebang to explicitly state python3 (to work via WSL)

shared/attributes.asciidoc
https://github.com/elastic/elasticsearch/pull/79162 reorganized the ES breaking changes. The PR added [attributes](https://github.com/jrodewig/elasticsearch/blame/101809cc6a10761f609832ba3708d4c5124ca02e/docs/reference/migration/index.asciidoc#L4-L5) to help Cloud users know which changes to skip or review.
This adds those attributes to the docs repo so they can be reused in the Installation and Upgrade Guide. The copy was already approved as part of https://github.com/elastic/elasticsearch/pull/79162.
=> [DOCS] Add attributes for ESS breaking changes

conf.yaml
Change `master` --> `main` in obs-docs. This will fail for now.
Closes https://github.com/elastic/observability-docs/issues/991.
=> docs: add main branch to obs-docs

resources/web/style/list.pcss
Currently, lists that follow paragraphs get mushed together in tabbed widgets. This change aims to fix that smushing.
=> Update lists that follow paragraphs

conf.yaml
required versioned book references as it was blocking for https://github.com/elastic/kibana/issues/118591
=> Add 7.16 version of PHP & .NET client books

conf.yaml
This changes "current" for the Cloud ESS docs to MS-65.
Cloud MS-65 release is planned for Tuesday, Nov.9.
=> ESS - Change current to MS-65

build_docs.pl, integtest/spec/all_books_broken_link_detection_spec.rb
This PR adds STACK_GETTING_STARTED, STACK_DOCS, and SECURITY_SOLUTION_DOCS variables to align with the variables in the Kibana documentation link service
=> Add stack and security variables to Kibana link check

build_docs.pl, integtest/spec/all_books_broken_link_detection_spec.rb
This PR adds APP_SEARCH_DOCS, ENTERPRISE_SEARCH_DOCS, and WORKPLACE_SEARCH_DOCS variables to align with the variables in the Kibana documentation link service
Related to https://github.com/elastic/kibana/pull/118814
=> Adds search variables to Kibana link checker

conf.yaml
Moves Journalbeat docs to the legacy section and stops building them in master, 8.0, and 7.16 branches.
Related docs PRs:
* https://github.com/elastic/beats/pull/29134
* https://github.com/elastic/beats/pull/29135
* https://github.com/elastic/beats/pull/29136
* https://github.com/elastic/stack-docs/pull/1893
* https://github.com/elastic/stack-docs/pull/1894
* https://github.com/elastic/stack-docs/pull/1895
* https://github.com/elastic/beats/pull/29137
Dev PR: https://github.com/elastic/beats/pull/29131
=> Move Journalbeat to legacy section and turn off 7.16+ builds

shared/attributes.asciidoc
Adds attribute to resolve path to the integrations developer guide.
@bmorelli25 Should we set this to `current` since we are not building in multiple branches?
=> Add attribute for the integrations developer guide

shared/versions/stack/8.0.asciidoc
Copies changes from #2300 to attributes for the 8.0 branch.
=> Add `prev-major-last` attr to 8.0 branch

conf.yaml
This changes "current" for the Cloud ESS docs to MS-66.
=> ESS - Change current to MS-66

conf.yaml
https://github.com/elastic/elasticsearch-java/pull/52 pulls code snippets in the document from test source code, which is not checked out by the docs build process.
This PR adds the path to that test source code in the `elasticsearch-java` (`java-api-client`) configuration.
=> Add elasticsearch-java doc code snippets directory

conf.yaml, shared/attributes.asciidoc, shared/versions/stack/7.15.asciidoc, shared/versions/stack/7.16.asciidoc, shared/versions/stack/current.asciidoc
=> Bump current version to 7.16

conf.yaml
Moves the APM Server Reference and APM Overview to the Legacy docs section of elastic.co/guide.
Merge after https://github.com/elastic/docs/pull/2299.
=> Move APM Reference and Overview to Legacy section

conf.yaml
This PR sets the ECK 1.9 branch as the current version.
I am submitting this early to get approval. It should only be merged after #2301 is merged and ECK 1.9 is released.
=> Promote ECK 1.9 branch to current

conf.yaml, doc_build_aliases.sh, shared/attributes.asciidoc
Relates to: https://github.com/elastic/docs.elastic.co/issues/1
Foundation for: https://github.com/elastic/elastic-docs-next/issues/335
---
Adds an "Elastic level" to the docs.
This is for:
1. @debadair's upgrade guide consolidation for 8.0
2. @goodroot's unified integration changes for 7.16
Content is located in a separate content repository: https://github.com/elastic/tech-content
DRAFT mode until more of the pieces land.
=> Add "Elastic" level

conf.yaml
This PR deprecates the Java REST Client book in favor of the Java API Client book. The PR appends the word `(deprecated)` to the book title and moves it down in the TOC of ES Client books.
**This PR needs to be merged after the 7.16 version release.**
Related PR: https://github.com/elastic/elasticsearch/pull/81513
=> Deprecates Java REST Client book

conf.yaml
Not sure how I missed this. Updating for 7.16 docs.
=> Use `*stackcurrent` for APM Guide

shared/versions/stack/7.16.asciidoc
Bumps version to `7.16.1`.
**DO NOT MERGE UNTIL RELEASE DAY.**
=> [DOCS] 7.16.1 version bump

doc_build_aliases.sh
Updates alias file by removing the Fleet Developer Guide, which no longer exists, and adding the Integrations Developer Guide.
=> Add alias for Integrations Developer Guide

conf.yaml, doc_build_aliases.sh
Adds a separate docbook for the legacy elasticsearch.js client docs.
We plan to remove similar docs from the current Elasticsearch JavaScript client docbook as part of https://github.com/elastic/docs/issues/2317.
Legacy docs: https://docs_2318.docs-preview.app.elstc.co/guide/en/elasticsearch/client/elasticsearch-js/current/index.html
TOC: https://docs_2318.docs-preview.app.elstc.co/guide/index.html
=> [DOCS] Add docbook for legacy elasticsearch.js client

conf.yaml
Some repositories have been changed from default `master` branch to `main`.
Relates:
- https://github.com/elastic/ecs-logging-ruby/pull/24
- https://github.com/elastic/ecs-logging-python/pull/75
- https://github.com/elastic/ecs-logging-php/pull/36
- https://github.com/elastic/ecs-logging-nodejs/pull/111
- https://github.com/elastic/ecs-logging-java/pull/160
- https://github.com/elastic/ecs-logging-go-zap/pull/41
- https://github.com/elastic/ecs-logging-go-logrus/pull/16
- https://github.com/elastic/ecs-logging/pull/65
- https://github.com/elastic/ecs-dotnet/pull/172
=> obs11: first batch to use main branch

conf.yaml
Removes the 16.x branch from the Elasticsearch JavaScript client docs.
This docs are now published as the [legacy elasticsearch.js docs](https://www.elastic.co/guide/en/elasticsearch/client/elasticsearch-js/current/index.html).
Merging is blocked until we confirm redirects are in place.
=> Remove 16.x branch from ES JS client docs

conf.yaml, shared/versions/stack/master.asciidoc
Adds the `8.1` ECS branch and points the stack `master` to ECS 8.1.
I am sharing some background for why the stack `master` branch will no longer point to ECS `master` (`main`).
With upcoming ECS versions aligned with stack versioning, ECS is adopting a [new process](https://docs.google.com/document/d/1z8KXg8UdSpyE_0eUfXTqWa4QOac_0RHoIDA-xeBGfj4/edit#) to communicate better and align upcoming schema changes. ECS will enter a Soft Feature Freeze (SFF) one release in advance* of the stack. Some teams kick off their development cycles for a minor release as soon as the FF happens for the previous one, so this schedule would mean that the next version of ECS would be stable enough to start consuming in development.
With this change, the `main` ECS branch pointing ECS 8.2 and is ahead of the …
=> Add ECS 8.1 branch

shared/attributes.asciidoc
The `eland-docs` attribute in https://github.com/elastic/docs/blob/master/shared/attributes.asciidoc has an incorrect URL, which results in broken links. The correct URL should match https://www.elastic.co/guide/en/elasticsearch/client/eland/master/installation.html
=> Fixes eland-docs attribute

conf.yaml, doc_build_aliases.sh
Preview: https://docs_2326.docs-preview.app.elstc.co/guide/en/enterprise-search-clients/index.html
Closes: https://github.com/elastic/enterprise-search-team/issues/888
=> Add docs for Enterprise Search JavaScript clients

conf.yaml
Amends https://github.com/elastic/docs/pull/2309 by moving legacy APM books back to `/en/apm/*`.
=> Move legacy APM books back to `/en/apm/*`

shared/attributes.asciidoc
Relates to https://github.com/elastic/docs/pull/2327
Since there is only a single version of the Eland client documentation at this time, the eland-docs attribute must use `current` as its version, otherwise links from branches other than master fail.
If more versions are added to this book in the future, we can handle it more like`ecs-logging-ref`, for example.
=> Update version in eland-docs attribute

shared/versions/stack/6.8.asciidoc
We recently updated some Logstash plugins and made them available for 6.8 as part of our log4j response.  So this means that the ECS support in plugins is now available in Logstash 6.8. The Logstash plugin lockfile was updated to allow these docs changes to get picked up.  Before now, we haven't needed to resolve the `{ecs_version}` attribute for the 6.8 branch, but now we do.  (See broken links in https://github.com/elastic/logstash-docs/pull/1244.) 
I can think of several ways to approach this fix, but I believe that adding the attribute to the 6.8 shared version file is the best approach.  
@lcawl @ebeahan @yaauie: What do you think about this approach?  Here are my thoughts: 
- If no other doc set is calling the {ecs-version} attribute for 6.8, I don't think we'll break anything. Can …
=> Add ecs-version attribute to 6.8 versioning file

conf.yaml
Relates to https://github.com/elastic/cloud-on-k8s/issues/5017.
NOTE: I will take care of the merge once the renaming of the branch is effective.
=> Add main branch to the cloud-on-k8s repo docs build

conf.yaml
bumps ecctl to 1.7 which was released in dec
=> bump ecctl to 1.7

conf.yaml
Related to https://github.com/elastic/dev/issues/1814
Updates the branches for: ECE, ecctl for the
upcoming ECE 2.13.0 release.
=> Update branches for 2.13.0 release

shared/attributes.asciidoc, shared/cloud/ess-getting-started-obs.asciidoc, shared/cloud/ess-getting-started.asciidoc
Closes https://github.com/elastic/docs/issues/2343
The widgets are used in the Kibana Quick Start, the Elasticsearch Quick Start, and the Observability docs (the Spin up the cluster page, which gets called from all over).  As far as I can tell, these are the only docs that use the widgets, but I did not search through every repo.  Here are before and after screenshots:
Note 1:
I don't think that the tag used to differentiate between Observability without APM and Observability with APM use cases is needed any longer.  APM is always deployed.  I removed the ifndef logic and added a note that the Cloud ID and APM endpoint are available from the deployment page.
Note 2:
I added an attribute for the Cloud Deployments page and included the tags used by Marketing to track the referrals we send …
=> bring widgets up to date with Cloud UI

conf.yaml
Neutral naming of git branches for the elastic/apm-agent-ruby
**Requires** elastic/apm-agent-ruby#1219
Similar to https://github.com/elastic/docs/pull/2323
=> [apm] main branch for apm-agent-ruby

shared/attributes.asciidoc
=> Add 7.last attribute for APM Guide

conf.yaml
Neutral naming for elastic/apm-agent-php
**Requires** https://github.com/elastic/apm-agent-php/pull/606
=> apm: Neutral naming for apm-agent-php

conf.yaml
Neutral naming for elastic/apm-agent-go
**Requires** https://github.com/elastic/apm-agent-go/pull/1197
=> apm: Neutral naming for apm-agent-go

conf.yaml
Neutral naming of git branches for the elastic/apm-agent-nodejs
**Requires** https://github.com/elastic/apm-agent-nodejs/pull/2535
=> apm: Neutral naming for apm-agent-nodejs

conf.yaml
Neutral naming of git branches for the elastic/apm-agent-dotnet
**Requires** https://github.com/elastic/apm-agent-dotnet/pull/1606
=> apm: Neutral naming for apm-agent-dotnet

conf.yaml
Neutral naming of git branches for the elastic/apm-agent-rum-js
**Requires** https://github.com/elastic/apm-agent-rum-js/pull/1141
=> apm: Neutral naming for apm-agent-rum-js

conf.yaml
Neutral naming for elastic/apm-agent-python
Requires https://github.com/elastic/apm-agent-python/pull/1447
=> apm: Neutral naming for apm-agent-python

shared/attributes.asciidoc
With https://github.com/elastic/elasticsearch/pull/81870, we migrated docs for the Azure, GCS, and S3 snapshot repositories to the ES guide from the ES plugin docs. However, this change only applies to Elastic 8.0+.
These attributes let the Cloud docs link to the "plugin" version of the docs when referencing 7.x and 6.x Elastic deployments without breaking links.
Relates to https://github.com/elastic/cloud/pull/95621 and https://github.com/elastic/docs/pull/2312
=> [DOCS] Add `plugins-7x` and `plugins-6x` attributes

README.asciidoc, integtest/spec/single_book_spec.rb, resources/asciidoctor/lib/care_admonition/extension.rb, resources/asciidoctor/spec/care_admonition_spec.rb
Adds a new macro for tech preview, updates old experimental macro to keep them both.
Closes https://github.com/elastic/docs/issues/2305.
=> Adds tech preview macro, updates experimental

conf.yaml
The https://github.com/elastic/package-spec repo's master branch has been renamed, therefore the conf.yaml needs to be updated. Otherwise, it's causing the following failures:
> 08:08:33 INFO:build_docs: -                      Elasticsearch Guide: Finished 7.16
08:08:46 INFO:build_docs:Error executing: git rev-parse master in GIT_DIR /docs_build/.repos/package-spec.git
08:08:46 INFO:build_docs:---out---
08:08:46 INFO:build_docs:master
08:08:46 INFO:build_docs:
08:08:46 INFO:build_docs:---err---
08:08:46 INFO:build_docs:fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
=> Remove unnecessary branch mapping for package-spec

conf.yaml
This changes "current" for the Cloud ESS docs to MS-68.
=> ESS - Change current to MS-68

conf.yaml
Neutral naming for elastic/apm-agent-java
**Requires** https://github.com/elastic/apm-agent-java/pull/2401
=> apm: Neutral naming for apm-agent-java

build_docs.pl
Required for https://github.com/elastic/kibana/pull/123818 / https://github.com/elastic/kibana/issues/95389
Add the new package path for Kibana links checking
=> add new path for kibana links check

conf.yaml, shared/attributes.asciidoc, shared/versions/stack/7.16.asciidoc, shared/versions/stack/7.17.asciidoc, shared/versions/stack/current.asciidoc
Bumps the Elastic documentation to version 7.17.
=> Bump current version to 7.17

README.asciidoc
When trying to confirm the issues on https://github.com/elastic/beats/pull/30014 I found this readme, but it wasn't clear that I needed a full path until I started reading through https://github.com/elastic/docs/blob/master/doc_build_aliases.sh
Seemed like we should probably clarify that a full path is expected.
=> Note that the full path is required for local doc build

conf.yaml
This PR adds a main branch to the `elasticsearch-net` repo in the conf.yml file of the docs build system.
**It cannot be merged until _after_ a "main" branch is created in the elasticsearch-net repo.**
=> Add main branch to elasticsearch-net repo to docs build

conf.yaml
I'll transition to ready and poke you around when we can move forward
Neutral name branch for elastic/apm-server
Requires https://github.com/elastic/apm-server/pull/7098
=> Rename master to main for APM Server project

resources/asciidoctor/lib/care_admonition/extension.rb, resources/asciidoctor/spec/care_admonition_spec.rb, resources/asciidoctor/spec/elastic_compat_preprocessor_spec.rb
Updates the old `experimental` admonition to use `preview` text when displayed inline.
Relates to https://github.com/elastic/docs/pull/2340
**Before**
**After**
=> Update text for inline experimental admon

conf.yaml, shared/versions/stack/8.1.asciidoc, shared/versions/stack/master.asciidoc
* Creates a new `/stack/versions/8.1.asciidoc` file copied from `master.asciidoc`
* Updates `conf.yaml` to include the 8.1 branch
=> Add 8.1 branch to docs build

conf.yaml
We need this in order to grab the ece-version.asciidoc file that's
included in that directory.
=> Include the whole cloud/docs directory for ECE

conf.yaml
Make the 2.0 branch the current one. To be merged on release day.
=> Promote ECK 2.0 to current

resources/asciidoctor/lib/chunker/extension.rb, resources/asciidoctor/lib/chunker/extra_docinfo.rb, resources/asciidoctor/spec/chunker_spec.rb
By adding a `canonical-url` attribute to a section, the chunked HTML
page for that section will contain a `<link rel="canonical" ...>` tag in
the page header. This tag does not get included in later chunks of the
same input document.
Fixes #2357
=> Support canonical links for section chunks

conf.yaml, shared/versions/stack/8.1.asciidoc
Do not merge. Please let the ECS team merge at release time.
Also correcting 8.1 platform docs to point to ECS 8.1.
=> Make ECS 8.0 the current release

conf.yaml
=> Add config for ECE 3.0.0 and Ecctl 1.8.0

conf.yaml, doc_build_aliases.sh
Relates to https://github.com/elastic/stack-docs/pull/1851
=> Make elasticsearch repo available to Getting Started Guide

conf.yaml
Updates the following ES clients docs to use the `stackcurrent` and `stacklivemain` variables:
- Java
- JavaScript
- Ruby
- Go
- .NET
- PHP
- Python
This will bump the `current` branch for these docs to 8.0. It'll also ensure the clients stay synced with stack releases in the future.
This **does not** update the current version for the Perl or Rust clients.
=> Update ES clients to use `stackcurrent` and `stacklivemain` variables

conf.yaml
This changes "current" for the Cloud ESS docs to MS-70.
=> ESS - Change current to MS-70

conf.yaml
The deprecated HLRC's branch version was not moved forward to the latest 7.x release branch
=> Bump HLRC branch version to 7.17

conf.yaml
Make the 2.1 branch the current one. To be merged on release day.
=> Make 2.1 current ECK branch.

conf.yaml
Will merge this change when ECS 8.1.0 is released.
=> Set 8.1 as the current ECS branch

conf.yaml
DO NOT MERGE BEFORE RELEASE DATE MARCH 8.
This PR changes `current` to 3.1.0.
Related to https://github.com/elastic/dev/issues/1929
=> ECE - change current to ECE 3.1.0

shared/attributes.asciidoc
Relates to https://github.com/elastic/kibana/issues/126956
The [case APIs](https://www.elastic.co/guide/en/security/master/cases-api-overview.html) currently use shared attributes for some of the third-party incident management systems. Some of those attributes are defined only in  https://github.com/elastic/security-docs/blob/8.1/docs/index.asciidoc
Since cases are available across multiple solutions, those attributes also need to be shared.
=> Add shared third-party connectors

conf.yaml
This has the side effect of removing the master version from the published docs, but we expect the impact to be minimal. They were more a side-effect of having a single version than intentional, and were not surfacing in Google searches.
Going forward, we'll publish in sync with the stack versioning.
=> Publish 8.1 branch of Welcome docs

resources/web/template.html
=> Adds license meta

conf.yaml, shared/versions/stack/7.17.asciidoc, shared/versions/stack/8.0.asciidoc, shared/versions/stack/8.1.asciidoc, shared/versions/stack/master.asciidoc
Add the apm-agent-go 2.x branch, and mark it as the current branch. v2.0.0 has just been released.
=> conf.yaml: add apm-agent-go 2.x branch

conf.yaml
This changes "current" for the Cloud ESS docs to MS-71 and should be merged on ms-71 release day.
=> ESS - Change current to ms-71

integtest/spec/all_books_spec.rb, lib/ES/Util.pm, resources/asciidoctor/lib/docbook_compat/convert_document.rb, resources/asciidoctor/spec/docbook_compat_spec.rb
This builds on #1909 and #1434 to allow inserting extra content below the primary heading on Docs Landing pages (like https://www.elastic.co/guide/index.html).
To actually add content, change what's in `extra/docs_landing.html`
=> Add content to docs landing page

conf.yaml, doc_build_aliases.sh
Adds the docs directory in [`elastic/apm-aws-lambda`](https://github.com/elastic/apm-aws-lambda) as a dependency to the following repos:
* `elastic/apm-agent-java`
* `elastic/apm-agent-nodejs`
* `elastic/apm-agent-python`
For https://github.com/elastic/observability-docs/issues/1707.
=> docs: add `apm-aws-lambda` as a dependency

conf.yaml
Follow up to https://github.com/elastic/docs/pull/2404. `main` needs to temporarily map to current for ci to pass. This will be reverted in a future PR.
For https://github.com/elastic/apm-agent-java/pull/2556.
=> More apm aws dependencies

shared/versions/stack/8.1.asciidoc, shared/versions/stack/8.2.asciidoc, shared/versions/stack/master.asciidoc
There will be broken links... seeing what they are
=> docs: bump apm-py back to 6.x

conf.yaml
This PR removes the `7.x` branch from the .NET docs as 7.x has been deleted in the .NET repo.
=> Removes .NET 7.x from docs

conf.yaml
Adds the `2.2` release branch for the upcoming ECK release.
=> Add ECK 2.2 branch

conf.yaml
This changes "current" for the Cloud ESS docs to MS-72 and should be merged on ms-72 release day.
=> ESS - Change current to ms-72

doc_build_aliases.sh
This adds an alias to build the Elastic Cloud on Kubernetes docs:
`docbldeck`
=> Add build alias for ECK

conf.yaml
Will merge this change when ECS 8.2.0 is released.
=> Set 8.2 as the current ECS branch

conf.yaml
Combines and releases MS-73 and MS-74.
This changes "current" for the Cloud ESS docs to MS-74.
=> ESS - Change current to ms-74

doc_build_aliases.sh
This PR updates the doc_build_aliases.sh file to align with the documentation build information in https://github.com/elastic/docs/blob/b09ea3aea2fc8699e132124f51be2cd83340f804/conf.yaml#L609
=> Update docbldela alias

conf.yaml
This changes "current" for the Cloud ESS docs to ms-75 and should be merged on ms-75 release day.
=> ESS - Change current to ms-75

shared/attributes.asciidoc
This attribute is defined in index.asciidoc files in the cloud repo, but those are not available to other content. Therefore, this PR adds it to the list of shared attributes.
It can then be used in PRs like https://github.com/elastic/kibana/pull/134552
=> Add shared attribute for Elasticsearch Service Console

shared/versions/stack/8.0.asciidoc, shared/versions/stack/8.1.asciidoc, shared/versions/stack/8.2.asciidoc, shared/versions/stack/8.3.asciidoc, shared/versions/stack/master.asciidoc
This makes stack links from master, and 8.x point to the 5.x RUM agent documentation. 
Thank you @yakhinvadim for bringing this to our notice!
Example of docs pointing to 4.x:  https://www.elastic.co/guide/en/apm/guide/current/apm-rum.html
**Question:** 
Does the current documentation will start pointing to the new link automatically once this is merged? Or do I need to do something else? Many thanks!!!
=> docs: update versions/stack rum agent

conf.yaml
We want to steer people toward the new onboarding content instead of to the old Stack Getting Started tutorial. The Docker information that's contained in this guide is largely replicated in the Elasticsearch guide and the ES pages appear at the top of the search results. The Kubernetes information is essentially a placeholder so we had something showing up in search results for ES + Kubernetes. Similar to Docker, the ECK docs appear at the top of the search results and are a better destination for people interested in deploying on Kubernetes. 
When this book is removed, we will set up the following redirects:
https://www.elastic.co/guide/en/elastic-stack-get-started/current/index.html
https://www.elastic.co/guide/index.html
https://www.elastic.co/guide/en/elastic-stack-get-started/current …
=> Set the noindex flag on the Stack Getting Started

shared/attributes.asciidoc
When you grant privileges to a role in Kibana, it refers to an "Actions and Connectors" feature. It would be useful to have a shared attribute for this feature name.
=> Add shared attribute for actions and connectors

shared/attributes.asciidoc
We only publish one version of the Welcome guide & the attribute was set up using {branch}.
=> [DOCS] Updated Welcome to Elastic attribute to use current

extra/docs_landing.html
I feel like there's a lot of empty space in the custom header on [elastic.co/guide](https://www.elastic.co/guide/index.html). This PR removes excess margin and padding to tighten things up a bit. I really wanted to figure out to get this to work for the rest of the elements on the page, but unfortunately, it appears that the doc build treats the TOC page the same as every other documentation page, so the only way I could specifically target the TOC H3s was by using jQuery.
Here's a screenshot of this change (or see the [preview](https://docs_2463.docs-preview.app.elstc.co/guide/index.html))
=> Remove excess margin and padding on guide index

conf.yaml
Adds the `2.3` release branch for the upcoming ECK release.
=> Add ECK 2.3 branch

extra/docs_landing.html
This PR changes the Add data link in Featured Topics from the Kibana page to the Cloud page, as discussed in https://github.com/elastic/observability-docs/issues/1759
Also contains additional sentence on Cloud context for Elastic Stack.
=> Update landing page with Add data link and cloud context

conf.yaml
This promotes ECK `2.3` release branch to current.
It should be merged:
* after #2454
* once ECK 2.3 is released
=> Promote ECK 2.3

conf.yaml, shared/versions/stack/8.2.asciidoc, shared/versions/stack/8.3.asciidoc, shared/versions/stack/current.asciidoc
Changes the "current" version of Elastic documentation to 8.3.
=> [Docs release] Bump current version to 8.3

conf.yaml
This changes "current" for the Cloud ESS docs to ms-76 and should be merged on ms-76 release day.
=> ESS - Change current to ms-76

conf.yaml
This changes "current" for the Cloud ESS docs to ms-77 and should be merged on ms-77 release day.
=> ESS - Change current to ms-77

conf.yaml
Adds 8.4 branches to conf.yaml
The documentation builds will fail until all the repos have 8.4 branches:
=> Add 8.4 branch to conf.yaml

shared/attributes.asciidoc
Relates to https://github.com/elastic/kibana/pull/137726
This PR adds shared attributes for the "Webhook" and "Webhook - Case Management" connector names.
=> [DOCS] Add shared attributes for Webhook connectors

conf.yaml
It seems versions after 7.16 never got added to the build.
=> Publish additional branches of enterprise-search-php

doc_build_aliases.sh
This adds an alias so that we can build the proposed / test Logstash and Kubernetes book using `docbldlsk8s`.
=> Add alias for Logstash K8s book

shared/attributes.asciidoc
Adding this attribute to distinguish the App Search web crawler from the new top level Elastic web crawler.
=> Add attribute for App Search web crawler

conf.yaml
Adds an 8.4 branch to conf.yaml specifically for the Enterprise Search PHP Client docs.
Rel: https://github.com/elastic/docs/pull/2483
Prep work for 8.4 release.
=> Add 8.4 branch to conf.yaml for Enterprise Search PHP client

conf.yaml
Adds the `2.4` release branch for the upcoming ECK release.
=> Add ECK 2.4 branch

conf.yaml
Promotes ECK to `2.4`. Has to be merged _after_ https://github.com/elastic/docs/pull/2493.
=> Promote ECK to 2.4

shared/attributes.asciidoc
Ref https://github.com/elastic/observability-docs/issues/2097, https://github.com/elastic/observability-docs/pull/2102
In 8.4 the high-level "Metrics" section of the Observability app will be changed to "Infrastructure". This PR adds an `infrastructure-app` shared attribute. I don't _think_ we want to replace the value of the `metrics-app` attribute since it will continue to be needed in pre-8.4 content, but going forward we should use `infrastructure-app` when referring to this section.
=> Add `infrastructure-app` shared attribute

conf.yaml
Fixes the errors in https://github.com/elastic/observability-docs/pull/2119.
=> Add package-spec/spec dir

extra/docs_landing.html
The getting started doc for Enterprise Search now lives within the Enterprise Search docs. Update the link on the landing page.
https://github.com/elastic/enterprise-search-team/issues/2450
=> Update Enterprise Search getting started for 8.4

conf.yaml
This changes "current" for the Cloud ESS docs to ms-78 and should be merged on ms-78 release day.
=> ESS - Change current to ms-78

shared/versions/stack/master.asciidoc
Related: https://github.com/elastic/docs/pull/2484
Updates attributes in the `shared/versions/stack/master.asciidoc` file.
=> Update `master` attributes for the 8.4 release

shared/versions/stack/8.4.asciidoc
Doc release issue: [#2105](https://github.com/elastic/dev/issues/2105)
=> Version bump for 8.4.1 patch release

doc_build_aliases.sh
This fixes the path in our build aliases file for a proposed Logstash and Kubernetes Guide.
=> Update path for Logstash K8s book

conf.yaml
This changes "current" for the Cloud ESS docs to ms-79 and should be merged on ms-79 release day.
=> ESS - Change current to ms-79

extra/docs_landing.html
This adds a link on the docs landing page to our new [Troubleshooting and FAQs page](https://www.elastic.co/guide/en/welcome-to-elastic/current/troubleshooting-and-faqs.html).
=> Add link on docs landing page for new troubleshooting and FAQs page

shared/versions/stack/8.4.asciidoc
[Doc release issue](https://github.com/elastic/dev/issues/2120)
=> Bump docs version to 8.4.2

shared/attributes.asciidoc
Resolves #2516.
The endpoint integration "Endpoint and Cloud Security" (previously "Endpoint Security") is being renamed to "Elastic Defend."
=> Create new attribute for Elastic Defend

conf.yaml
This PR changes the `current` branch and the `live` branches for the .NET docs. As the 8.0 client is not GA now, it might be confusing for the users to expose 8.1+ versions for the docs. For this reason, this PR sets `current` to 8.0 and stops exposing branches newer than 8.0 in `live`. When the client versioning and stack versioning are aligned, we start exposing those branches again.
DO NOT MERGE BEFORE https://github.com/elastic/elasticsearch-net/pull/6658
=> Changes current and live for .NET Client docs

conf.yaml
This PR updates the conf.yaml to include multiple versions for the welcome guide.  When the 8.5 release is underway, it will also be added to this list.
=> Add master to welcome guide

shared/attributes.asciidoc
This PR must be merged *after* https://github.com/elastic/docs/pull/2529
It updates the `estc-welcome` shared attribute to use the `branch` attribute.
=> Update welcome guide attributes

conf.yaml, shared/versions/stack/master.asciidoc
Related to ECS Soft Feature Freeze 8,6
PR Adds the new version `8.6` to the selector in `conf.yaml`.
PR does not update the `current` attribute
PR adds the new branch to the `branches` attribute and
also adds the upcoming release branch to the `live` attribute.
Maps the upcoming `ecs_version` to the next stack version in `shared/versions/stack/master.asciidoc`
=> ECS Soft Feature Freeze 8.6

conf.yaml, doc_build_aliases.sh, shared/attributes.asciidoc
Adds new APM extension books. Why? See https://github.com/elastic/observability-docs/issues/2207.
=> Add APM extension books

conf.yaml, doc_build_aliases.sh
In https://github.com/elastic/docs/pull/2535, we created standalone documentation books for APM extensions. This PR is a follow-up PR that removes old cross-repo dependencies from the APM Guide. 
Closes https://github.com/elastic/observability-docs/issues/2207.
~This PR will not pass ci yet. Still waiting for the following PRs to be merged and backported:~
=> remove APM Guide includes

conf.yaml
This changes "current" for the Cloud ESS docs to ms-81 and should be merged on ms-81 release day.
=> ESS - Change current to ms-81

resources/web/template.html
The previous image is a 404, so this puts an image on Twitter, Facebook,
etc.
Fixes #2428
=> Update og:image meta tag

conf.yaml
To be merged on release day Elastic Stack 8.5/ECK 2.5
=> Make the ECK 2.5 the current branch

conf.yaml, shared/versions/stack/8.4.asciidoc, shared/versions/stack/8.5.asciidoc, shared/versions/stack/current.asciidoc, shared/versions/stack/master.asciidoc
Changes the "current" version of Elastic documentation to 8.5.
=> [Docs release] Bump current version to 8.5

conf.yaml
This PR changes `current` for the Cloud ECE docs to `3.5.0` based off milestone release `ms-81`
To be merged on the release day, NOV 1.
Relates to https://github.com/elastic/dev/issues/2141
=> ECE - Change current to 3.5.0

shared/versions/stack/8.5.asciidoc
[Doc release issue](https://github.com/elastic/dev/issues/2161)
=> Bumps the version to 8.5.1

shared/attributes.asciidoc
Relates to https://github.com/elastic/kibana/issues/143809
The Stack Management > "Rules and Connectors" app has split into separate "Rules" and "Connectors" apps. Since the "rules-ui" attribute is used in 8.0 and later docs, we must:
1) Create a new "rac-ui" attribute for the old app name for use in 8.0-8.5 docs
2) Create a new "connectors-ui" attribute for the new Connectors app
3) Change the "rules-ui" attribute to use the appropriate label for the new Rules app
This PR accomplishes (1) and (2).  (3) is accomplished in https://github.com/elastic/docs/pull/2568
=> Update attributes for rules and connectors

shared/attributes.asciidoc
This PR must be merged *after* https://github.com/elastic/docs/pull/2567 and https://github.com/elastic/kibana/pull/145500
It updates the "rules-ui" attribute to reflect the new name for the "Rules" app in 8.6+
=> Update attribute for Rules UI

conf.yaml
Adds 8.6 branches to conf.yaml
The documentation builds will fail until all the repos have 8.6 branches:
=> Add 8.6 branch to conf.yaml

shared/versions/stack/8.5.asciidoc
[docs release issue ](https://github.com/elastic/dev/issues/2171)
=> Bumps the docs version to 8.5.2

resources/asciidoctor/lib/extensions.rb, resources/asciidoctor/lib/glob_include_processor/extension.rb
This PR adds an extension that enables the use of wildcards in include statements.
=> Add glob include processor extension

extra/docs_landing.html
Addresses #242 to update the Welcome to Elastic Docs page and make it more visually appealing. 
[Preview](https://docs_2559.docs-preview.app.elstc.co/guide/index.html)
I want to make sure we're all aligned on the changes, so please leave any feedback, make updates, etc. 
Let's wrap this up in time to merge for 8.6.0.
=> Updates landing page for 8.6

shared/versions/stack/8.5.asciidoc
🛑 Do not merge until release day.
This updates the stack docs shared version attributes to `8.5.3`.
[docs release issue](https://github.com/elastic/dev/issues/2172)
=> Bump docs version to 8.5.3

conf.yaml
Client docs have been moved out of the Cloud guides and into the Elasticsearch Reference. So, we can remove most of the dependencies on the `client-team` repo from the Cloud docs builds. 
Specifically, I removed the client dependencies for ESS (Elasticsearch Service) and ECH (Heroku) builds. Previous versions of ECE still include the client content so those dependencies are still in place.
=> Remove client dependencies from ESS and ECH docs builds

conf.yaml
This changes "current" for the Cloud ESS docs to MS-84.
=> ESS - Change current to ms-84

build_docs, gitconfig
With a recent change to git [1], running commands like `git rev-parse --show-toplevel` will fail when different directories are owned by different users. Because of the complexity of how we use Docker and expect it to work across different operating systems, the easiest approach is to restore the prior behavior. [2]
Rather than trying to run `git config` from within the build process (which runs into its own file permission errors depending on who is running the command), instead we just hardcode the "global" gitconfig file (which is located at the root of the Docker container).
[1]: https://github.com/git/git/commit/8959555cee7ec045958f9b6dd62e541affb7e7d9
[2]: https://git-scm.com/docs/git-config#Documentation/git-config.txt-safedirectory
=> Tell git to treat all directories as safe

resources/web/docs_js/index.js
Fixes a race condition that would break the link to the current release documentation in the banner at the top of older docs. Thank you @jloleysens  !
I've tested this fix on a local build of the docs and haven't seen the race condition since.
=> Fix race condition in link to current docs

conf.yaml, doc_build_aliases.sh
This PR updates the Elastic Security Guide to pull content from the kibana repo so that we can re-use some tagged regions.
=> Add kibana repo dependency to Security Guide

conf.yaml, shared/versions/stack/8.5.asciidoc, shared/versions/stack/8.6.asciidoc, shared/versions/stack/current.asciidoc
Changes the "current" version of Elastic documentation to 8.6.
=> [Docs release] Bump current version to 8.6

conf.yaml
Add 2.6 branch for the upcoming ECK operator release.
=> Add ECK 2.6 branch

conf.yaml
This PR sets the ECK 2.6 branch as the current version.
I am submitting this early to get approval. It should only be merged on Jan 10th after https://github.com/elastic/docs/pull/2590 is merged and ECK 2.6 is released.
=> Promote ECK 2.6 branch to current

conf.yaml
Open a docs PR to change the "current" version selector.
=> ECS 8.6 Release - change the "current" version selector

conf.yaml, doc_build_aliases.sh
This PR updates the Observability Guide to pull content from the kibana repo so that we can re-use some tagged regions.
=> Add kibana dependency to Observability Guide

conf.yaml, shared/versions/stack/master.asciidoc
Related to ECS Soft Feature Freeze 8.7
PR Adds the new version 8.7 to the selector in conf.yaml.
PR does not update the current attribute
PR adds the new branch to the branches attribute and
also adds the upcoming release branch to the live attribute.
Maps the upcoming ecs_version to the next stack version in shared/versions/stack/master.asciidoc
=> Changes for ECS 8.7 SFF

conf.yaml, shared/attributes.asciidoc
Updates build to generate Ent Search node client docs, added in this [PR](https://github.com/elastic/enterprise-search-js/pull/20) and to 8.6 branch in [this PR](https://github.com/elastic/enterprise-search-js/pull/21).
- Updates `conf.yaml` to build Enterprise Search Node.js client docs from the [GH repo](https://github.com/elastic/enterprise-search-js/tree/main/packages/enterprise-search)
- Remove deprecated clients from build
- Adds `enterprise-search-node-ref` to shared attributes
=> Update build config for Enterprise Search Node.js client

conf.yaml
This changes "current" for the Cloud ESS docs to MS-86.
=> ESS - Changing current to ms-86

shared/versions/stack/8.6.asciidoc
This updates the stack docs shared version attributes to `8.6.1`.
[docs release issue](https://github.com/elastic/dev/issues/2195)
Note that this is a replacement for #2598 that strangely started to repeatedly fail the `self-check` CI check.
=> Bump docs version to 8.6.1

shared/attributes.asciidoc
The `:ingest-guide:` attribute is set to resolve to `https://www.elastic.co/guide/en/fleet/{branch}`.  This PR updates the attribute.
Is the `:ingest-guide:` attribute currently in use anywhere?  Docs-ci will tell us... but we might have to wait until after #2578 is merged. 
UPDATE: Yes!  The attribute is in use for some 7.x branches.  See comments.
DO NOT MERGE until after #2578 has been merged.
=> Modify attribute for Ingest Guide

conf.yaml
I previously fixed these as well, but wanted 8.0 in for certain, rather than have it held up.
Apparently, anchor links with underscores are problematic in Asciidoc. I pruned the offenders.
=> Adding Curator 6.0 and 7.0 doc branches (take 2)

shared/versions/stack/7.17.asciidoc
🛑 Do not merge until release day.
This updates the stack docs shared version attributes to `7.17.9`.
[docs release issue](https://github.com/elastic/dev/issues/2195)
=> Bump docs version to 7.17.9

extra/docs_landing.html
I just noticed that the text on our [landing page](https://www.elastic.co/guide/index.html) for the SIEM getting started guide needs a small fix to remove the "Use".
=> Fix text on landing page SIEM card

shared/versions/stack/8.6.asciidoc
This updates the stack docs shared version attributes to 8.6.2.
[Docs release issue](https://github.com/elastic/dev/issues/2219)
=> Bump docs version to 8.6.2

conf.yaml
This changes "current" for the Cloud ESS docs to ms-87.
=> ESS - Change current to ms-87

lib/ES/Util.pm, resources/asciidoctor/lib/docbook_compat/convert_document.rb, resources/asciidoctor/lib/docbook_compat/extra_docinfo.rb, resources/asciidoctor/spec/chunker_spec.rb, resources/asciidoctor/spec/docbook_compat_spec.rb
This PR adds the following Elastic meta attributes to the doc build:
For example, [this page](https://docs_2581.docs-preview.app.elstc.co/guide/en/observability/current/observability-introduction.html) in the preview has the following meta tags:
```html
<meta class="elastic" name="content" content="What is Elastic Observability? | Observability Guide [8.5]">
<meta class="elastic" name="product_name" content="Observability">
<meta class="elastic" name="product_version" content="8.5">
<meta class="elastic" name="website_area" content="documentation">
```
I added to the existing DocBook compatibility components of our doc build:
`convert_document.rb` manipulates the page `<title>` using book attributes. I extended this functionality to add an Elastic meta tag using the same attributes. …
=> Add `elastic` meta attributes to legacy doc build

conf.yaml
Removing the reference to the outdated .NET examples folder which doesn't seem to be used.
=> Remove .NET example reference

doc_build_aliases.sh
The `docbldab` alias does not work. The files in the x-pack directory are required to build the Auditbeat Reference.
=> Update auditbeat doc build alias

build_docs.pl, lib/ES/LinkCheck.pm
This reverts commit d09314fcaf2049b8486d5d44768decbd45171776.
It should be safe now. It didn't work because we hadn't run a "real" build when I tried to run my test.
=> Revert "Revert "Test Elasticsearch's links (#2631)""

conf.yaml
This promotes ECK 2.7 branch to current.
It should be merged:
- after https://github.com/elastic/docs/pull/2632
- once ECK 2.7 is released
=> Promote ECK 2.7

extra/docs_landing.html
This updates the [docs landing page](https://www.elastic.co/guide/index.html) with a card for the new [K8s monitoring onboarding guide](https://www.elastic.co/guide/en/welcome-to-elastic/8.7/getting-started-kubernetes.html).
Please don't merge until 8.7 GA. CI checks should pass once `current` is switched over to 8.7.
=> Add K8s monitoring guide to docs landing page

extra/docs_landing.html
This should fix the arrangement of the GS Guide cards on the docs landing page.
=> Fix GS guide cards arrangement on landing page

conf.yaml
Relates to https://github.com/elastic/elasticsearch/issues/92802 
This PR attempts to address these doc build errors...
```
10:43:55 INFO:build_docs:Checking Elasticsearch links
10:43:55 INFO:build_docs:  Branch: 8.7, Version: 8.7
10:43:55 INFO:build_docs:  Branch: main, Version: master
10:43:55 INFO:build_docs:Can't read /doc/elastic+elasticsearch+pull-request+build-docs/server/src/main/resources/org/elasticsearch/common/reference-docs-links.json: No such file or directory at lib/ES/Repo.pm line 363.
10:43:55 runbld>>> <<<<<<<<<<<< SCRIPT EXECUTION END <<<<<<<<<<<<
```
By adding this path to the list of sources for the Elasticsearch Guide:
https://github.com/elastic/elasticsearch/blob/8.7/server/src/main/resources/org/elasticsearch/common/reference-docs-links.json
=> Add Elasticsearch link checking path

build_docs.pl
Relates to https://github.com/elastic/elasticsearch/issues/92802
https://github.com/elastic/docs/pull/2655 failed to resolve the build error in https://github.com/elastic/elasticsearch/pull/91491 so this PR temporarily comments out the link checker until it can be fixed.
=> Comment out elasticsearch link checker

conf.yaml
We have now released 8.1.0 of the client and, therefore, should direct the current version in the docs to that branch.
=> Update current version for .NET client docs

shared/attributes.asciidoc
This PR updates https://github.com/elastic/docs/blob/master/shared/attributes.asciidoc in order to remove the book-scoped `blob` attribute from https://github.com/elastic/kibana/blob/main/docs/index.asciidoc
=> Add shared attribute for kibana blob

conf.yaml
This changes "current" for the Cloud docs to ms-90.
=> Change current to ms-90

conf.yaml, doc_build_aliases.sh, shared/attributes.asciidoc, shared/versions/stack/master.asciidoc
* https://github.com/elastic/observability-docs/issues/2716
* https://github.com/elastic/elastic-serverless-forwarder/pull/270
* https://github.com/elastic/elastic-serverless-forwarder/pull/311
Note that https://github.com/elastic/elastic-serverless-forwarder/pull/311 contains https://github.com/elastic/elastic-serverless-forwarder/pull/270. Just wanted to work in an isolated branch until [#270](https://github.com/elastic/elastic-serverless-forwarder/pull/270) is merged.
=> Start building ESF documentation

shared/attributes.asciidoc
Forgot that I used an underscore instead of dash to match the convention used for ECS. :-) 
This will fix the build error in https://github.com/elastic/observability-docs/pull/2853.
=> Fix typo in esf version attribute

extra/docs_landing.html
Change link to land on new [Enterprise Search docs landing page](https://www.elastic.co/guide/en/enterprise-search/current/index.html) instead of [getting started](https://www.elastic.co/guide/en/enterprise-search/current/start.html) section.
_Not sure if we want to do this but it's quicker to open a PR than to ask the question :)_
=> Change Enterprise Search link on docs landing page

conf.yaml, doc_build_aliases.sh, shared/attributes.asciidoc
https://github.com/elastic/observability-docs/pull/2802 adds new docs for ingesting data for Amazon Kinesis. This PR gets them building.
https://github.com/elastic/observability-docs/pull/2802 must be merged before this PR will build.
Note: Because we're building these docs out of the observability-docs repo, they will follow the stack versioning strategy. If we want to have a different versioning strategy, we'll need to move these files to a repo with branches that match the versions we want to build.
Preview is here: https://docs_2671.docs-preview.app.elstc.co/guide/en/kinesis/current/aws-firehose.html 
I'll fix the actual book structure when I work on https://github.com/elastic/observability-docs/issues/2893
=> Build Amazon Kinesis Firehose docs

conf.yaml, doc_build_aliases.sh
This PR needs to be merged at the same time as https://github.com/elastic/docs/pull/2674.
To test this PR:
1. Checkout https://github.com/elastic/observability-docs/pull/2895
2. Checkout this PR.
3. Reload the doc_build_aliases.sh file (for example, `source ~/.bash_profile` or whatever works on your system).
4. Run `docbldakf --open` to preview the output in your browser.
=> Change location of Kinesis index file

resources/asciidoctor/lib/chunker/breadcrumbs.rb, resources/asciidoctor/lib/chunker/obs_breadcrumbs.rb, resources/asciidoctor/lib/chunker/search_breadcrumbs.rb
Adds dropdown for the 3 principal Enterprise Search books to help users toggle books.
- Naive copy/paste of https://github.com/elastic/docs/pull/2619 😄. 
- ⚠️ Unlikely not to have side effects.
- Not sure what protocol is for tests
=> Add dropdowns for Ent Search, App Search, Workplace Search books

shared/versions/stack/7.17.asciidoc
This updates the stack docs shared version attributes to 7.17.10.
[Docs release issue](https://github.com/elastic/dev/issues/2248)
=> Bumps docs version to 7.17.10

build_docs.pl, integtest/spec/helper/dest.rb, lib/ES/LinkCheck.pm
This PR adds an optional --warnlinkcheck option, which enables you to run the build without failing if there's a broken link. Unlike the `--skiplinkcheck` option, it still performs the check and prints the details in the log.
For example, in a local test with broken links, the output still contains info like this:
```
INFO:build_docs:Bad cross-document links:
INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/apm/agent/java/1.x/config-logging.html contains broken links to:
INFO:build_docs:   - en/ecs-logging/overview/master/intro.html
...
```
=> Add warnlinkcheck build option

resources/web/docs_js/components/tabbed_widget.js
There was a report today that the tabbed widgets were not working. Hovering over an inactive tab results in style changes, but the click event listener is not being applied, so the active tab doesn't change and the panel contents don't change.
After poking around, I found that the [`DOMContentLoaded` event listener](https://github.com/elastic/docs/blob/master/resources/web/docs_js/components/tabbed_widget.js#LL2C20-L2C20) in the tabbed widget component isn't working. I don't know why, but using the `readystatechange` event listener and waiting for the document's `readyState` to be `interactive` does work locally at least. 🤷‍♀️ 
Find a couple pages in your team's docs that use the tabbed widget and make sure switching between tabs works as expected. Preview link: …
=> Fix tabbed widgets

README.asciidoc
We're seeing some unexpected behavior when attributes are used to set metadata. Resetting the attribute when it's no longer needed should be a best practice (just as it is when variables are used in code).
=> Add section about attribute scope to readme

conf.yaml
Add 2.8 branch for the upcoming ECK operator release, scheduled on May 23, 2023
=> Add ECK 2.8

shared/attributes.asciidoc, shared/versions/stack/8.8.asciidoc
Adds version attribute for Kinesis firehose docs because this feature "is not tied to stack release versions, but for under-the-hood reasons is tied to ESS release milestones. in the future though this we be silently decoupled from the ESS releases."
=> Add version attribute for Kinesis firehose docs

conf.yaml
This pr promotes the branch `2.8` of the ECK project.
Should be merged:
* After https://github.com/elastic/docs/pull/2679
* Once ECK 2.8 has been released.
=> Promote ECK 2.8

conf.yaml
Creates a new `stackliveNoMain` in `conf.yml` that includes an array of recent versions _without_ `main` or `master`, and applies that variable to Observability books where possible. (It's not possible where `main`/`master` is the value for the `current` property.)
=> Stop indexing `master`/`main` in all stack-versioned books

resources/web/template.html
Removes the Qualtrics feedback survey from all elastic.co/guide pages.
We're not currently acting on feedback from the survey, which can create a poor user experience. We may revisit the idea of another feedback mechanism in the future.
=> Remove Qualtrics survey

shared/versions/stack/8.8.asciidoc
This updates the stack docs shared version attributes to 8.8.1.
[Docs release issue](https://github.com/elastic/dev/issues/2286)
=> Bumps docs version to 8.8.1

conf.yaml
Legacy APM documentation still shows up in google search results. This PR stops indexing some very old versions 😨 .
For https://github.com/elastic/observability-docs/issues/2986.
=> Stop indexing legacy APM documentation

conf.yaml, doc_build_aliases.sh
Book content (in other repository) is still placeholder, so:
- Placed book in "In development" section of docs landing page
- Removed all "live" versions to keep content out of search indices
=> Create ESRE book

resources/asciidoctor/lib/docbook_compat/convert_table.rb, resources/asciidoctor/spec/docbook_compat_spec.rb, resources/web/style/table.pcss
The current default styling of tables is not great. Even though Asciidoctor allows [assigning roles to a table](https://docs.asciidoctor.org/asciidoc/latest/tables/assign-a-role/), which are rendered as CSS `class` attributes in HTML, [our implementation of tables](https://github.com/elastic/docs/blob/master/resources/asciidoctor/lib/docbook_compat/convert_table.rb#L50) does not support that.
This PR enables that functionality, by passing any roles as `class` attributes of the rendered table. 
The PR also introduces two new CSS classes: `styled` and `fixed-width`, which can optionally be assigned as roles to a table, using for example `[.styled]`,  or even `[.styled.fixed-width]`, if you want to apply both.
It enables us to do something like this (note the `.styled`):
```
.Script …
```
=> Make tables stylable

extra/docs_landing.html
The dimensions set for the embedded video on our [docs landing page](https://www.elastic.co/guide/index.html) are incorrectly coded (invalid HTML) and do not optimize usage of space on the page.
This PR fixes the existing HTML.
I may try a few different settings to see what works best.
=> Fix aspect ratio of video on docs landing page

resources/web/docs_js/index.js, resources/web/lib/prettify/lang-esql.js, resources/web/style/code.pcss, resources/web/style/table.pcss
This implements the `esql` language in prettify so it'll look nice and it adds another couple of styles that let us merge the results like I'm trying to do here:
https://github.com/elastic/elasticsearch-internal/pull/1259
=> Expand styles for ESQL

conf.yaml
This PR removes the `branches` and `live` for Perl Client in favor of `8.x` and `7.x` only. This change is required since the Perl client announced [End-of-Life for version 8](https://github.com/elastic/elasticsearch-perl/issues/220) and we are not going to branch anymore with the stack version. Moreover, the old 8.0 to 8.6 branches are going to be removed.
=> Removed Perl client branches in favor of 8.x and 7.x

extra/docs_landing.html
This PR closes [Issue 93](https://github.com/elastic/obs-docs-projects/issues/93). The "Monitor hosts with Elastic Observability" was updated to mention logs to increase visibility into the fact that Observability is the home of logging.
=> Add mention of logs to the Observability getting started card

conf.yaml
This changes "current" for the Cloud ESS docs to MS-92.
=> ESS - Change current to MS-92

resources/web/lib/prettify/lang-esql.js
PROJECT has been renamed KEEP. This PR updates the ESQL prettify library.
=> Rename PROJECT to KEEP in lang-esql.js

resources/web/docs_js/__tests__/components/alternative_picker.test.jsx, resources/web/docs_js/components/alternative_picker.jsx, resources/web/docs_js/components/console_widget.jsx, resources/web/docs_js/index.js
In books that have configured alternative languages for `console` code examples, the alternative picker currently shows all the configured languages, regardless of whether a snippet actually exists for each of the languages:
This leads to a poor UX, as users can select a language, only to find out that a code snippet does not exist for that language.
This PR changes the alternative picker such that, per code snippet, only those languages for which snippets actually exist are enabled. Other languages are still shown greyed out, but cannot be selected:
If a user has previously selected a language on another code snippet, but that language does not exist on the current example, the option will be disabled, but still preselected, so their preference is not reset:
(If you want to give it a …
=> Only enable console alternatives that have a snippet

shared/versions/stack/8.8.asciidoc
This updates the stack docs shared version attributes to 8.8.2.
[Docs release issue](https://github.com/elastic/dev/issues/2303)
=> Bumps docs version to 8.8.2

shared/versions/stack/7.17.asciidoc
This updates the stack docs shared version attributes to 7.17.11.
[Docs release issue](https://github.com/elastic/dev/issues/2304)
=> Bumps docs version to 7.17.11

build_docs.pl, integtest/spec/all_books_broken_link_detection_spec.rb
The checker isn't skipping GitHub links as intended. This is blocking https://github.com/elastic/kibana/pull/160535.
I think we can fix this by updating the [check_kibana_links](https://github.com/elastic/docs/blob/master/build_docs.pl#L381) function, but I don't want to halt the above PR while we research.
=> Temporarily pause Kibana link checks

build_docs.pl, integtest/spec/all_books_broken_link_detection_spec.rb
This PR skips the "ELASTIC_GITHUB" URL added in https://github.com/elastic/kibana/pull/160535, which would otherwise cause the Kibana link checks to fail.
It also reverts the temporary changes from https://github.com/elastic/docs/pull/2710
=> Add ELASTIC_GITHUB to link checker

conf.yaml
If we must keep these translations of very old docs (5.x and 6.0), I propose that we move them to the legacy section. Otherwise I think we are raising expectations pretty high and will only disappoint users.
This PR moves the translated content to the Legacy section. Someone should explore whether we can just remove them completely. I did spot check a couple of the books in google analytics and there was no traffic, but someone should look more closely.
@KOTungseth Thoughts?
(Marking as draft for now until I can see the output)
=> Move old translations to legacy section of the docs landing page

integtest/spec/all_books_spec.rb, lib/ES/Book.pm
Re-enables `Edit` links for the `master`/`main` branches of docs.
When https://github.com/elastic/docs/pull/2690 disabled indexing for these branches, it also removed the `Edit` links as an unintended side effect.
Closes https://github.com/elastic/platform-docs-team/issues/119 (sorry — internal link)
=> Enable edit links on `master`/`main` branches

conf.yaml
This changes "current" for the ECE docs to version 3.6.0.
Do not merge until release day (June 20th 2023)
=> Change current to 3.6.0

conf.yaml
The MVP content has all been merged in the source repository.
- Move book from "Docs in Development" to "Elastic Stack"
- Add "live" versions to enable search engine indexing
=> Formally publish ESRE book

extra/docs_landing.html
This adds a link on the [docs landing page](https://www.elastic.co/guide/index.html) to a new "Introducing Elastic docs" page. I'm not sure if there's maybe a better spot for it? This is the best I could think of.
Rel: https://github.com/elastic/tech-content/pull/342
(and of course this PR needs to wait for the above to merge)
=> Add a link on the landing page to Introducing Elastic Docs

conf.yaml
This adds the 2.9 docs branch in preparation of the upcoming release
=> ECK: add 2.9 version

conf.yaml, shared/versions/stack/8.8.asciidoc, shared/versions/stack/8.9.asciidoc, shared/versions/stack/current.asciidoc
This PR changes the "current" version of the documentation to 8.9 and changes that set of docs from "unreleased" to "released".
=> Bumps current version to 8.9

shared/versions/stack/7.17.asciidoc
This updates the stack docs shared version attributes to 7.17.12.
Rel: https://github.com/elastic/dev/issues/2311
=> Bumps docs version to 7.17.12

conf.yaml
Do not merge before release of Elastic stack 8.9/ECK 2.9
=> ECK: Promote 2.9 version to current

conf.yaml
This changes "current" for the Cloud ESS docs to MS-94.
=> ESS - Change current to MS-94

shared/versions/stack/8.9.asciidoc
The ECS version in the 8.9 docs was accidentally left at `master` rather than `8.9`.
=> Update ECS docs to version 8.9

conf.yaml
As the 8.9 version of the .NET Client has been released, this PR bumps the docs version number appropriately.
=> Releases 8.9 branch for .NET Client docs

extra/docs_landing.html
Adds a query parameter to the Azure Marketplace link on the [Docs landing page](https://www.elastic.co/guide/index.html).
Currently, a third-party script is appending `&euid=foo` to this URL. Without a query param, the link breaks.
Closes https://github.com/elastic/docs/issues/2730
=> Fix Azure Marketplace link

shared/attributes.asciidoc, shared/versions/stack/8.9.asciidoc, shared/versions/stack/master.asciidoc
🧀  Pairs with https://github.com/elastic/observability-docs/pull/3138
Moves some book-scoped variables from /observability-docs here.
=> Move some book-scoped attributes from /observability-docs

shared/attributes.asciidoc
I expect we'll want this attribute for mentioning any restrictions or other references about Serverless from within the classic docs.
=> Add 'Elastic Serverless' shared attribute

conf.yaml
Related: https://github.com/elastic/ingest-dev/issues/2307
* Moves Ingest architecture docs from "Docs in Development" section to Stack section for find-ability
* Removes `noindex` tag to get content indexed and available from internet searches
* Sets up versioning starting with 8.9
=> Make Ingest Architecture docs generally available

shared/versions/stack/8.10.asciidoc
Creates a new version attributes file for the 8.10 release, per the instructions [here](https://docs.elastic.dev/docs/releases). Does not edit the master version attributes file because that was completed in another [PR](https://github.com/elastic/docs/pull/2736).
=> Creates 8.10 version attributes file

conf.yaml
This changes `current` to `ms-95`.
DO NOT merge until release day (Aug 15).
=> ESS - Change current to MS-95

resources/web/template.html, shared/attributes.asciidoc, shared/cloud/cloud-login.asciidoc
**IMPORTANT: DO NOT MERGE UNTIL AUG 31, 2023**
Updates the UTM parameters used to track Cloud trial signups from the docs.
Per Marketing, the old parameter keys (`baymax`, `elektra`) are outdated: https://elastic.slack.com/archives/C01AA2TLEUX/p1691580994671689 (Sorry — internal link only)
=> Update Cloud UTM parameters

extra/docs_landing.html
Over the past year, we've received numerous complaints from users and employees that the link to Observability getting started content is confusing and not where users ultimately want to end up. I'm changing this link to point to our getting started content in the Observability Guide.
=> Update Observability link

conf.yaml
Adds a `live` branch property to the ECE docs. This ensures that branches for 2.x docs are no longer indexed.
=> [DOCS] Add `live` branches to ECE docs

conf.yaml
Replaces `Welcome to Elastic` with new `Starting with the Elasticsearch Platform and its Solutions` terminology introduced in https://github.com/elastic/tech-content/pull/232.
=> Updates title of welcome to elastic

shared/versions/stack/7.17.asciidoc
This updates the stack docs shared version attributes to 7.17.13.
Rel: https://github.com/elastic/dev/issues/2339
=> Bump docs version to 7.17.13

shared/versions/stack/8.9.asciidoc
This updates the stack docs shared version attributes to 8.9.2.
Rel: https://github.com/elastic/dev/issues/2338
=> Bump docs version to 8.9.2

extra/client_docs_landing.html, extra/docs_landing.html, shared/attributes.asciidoc
**Problem:** In https://github.com/elastic/docs/pull/2752, we updated the URL prefix and name for the "Welcome to Elastic Docs" docs. Several links and attributes still point to the old URLs.
**Solution:** Change any `/welcome-to-elastic` to `/starting-with-the-elasticsearch-platform-and-its-solutions` in any links and attributes.
**Note:** https://github.com/elastic/website-development/issues/11616 will add related redirects.
=> Update `/welcome-to-elastic` links

conf.yaml
**Problem:** With https://github.com/elastic/elasticsearch/pull/99209, the elasticsearch repo's `x-pack/docs` directory no longer contains docs for the Elasticsearch Guide in 8.10+. However, the docs build config still lists the `x-pack/docs` directory as a dependency.
**Solution:** Update the docs build config to remove the `x-pack/docs` dependency for the Elasticsearch Guide in 8.10+.
Depends on https://github.com/elastic/elasticsearch/pull/99209
Rel: https://github.com/elastic/platform-docs-team/issues/208
=> Remove x-pack docs dir from ES book

conf.yaml, shared/versions/stack/8.10.asciidoc, shared/versions/stack/8.9.asciidoc, shared/versions/stack/current.asciidoc
Reverts `current` to 8.9.2.
This reverts commit 92c8cbb674e8c484fb4dfad758a18116e4987149.
=> Revert "bumps current version to 8.10 (#2756)"

conf.yaml, shared/versions/stack/8.10.asciidoc, shared/versions/stack/8.9.asciidoc, shared/versions/stack/current.asciidoc
[docs release issue ](https://github.com/elastic/dev/issues/2355)
=> Bump docs version to 8.10.1

shared/attributes.asciidoc
Related to https://github.com/elastic/docs/pull/2735
@bmorelli25 it looks like we missed the PHP agent in https://github.com/elastic/docs/pull/2735. I'm seeing unresolved attributes in the ["PHP" tab in the "Step 2: Install APM agents" section](https://www.elastic.co/guide/en/observability/current/ingest-traces.html#add-apm-integration-agents). I think might fix it?
=> Add APM PHP agent conditional

shared/versions/stack/8.10.asciidoc
This updates the stack docs shared version attributes to 8.10.2.
=> Bump docs version to 8.10.2

conf.yaml
This PR changes "current" for the Cloud ESS docs to ms-97.
=> ESS - Change current to ms-97

shared/attributes.asciidoc
This adds a Serverless feature flag so that we can add any content, admonitions, etc. to the classic docs and have it disabled until the Serverless documentation is live. I've CCed folks just for awareness in case you need to use this.
For example:
```
ifeval::["{serverless-feature-flag}"=="yes"]
IMPORTANT: On-premises {fleet-server} is not currently available for use with
link:{serverless-docs}[{serverless-full}] projects. In a {serverless-short}
environment we recommend using {fleet-server} hosted on {ess}.
endif::[]
```
=> Add feature flag for Serverless

conf.yaml
**Problem:**
A book's `live` variable determines what versions display outside of "other versions" in the version drop down. The following books have outdated `live` values:
- [Starting with the Elasticsearch Platform and its Solutions](https://www.elastic.co/guide/en/starting-with-the-elasticsearch-platform-and-its-solutions/current/index.html)
- [Elasticsearch Relevance Engine (ESRE)](https://www.elastic.co/guide/en/esre/current/index.html)
- [Elasticsearch Ingest Architectures](https://www.elastic.co/guide/en/ingest/current/index.html)
- [Enterprise Search Node.js client](https://www.elastic.co/guide/en/enterprise-search-clients/enterprise-search-node/current/index.html)
This means old versions appear in the dropdown. Example screenshot:
**Solution:**
Updates the `live` values for the …
=> Update `live` value for several Stack books

doc_build_aliases.sh
The Elasticsearch docs that used to live in the `x-pack` directory have moved (https://github.com/elastic/elasticsearch/pull/99209). We no longer need the dependency to that directory in the `docbldesx` build alias.
=> Remove x-pack directory dependency from docbldesx build alias

conf.yaml
This changes `current` for the Cloud ESS docs to MS-98.
=> ESS - Change current to MS-98

shared/attributes.asciidoc
This PR clarifies the shared attributes for data views, since we want to have less duplication and potential confusion as we port them forward to the new docs system.
I have verified that the attributes that I have moved to the "legacy"/"do not use" sections are not used in the main branch of the kibana repo, with the exception of those cleaned up in https://github.com/elastic/kibana/pull/167943
=> Clarify data view shared attributes

catalog-info.yaml
Added Slack notification sending to #docs-builds channel using [Terrazzo](https://docs.elastic.dev/ci/notifications-in-buildkite#slack---alternative) for main branch failure cases.
Required for issue [134](https://github.com/elastic/docs-projects/issues/134)
=> Slack notification on main failure for docs build

.buildkite/pr_main_mr_test.yml, catalog-info.yaml
To migrate Jenkins job with tests to Buildkite (issue [130](https://github.com/elastic/docs-projects/issues/130) new pipeline was created. It need to be pushed to master to continue with migrating scripts.
=> New pipeline for test execution

conf.yaml, shared/versions/stack/master.asciidoc
Updating ECS versions for 8.11 feature freeze.
- Relates elastic/security-team#7620
=> Update ECS versions for 8.11 feature freeze

catalog-info.yaml
This PR renames so docs pipelines so that they're better organized in Buildkite (before they start getting used widely). Our original naive approach produced pipelines such as buildkite.com/elastic/preview-cleaner - which is not very descriptive or obvious.
This changeset also update some teams permissions to reflect the end-state.
cc @bmorelli25 for review on the teams permissions.
current looking state:
Note - this change will be fairly destructive from a terrazzo perspective and will require some manul tending from the CI team (I should also be able to help out with it).
=> Re organize docs pipelines

shared/attributes.asciidoc
Relates to https://github.com/elastic/security-docs/issues/4031, which indicates this name might soon change.
The attribute will be used in pages like https://www.elastic.co/guide/en/kibana/master/bedrock-action-type.html
=> Add shared attribute for AWS Bedrock connector

shared/versions/stack/8.10.asciidoc
This updates the stack docs shared version attributes to 8.10.4.
=> Bumps docs version to 8.10.4

.buildkite/pull-requests.org-wide.json
=> add parameters to pr bot org wide config

integtest/spec/single_book_spec.rb, resources/asciidoctor/lib/care_admonition/extension.rb, resources/asciidoctor/spec/care_admonition_spec.rb
Adjusts the copy for the `preview` admonition.
=> Update tech preview copy

shared/attributes.asciidoc
Based on request from PMM we are changing the serverless product names to:
Full: `Elastic Cloud serverless`
Short: `serverless`
=> Update Serverless attribute to 'serverless'

conf.yaml
This changes "current" for the Cloud ESS docs to ms-99.
=> ESS - change current to ms-99

extra/docs_landing.html
For the "Search" solution, direct readers to the Elasticsearch docs rather than the Enterprise Search docs.
For the link text, use the same text we use in the Elastic Cloud console to describe Elasticsearch projects.
=> Change destination for Search solution to Elasticsearch

conf.yaml
This adds the ECK 2.10 branch to the build list. ECK 2.10 is planned for release on November 7th 2023.
=> Add ECK 2.10

shared/versions/stack/master.asciidoc
Bumps the current Stack version to 8.12 in `master` and `main` branches.
Rel: https://github.com/elastic/docs/pull/2809
=> Bump `master` attributes to 8.12

conf.yaml
This PR sets the ECK 2.10 branch as the current version.
I am submitting this early to get approval. It should only be merged on November 7th after https://github.com/elastic/docs/pull/2810 is merged and ECK 2.10 is released.
=> Promote ECK 2.10

shared/attributes.asciidoc
I think I was the only one using this feature flag, so in the end it seems cleaner just to remove it rather than enabling it.
=> Remove 'serverless-feature-flag'

.buildkite/pull-requests.org-wide.json
This is the config to enable the PRs in elastic/observability-docs to build in Buildkite - I also setup a webhook following these [instructions](https://docs.elastic.dev/ci/configuring-pull-requests-for-buildkite#1-create-a-github-webhook)
Note - only changes in ./docs will trigger Buildkite builds - let me know if this is too restrictive.
=> Add o11y docs to Buildkite for validation

shared/versions/stack/7.17.asciidoc
This updates the stack docs shared version attributes to 7.17.15.
=> Bumps docs version to 7.17.15

shared/versions/stack/8.11.asciidoc
This updates the stack docs shared version attributes to 8.11.1.
=> Bumps docs version to 8.11.1

.github/CODEOWNER
We need to add a code owner to this repository. No one commented on my spreadsheet with suggestions, so here's what I propose:
* @elastic/docs-release-team: This team includes, @bmorelli25, @KOTungseth, @abdonpijpelink, @joepeeples, and @lcawl
* The writer who knows the most about how the classic doc system works: @colleenmcginnis
* The two highest contributors (based on number of commits in the past year) to this repo outside of the above folks: @kilfoyle and @leemthompo 
These eight folks provide wide geographic coverage and wide coverage across elastic documentation teams.
A review from one of the eight folks listed above will be required to merge a PR in this repository.
~Note: We'll also eventually add @elastic/docs-engineering as codeowners and admins to this repo.~ I've updated …
=> Add CODEOWNER file

extra/docs_landing.html
Moves serverless docs link under `Learn about the Elastic Stack`.
=> Promotes serverless link higher on page

resources/web/docs_js/components/feedback_modal.jsx, resources/web/docs_js/components/feedback_widget.jsx, resources/web/docs_js/index.js, resources/web/style/feedback.pcss, resources/web/styles.pcss, resources/web/template.html
Closes https://github.com/elastic/docsmobile/issues/697
This PR adds a feedback widget to the end of the right sidebar. This mimics the feedback experience that exists on https://docs.elastic.co.
Here is a video of the experience:
https://github.com/elastic/docs/assets/1869731/d0bf6260-45f1-4375-9f38-894a166c62bc
Notes: 
- Because of the need for shared state but different locations in the markup (modal needs to be outside of the content and the widget in the sidebar), I opted to maintain all state in the modal component and use JavaScript to alter class names in the widget. The codebase contains redux, but I thought it overkill to wire up a solution that shares state as the need in the widget is minimal.
=> Add feedback widget to docs sidebar

.buildkite/build_pr_pipeline.yml, .buildkite/hooks/pre-command, .buildkite/scripts/build_pr.sh
We always do a full rebuild on `elastic/docs` which takes up to 2 hours with the standard n1-standard-4 CI machine. This PR introduces an optimization only for builds on elastic/docs to use n2-standard-32 to drop the build time to about 1 hour. For any other builds, we'll use n2-standard-4 and tolerate the <20 min build time for docs given the price difference (10x cheaper).
=> Use bigger CI machine for docs repo

.buildkite/pull-requests.org-wide.json, catalog-info.yaml
This PR that goes hand in hand with [this one](https://github.com/elastic/docs/pull/2835) hooks up a few more products-docs repositories to Buildkite. On such repos, when a PR is opened or commented on (with `run docs-build`), the [docs-build-pr](https://buildkite.com/elastic/docs-build-pr) job will be triggered (alongside it's Jenkins counterpart), and push preview changes to the `elastic/built-docs` repo under the `<doc>_bk_<PR_NUMBER>` branch name.
Commit statuses for the Buildkite build will be set but they are not configured to be blocking. 
Additionally, the Buildkite job is configured to report back on the PR with a link to the preview and diff reports. [Here's](https://github.com/elastic/observability-docs/pull/3356#issuecomment-1819842064) an example of such comment.
The intent …
=> Set Buildkite PR job to use master and add batch1 of repos

.buildkite/scripts/build_pr_commit_status.sh
The Buildkite commit statuses were not being set for PRs created from forks. This should fix the issue.
=> Fix commit status posting for forked repos

.buildkite/scripts/build.sh, .buildkite/scripts/build_pr.sh
This PR addressed @gtback comment [here](https://github.com/elastic/docs/pull/2835#discussion_r1399839697)
=> Allow skip link checks or warn link checks but not both

shared/attributes.asciidoc
Add attribute for Elasticsearch on serverless for use in classic docs
=> Add attribute for Elasticsearch serverless

catalog-info.yaml
I just realized that the cronjob was not setup - we're still pushing to the `staging` branch, but we won't be able to compare the elastic/built-docs master and staging branch if they don't build at the same frequency.
=> Build doc every 30 minutes

.buildkite/scripts/build_pr.sh
Context for this fix in https://elastic.slack.com/archives/C04SQJJDM98/p1702291939642629
=> Drop keep-hash fro docs PR builds

conf.yaml, lib/ES/Repo.pm
This PR updates the conf.yaml to remove two books that were appearing in multiple sections (and thus potentially causing build problems).  It also updates the conf.yaml such that the Beats books are all grouped together.
=> Remove duplicates from conf.yaml

conf.yaml
This changes "current" for the Cloud ESS docs to ms-101.
=> ESS - Change current to ms-101

.github/actions/docs-preview/action.yml, .github/workflows/doc-preview.yml
=> Add rebuild instructions

conf.yaml, doc_build_aliases.sh
* Rename `apm-mutating-webhook` to `apm-k8s-attacher`
* The repository `apm-mutating-webhook` has been renamed to `apm-k8s-attacher`.
=> chore: rename apm-mutating-webhook to apm-k8s-attacher

conf.yaml
This PR moves the Elastic Cloud book to the top of the appropriate section of the landing page.
=> Change Elastic Cloud placement on landing page

conf.yaml
For https://github.com/elastic/obs-docs-projects/issues/216.
=> Remove apm-server dependency from Fleet docs

conf.yaml
Related to https://github.com/elastic/observability-docs/pull/3476
We need to be able to access the `docs/data` and `docs/spec` directories in /apm-server in order for https://github.com/elastic/observability-docs/pull/3476 to work. I defined each individually to make sure we're not relying on any other AsciiDoc files in `docs/` outside those two subdirectories.
=> Add `docs/data` and `docs/spec` to APM guide sources

.buildkite/pull-requests.org-wide.json
As explained in [Slack](https://elastic.slack.com/archives/C05SZ9CGB19/p1704726015608749), PR opened by bots do not kick-off docs builds, which is the major source of discrepancies between Jenkins and Buildkite builds.
This PR fixes that.
=> Allow bots actions PR's to trigger docs builds

.buildkite/build_pipeline.yml
We are trying to understand build discrepancies between Jenkins and Buildkite and exploring if this may be the issue.
=> Do a full rebuild of the docs every 30 minutes

conf.yaml
This adds the ECK 2.11 branch to the build list. ECK 2.11.0 is planned for release on January 9th.
=> Add ECK 2.11

conf.yaml
This PR sets the ECK 2.11 branch as the current version.
It should only be merged on Jan 9th after #2880 is merged and ECK 2.11 is released.
=> Promote ECK 2.11 branch to current

conf.yaml, extra/docs_landing.html
This makes two minor changes to the docs homepage based on discussion with Kaarina.
- Moves "[Starting with the Elasticsearch Platform and its Solutions [8.11]](https://www.elastic.co/guide/en/starting-with-the-elasticsearch-platform-and-its-solutions/current/index.html) — [other versions](https://www.elastic.co/guide/en/starting-with-the-elasticsearch-platform-and-its-solutions/index.html)" to the top of the list under the "Elastic Stack" heading.
- Changes the text on the "Self managed" card to `Install, configure, and run Elastic products on your own premises.`
=> Tiny updates for the docs homepage

conf.yaml, shared/versions/stack/8.12.asciidoc
The team will not be releasing an ECS 8.12 while we decide how to approach releases of ECS going forward
I also cleared out some of the older versions from the live options.
___
Relates https://github.com/elastic/security-team/issues/8182
=> ECS current to 8.11

shared/versions/stack/7.17.asciidoc
This PR updates the documentation version from 7.17.16 to 7.17.17.
This PR was opened with automation that is still being tested. Please review accordingly.
=> Bump to 7.17.17

.buildkite/build_pr_pipeline.yml, .buildkite/scripts/build_pr.sh, .buildkite/scripts/build_pr_commit_status.sh
It seems like docs PR coming from a local main branch fail to checkout on Buildkite with the error:
`fatal: Refusing to fetch into current branch refs/heads/main of non-bare repository`
This PR attempts solves the issue by using the `--update-head-ok` flag - see explanation in this [stack overflow](https://stackoverflow.com/questions/2236743/git-refusing-to-fetch-into-current-branch).
Note - this also addresses the issue where status checks were not reported when the build was failing
This was tested using one of the [problematic PR](https://github.com/elastic/apm-agent-android/pull/265):
* reproducing the failure
* with the fix (additional flag) (but then aborting the build)
=> Pass the --update-head-ok to fetch for PRs out of main

conf.yaml
This changes "current" for the Cloud ESS docs to ms-103.
=> ESS - Change current to ms-103

.buildkite/build_pr_pipeline.yml, .buildkite/preview_cleaner_pipeline.yml, .buildkite/scripts/build_pr_commit_status.sh, .buildkite/scripts/clean_preview_branches.sh
Switch to using the short lived personal access tokens rolled out by the CI team - see https://github.com/elastic/docs-projects/issues/142
=> Bk use pat for commit statuses

.github/actions/docs-preview/README.md
@nkammah, I believe this actually needs to be `@master`.  When using `@current`, Kibana checks fail:
Repos like stack-docs and docs use `@master`. For example: https://github.com/elastic/docs/blob/master/.github/workflows/doc-preview.yml#L17
=> Update doc comment README.md

.buildkite/build_pr_pipeline.yml, .buildkite/scripts/build_pr.sh
In https://github.com/elastic/docs/pull/2904 we tried to fix the PR checkout mechanism to work even when the branch name of the original PR matched an existing branch name, such as `main`. This turned out to be creating some issues and was reverted in https://github.com/elastic/docs/commit/0854c6ecb30e0bb28158ecd60a53c4da1bd2de51.
In this PR, we checkout the PR into a local pr_<number> head, to avoid any sort of conflicts.
=> Fix product repo PR checkout

.buildkite/build_pr_pipeline.yml, .buildkite/hooks/pre-command, .buildkite/preview_cleaner_pipeline.yml, .buildkite/scripts/build_pr_commit_status.sh, .buildkite/scripts/clean_preview_branches.sh
We're seeing a few issues with the preview-cleaner-job and docs-build-pr, and I have a hunch that it is related to this PR; I am reverting it for now to see if things get more stable.
Reverts elastic/docs#2902
=> Revert "Bk use pat for commit statuses"

conf.yaml
Fixes: https://github.com/elastic/logstash/issues/15863
Updates `conf.yaml` to remove Logstash on Kubernets from docs landing page.
[Logstash on ECK](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-logstash.html) is the preferred path forward with Logstash on Kubernetes.
=> Remove Logstash Kubernetes from published docs

conf.yaml
Moves "cloud native" methods of data ingestion to the ingest section under "Browse all docs".
One could argue that the [Amazon Kinesis Data Firehose Ingest Guide](https://www.elastic.co/guide/en/kinesis/current/index.html) does belong under cloud, but IMO it does not belong under the description "Provision, manage, and monitor the Elastic Stack".
The [Elastic Serverless Forwarder Guide](https://www.elastic.co/guide/en/esf/current/index.html) on the other hand is not cloud-specific and shouldn't be under that category.
I think it would be good to keep all the data ingestion topics under ingest. Thoughts?
The section seems to be mostly organized alphabetically, with Beats books being grouped together, so I added these guides in alphabetical order. I'm open to other suggestions.
=> Move cloud native ingest docs to ingest section of docs landing page

build_docs.pl
As a follow-on to https://github.com/elastic/kibana/pull/174725, adds observability link checking (for in-product links) back into the doc build.
=> Check observability doc links in Kibana

conf.yaml
As requested by our ingest PM, it'd be very nice to have the Fleet, Integrations, and Logstash docs appear at the top of the `Ingest: Add your data` section.
=> Bump primary ingest tools to top of ingest section

.github/CODEOWNERS
=> Remove `ci-docs-migration-taskforce` as CODEOWNERS

.buildkite/build_pr_pipeline.yml, .buildkite/preview_cleaner_pipeline.yml, .buildkite/scripts/build_pr.sh, .buildkite/scripts/build_pr_commit_status.sh, .buildkite/scripts/clean_preview_branches.sh, preview/clean.js
This PR re-enables the use of pat (personal access token) to perform various GitHub operations (preview-cleaner, setting commit status). This was rolled out a first time a week ago, then reverted due to un-expected issues (explained [here](https://github.com/elastic/ci/discussions/2542#discussioncomment-8294238) and fixed since then).
The testing done on this PR shows the problem to be addressed for both the docs-build-pr and preview-cleaner.
=> Buildkite use pat

.buildkite/build_pipeline.yml, .buildkite/hooks/pre-command, .buildkite/scripts/build.sh, .buildkite/scripts/compare_commits.sh
In https://github.com/elastic/docs/pull/2929, we reverted to incremental builds run every 30 minutes. This works great, until a PR is merged to the elastic/docs repository. Almost every PR merged in this repo requires a `rebuild` in order for the changes to take effect on `elastic.co/guide/*`.
This PR updates our scheduled builds to first check to see if the build commit of `elastic/docs` has changed since the previous successful, scheduled run. If the commit **has** changed, we run a full docs rebuild to ensure the elastic/docs changes are propagated to all corners of elastic.co/guide. If the commit **hasn't** changed, there's no need for a full rebuild, and we instead run an incremental build—the faster and cheaper option.
Testing this PR is fun and easy!
- You can run the bash script …
=> Set build type for scheduled builds based on doc repo changes

extra/docs_landing.html
Adds a link to each solution card to direct serverless solution users to the correct docs.
You can [view the preview here](https://docs_bk_2918.docs-preview.app.elstc.co/guide/index.html).
I'd like some feedback on the link text. I used generic text even though the links are specific because text like "View the Observability serverless docs" was quite long. I'd rather use text that's specific, if possible.
Closes https://github.com/elastic/observability-docs/issues/3594
=> Add serverless links to solution cards in landing page

.buildkite/pull-requests.org-wide.json, .buildkite/test_pipeline.yml
By default Buildkite can build PRs or branches from the repo but not from forks outside of the org, for security purposes. This PR configure the PR bot so that PR from forks can also run the tests.
PRs from contributors without `admin` or `write` access to the repo will require an explicit `run docs-test` comment to kick-off the tests.
=> Enable running tests for PR's and forks

shared/versions/stack/8.13.asciidoc, shared/versions/stack/master.asciidoc
Contributes to https://github.com/elastic/dev/issues/2505 by adding version attributes for 8.13.0.
=> Add version attributes for 8.13.0

shared/versions/stack/8.12.asciidoc
Contributes to https://github.com/elastic/dev/issues/2507 by incrementing the docs version to 8.12.2.
> [!IMPORTANT]
> Don't merge this PR until release day.
=> Bump the docs version to 8.12.2

.buildkite/build_pr_pipeline.yml
Increase agent disk for PR builds from 100GB to 150GB, we were starting to run out of space.
Add `allow_failure` to `depends_on` stanza so the teardown step runs and updates the PR's status even if the previous step fails.
=> increase agent disk for pr builds

conf.yaml
Contributes to https://github.com/elastic/dev/issues/2505 by adding a branch for 8.13 to `conf.yaml`.
> [!IMPORTANT]
> Merge this PR after all teams have created a new 8.13 branch in their repos.
> ✅ ~~Also need to wait until https://github.com/elastic/docs/pull/2937 is merged to use 8.13 attributes.~~
=> Add 8.13 branch

.buildkite/build_pipeline.yml
Increase VM disk space for docs build process to 150GB, to prevent intermittent breaks where the build runs out of space.
Follows a similar fix from https://github.com/elastic/docs/pull/2946.
=> Increase agent disk for docs builds

extra/docs_landing.html
Adds `API reference` to the top nav so users can easily access the single location for all Elastic API documentation.
=> Adds API reference page to top nav on landing page

conf.yaml
Received a request from @karenzone to move the reference architecture docs up in the ingest section because the content is fundamental to choosing which ingest method to use. I think this is OK since the section is not alphabetized anyhow.
=> Move ingest reference architectures up in the ingest section

conf.yaml
This PR makes it possible to generate a `8.13` branch to the Ingest Ref book.
=> Adds 8.13 branch to Ingest Ref book

conf.yaml
Fixes the following in the ingest-docs PRs:
```
2024-03-13 07:06:34 EDT | INFO:build_docs:--keep_hash can't build on top of --sub_dir at lib/ES/Repo.pm line 410.
-- | --
  | 2024-03-13 07:07:00 EDT | 🚨 Error: The command exited with status 255
  | 2024-03-13 07:07:00 EDT | user command error: exit status 255
```
=> Remove duplicate Ingest Ref Architectures entry from conf.yaml

shared/attributes.asciidoc
Relates to https://github.com/elastic/docs/pull/2778, https://github.com/elastic/kibana/pull/178759
Per https://docs.asciidoctor.org/asciidoc/latest/attributes/names-and-values/ "Although uppercase characters are permitted in an attribute name, the name is converted to lowercase before being stored. For example, URL-REPO and URL-Repo are treated as url-repo when a document is loaded or converted. A best practice is to only use lowercase letters in the name and avoid starting the name with a number".  Therefore the "legacy" attributes like `Data-Sources` are considered to be the same as `data-sources` and since the former appears later in the attributes file, its value is used in pages such as:
https://www.elastic.co/guide/en/kibana/current/introduction.html …
=> Remove duplicate data view attributes

conf.yaml
This adds the ECK `2.12` branch to the branches list.
ECK `2.12.0` is planned for release on March 26th, so this has to be merged 1 day before, March 25th.
Relates to:
- https://github.com/elastic/k8s-dev/issues/488
=> Add ECK 2.12

conf.yaml, shared/versions/stack/8.12.asciidoc, shared/versions/stack/8.13.asciidoc, shared/versions/stack/current.asciidoc
Contributes to https://github.com/elastic/dev/issues/2505 by bumping the current version of documentation to 8.13.
> [!IMPORTANT]
> Do not merge until release day.
=> Bump current version to 8.13

shared/versions/stack/7.17.asciidoc
Contributes to https://github.com/elastic/dev/issues/2525 by incrementing the docs version to 7.17.19.
> [!IMPORTANT]
> Don't merge this PR until release day.
=> Bump the docs version to 7.17.19

conf.yaml
This sets the ECK 2.12 branch as the current version.
It should only be merged after #2948 and ECK 2.12 is released (planned March 26th).
=> Promote ECK 2.12 branch to current

conf.yaml
This changes "current" for the Cloud ESS docs to MS-105.
Rel: [MS-105 Release Notes PR](https://github.com/elastic/cloud/pull/124568)
=> ESS - Change current to MS-105

shared/attributes.asciidoc
As book-scoped attributes are no longer supported, this PR proposes to add the AWS attribute that is used in the AWS Monitoring docs.
=> Add AWS attribute

README.asciidoc, resources/web/docs_js/components/console_widget.jsx, resources/web/docs_js/index.js, resources/web/docs_js/localization.js, resources/web/docs_js/utils.js, resources/web/style/console_widget.pcss
Updates the "View Console" link to say "Try Console" and adds a selector to the Console Widget, when the server cannot be reached.
[Example](https://docs_bk_2974.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/current/getting-started.html#add-single-document)
Demo:
https://github.com/elastic/docs/assets/1869731/ac627840-9653-4683-8e33-e23ce8c2a226
=> Add "Try Console" selector to the Console Widget

shared/versions/stack/7.17.asciidoc
This reverts commit 9af2730fdbe41e403cff76af41c5bded525710eb.
=> Revert "Bumps the docs version to 7.17.20 (#2978)"

shared/versions/stack/7.17.asciidoc
This PR cherry-picks the commit from https://github.com/elastic/docs/pull/2978, since that PR was reverted but is now ready to go again.
=> Bumps the docs version to 7.17.20 (#2978)

conf.yaml
This PR removes the entire Amazon Kinesis Data Firehose Ingest Guide https://www.elastic.co/guide/en/kinesis/current/index.html because:
- most of this content is out-of-date
- the updated pages will live in the AWS Monitoring section (Observability docset)
=> Remove Amazon Firehose guide

conf.yaml
Update docs to reference latest released `ecctl` version.
Release issue: https://github.com/elastic/ecctl/issues/644
=> Add 1.13 branch for ecctl

Dockerfile, preview/Dockerfile, preview/build.sh
`build_docs.pl` runs a number of git commands through its normal course of operation. After a certain point, these git commands will implicitly run `git gc` in the background. By design, the original git process forks off the gc child process and forgets about it. The child process will get reparented to PID 1, which is either `build_docs.pl` or a shell. Neither of those will handle `SIGCHLD` for processes they're not aware of, so the number of zombie processes grows indefinitely.
With a large number of zombie processes (80k processes observed in elastic-apps-web), metricbeat starts consuming all available CPU resources, severely degradating the performance of the cluster. This has a side effect of reducing the network performance to around ~50Mbps and increasing the I/O wait to ~30%. …
=> preview: Use dumb-init as PID 1

doc_build_aliases.sh
When I attempt to build the Installation and Upgrade Guide using `docbldstk` it returns:
`Can't find --resource /Users/kilfoyle/repos/apm-server/docs/guide`
It's just a guess, but maybe this path was removed as part of https://github.com/elastic/apm-server/pull/12341
Anyway, removing the `--resource=$GIT_HOME/apm-server/docs/guide` part of the alias for `docbldstk` has the Install and Upgrade Guide building nicely again. 🎉
=> Update the aliases file for removed APM guide

resources/web/docs_js/components/console_widget.jsx, resources/web/docs_js/index.js, resources/web/docs_js/localization.js
- Updates UI copy from https://github.com/elastic/docs/pull/2974
- Tries to help orient users who don't know what Kibana or Console is yet
- The CTA is "Set your Kibana Console URL" 
- Makes "Try in Console" button more explicit: "Try in Elastic Console"
- Focuses on helping users set up their Console URL first and foremost
- Clearly separates this from new users who don't yet have deployment, making cloud and local installations sibling buttons with emphasis on Cloud
In configuration itself:
- Clearly separates the Console and curl setup, as these are two different flows
- Fixes bugs like "curl username" and "curl password" by `s/curl/elasticsearch`
**Before**
**After**
**Before**
**After**
**Before**
**After**
Here's a [page](https://docs_bk_2979.docs-preview.app.elstc.co/guide/en/elasti …
=> Update code example widget

conf.yaml
This changes "current" for the ECE docs to version 3.7.0.
Do not merge until release day (April 10th 2024)
=> Change current for ECE docs to 3.7.0

resources/web/style/heading.pcss
We have a new navigation refactor coming in. Despite setting the z-index for the dropdowns in the new navigation to larger than 1000 (as seen in this PR), the browsers still didn't respect the enforcement. This is also a better long term way as the z-index isn't necessary on this element. In addition, the main bug here is that `opacity: 0.3` created a new stacking order that broke any z-index declarations.
=> Remove z-index for edit button to prepare for incoming nav refactor

.buildkite/scripts/build.sh, .buildkite/scripts/build_pr.sh, .buildkite/scripts/clean_preview_branches.sh
Update build scripts to pull SSH key pair and set it up at runtime.
=> ssh key fix

build_docs.pl
Relates to https://github.com/elastic/kibana/pull/182192
This PR fixes the documentation link tests so that they're aware of the `ECS_VERSION` that is being added in the Kibana doc link service.  It addresses the following errors that otherwise appear in the doc build output:
````
INFO:build_docs:Bad cross-document links:
--
  | INFO:build_docs:  Kibana [master]: packages/kbn-doc-links/src/get_doc_links.ts contains broken links to:
  | INFO:build_docs:   - en/ecs/${ECS_VERSION}/ecs-converting.html
  | INFO:build_docs:   - en/ecs/${ECS_VERSION}/index.html
````
=> Add ECS_VERSION to doc link checker

conf.yaml, shared/versions/ece/current.asciidoc
This PR removes ECE 3.7 from the build as per ongoing incident around ECE https://elastic.slack.com/archives/C071N20PEF7
This PR can be reverted once ECE 3.7.1 version gets released, in the coming days
=> Remove ECE 3.7

conf.yaml, shared/versions/ece/current.asciidoc, shared/versions/ece/master.asciidoc, shared/versions/ece/ms-105.asciidoc
This changes "current" for the ECE docs to version 3.7.1.
Do not merge until release day (May 9th 2024)
=> Change current for ECE docs to 3.7.1

conf.yaml
Add ECK 2.13 to the build list, the release of ECK 2.13.0 is planned for May 21 2024. Should be merged only on May 21
=> Add eck 2.13 to build list

conf.yaml
Our terraform doc versions are 8+ versions behind, and nothing changes between versions (the docs are just a stub that redirects)
This PR flattens the terraform docs so we just have one version, and no versioning confusion for end users.
---
When I preview this, I still see this index page that has links - not sure how this is generated/whether this can be previewed in this build
https://docs_bk_3007.docs-preview.app.elstc.co/guide/en/tpec/index.html
@elastic/docs-engineering is there any way I can preview this before it ships?
=> Remove versioning for terraform docs

conf.yaml
This adds ECK 2.13 as the current branch. ECK 2.13.0 is planned for 21st May 2024, so this PR should be merged on 21st and after #3002 .
=> promote eck 2.13

conf.yaml
This changes "current" for the Cloud ESS docs to MS-108.
=> ESS - Change current to ms-108

extra/docs_landing.html, integtest/spec/single_book_spec.rb, resources/asciidoctor/lib/chunker/breadcrumbs.rb, resources/asciidoctor/lib/chunker/extension.rb, resources/asciidoctor/lib/docbook_compat/convert_document.rb, resources/asciidoctor/lib/docbook_compat/extension.rb, resources/asciidoctor/spec/chunker_spec.rb, resources/asciidoctor/spec/docbook_compat_spec.rb, resources/asciidoctor/spec/elastic_compat_preprocessor_spec.rb, resources/web/docs_js/__tests__/docs.test.js, resources/web/docs_js/index.js, resources/web/style/admonishment.pcss, resources/web/style/console_widget.pcss, resources/web/style/heading.pcss
This reverts commit d16085bebe5c46534a1242a0f1fd85c984643f4e.
=> Revert "Always use h1 for first heading on a page (#3009)"

conf.yaml
This changes "current" for the Cloud ESS docs to ms-109.
=> ESS - Change current to ms-109

shared/versions/ece/ms-105.asciidoc
This changes "current" for the ECE docs to version 3.7.2.
=> Bump ECE docs to 3.7.2

shared/attributes.asciidoc
Adds an attribute for Elastic Stack docs v8.0.
=> Add stack-ref-80 attribute

build_docs.pl
This PR adds INTEGRATIONS_DEV_DOCS to the list of variables that are interpreted by the doc link checks, since it was added to the Kibana doc link service in https://github.com/elastic/kibana/pull/186304 and is causing errors in https://github.com/elastic/docs/pull/3029
=> Add INTEGRATIONS_DEV_DOCS variable to doc link checks

.buildkite/pull-requests.org-wide.json
This will be needed in https://github.com/elastic/apm-agent-python/pull/2082 and future PRs by the bot.
=> Add `elastic-renovate-prod[bot]` to `allowed_list`

integtest/spec/all_books_spec.rb, lib/ES/Book.pm
This PR updates the banner that appears in "master" versions of the documentation, since it's currently unclear about the state of the serverless details in that branch.
=> Update banner for master doc versions

conf.yaml
This changes "current" for the Cloud ESS docs to ms-110.
=> ESS - Change current to ms-110

conf.yaml
This PR sets the ECK 2.14 branch as the current version.
**This PR depends on https://github.com/elastic/docs/pull/3042 which should be merged first**. It's submitted early only to get approval, I'll rebase on Wed, Aug 07 once https://github.com/elastic/docs/pull/3042 is merged.
Do not merge before ECK 2.14 release date.
=> Make 2.14 the current version for ECK

conf.yaml
This changes "current" for the Cloud ESS docs to ms-111.
=> ESS - Change current to ms-111

resources/asciidoctor/lib/docbook_compat/convert_floating_title.rb, resources/asciidoctor/lib/docbook_compat/extension.rb, resources/asciidoctor/spec/docbook_compat_spec.rb, resources/asciidoctor/spec/edit_me_spec.rb, resources/asciidoctor/spec/elastic_compat_preprocessor_spec.rb
Closes https://github.com/elastic/docs/issues/1966
This PR moves the edit button out of the heading elements in the body of the content (edit buttons were already added outside page titles in #3015). This is important because when the edit button is inside the heading element, technically the full text of the heading includes `edit` appended to the end of the intended heading text. This is getting picked up by Google, but may also cause unexpected results elsewhere including for users using screenreaders.
Note: I opted for updating the HTML and using Bootstrap CSS classes to avoid having to bump the name (`-v1` to `-v2`) of the CSS file. If the user gets the updated HTML with a cached version of the CSS and JavaScript files, the edit button should still be positioned correctly and work as …
=> Move edit button out of heading elements

conf.yaml
This changes "current" for the Cloud ESS docs to ms-112.
=> ESS - Change current to ms-112

shared/attributes.asciidoc
This PR adds a variable / shared attribute for https://www.elastic.co/docs/api/doc/cloud
=> Add shared attribute for Elastic Cloud API

.buildkite/scripts/build_pr.sh
docs/build-pr is the slowest job in apm-server CI pipeline and it is impacting significantly developer velocity when merging PRs. Update the buildkite pipeline to exit early if there are no docs changes.
APM Server docs is actually in a separate repository (observability-docs) and the few remaining files are barely touched (except for the changelog)
=> feat: skip build for APM Server if there are no code changes

resources/web/docs_js/components/console_widget.jsx
Flagged by @serenachou, we didn't have this [nice local dev page](https://www.elastic.co/guide/en/elasticsearch/reference/current/run-elasticsearch-locally.html) when we updated the widget.
This only spins up ES and Kibana, so reviewer let me know if you agree with pointing there.
ℹ️ We'll update again to point to `start-local` when the time comes
=> Update local installation URL in code widget

.buildkite/scripts/build_pr.sh
the check fails if we're targeting a branch that is not the default branch.
Since we run git fetch before the diff, we know for a fact that the remote branch exist so just specify the remote and use the remote branch in the diff.
=> fix(apm-agent-go): always diff against the remote branch 

.buildkite/scripts/build_pr.sh
print the PR number and clarify it has no changes compared to the target branch
=> feat: reword message when skipping docs PR

.buildkite/scripts/build_pr.sh
extend the check to all apm repositories and use a switch to make it easier to add more repo that share common file patterns
as usual nothing changes for repositories not mentioned in the switch (they always build and no git diff is run)
=> feat(apm-*): only build docs if there's a doc change

resources/web/docs_js/index-v1.js, resources/web/style/heading.pcss
In support of https://github.com/elastic/observability-docs/pull/4230
In https://github.com/elastic/observability-docs/pull/4230 I noticed that page subheadings in deeply-nested pages weren't working as expected. The highest heading level I found was h10, but in this PR I added logic for up to h12. Here's [an example](https://observability-docs_bk_4230.docs-preview.app.elstc.co/guide/en/observability/master/apm-sampling.html#distributed-tracing-examples) of before/after this PR:
| Before<br>(`h10`, no formatting) | After<br>(`h3`, with formatting) |
|---|---|
| <img width="1422" alt="Screenshot 2024-09-10 at 2 57 48 PM" src="https://github.com/user-attachments/assets/b2fc2410-142f-4ceb-a875-29fbad65e832">  | <img width="1415" alt="Screenshot 2024-09-10 at 2 59 55 PM" …
=> Handle more heading levels

conf.yaml, shared/attributes.asciidoc
This PR updates the conf.yaml to start building 8.16 doc from the 8.x branch that now exist in the apm-server and observability-docs repos.  It removes attributes that were added to work around broken links from other books.
=> Add 8.x in Observability, Fleet, APM Guides

conf.yaml, shared/attributes.asciidoc
This PR starts publishing the Security Guide from the 8.x branch
=> Add 8.x for security-docs

conf.yaml, shared/attributes.asciidoc
This PR adds the 8.x branches in all of the Elasticsearch and Enterprise Search client repos.
=> Add 8.x for clients

.buildkite/pull-requests.org-wide.json
Grant build access to the `elastic-observability-automation` GitHub app - https://github.com/apps/elastic-observability-automation
Otherwise no docs builds are triggered automatically.
See https://github.com/elastic/apm-server/pull/14119
Part of https://github.com/elastic/observability-robots/issues/2418
=> support elastic-observability-automation in pull-requests.org-wide.json

conf.yaml
This changes "current" for the Cloud ESS docs to ms-113.
=> ESS - Change current to ms-113

conf.yaml
This changes "current" for the Cloud ESS docs to ms-114.
=> [Merge on release day] ESS - Change current to ms-114

shared/versions/stack/8.16.asciidoc
This PR copies the contents of 8.x.asciidoc to a new 8.16.asciidoc file.
Updating the former to now reflect 8.17 will occur in a separate PR when all the necessary branches exist.
=> Add 8.16 version attributes

.buildkite/scripts/build_pr.sh
extend the check to all remaining repositories
=> feat(all): only build docs if there's a doc change

shared/versions/ece/ms-105.asciidoc
This changes the version of the ms-105 branch in the ECE docs to version 3.7.3.
=> Update ECE version to 3.7.3

.buildkite/scripts/build_pr.sh
do not fetch tags (they are unused)
use a treeless clone of the target branch instead of cloning the default branch: the initial clone of the default branch is unused, we are only interested in the target branch to compare the diff with the PR.
=> feat: reduce clone/fetch size when building docs PRs

.buildkite/scripts/build_pr.sh
This reverts commit 3de8dadcacaba6e3b9973e6b5c34a8d52be86f82.
This commit seems to break Kibana PR CI
=> Revert "feat: reduce clone/fetch size when building docs PRs (#3094)"

conf.yaml
This changes "current" for the Elastic Cloud docs to ms-115
=> Update Cloud current to ms-115

resources/asciidoctor/lib/docbook_compat/convert_admonition.rb, resources/asciidoctor/spec/change_admonition_spec.rb, resources/asciidoctor/spec/docbook_compat_spec.rb, resources/web/style/admonishment.pcss
The new AsciiDoc serverless docs have lots of admonitions with titles. Admonition titles are currently `h3`s. I'd like to change them to:
* _Not_ use a heading tag. Using an `h3` messes with the "On this page" list of headings and can result in headings that are not necessarily incremental (admonitions can come after `h3`s, `h4`s, etc).
* Style using bold text instead of larger text. This is subjective. I just think the current text is too big. 
| Before | After |
|---|---|
| <img width="819" alt="Screenshot 2024-11-06 at 5 03 33 PM" src="https://github.com/user-attachments/assets/ea6099d0-4afc-4c7e-9224-2dbe930d067e"> | <img width="819" alt="Screenshot 2024-11-06 at 5 03 54 PM" src="https://github.com/user-attachments/assets/dfe0c1be-1cd6-49d6-8832-811fa71fb480"> |
=> Change admonition title style/syntax

shared/attributes.asciidoc, shared/versions/stack/master.asciidoc
Relates to https://github.com/elastic/docs-content/pull/182
This PR moves the declarations from https://github.com/elastic/docs-content/blob/7602ddbdb3de8fe99b0850423c308f85e2952d6d/serverless/index.asciidoc?plain=1#L13 to the list of shared attributes so that they can be used in all books.
=> Add serverless shared attributes

conf.yaml
This adds the ECK 2.15 branch to the build list. ECK 2.15.0 is planned for release on Thu, November 07, 2024. Please do not merge until the day before (Wed, November 06).
=> Add ECK 2.15

conf.yaml, shared/versions/stack/8.15.asciidoc, shared/versions/stack/8.16.asciidoc, shared/versions/stack/current.asciidoc
The following PRs/issues address broken links:
- https://github.com/elastic/kibana/pull/198854
- https://github.com/elastic/cloud/pull/133754
- https://github.com/elastic/search-docs-team/issues/220
- https://github.com/elastic/observability-docs/issues/4479
=> Bump current to 8.16

doc_build_aliases.sh
To be consistent with other build aliases, we should remove the --open flag. Might be worth adding it to all the other aliases at some point.
=> Remove open flag on docbldserverless

build_docs.pl
This PR must be merged after https://github.com/elastic/kibana/pull/199396
It starts checking the SERVERLESS_DOCS links in the Kibana doc link service.
=> Check SERVERLESS_DOCS links in Kibana

doc_build_aliases.sh
Removing flag to be consistent with other build aliases.
=> Remove --open flag from apm doc build

conf.yaml
This PR sets the ECK 2.15 branch as the current version.
This PR depends on https://github.com/elastic/docs/pull/3100 which should be merged first. It's submitted early only to get approval, I'll rebase on Wed, November 06 once https://github.com/elastic/docs/pull/3100 is merged.
Do not merge before ECK 2.15 release date (November 7, 2024).
=> Make ECK 2.15.0 the current version

shared/versions/stack/8.16.asciidoc
DO NOT MERGE UNTIL 8.16.1 IS OFFICIALLY RELEASED
[Docs release issue](https://github.com/elastic/dev/issues/2884)
=> Bumps the doc version to 8.16.1

resources/web/style/base_styles.pcss
It looks like the marketing nav is now sticky when you scroll down the page. As a result it's covering the book title and version dropdown on the left and part of the "On this page" section on the right. 
| Before marketing nav change | Now (with sticky marketing nav) |
|---|---|
| <img width="1645" alt="Screenshot 2024-11-21 at 5 58 23 PM" src="https://github.com/user-attachments/assets/b6d9c949-7e2b-4dab-bb3a-fe5de305e2e1"> | <img width="1644" alt="Screenshot 2024-11-21 at 5 57 45 PM" src="https://github.com/user-attachments/assets/81db9d59-fa94-4a09-8211-4d95736e6341"> |
This PR adjusts the CSS to accommodate the new nav behavior. This fix is pretty fragile &mdash; if the height of the nav at any screen width changes, the docs content may have too much or too little space at the top. …
=> Accommodate sticky marketing nav

.buildkite/pull-requests.org-wide.json, .buildkite/scripts/build_pr.sh
Add docs PR builds for https://github.com/elastic/observability-robots-playground
I'm figuring out how the buildkite-pr-bot works for the Organization so I can support the case of enabling the merge-queue for the APM Server and other projects.
For that reason, I only want to enable the docs-builds in https://github.com/elastic/observability-robots-playground without actually building anything, but I want to exit as soon as the repository is cloned.
Part of https://github.com/elastic/observability-robots/issues/2009
=> test: figure out how to enable the merge-queue in elastic/observability-robots-playground

.buildkite/pull-requests.org-wide.json
Adds elastic/integration-docs repo to the pull-requests template file to enable PR previews in integration-docs.
=> Add elastic/integration-docs to pull-requests template file

shared/attributes.asciidoc
This PR adds a shared attribute for https://www.elastic.co/docs/api/doc/serverless.
=> Adds api-kibana-serverless attribute

conf.yaml, doc_build_aliases.sh
⚠️ Dependent on https://github.com/elastic/search-ui/pull/1093
Adds a new Search UI book to the config. This is part of an effort to move the [current Search UI docs](https://www.elastic.co/docs/current/search-ui/overview) to AsciiDoc. There is a bit of a 🐔 / 🥚 problem with this process:
* This PR is dependent on a PR in elastic/search-ui that adds an AsciiDoc index file (https://github.com/elastic/search-ui/pull/1093).
* This PR adds a stub Search UI book with just a single index page from the elastic/search-ui repo. This stub book will _not_ be indexable by search engines. 
* After this PR is merged, I will open a PR in elastic/search-ui to add all the AsciiDoc content. That PR will include a preview that the docs and search teams can use to validate the AsciiDoc version of the Search …
=> Add Search UI to config

.buildkite/pull-requests.org-wide.json
Adds `elastic/search-ui` repo to the pull-requests template file to enable PR previews in [elastic/search-ui](https://github.com/elastic/search-ui).
=> Add elastic/search-ui to pull-requests template

conf.yaml
This changes "current" for the Cloud ESS docs to ms-117.
=> ESS - Change current to ms-117

shared/versions/stack/8.16.asciidoc, shared/versions/stack/8.17.asciidoc, shared/versions/stack/8.x.asciidoc, shared/versions/stack/master.asciidoc
This PR adds a shared attribute to link to the appropriate branch in https://www.elastic.co/docs/api/doc/elasticsearch
=> Add api-es shared attribute

resources/web/style/base_styles.pcss
In collapsible blocks, only animate the icon before the `summary` that is a direct child of the `details` element.
=> Fix collapsible animation

conf.yaml, doc_build_aliases.sh
PR to add reference architectures section to the docs
=> adding reference architecture content set

conf.yaml
This changes "current" for the Cloud ESS docs to ms-119.
=> ESS - Change current to ms-119

shared/attributes.asciidoc
This PR adds a shared attribute for https://www.elastic.co/guide/en/elastic-stack/9.0/index.html for links to that book for release notes during the content migration.
=> Add stack-ref-90 attribute

.buildkite/scripts/build_pr.sh
This PR updates the legacy doc build to only run in https://github.com/elastic/docs-content when the serverless dir has changes. All other updates made in that repo impact V3.
=> Only run the legacy docs build in elastic/docs-content when needed

conf.yaml
This changes "current" for the Cloud ~ESS~ ECH docs to ms-120.
=> ESS - Change current to ms-120

conf.yaml
Follow up to https://github.com/elastic/docs/pull/3173.
Removes `master` from the doc build in `cloud-on-k8s` and `ecctl`
=> remove more master branches

.buildkite/scripts/build_pr.sh
Test out using a glob pattern in `build_pr.sh` to determine when we should run the AsciiDoc preview build. If this works, it will be an imperfect solution because it would not build if only an image was updated in a PR, but that might be ok. 🤷 
To test this we'll have to:
1. Merge this PR
2. Open a test PR in elastic/ecs-logging
Then come back here and update the other repos.
@bmorelli25 what do you think about this approach?
=> Test using glob in `build_pr.sh`

conf.yaml
To merge on release day (Currently scheduled to March 6)
=> Make ms-121 current for ESS/ECH

doc_build_aliases.sh
This PR adds an alias for the 9.0 Installation and Upgrade Guide, which uses a different set of sources that its earlier versions. The lack of asciidoc content in those folders otherwise causes build errors.
=> Add alias for temporary Installation and Upgrade Guide

conf.yaml
Follow up to https://github.com/elastic/docs/pull/3173
We're migrating the latest major version of each APM agent's docs from AsciiDoc to Markdown. Because of the way APM agent teams manage release branches, it's important that they are able to force push from `main` to the latest major version branch.
In the initial migration PRs (https://github.com/elastic/docs-eng-team/issues/130), we deleted AsciiDoc files and added Markdown files to `main`. We should also do the same for the latest major version to make it easier for engineers to make changes to the latest version. But, if we delete the AsciiDoc files on the latest major version branch, we need to pull AsciiDoc files from a different branch for the next ~3 weeks (until the Markdown docs are live on `elastic.co`).
I created a new …
=> [migration] Update `current` branch for APM agent docs

.buildkite/scripts/build_pr.sh
Test out using a wildcard pattern in `build_pr.sh` to determine when we should run the AsciiDoc preview build. If this works, it will be an imperfect solution because it would not build if only an image was updated in a PR, but that might be ok. 🤷 
This PR builds on https://github.com/elastic/docs/pull/3182 by wrapping the path in quotes. It looks like that _could_ be necessary in some environments when using wildcards, and since `"origin/$GITHUB_PR_TARGET_BRANCH"` is wrapped in quotes even though it works without them on my local machine... I'm hoping this is the trick. I also expanded the matching pattern to include any AsciiDoc file. (I'm not sure if there's a better way to test this.)
To test this we'll have to:
1. Merge this PR
2. Open a test PR in elastic/ecs-logging
Then come back …
=>  Test wildcard pattern in `build_pr.sh` (part 2)

conf.yaml
This PR changes the current version of the Elastic Cloud Hosted docs to ms-122. This should be the last milestone published with the current asciidoc system.
To merge on release day (currently scheduled for March 25)
Closes: https://github.com/elastic/dev/issues/3070
=> [Cloud Hosted] Make ms-122 current

conf.yaml, shared/versions/stack/8.17.asciidoc, shared/versions/stack/8.18.asciidoc, shared/versions/stack/8.x.asciidoc, shared/versions/stack/9.0.asciidoc, shared/versions/stack/master.asciidoc
Bumps APM Android agent to 1.x. Related to https://github.com/elastic/apm-agent-android/pull/443.
=> Bump APM Android agent to 1.x

conf.yaml, shared/versions/ece/current.asciidoc, shared/versions/ece/master.asciidoc, shared/versions/ece/ms-119.asciidoc
This changes "current" for the ECE docs to version 3.8.0.
Do not merge until release day (~February 5th~ April 4th 2025)
=> Change current for ECE docs to 3.8

.buildkite/scripts/build_pr.sh
Follow up to #3182 
Only run the docs PR preview job when an AsciiDoc file is edited. 
Note: This is an imperfect solution because it would not build if only an image was updated in a PR, but that might be ok at this point. 🤷
=> Make `build_pr` script more specific

conf.yaml
This PR updates conf.yaml since 8.x branch has been replaced by 8.19 in logstash-docs
=> Update logstash-docs in conf.yaml

build_docs.pl
Relates to https://github.com/elastic/kibana/pull/218492, https://github.com/elastic/kibana/pull/218493
The Kibana doc link service now includes some links to API docs that are published outside the docs system, so they should not be included in the current docs system link checker.
=> Omit API URLS from Kibana doc link checks

conf.yaml
Attempts to fix broken build
@pquentin pointed to this list of repos that renamed 8.x to 8.19: https://github.com/elastic/devtools-team/blob/main/.github/workflows/scripts/clients.config
=> Update clients docs to use 8.19 branch

shared/attributes.asciidoc
Logstash plugin docs need this attribute in order to resolve correctly for 8.x and earlier versions.
=> Add shared attribute for classic docs

Dockerfile
Following its EOL, Debian Buster has been removed from upstream, breaking asciidoc builds. This PR will introduce an updated environment aiming for as little friction as possible with the current implementation.
=> [WIP] Update Dockerfile

shared/versions/stack/8.19.asciidoc
❗ DO NOT MERGE UNTIL RELEASE DAY ❗ 
Related issue: https://github.com/elastic/dev/issues/3253
Bumps the version to `8.19.2`.
=> 8.19.2 Bump PR 

conf.yaml, extra/docs_landing.html
Updates the /guide landing page to specify the Elastic Stack 8.19 and earlier. 
Adds SEO title and description meta data to specify the Elastic Stack 8.19 and earlier.
=> Updates landing page and conf.yaml to specify Elastic Stack 8.19 and earlier

resources/asciidoctor/lib/chunker/v3-mapping.json
Fixes the link from the /guide ECH release notes to the /docs ECH release notes
=> Updates URL for ECH release notes

shared/versions/stack/8.19.asciidoc
8.19 released a few months ago. need to change the release state so "this is unreleased" notes that rely on the state disappear
=> Change 8.19 release state from unreleased to released
