elastic/docs

- conf.yaml
Also adds Oxford comma in several places where it was absent. Do not merge until 4.1 is released.
> Adds Kibana 4.1 branch.

- conf.yaml
It used to be a single document, now it's a multi-page guide, similar
with the others.
> Libbeat has now a normal reference guide

- conf.yaml
It's practically identical with 1.0.1, so we don't need to keep it around.
> Removed version 1.0.0 for Beats

- conf.yaml
Removes the Logstash Roadmap from the doc build as requested by @acchen97 and @suyograo
> Remove logstash roadmap from the doc build

- conf.yaml
Topbeat was removed in 5.0 release but still exists in the 1.x releases. As master is 5.x releases, the most recent docs have to be pointed to 1.3.
> Point most recent topbeat build to 1.3 instead of master

- conf.yaml
The 1.3 docs should be enabled when the 1.3.0 release is officially made.
> Remove docs for Topbeat 1.3

- conf.yaml
Still referring to alpha4 for now, will change it to alpha5 on the release day. But this gets us the 5.0 online so we know it works.
> Add 5.0 branch for Beats

- conf.yaml
@clintongormley or @debadair Could you review and let me know if these changes are LGTM?
I updated conf.yaml to change where Elastic Cloud docs get built (and externalized) from. See #1820 for the background why this change is being made.  
(Not sure what the change at l193 is. I'm guessing there were some stray spaces that got removed. )
> Add new branch for Elastic Cloud to externalize doc changes from

- conf.yaml
Changed lines 393-395, and tested with `build_docs.pl --all`
```
current:    1.0.0-alpha3
branches:
- 1.0.0-alpha3
```
> Update conf.yaml for Cloud Enterprise to pull from 1.0.0-alpha3 branch

- resources/website_common.xsl
Those are just for explicitly tracking snippets that shouldn't be
converted to `// CONSOLE`. The console widget doesn't make sense
for them.
> Don't add console widget to snippets marked // NOTCONSOLE

- conf.yaml
Curator 4.1 release can happen once this works.
> Add Curator 4.1 as a potential branch

- conf.yaml
Preparing for the beta release.
> Metricbeat can in alpha no more

- build_docs.pl
Although `--chunk=1` works well, we document in the README to use `--chunk 1`.
This commit makes that consistent.
> Update chunk option documentation

- conf.yaml
Just a quick change of which is current
> Make Curator 4.2 the current branch

- resources/web/docs.js
Adds the `Content-Type: application/json` header to the curl
request generated by the `COPY AS CURL` links if the request
has a body.
Closes #143
> Add Content-Type header to COPY AS CURL

- conf.yaml
This path does not exist anymore in 5.x and 5.3.
> Exclude 5.x, 5.3 branch for metricset path

- conf.yaml
Two changes in this PR:
- ECE beta1 goes live in two days and we need to be able to build from the 1.0.0-beta1 branch  
- On Clint's recommendation, switching to chunk=1 so that we can build the Swagger API docs as hoped (I'm going through the output separately to add any missing [float] tags)
> Update conf.yaml for ECE beta1 and add chunk=1

- resources/es-asciidoc.conf
- resources/extract-tagged.py
This macro allows you to include a portion of a file like this:
```
["source","java",subs="attributes,callouts,macros"]
--------------------------------------------------
include-tagged::{doc-tests}/DeleteDocumentationIT.java[delete-request]
--------------------------------------------------
<1> Index name
<2> Type
<3> Document id
```
Which can be used to extract a section of a file like this:
```
// tag::delete-request
DeleteRequest request = new DeleteRequest(
"index",    // <1>
"type",     // <2>
"id");      // <3>
// end::delete-request
```
> Add include-tagged macro

- conf.yaml
In preparation for translation, "docs/en" folders are being added to the x-pack-* repositories.
This PR updates the conf.yaml to use those new directories for the documentation builds.
> [DOCS] Update conf.yaml with new X-Pack translation folders

- conf.yaml
Last of the 4.x branch. Not the current version.
> Add Curator 4.3

- conf.yaml
We're releasing a 1.0.0-beta2 branch next week, which requires an accompanying doc branch.
> Add ECE 1.0.0-beta2 branch

- conf.yaml
The Elastic Cloud Enterprise docs already used chunk=1. I did some reshuffling of Elastic Cloud content and I would prefer that content to also use --chunk=1. By and large, we have the right [float] tags in place to make this work.
> Change Elastic Cloud docs build to use --chunk=1

- conf.yaml
Adds the Beats Developer Guide to the docs.
This PR needs to be merged at the same time as https://github.com/elastic/beats/pull/4030
Note that `generate/metricbeat/metricset` was removed from the Metricbeat section because the file at the path is no longer used in the docs.
> Add Beats devguide

- resources/extract-tagged.py
Java files that are references by `include-tagged` have to
comment out the callouts so the java files compile:
```java
// tag::bool
boolQuery()
.must(termQuery("content", "test1"))    // <1>
.must(termQuery("content", "test4"))    // <1>
.mustNot(termQuery("content", "test2")) // <2>
.should(termQuery("content", "test3"))  // <3>
.filter(termQuery("content", "test5")); // <4>
// end::bool
```
This removes the `// ` part from the docs because it is distracting.
> Remove `//` from included callouts

- conf.yaml
This PR adds 5.4 to the list of version branches in the X-Pack Reference.
> [DOCS] Add X-Pack 5.4 doc version

- build_docs.pl
- lib/File/Which.pm
- python
This PR adds the `docs/` dir into the `PATH` and provides a `python` executable (written in Perl) which tries to find `python2.7` down to `python2.3`.
Closes #178
> Add a proxy for the python executable which can look up python2 binaries

- conf.yaml
We need to start building the 1.0.0 ECE docs, so that UI help links will work, both for manual and automated testing. Replaces https://github.com/elastic/docs/pull/181.
> Start building the 1.0.0 ECE docs for testing

- conf.yaml
This PR adds the x-pack-kibana repo to the Kibana Reference in the conf.yaml so that it can start including content from that repo in the 5.x and master versions.
> [DOCS] Add xpack-kibana repo to Kibana Reference

- conf.yaml
We GA on May 31. I need to switch the current branch for the ECE doc builds to 1.0.0 for that event.
> Switch ECE current branch to 1.0.0

- conf.yaml
ECE has GA'ed and we no longer offer the install scripts for versions before GA. Time to remove the old docs?
> Remove pre-1.0.0 ECE docs except beta2

- conf.yaml
This pull request updates the conf.yaml to use the index-all.asciidoc for building the Elasticsearch Reference. 
The index-all.asciidoc was created in https://github.com/elastic/elasticsearch/pull/25186 and https://github.com/elastic/elasticsearch/pull/25164
As a result of all these pull requests, the Elasticsearch Reference can integrate content from X-Pack-specific repositories.
> [DOCS] Use index-all.asciidoc for Elasticsearch Reference

- web/search.psgi
This patch makes the search app return an HTTP error (502) when it's unable
to interact with Elasticsearch. This is extremely useful in a load-balanced
configuration, since it allows the load-balancer to automatically drop a
node from rotation in the event of the localhost Elasticsearch process
stopping.
Without the patch, 200-OK is returned, the node stays in rotation, and null
results are returned all the way to the web client.
> Return "502 Bad Gateway" if Elasticsearch is down

- conf.yaml
This pull request is related to https://github.com/elastic/kibana/pull/12062
It updates the conf.yaml to match changes made in the section for the Elasticsearch Reference, so that the Kibana Guide is built from the appropriate directory and has appropriate edit_url paths.
> [DOCS] Update paths for Kibana Guide in conf.yaml

- conf.yaml
This pull request updates the conf.yaml to build the Logstash Reference from the x-pack-logstash repository instead of the logstash or logstash-docs repos.
I have run successful local documentation build tests against all of the Logstash releases.
Note that it also integrates and duplicates a recent commit @clintongormley made to address problems with the edit_url links.
> [DOCS] Build Logstash Reference from x-pack-logstash

- sharedattributes.asciidoc
This pull request creates a list of attributes that can be used by all the documentation builds, so that attribute names are synchronized across the repositories.  This is particularly important since many of the builds now integrate content from multiple repositories.
> [DOCS] Created shared attribute file

- conf.yaml
This pull request adds the elastic/docs repository to the conflict.yaml and associates it with several books that are seeking a shared attributes file in that repository.
> [DOCS] Add elastic/docs repo to conf.yaml

- sharedattributes.asciidoc
This PR adds the "javaclient" attribute to the list of shared attributes.
> [DOCS] Add Java API URL to shared attributes

- conf.yaml
This pull request is related to efforts to re-use a set of shared attributes across multiple books.  
It adds the docs repo to multiple books, in particular the docs/shared folder.
For example, see https://github.com/elastic/elasticsearch/pull/25479
> [DOCS] Add docs repo to books

- conf.yaml
As discussed during a Cloud meeting, we plan to start building the docs for the ECE 1.0.x releases out of the `1.0` branch. We also want to remove the old 1.0.0-beta2 docs and, eventually, the  1.0.1 & 1.0.0 doc builds.
We probably want to do this in two stages, as we'll need to get the 1.0 docs building before putting redirects for 1.0.1 & 1.0.0 in place. So, add new current `1.0` branch first,  remove old 1.0.x branches later. 
Depends on:
> Switch to 1.0 branch for ECE 1.0.x releases

- resources/web/styles.css
This pull request adds the x-pack icon for sidebars that are tagged as follows:
````
[role="xpack"]
.Block heading
*******************************************
Block text
*******************************************
````
> [DOCS] Add xpack icon for sidebars

- conf.yaml
Two changes here:
- Remove the 1.0.1 and 1.0.0 doc builds now that we are building from 1.0 as our preferred 1.0.x doc branch (depends on redirects to 1.0 being live via https://github.com/elastic/website-www.elastic.co/issues/1782)
- Add builds for master branches for both EC and ECE
> Update Elastic Cloud and ECE doc builds

- conf.yaml
This adds the apm server and apm agents to the doc build. On the top level there will be a link to the `APM Server` docs and a link to the `Agents`. The Agents are nested the same way as the Elasticsearch Clients. Under `Agents` there is a list with the Node.js and Python agent at the moment. The docs for now are only shown from `master` as there are no release branches yet.
Server and Agents already have the `docs/index.asciidoc` file in their master branch.
* @roncohen @makwarth Does this structure work for you? Later on we should probably come up with a longer title.
* @debadair I saw that some projects now have `docs/en/index.asciidoc` in the repo itself. Could it make sense to introduce this structure or will this only apply to a subset of repos?
* @dedemorton I was not sure what to …
> Add APM Server and Agents to doc build

- conf.yaml
- shared/versions56.asciidoc
Opening this now so we don't forget to change the order of the client docs to put the Java REST client before the Java API client.
> Bumped versions for 5.6/beta2 and swapped order of ES Java client docs.

- shared/attributes.asciidoc
I'm not sure if this is the normal procedure for adding new references, so please let me know if I should do this in another way.
We're going to be making a lot of cross reference links in the docs between the different APM components. So having these references will help keep everything nice and clean.
> Add apm related asciidoc attributes

- shared/attributes.asciidoc
This centralizes the definition of the password that we show in examples.
> Add pwd attribute to shared attributres

- conf.yaml
Change file name to index.asciidoc to be more aligned with standard naming.
> Rename entry point for APM getting started.

- README.asciidoc
Without this, the instructions are incomplete and I got errors such as `Can't locate Storable.pm'
> Add required perl module installation for Fedora 25

- conf.yaml
Elastic Cloud has switched to the `saas-release` branch for service releases. In an effort to keep the code and the docs together, I'd like to switch to the same branch for the current Elastic Cloud docs and to retire the arbitrarily chosen docs-only `external` branch.
Merging this PR should coincide with the release of the Cloud ID on Tuesday Oct 31 (see https://github.com/elastic/cloud/issues/7412), as `saas-external` already contains those docs.
> Elastic Cloud docs: Switch to saas-release and retire external branch

- conf.yaml
This should only be merged shortly before rc2 is released.
> Add 6.0 version for apm-server documentation.

- shared/settings.asciidoc
This PR adds links to the Centralized Pipeline Configuration Management settings in the Logstash Reference.
> [DOCS] Add centralized pipeline configuration management

- conf.yaml
This PR sets the current branch for ECE to `1.1`, which is the correct branch when we GA tomorrow morning.
> Change current ECE branch to 1.1

- build_docs.pl
Related to https://github.com/elastic/docs/issues/249
This PR adds the --nolinkcheck parameter, which skips the step that checks links at the end of a --all build.  For example, you can use it as follows:
> ./build_docs.pl —all —nolinkcheck
...
Writing main TOC
Writing extra HTML redirects
Skipped Checking links
This is required for when a broken link is preventing us from successfully publishing the documentation in a time-critical situation.  
The expectation is that any broken links would be fixed as soon as possible and link checking would be resumed immediately thereafter.
> [DOCS] Added --nolinkcheck parameter

- build_docs.pl
Relates to https://github.com/elastic/docs/issues/249, in particular: 
> Check cross-doc links and perform other post-build verification on specific books using the already-built versions of everything else.
This PR adds the ability to skip the time-consuming steps related to fetching and building documentation.  For example:
> ./build_docs.pl --all --linkcheckonly
*** USING lcawley-linkcheckonly BRANCH ***
Checking GitHub username and password
Updating repositories
Skipping fetching repo apm-agent-nodejs.
Skipping fetching repo apm-agent-python.
Skipping fetching repo apm-server.
Skipping fetching repo beats.
Skipping fetching repo cloud.
Skipping fetching repo curator.
Skipping fetching repo elasticsearch.
Skipping fetching repo elasticsearch-hadoop.
Skipping fetching repo …
> [DOCS] Added --linkcheckonly parameter for build_docs.pl

- conf.yaml
The master branch will see some incompatibilities landed between
now and 6.2 (when APM goes GA). This should avoid that those
incompatibilities land on
https://www.elastic.co/guide/en/apm/agent/python/current/index.html
before GA.
> set current branch of apm-agent-python to "1.x"

- conf.yaml
The entry was missing the leading dash and the docs path had been removed.
> Fix entry for APM frontend docs

- conf.yaml
Adds the kibana-extra folder to the paths in the conf.yaml
> [DOCS] Add kibana-extra folder to conf.yaml

- conf.yaml
In anticipation of the upcoming release of version 1.0.0 of the Node.js APM Agent we have made a `1.x` branch. In the upcoming Kibana 6.2 we have embedded links to the `1.x` version of the Node agent docs, so it's important that this is merged in before the 6.2 release.
Once version 1.0.0 is released I'll make a PR to switch `current` to point to `1.x` instead.
> apm-agent-nodejs: add 0.x and 1.x branch

- conf.yaml
The Japanese and Korean versions of the X-Pack Reference have dependencies on the x-pack-kibana repository, so this PR adds those dependencies to the conf.yaml.
> [DOCS] Added x-pack-kibana to jp and kr

- shared/settings.asciidoc
- shared/settings55.asciidoc
- shared/settings56.asciidoc
- shared/settings60.asciidoc
- shared/settings61.asciidoc
This PR updates the X-Pack Settings tables to include a link to the new auditing settings page.
> [DOCS] Add links to X-Pack Security auditing settings

- conf.yaml
This PR adds the 6.2 branch to the documentation builds. 
At this time, only the Kibana and Logstash versioning is in place to go ahead with the documentation.
> [DOCS] Added 6.2 to documentation builds

- conf.yaml
Don't merge this yet. Waiting for final approval from dev team.
Adds the versioned plugin reference to the documentation build.
> Add versioned plugin docs to the build

- conf.yaml
- shared/attributes.asciidoc
This PR updates the URL for the Elastic Stack Glossary. This change was necessary to address documentation build issues.
> [DOCS] Updated glossary URL

- conf.yaml
The source files are in a new private repo: elastic/swiftype-doc-placeholder 
You can view the generated doc at: https://swiftype-doc.firebaseapp.com
> Added Swiftype placeholder book to the build.

- conf.yaml
- doc_build_aliases.sh
This PR is related to https://github.com/elastic/docs/pull/302
It updates the conf.yaml and doc_build_aliases.sh so that "index.asciidoc" is unchanged and a new index.x.asciidoc is added instead.
> [DOCS] Update Logstash Ref doc build

- conf.yaml
- doc_build_aliases.sh
This PR is related to https://github.com/elastic/kibana/pull/16450
It updates the conf.yaml and doc_build_aliases.sh to reflect the changed location of the Kibana Guide's index.asciidoc.
> [DOCS] Update Kibana doc build

- conf.yaml
- doc_build_aliases.sh
This PR is related to https://github.com/elastic/elasticsearch/pull/28469
It updates the conf.yaml and doc_build_aliases.sh to reflect the changed location of the index for the Elasticsearch Reference.
> [DOCS] Update Elasticsearch doc build

- conf.yaml
Fixes the doc build so the versioned plugin reference doesn't get build every time you run the doc build with the --all option.
> Fix URL for versioned plugin reference

- conf.yaml
There's [already a PR](https://github.com/elastic/docs/pull/307) that indirectly adds these, but it would be nice to get this in to `master` prior to that PR is merged so we know that the docs are building without any issues before the release.
> Add 6.2 branch to apm-server project

- conf.yaml
- lib/ES/Book.pm
- lib/ES/Util.pm
- resources/website_common.xsl
These  changes inject two new meta tags into the HTML files, DC.subject and DC.identifier. 
DC.subject is the subject set for each book in conf.yaml. This is the product facet that will be used for filtering in the Swiftype search results and aligns with the tags that the web team is applying to other types of content on the site.
DC.identifier is the version of the book. Explicitly setting the version in a separate meta tag makes it easier to extract.
These tags make it easier to extract and align the information needed for the Swiftype search, without affecting the values currently set in the tags attribute in conf.yaml.
> Meta tags for Swiftype Search

- conf.yaml
Fixes issue in the broken doc build. I had to exclude all branches because this file was added to master only. Someone will need to update the exclude_branches setting when https://github.com/elastic/elasticsearch/pull/28814 gets ported to other branches.
@debadair
> Fix broken doc build

- resources/web/docs.js
Adds support to copy-as-curl for `"""` delimited strings. `"""` delimited
strings are natively supported by Kibana's CONSOLE but don't work
properly in Elasticsearch unless you convert them into normal JSON. This
adds support to `copy-as-curl` to do that conversion.
> Add support for """ strings in copy-as-curl

- resources/web/docs.js
Clean up """ed strings output by copy-as-curl so they look fairly good.
* Trim leading newlines
* Trim leading whitespace from the first line
* Trim the same amount of whitespace from each subsequent line
* Trim trailing whitespace
> Clean up """ed strings in copy-as-curl

- conf.yaml
This PR fixes the Stack Overview Guide in the conf.yaml, so that it uses the same syntax as the successful command in the doc_build_aliases.sh.  That is to say:
'$GIT_HOME/docs/build_docs.pl --doc $GIT_HOME/stack-docs/x-pack/docs/en/index.asciidoc --resource=$GIT_HOME/kibana/x-pack/docs --resource=$GIT_HOME/elasticsearch/x-pack/docs --chunk 1'
> [DOCS] Added --resources for Stack Overview Guide in conf.yaml

- conf.yaml
This PR adds the x-pack/qa/sql resource for building the Elasticsearch Reference in 6.x and master branches.  That directory contains files that are used for code snippet testing.
> [DOCS] Adds qa/sql to conf.yaml

- conf.yaml
This PR corrects the path for the Logstash Reference in the conf.yaml to address documentation build errors.
> [DOCS] Fixes Logstash path

- README.asciidoc
Devs and contributors are confused about how to do this now. I think we need to continue to mention that attributes can be defined in under the book title (until we get the whole library cleaned up), or people will be confused.
> Add info about shared attributes

- conf.yaml
Two purposes for this branch:
1. Build UCv2 docs for testing
2. Have a Plan B in case we don't have a hard cut-over from UCv1 to UCv2
> Add saas-release-v2 branch for UCv2 docs

- doc_build_aliases.sh
This PR re-adds the commands necessary to build the Elasticsearch Reference, Logstash Reference, and Kibana User Guide in 6.2 and earlier.
If you have better suggestions for the alias names, let me know!
> [DOCS] Adds aliases for pre-6.2 build commands

- conf.yaml
This PR adds a reference to the CHANGELOG.asciidoc in the conf.yaml, since it was otherwise not being found during the ./build_docs.pl --all build.
> [DOCS] Adds CHANGELOG.asciidoc

- doc_build_aliases.sh
This PR updates the doc_build_aliases.sh file such that people who are using the aliases to build OSS-only documentation now build the full documentation instead. 
Related to https://github.com/elastic/logstash/issues/9596, https://github.com/elastic/kibana/issues/19156, and https://github.com/elastic/elasticsearch/issues/30665
The following PRs should be merged first:
https://github.com/elastic/kibana/pull/19192
https://github.com/elastic/logstash/pull/9607
https://github.com/elastic/elasticsearch/pull/30707
> [DOCS] Replaces OSS-only doc build command aliases

- conf.yaml
With UCv2 out, we need to change `current`.
> Change Elastic Cloud current for UCv2

- conf.yaml
Relates to https://github.com/elastic/cloud/issues/15752. We need to start building Heroku docs as part of the UCv2 clean-up work.
> Add Heroku doc builds for Cloud

- conf.yaml
Looks like https://github.com/elastic/docs/pull/361 introduced an error into `conf.yaml`. This is the fix. I've hung my head in shame.
> Fix Cloud branches

- conf.yaml
- doc_build_aliases.sh
Related to https://github.com/elastic/logstash/issues/9596 and https://github.com/elastic/kibana/issues/19156
This PR removes references to the x-pack/docs directories in the elastic/logstash and elastic/kibana repos, since that directory doesn't exist anymore in 6.3+
> [DOCS] Remove x-pack/docs from Logstash, Kibana, and Stack Overview doc builds

- conf.yaml
- doc_build_aliases.sh
Related to https://github.com/elastic/stack-docs/pull/49
This PR updates the conf.yaml and build commands to find the new location of the Stack Overview source files.
> [DOCS] Updates stack overview location

- conf.yaml
We started single-sourcing some content in a shared folder. Looks like we might need to add that folder for the builds to work.
> Add shared folder for Cloud docs

- conf.yaml
Looks like the builds are failing because the `shared` folder isn't in all branches (and shouldn't be). This PR excludes the folder from the branches that don't need the folder.
> Exclude certain branches for shared folder

- shared/attributes.asciidoc
Add the apm-server-ref-62 attribute for referring
to version 6.2 specifically, when another branch
is used generally.
(In the Frontend JavaScript APM Agent docs
we use "current" generally, but make specific
reference to 6.2 in one case.)
> shared/attributes: add apm-server-ref-62

- conf.yaml
- shared/versions63.asciidoc
This PR sets the state of the Stack Overview and Kibana Reference to "released" and changes the "current" documentation version to 6.3 in the conf.yaml.
This PR should not be merged until the day of the release.
> [DOCS] Set current documentation to 6.3

- conf.yaml
This PR moves the X-Pack Reference to a lower position on the documentation site, since it won't be updated for 6.3 or later releases.
> [DOCS] Lowers X-Pack Reference on documentation site

- conf.yaml
This PR creates a "Legacy Documentation" section, which contains the old X-Pack, Shield, Marvel, Watcher, and Reporting documentation.  Additional legacy content can be added to that section in subsequent PRs.
> [DOCS] Creates a Legacy Documentation section

- conf.yaml
Updated the config to move the Definitive Guide to the Legacy docs section. It builds locally.
> Moved Definitive Guide to the Legacy section.

- shared/attributes.asciidoc
We need an additional attribute pointing to the real user monitoring agent, so we can refer to it from the APM Server docs.
> Add attribute for APM RUM agent.

- shared/versions64.asciidoc
- shared/versions65.asciidoc
This PR creates the versions65.asciidoc file for use by the 6.x branches.
> [DOCS] Adds 6.5 version information

- conf.yaml
With UCv2 out the door, one clean-up item is to remove our `saas-release-v2` builds, as UCv2 docs will build out of `saas-release`.
Depends on merging down `saas-release-v2` into `saas-release` via  https://github.com/elastic/cloud/pull/15813 
Depends on changing help links from UCv2 to `saas-release` via https://github.com/elastic/cloud/issues/15816
Relates to UCv2 clean-up https://github.com/elastic/cloud/issues/15752
> Elastic Cloud: Switch current for DNT and remove saas-release-v2  (merge on Aug 1)

- conf.yaml
With the arrival of the ECE 1.2 dev branch, it's time to add ECE 1.2 to our roster of doc builds.
> Add ECE 1.2 doc builds

- resources/website-l10n.xsl
Per Carl Spataro, the language we use in the beta tag needs to be updated.
> Beta boilerplate language update per Legal

- conf.yaml
Based on the email thread "When should Cloud docs go live?", we decided to pull the doc build for upcoming releases, such as ECE 1.2 and master. This PR removes these branches from our builds.
> Remove ECE 1.2 and all Cloud master doc builds

- shared/versions56.asciidoc
This PR updates the shared version information that is used by a subset of the 5.6.11 documentation.
> [DOCS] Updates shared versions for 5.6.11

- conf.yaml
Add 6.x to APM UI docs:
https://www.elastic.co/guide/en/apm/get-started/current/index.html
Closes elastic/kibana#22318
> Add 6.x to APM UI docs

- web/config_pages.json
- web/config_site.json
- web/config_titles.json
The public search interface currently runs on a three node cluster. This
patch increases replica shards from 1 to 2, in order to distribute
search load more evenly across the production cluster.
Relates: elastic/infra#6636
> Increase replica shards for Site/Docs Search

- conf.yaml
- doc_build_aliases.sh
- shared/attributes.asciidoc
Related to https://github.com/elastic/docs/issues/423
This PR adds the "Getting Started" book under the "Elastic Stack" section of the documentation landing page.
> [DOCS] Adds Getting Started book

- conf.yaml
- doc_build_aliases.sh
Related to elastic/elasticsearch#30665, elastic/elasticsearch#33248, and https://github.com/elastic/stack-docs/pull/107.
As content moves from the x-pack/docs folder to the docs folder in the elasticsearch repo, the build commands for the Stack Overview (which pulls in some of those files) needs to be updated to find those files.
> [DOCS] Adds elasticsearch/docs to Stack Overview resources

- conf.yaml
This commit adds the Azure Marketplace and
Azure Resource Manager (ARM) template documentation
to the elastic.co documentation.
Closes https://github.com/elastic/azure-marketplace/issues/97
> Add Azure Marketplace and ARM template docs

- conf.yaml
follows on from #427 and #428.  Merge needs to be coordinated with elastic/apm-server#1361, elastic/apm-server#1363, elastic/apm-server#1364, elastic/apm-server#1365
> include apm-server changelogs for all branches

- conf.yaml
On https://www.elastic.co/guide/index.html, added a `:` between `Elasticsearch` and `Store`, and between `Cloud` and `Provision`.
> [DOCS] Updated Elasticsearch and Cloud titles

- conf.yaml
Re-adding the ECE 2.0 doc build in preparation for GA next week, as discussed with Brad.
> Re-add 2.0 ECE doc builds

- shared/versions56.asciidoc
- shared/versions64.asciidoc
This PR updates the version information that is used by books such as the X-Pack Reference, Stack Overview, and Kibana Guide.
> [DOCS] Updates version attributes for 5.6.12 and 6.4.1

- shared/attributes.asciidoc
- shared/attributes62.asciidoc
The "ref-64" attributes contain URLs that are pointing to the 6.x documentation.  This PR fixes the URLs.
> [DOCS] Updates ref-64 URLs

- conf.yaml
This commit adds a 6.4 branch to ARM template documentation in preparation for a new Marketplace release.
> Add 6.4 branch to Azure ARM documentation

- conf.yaml
Our Elastic Cloud (Elasticsearch Service) releases are moving to a milestone-based release cycle. The docs are kept with the production code just as before (we follow the 'docs as code' principle), and so our docs need to follow suit. For the coming Cloud Service Release that goes to staging on November 1, this change means that we need to add `release-ms-13` and use it as `current`. 
(Looking ahead, milestone releases need to be removed and replaced at each milestone boundary. The next build change will remove `release-ms-13` and replace it with `release-ms-14`.)
EDIT: For testing purposes, we want to start building the milestone docs, but not yet change current. Current points to `saas-release` for now.
> Update Elastic Cloud builds to use milestones

- shared/versions56.asciidoc
- shared/versions64.asciidoc
Updated the version information that the doc books use, such as the X-Pack Reference, Stack Overview, and Kibana Guide.
> [DOCS] Updated version attributes for 5.6.13 and 6.4.3

- lib/ES/Util.pm
This removes the "test build" value from the DC.identifier tag for index pages that don't have an associated version. 
This is a bit of a hammer, but I'm not seeing anywhere were removing the default "test build" value for the version variable is going to blow things up. 
@brianjolly
> Removed the default "test build" value from the version variable.

- conf.yaml
I'm open for recommendations about the prefix used to determine the URL.
> Add Infrastructure monitoring docs

- shared/attributes.asciidoc
This is needed to v6.5
When 6.5 is released we'll bump the version of the Node.js APM agent to v2.0.0 which will only support version 6.5 and above of the APM Server.
For users who are still on <6.5, I need to link them to the old version of the agent (v1.x) which still have support for older versions of the stack.
I'm not sure if I could make use of `{branch}` or something similar or if this is the way to do it?
> apm: add ref for Elastic APM Node.js Agent v1.x

- conf.yaml
When the release-ms-13 goes to production, we need to change `current`.
> Update current for Elastic Cloud to release-ms-13

- conf.yaml
Gets functionbeat and journalbeat docs building in 6.x and 6.5 branches.
> Add 6.x and 6.5 branches for Functionbeat and Journalbeat

- conf.yaml
Even though the agent is not released just yet, this is safe to merge as I have already created a `1.x` branch. After the release, I'll move the branch to point to the `v1.0.0` tag.
> Build Java agent 1.x branch

- conf.yaml
This is needed for 6.5.
While the `2.x` branch already exists, version 2.0.0 of the agent hasn't been released yet. It will be at the same time as the 6.5 release, but as the docs build is currently halted until the 6.5 release, this PR should be safe to merge already now.
> elastic-apm-nodejs: add 2.x branch

- conf.yaml
The 4.x branch coincides with the 6.5 release. Unfortunately I forgot to add the 3.x branch earlier, since it is virtually identical with the 2.x branch when it comes to docs.
> Added 4.x and 3.x branches for APM Python agent

- shared/attributes.asciidoc
This should allow APM-Server <6.5 to link to the agent docs
> Added ref for pre 4.x Python APM agent

- doc_build_aliases.sh
This PR adds build commands for the APM books that were missing from the doc_build_aliases.sh file.  If there are better alias names, we can change them as needed.
> [DOCS] Add aliases for APM books

- conf.yaml
This PR updates the ARM template docs to point at the 6.5 branch, to align with the release of 6.5.0 of the ARM template.
> Update ARM template docs to 6.5

- conf.yaml
We've got a `release-ms-14` branch now, so it's time for us to start building those docs. For now, `current` remains unchanged.
EDIT: Don't merge this, yet. It seems we have some bum Asciidoc in the branch that breaks when trying to build it. 
EDIT EDIT: Now fixed, merging.
> Start building our Milestone 14 docs

- conf.yaml
This PR adds a "Legacy" tag to the documentation Topbeat reference and to all the books in the "legacy" section of https://www.elastic.co/guide/index.html
For example, it adds the following to pages in the v6.2 X-Pack Reference:
`<meta name="DC.type" content="Learn/Docs/Legacy/XPack/Reference/6.2" />`
> [DOCS] Add legacy tags

- conf.yaml
The weird branch order for the node and java apm agents has annoyed me for quite some time, and I just figured out how to fix it:
Updating the order of branches for the Node and Java agents to match the rest of the stack. 
@lcawl - is this a safe change to make?
> Update branch order for apm agents

- shared/versions65.asciidoc
Updates the version information that is used by the Logstash, Elasticsearch, and Kibana books.
> [DOCS] Updates for 6.5.2 version attributes

- shared/versions65.asciidoc
This PR updates the version information that is used by documentation such as the Stack Overview, Kibana Guide, Getting Started Guide, etc. 
This PR should not be merged until that release is underway.
> [DOCS] Updates version to 6.5.3

- doc_build_aliases.sh
This PR updates the doc_build_aliases.sh file such that the docbldesold alias creates the OSS-only Elasticsearch Reference for old versions. It adds the docbldesoldx to build the X-Pack-inclusive Elasticsearch Reference for old versions.
> [DOCS] Updates docbldesold alias and adds docbldesoldx

- conf.yaml
This PR adds the `x-pack/filebeat/docs` to the list of directories to look for docs in Filebeat. This is needed so that we can include x-pack specific docs.
> Beats: add x-pack/filebeat/docs to contents

- build_docs.pl
- lib/ES/BranchTracker.pm
- lib/ES/Repo.pm
- lib/ES/Util.pm
Adds the `--target-repo` option to the `--all` mode of `build_docs.pl`
to build the docs into a separate repository. For example:
```
./build_docs.pl --all --target_repo=https://github.com/nik9000/built-docs --skiplinkcheck --push
```
That example will clone the nik9000's `built-docs` repository and build
the documentation into that repository instead of the current
repository.
I'd like this to be required at some point but for now it probably
should stay optional while we work on getting it published.
> Support building docs into a separate repo

- conf.yaml
This PR changes `current` for the Elasticsearch Service to point to `release-ms-14` and removes the previous `release-ms-13` build. 
Relates to https://github.com/elastic/cloud/issues/23611 and https://github.com/elastic/cloud/issues/22665.
> Update Cloud milestone release builds

- conf.yaml
This updates the docs build to look for docs in `x-pack/filebeat/docs` in the 6.x branch too.
> Beats: add path x-pack/filebeat/docs to 6.x branch

- shared/attributes.asciidoc
This PR adds the attributes related to index lifecycle management (which currently exist in
https://github.com/elastic/elasticsearch/blob/master/docs/reference/ilm/index.asciidoc) to the shared list of attributes, so that they can be used in the Stack Overview as well. 
Related to https://github.com/elastic/stack-docs/pull/172
> [DOCS] Adds ilm attributes

- conf.yaml
- doc_build_aliases.sh
Similar to https://github.com/elastic/docs/pull/507, this adds the [`x-pack/auditbeat/docs`](https://github.com/elastic/beats/tree/master/x-pack/auditbeat/docs/modules) folder to the contents.
This is being used by the new Auditbeat system module, and is already present in `master` and `6.x`.
> Add x-pack/auditbeat/docs to contents

- shared/versions66.asciidoc
- shared/versions67.asciidoc
This PR adds the shared versions67.asciidoc, which will be used by 6.7 documentation
> [DOCS] Adds 6.7.0 version info

- conf.yaml
- doc_build_aliases.sh
Related to https://github.com/elastic/docs/pull/512
The Auditbeat Reference was failing with the following errors:
> 13:44:15 asciidoc: WARNING: host.asciidoc: line 8: include file not found: /home/docs/docs/.repos/.temp/nUU8NVjbpg/beats/x-pack/auditbeat/module/system/host/_meta/docs.asciidoc
13:44:15 asciidoc: WARNING: host.asciidoc: line 20: include file not found: /home/docs/docs/.repos/.temp/nUU8NVjbpg/beats/x-pack/auditbeat/module/system/host/_meta/data.json
13:44:15 asciidoc: WARNING: process.asciidoc: line 8: include file not found: /home/docs/docs/.repos/.temp/nUU8NVjbpg/beats/x-pack/auditbeat/module/system/process/_meta/docs.asciidoc
13:44:15 asciidoc: WARNING: process.asciidoc: line 20: include file not found: /home/docs/docs/.repos/.temp/nUU8NVjbpg/beats/x-pack/auditbeat/module/ …
> Fixes x-pack/auditbeat path

- build_docs.pl
- lib/ES/Repo.pm
`--reference` adds support for using a local mirror which is how
Elastic's CI infrastructure usually speeds up big clones.
`--rely_on_ssh_auth` relies on the SSH authentication already configured
to perform all tasks which is conventient because Elastic's CI already
*has* SSH authentication configured and so do many users. Mechanically
causes the script to skip the git authentication tests entirely,
presuming that SSH authentication is already configured. It also causes
the script to transform all configured repositories that happen to use
`https` into `ssh`.
> Add two arguments for ES's Jenkins

- resources/asciidoctor/lib/elastic_compat_preprocessor/extension.rb
- resources/asciidoctor/lib/elastic_compat_tree_processor/extension.rb
- resources/asciidoctor/spec/elastic_compat_preprocessor_spec.rb
- resources/asciidoctor/spec/spec_helper.rb
Asciidoc requires that we fence attributes at the beginning of a section
like so:
```
--
:api: index
:request: IndexRequest
:response: IndexResponse
--
```
But asciidoctor drops the attribute values if they are in the block
which I've filed here:
https://github.com/asciidoctor/asciidoctor/issues/2993
That means that we have to *remove* the blocks for asciidoctor. This
does that.
> Asciidoctor: Work around strange attribute rules

- lib/ES/Util.pm
My previous work on raw xslt opts added extra `'`s around every
variable. This broke all kinds of stuff like chunking and headers and,
well, almost everything! This fixes that and makes that `--verbose`
printing of commands a little more clear.
> Asciidoctor: Fix raw xslt opts

- shared/attributes.asciidoc
- shared/attributes62.asciidoc
This PR updates the {searchprofiler} attribute to match the "Query Profiler" terminology on https://www.elastic.co/subscriptions
> [DOCS] Updates searchprofiler attribute

- resources/asciidoctor/lib/elastic_compat_preprocessor/extension.rb
- resources/asciidoctor/spec/elastic_compat_preprocessor_spec.rb
Asciidoc automatically adds callouts to all source listing regardless of
whether you ask for them or not and we rely on this behavior in the
Elasticsearch docs. This emulates it in asciidoctor. It isn't super
clean because we have to edit the text on the way in, but that is life
sometimes.
> Asciidoctor: Force callouts into source listing

- lib/ES/Util.pm
In Asciidoctor 1.5.0 they switched ` to turn on monospaced formatting
instead of delimiting a monospaced literal. Our docs assume that `
delimits a monospaced literal. Asciidoctor has an attribute that allows
us to go back to the old behavior and this does that.
> Asciidoctor: Handle ` as monospaced literal

- shared/settings.asciidoc
The overview topic was missing links for the infra and logs UIs added in 6.5. 
@lcawl FYI. For backporting, I guess we need a new version of the settings file, no? Let me know if there is anything I'm overlooking.
> Add infra and logs UI to overview topic

- build_docs.pl
- lib/ES/Book.pm
Adds a `--rebuild` option to force rebuilding all branches of all books
regardless of whether or not the source of the books has changed. This
is useful when we need to rebuild the version drop downs after a
release.
> Add option to force rebuilding

- build_docs.pl
Sometimes it is difficult to experiment with changes to the docs build
because we always fetch changes from the source repositories and those
changes can get mixed up in the changes from the experiment. This adds a
`--no_fetch` option to skip fetching changes from the source
repositories. We still fetch changes from the destination repo if there
is one, but the docs that we build are then based on whatever changes
we've pulled locally.
I suspect this'll never get used in CI, but I'll use it fairly
frequently when experimenting locally.
> Add option to skip fetching source repos

- lib/ES/Repo.pm
The `--rely_on_ssh_auth` option designed for use with new-style CI
breaks that the "Edit Me" links by using ssh-style repos for the basis
of the links instead of https. These links obviously don't work in the
browser. This converts this ssh style links into https style links when
building the edit url.
> Fix the edit url with --rely_on_ssh_auth

- build_docs.pl
- lib/ES/Repo.pm
The "Edit" links on each page have historically been broken when
building books with `./build_docs.pl --doc` because we don't have the
right urls. This is mostly fine, but I'd like to do some debugging of
how asciidoctor generates those links so it'd be nice if they worked
with `--doc`. This takes a reasonable stab at making them work by
looking for the git repository that contains the target of the `--doc`
parameter. It then looks for the clone that comes from the `elastic`
organization. It uses that clone as the basis for the edit url.
> Fix edit links for local books

- lib/ES/Util.pm
- resources/asciidoctor/lib/edit_me/extension.rb
- resources/asciidoctor/spec/edit_me_spec.rb
Fixes the edit url when the "base" document directory isn't the base of
the repository.
> Asciidoctor: Fix edit url for nested roots

- lib/ES/Util.pm
Drop the giant xml file produced by asciidoctor after docbook is all done.
We don't keep the xml file we make with asciidoc so we shouldn't keep
the xml file from asciidoctor either. It is useful for debugging, but we
can always get it if we need it.
> Asciidoctor: Drop xml file after docbook

- resources/asciidoctor/lib/scaffold.rb
- resources/asciidoctor/spec/elastic_compat_tree_processor_spec.rb
Our `TreeProcessorScaffold` would crash on definition lists where a term
wasn't matched with a definition. While these *are* broken definition
lists it is not ok for us to crash on them. This skips processing the
`nil` block that comes from such lists.
At this point the Elasticsearch reference builds, though it builds with
quite a few errors. The difference in performance is not as amazing
as the java-rest client but it is still substantial:
```
Asciidoctor   Asciidoc
real  1m01.913s     3m09.738s
user  0m55.742s     3m02.545s
sys   0m02.910s     0m04.420s
```
So about 1/3 the time. For reference, this is the java rest client:
```
Asciidoctor   Asciidoc
real  0m10.341s     1m05.432s
user  0m09.497s     0m55.270s
sys   0m00.616s     0m07.758s
```
Which, I suppose, is still just 1/6. It …
> Asciidoctor: Fix crash on broken definition lists

- shared/versions66.asciidoc
This PR changes the release-state information that is used by the Stack Overview, Kibana Reference, etc.
> [DOCS] Update 6.6.0 release-state

- conf.yaml
Reverts elastic/docs#549 because of delayed release date for 6.6.0.
> Revert "Updating current to 6.6"

- shared/versions66.asciidoc
Reverts elastic/docs#550 because of delayed release date for 6.6.0
> Revert "[DOCS] Update 6.6.0 release-state"

- conf.yaml
With the introduction of x-pack modules we started to add doc files in this directory.
> Add x-pack/metricbeat/module to build path

- conf.yaml
In preparation for ECE 2.1.0, adding the 2.1.0 docs to our doc builds.
**Do not merge this PR before January 25th.**
> [DOCS] Add ECE 2.1 doc builds

- conf.yaml
- shared/versions66.asciidoc
Related to https://github.com/elastic/docs/pull/550 and https://github.com/elastic/docs/pull/549
This PR re-implements the reverted changes.
> [DOCS] Updates current and release-state for 6.6

- conf.yaml
Adds the ESS milestone 17 release (which combines MS16 and MS17) to the doc builds but does not set MS17 to current.
> Add MS17 to Cloud ESS builds

- appspec.yml
- docs-push.sh
Drops two files that were used to deploy this repo to the web servers.
They have been moved to the `built-docs` repo.
> Drop files used to deploy this repo

- conf.yaml
- shared/versions67.asciidoc
We're removing the 6.x branch from all of the stack repos in favor of the
6.7 branch. I'm not sure what else needs to be updated here.
> Branch 6.x to 6.7

- conf.yaml
The .NET API doesn't branch the same way as the stack. It looks like
most of the clients don't actually. We bumped its branch to 6.7 as part
of bumping the stack. This was incorrect because they have no plans to
create a 6.7 branch.
> Revert .NET API's branch to 6.x

- shared/versions.asciidoc
- shared/versions70.asciidoc
- shared/versions71.asciidoc
This PR adds the versions70.asciidoc for use by 7.0 branches and the versions71.asciidoc file for use by 7.x branches. It also updates the details in the versions.asciidoc file, which is used by master branches.
> Add version attributes for 7.0 and 7.x

- build_docs
- build_docs.pl
When I first allowed running the docs build in docker I made the
incorrect assumption that any time the build is running in docker it is
running in the docker container that we manage. Lots of folks were using
docker to manage the pl dependencies of the build. This drops that
assumption and adds an explicit parameter to engage `build_docs.pl`'s
customizations that work for our docker image. The folks who were building
the docs in their own docker image have their own customizations and
won't need ours.
> Remove docker detection

- resources/asciidoctor/lib/copy_images/extension.rb
- resources/asciidoctor/spec/copy_images_spec.rb
Prevents the copy images asciidoctor extension from dying if the
`resources` attribute is an empty string and improves the error message
if it is invalid CSV.
> Asciidoctor: Better handling for resources attribute

- build_docs.pl
Require `--target_repo` when running with `--all`, effectively forcing
folks to build the docs into a separate repo, just like jenkins.
> Force --target_repo with --all

- shared/attributes.asciidoc
This PR updates the "ref-70" attribute and adds the "ref-80" attribute, since the former is no longer associated with the master branch.
> Updates URL for ref-70 adds ref-80

- build_docs.pl
- lib/ES/Repo.pm
If you run `build_docs.pl --all --reference ....` then the cloned repos
retain a reference to the path on your filesystem. If you run
`build_docs --all --reference ....` then the cloned repos retain a
reference to the path that docker mounts the reference directory which
isn't the same as your filesystem. If you switch back and forth between
`build_docs` and `build_docs.pl` then the git operations will fail
because those paths don't exist. This change fixes that problem by
blowing away the clone if the reference repository doesn't exist.
We don't just mount the reference repository into the docker container
in the same spot as it is on your filesystem because it could be
*anywhere* on your filesystem. If it happened to be some place *weird*
then if likely wouldn't mount into the docker …
> Docker: Handle switching reference repo

- build_docs
Fix the paths that docs repos are mounted into the container when
`--doc` and `--resource` are used to allow building more books. These
books expect the all repositories to be cloned into the same root
directory which is "normal" but isn't exactly how docker did it. It *is*
how `--all` does it. But users don't always do it that way....
This fixes the mounted paths so they are always mounted into
`/doc/{reponame}` in docker. Which *should* make the paths even more
consistent then when they are built locally. This should make it
possible to build the stack reference with docker.
Relates to #591
> Docker: Fix docs path mounting

- build_docs
- build_docs.pl
Drops support for single dashed long-opts from the docker build. Drops
support for "abbreviated" options, drops support for starting options
with a `+`, and drops support for specifying options in any case from the
perl build. I haven't see folks use any of the last three options and
they are incompatible with the docker build and would be very difficult
to *make* compatible with the docker build. I *have* seen folks use
single dashed long options. This will fail those single dashed arguments
on the docker build *only* and tell the user to use the double dashed
option.
I believe this might break some folks that are relying on undocumented
options, mostly the "automatic abbreviations" that the script supported.
For command line users I don't foresee an issue though - they'll get the
usage …
> Clean up argument handling

- build_docs
The docker based docs build assume that you are running it as a normal
user and will likely fail if you are running it as root. Specifically
running `--open` will fail because `nginx` will fail to switch to the
"nobody" user.
> Docker: Fail gracefully if run as root

- .ci/packer_cache.sh
- build_docs
1. Add a packger-cache.sh script to build the docker image as part of
building the packer image.
2. Switch the mechanism we use to share the committer information to one
that is a little more precise and more friendly to CI.
3. Make sure to pipe return code from running docker into exit code.
> Docker infrastructure changes for jenkins

- build_docs.pl
This doesn't seem to be needed anymore, especially once we switch CI to
building with docker.
> Drop printing the path on startup

- build_docs
When I first made `build_docs` I picked the wrong default output
directory when you specify `--doc`. It should be `./html_docs`. I made
it `../html_docs`. See the subtle difference? I didn't notice for a
while at first. Then I was really confused. Then I tracked down the
extra `dirname`. Then I fixed it. This is the fix.
> Docker: Fix default destionation directory

- resources/asciidoctor/lib/copy_images/extension.rb
- resources/asciidoctor/spec/copy_images_spec.rb
When our copy images extension can't find an image it outputs *all* of
the paths that it searched so you can be super sure it searched all the
places that you wanted it to search. This sorts the output so that the
error message is consistent. Which is mostly nice for tests. I mean, it
is nice for stuff like reproducibility of errors locally too, but it is
super nice for tests. And it is my tests that are failing.
> Asciidoctor: Consistent sorting in warning message

- conf.yaml
Changes the ESS current to MS17, removes MS15. To be merged when MS 17 releases.
> Switch MS17 to current

- conf.yaml
This PR bumps azure arm template docs to 6.6, now that 6.6.0 is released to the Marketplace
> Bump Azure ARM template docs to 6.6

- conf.yaml
- doc_build_aliases.sh
Replaces https://github.com/elastic/docs/pull/571
This PR adds the missing --resource parameter to the docbldstk build alias and updates the path information for the Installation and Upgrade Guide.
> [DOCS] Update location of Installation and Upgrade guide

- shared/versions56.asciidoc
> Bump stack version to 5.6.15

- Makefile
- README.asciidoc
- lib/ES/Util.pm
Adds rendering the `README.asciidoc` with Asciidoctor in `--self-test`
as a test of Asciidoctor. These two renders can act as a basic
integration test of the docs build. Right now they just validate that
neither AsiiDoc nor Asciidoctor crash when rendering the
`README.asciidoc` file, but I expect to be able to flesh out the tests
in follow up changes.
> Add asciidoctor to --self-test

- resources/asciidoctor/lib/change_admonition/extension.rb
- resources/asciidoctor/lib/extensions.rb
- resources/asciidoctor/spec/change_admonishment_spec.rb
- resources/asciidoctor/spec/copy_images_spec.rb
- resources/asciidoctor/spec/elastic_compat_preprocessor_spec.rb
The "change admonitions" are "admonitions" not "admonishments". They are
"authoritative council" not "firm warnings". Words are hard. For what it
is worth, the AsciiDoc source also has this error in some places.
Asciidoctor gets right every time.
> Asciidoctor: Rename change admonition

- Makefile
Adds a test that asserts that building with `Asciidoctor` produces the
same files as building with `AsciiDoc`. It doesn't actually pass right
now which is wonderful! Tests that find problems are great. We add a
`grep -v` line to the test to ignore the parts that don't pass for now
and we'll fix the failing part in a follow up.
> self-test: File list matches

- build_docs
- build_docs.pl
The root problem is that the docker-based build is busted with `--all`
on macOS because we use a `cached` mounted directory as scratch space.
Building individual books works fine. `--all` works fine on Linux because
bind mounts are fast. But it is slow on macOS because `cached` forces
those writes to be consistent to the macOS filesystem and it causes
crashes because `git checkout` complains that  there are "too many open
files". The latter seems to happen outside of the docker based build,
but I'm not sure when it started or, really, why. I don't really care
why, though, because this change fixes it.
I considered allowing you to specify the temp directory and making sure
it is mounted with the `delegated` flag which should improve performance
but this doesn't really fix the problem of …
> Docker: Fix --all on macOS

- build_docs
- build_docs.pl
Always function as though `--rely_on_ssh_auth` is provided when `--all`
is provided. The http-based auth isn't simple to make compatible with
the docker build and ssh-agent based auth is what we do in CI anyway.
This leaves the `--rely_on_ssh_auth` argument but as a noop so that CI
doesn't break. The argument is new enough that I don't expect anyone
other than CI to be relying on it so once I remove it from CI then I
can remove it from the script.
> Force --rely_on_ssh_auth

- resources/asciidoctor/.rubocop.yml
- resources/asciidoctor/lib/change_admonishment/extension.rb
- resources/asciidoctor/lib/copy_images/copier.rb
- resources/asciidoctor/lib/copy_images/extension.rb
- resources/asciidoctor/lib/cramped_include/extension.rb
- resources/asciidoctor/lib/edit_me/extension.rb
- resources/asciidoctor/lib/elastic_compat_preprocessor/extension.rb
- resources/asciidoctor/lib/elastic_compat_tree_processor/extension.rb
- resources/asciidoctor/lib/elastic_include_tagged/extension.rb
- resources/asciidoctor/lib/extensions.rb
- resources/asciidoctor/lib/scaffold.rb
- resources/asciidoctor/spec/change_admonishment_spec.rb
- resources/asciidoctor/spec/copy_images_spec.rb
- resources/asciidoctor/spec/cramped_include_spec.rb
- resources/asciidoctor/spec/edit_me_spec.rb
- resources/asciidoctor/spec/elastic_compat_preprocessor_spec.rb
- resources/asciidoctor/spec/elastic_compat_tree_processor_spec.rb
- resources/asciidoctor/spec/elastic_include_tagged_spec.rb
- resources/asciidoctor/spec/shared_examples/does_not_break_line_numbers.rb
- resources/asciidoctor/spec/spec_helper.rb
Enables many of the currently disabled rubocop checks and fixes them. The
biggest change is in the `copy_images` extension which is now split into
two classes, on that processes blocks looking for candidates to copy and
one that does the actual copying. Beyond that I've converted many tests
from blocks into guards. Rubocop seems to really like guards and I find
them pretty readble, partially because they force you to create a new
method in some cases and those methods can have nice names.
> Asciidoctor: Ruby style

- Makefile
- integtest/Makefile
- integtest/included.asciidoc
- integtest/includes.asciidoc
- resources/asciidoctor/lib/cramped_include/extension.rb
- resources/asciidoctor/spec/cramped_include_spec.rb
Fixes the cramped include preprocessor to be compatible with the elastic
compat preprocessor. The trouble here is that the cramped include
preprocessor adds a frozen `''` to the stream of lines and the elastic
compat processor attempts to modify it. It is tempting to remove all of
the string mutation from the elastic compat preprocessor but that isn't
compatible with how preprocessors have to hook in to asciidoctor.
Asciidoctor expects them to mutate the strings they are given. Or, to be
more precise, it expects that it only needs to call `process` on each
line once, and that calling it will mutate the line in place. Which
isn't possible for the frozen empty line that the cramped include
preprocessor adds.
We instead fix the problem by adding a mutable empty line to the stream.
Making …
> Asciidoctor: Fix cramped include

- resources/asciidoctor/lib/cramped_include/extension.rb
Adds a comment explaining a the fairly string looking `+''` construct
in the cramped include extension.
> Asciidoctor: Explain unary plus on string

- resources/asciidoctor/.rubocop.yml
- resources/asciidoctor/lib/copy_images/extension.rb
- resources/asciidoctor/lib/elastic_compat_preprocessor/extension.rb
Freezes all of the variables that have CONSTANT_CASE so we don't
accidentally mutate them and enables rubocop enforcement for this.
> Asciidoctor: Freeze constants

- Dockerfile
- Makefile
- integtest/Makefile
- integtest/html_diff
Compare the html built by AsciiDoc and Asciidoctor as part of the
self-test. Like all good tests, it doesn't pass at first. I've
temporarilly ignored all of the failures and have added them to the
main asciidoctor issue or filed them as their own issue.
> Self-Test: Add html diffing

- conf.yaml
- doc_build_aliases.sh
This PR updates the Installation and Upgrade Guide (https://www.elastic.co/guide/en/elastic-stack/master/index.html) such that it's built via Asciidoctor.
Related to https://github.com/elastic/docs/pull/606
> Switches Install Upgrade Guide to asciidoctor builds

- build_docs
Supporting `--all` on mac is "fun" because we rely on ssh auth and, unlike
Linux's lovely bind mounts, macOS can't share the ssh authorization
directly. Instead we have to carefully bounce the ssh authorization into
the container by `ssh`ing into it. One of the steps in this process
requires that the user has an ssh identity configured with their agent.
This is fairly easy to do, but if you haven't done it the error message
was garbage. This catches the original message from `ssh-add` and sends
the user a nicer one that includes a link to instructions.
> Mac: Nice warning if you don't have an identity

- resources/asciidoctor/lib/change_admonition/extension.rb
- resources/asciidoctor/spec/change_admonishment_spec.rb
- resources/asciidoctor/spec/elastic_compat_preprocessor_spec.rb
When I added deprecations I created a `note` element but it should have
been a `warning` element. This is one of the things that the new
`html_diff`-based integration tests caught!
> Asciidoctor: Fix deprecation

- README.asciidoc
- integtest/Makefile
Our README.asciidoc file has source listing containing asciidoc code
which is rare for our books. Asciidoctor was rendering it incorrectly
because of its "automatic comment detection" that it uses with callouts.
It saw
```
-- <1>
```
And through "that is a SQL comment preceeding a callout so I will eat
the `--`". While *normally* helpful, this is wrong when commenting on
asciidoc source. I work around this by writing
```
pass:[--] <1>
```
Which spits out the desired `--` followed by a callout. To get that
working I had to poke the language declaration line some, especially
because AsciiDoc doesn't support the simpler Asciidoctor syntax for
enabling macros inside of listings.
This another thing that our `html_diff` based integration tests caught.
> Asciidoctor compatibility for part of readme

- build_docs.pl
`--skiplinkcheck` and `--linkcheckonly` were documented as only working
with `--doc` but they are actually only used with `--all`. This fixes
the documentation and the preflight checks to reflect that reality.
> Fix skiplinkcheck

- resources/asciidoctor/lib/elastic_compat_preprocessor/extension.rb
- resources/asciidoctor/spec/elastic_compat_preprocessor_spec.rb
Our compat-preprocessor wasn't properly handling "skipped" lines
sometimes, mostly because we didn't have any tests for them. This fixes
both problems. It is a prerequisite to switching the "Getting Started"
book to asciidoctor.
> Asciidoctor: Handle skipped lines

- conf.yaml
- doc_build_aliases.sh
This PR updates the Getting Started Guide (https://www.elastic.co/guide/en/elastic-stack-get-started/master/index.html) such that it's built via Asciidoctor.
Related to #606
This PR must not be merged until https://github.com/elastic/docs/pull/643 is complete.
> Switches Getting Started Guide to asciidoctor builds

- build_docs
- build_docs.pl
- resources/asciidoctor/Makefile
Allows you to send arbitrary arguments to make. This makes it possible to
do things like "only run rubocop" with:
```
./build_docs --self-test -C resources/asciidoctor rubocop
```
While it doesn't take *that* long to run the entire `--self-test`
sequence, it is wonderful to be able to selectively run tests.
> Self-Test: Generalize wrapping and document

- build_docs.pl
It has been a noop for a week or two. We don't use it in CI any more.
> Drop --rely_on_ssh_auth

- build_docs
- build_docs.pl
- integtest/Makefile
- integtest/minimal.asciidoc
- integtest/small_conf.yaml
Adds support for `--conf` to specify the config file used by the docs
build and uses that to add a test for `--all`. This will allow us to add
more features with more confidence that we're not breaking `--all`. It
makes my life less terrifying.
> Add --conf option and test for --all

- shared/attributes.asciidoc
This PR removes the hyphen from the attribute for the "cross-cluster replication" feature. 
It also adds an attribute for cross cluster search.
> Updates hyphenation of CCR and CCS

- build_docs.pl
- integtest/html_diff
- resources/asciidoctor/lib/edit_me/extension.rb
- resources/asciidoctor/spec/edit_me_spec.rb
A minor fix and minor clean up for the "Edit Me" links that allow us to
remove the "temporary workaround" in our `html_diff`ing integration tests:
1. Switch detection of the root of the repository from a loop to a call
out to `git rev-parse --show-toplevel`, a trick Jarpy tought me when he
saw my loop in the docker code.
2. Do not add `./` to the url if the `base_dir` of the document is also
the root of the repository. This is *probably* only true of
`README.asciidoc` in the docs repo, but we test with that file so we
should get it right.
Closes #634
> Clean up Edit Me links

- build_docs.pl
This allows you to `--open` the docs built with `--all`. This should be
useful when testing changes that effect all docs, like the redirect work
that I plan on doing soon.
There is a wrinkle though: to make serving the docs locally work we
actually built *different* docs. We'd switch from finding jQuery at
`/static/js/jquery.min.js` to getting it from
`https://www.elastic.co/static/js/jquery.min.js`. This worked, and it
was simple enough to do for the built in python web server that we use
when you run `--open` outside of docker, but we don't want to do that
when we serve all of the docs because most of the docs will have been
built with the standard template.
But now that we have docker we don't have to! In docker we're using
nginx to serve the docs and we can write a few rewrite rules …
> Allow running --open with --all

- build_docs.pl
- lib/ES/Book.pm
- lib/ES/Source.pm
- lib/ES/Toc.pm
- lib/ES/Util.pm
- resources/asciidoctor/lib/edit_me/extension.rb
- resources/asciidoctor/spec/edit_me_spec.rb
The "Edit Me" link generation in Asciidoctor was basically a copy of the
asciidoc implementation which was simple because it *had* to be simple.
The asciidoctor implementation had trouble dealing with books built from
multiple repositories because the asciidoc implementation does. The
asciidoc implementation works around it by allowing files to set their
`edit_url` whenever they include a book from a different repo. We had a
bug the asciidoctor implementation that led to cross repo links not
working that was unrelated, but it led me to notice how silly this whole
thing was.
This change replaces way that asciidoctor finds the edit url. We now
pass in an attribute with the root of each repo and the edit me url for
that root. When we want to generate the a link we pick the first repo
that …
> Asciidoctor: Make Edit Me links know about repos

- README.asciidoc
- integtest/Makefile
- integtest/beta.asciidoc
- integtest/experimental.asciidoc
- lib/ES/Template.pm
- resources/asciidoctor/lib/care_admonition/extension.rb
- resources/asciidoctor/lib/elastic_compat_preprocessor/extension.rb
- resources/asciidoctor/lib/extensions.rb
- resources/asciidoctor/spec/care_admonition_spec.rb
- resources/asciidoctor/spec/copy_images_spec.rb
- resources/asciidoctor/spec/elastic_compat_preprocessor_spec.rb
Implements the `beta[]` and `experimental[]` macros for asciidoctor. It
adds integration tests that make sure that we copy the required image
even if that is the only admonition in the book. This is an especially
good idea here because the code that copies the images for the
admonitions is a little sneaky.
> Asciidoctor: Implement beta and experimental

- build_docs
Fixes building the x-pack reference books with `--doc`. They require a
special directory layout that `build_docs.pl` relied on the user to
build manually. `build_docs` builds the docker filesystem agnostic of
the user's filesystem and without this change would stuff all of the
source repos into `/doc` in the docker image.
For example, the `elasticsearch` and `x-pack-elasticsearch` repo expect
to be layed out like this:
```
+ elasticsearch
\ elasticsearch-extra
+ x-pack-elasticsearch
```
but docker was putting them in `/docs/elasticsearch` and
`/docs/x-pack-elasticsearch`.
This changes how they are mounted in the docker image so they'll build.
Now all repos with names like `x-pack-foo` are mounted in `foo-extra`.
This isn't the cleanest thing in the world, but I expect we can revert
it …
> Docker: Fix building x-pack references

- integtest/Makefile
- integtest/missing_include.asciidoc
- lib/ES/Util.pm
We used to fail when building a book resulted in any `WARNING`s or the
process the builds the book exits with a non-0 status. This was fine
when we were only using `AsciiDoc` because `a2x` would always exit with
a non-0 status if it output any `ERROR`s. But Asciidoctor will happily
exit with a 0 status after output errors! If that happens, we should
fail to build the book. This change does exactly that. And it adds an
integration test that attempt to build a file with a missing include.
That tests this change.
> Fail the build if there are any errors 

- conf.yaml
- doc_build_aliases.sh
Switches the Elasticsearch resiliency status page to asciidoctor. It
doesn't look 100% the same but the differences are minor and look ok to
me.
> Switch resiliency status to asciidoctor

- conf.yaml
- doc_build_aliases.sh
Related to https://github.com/elastic/stack-docs/pull/197 and https://github.com/elastic/kibana/pull/30155
This PR adds the kibana repo as a resource for the Installation and Upgrade Guide, so that it can pull notable breaking changes from that repo.
> Add Kibana to Installation and Upgrade dependencies

- build_docs
- build_docs.pl
When you run a build with `--open` we start a web server locally and
open up a browser window for you to look at them. With the docker-based
`build_docs` that server is nginx. nginx is fancy, and one of the things
that we can do pretty easily is lay out the files that we serve so they
look fairly like the public web site. This change does just that and it
should come in handy to test future work we plan to do that generates an
nginx config to deploy to the site serving the docs.
> Change nginx layout of --open

- integtest/Makefile
- integtest/emdash.asciidoc
- integtest/html_diff
AsciiDoctor spits out an em dash when there is an em dash between two
words. This is kind of a pleasant surprise because it makes it clear
that we can break words after the em dash. This change teaches the
`html_diff` utility that we use for finding differences in pages that
this particular zero width space doesn't count as a difference.
> Self-Test: Ignore width space after em dash

- conf.yaml
- doc_build_aliases.sh
Switches the perl client docs to asciidoctor. `html_diff` says
asciidoctor produces exactly the same output modulo new lines.
> Switch the perl client docs to asciidoctor

- conf.yaml
"Cloud Enterprise" is not an accepted name for ECE. I suspect this has always been here, but we've just never noticed it. 😬
> Fix ECE product name

- build_docs.pl
- integtest/Makefile
- integtest/migration_warnings.asciidoc
- lib/ES/Book.pm
- lib/ES/Toc.pm
- lib/ES/Util.pm
- resources/asciidoctor/lib/elastic_compat_preprocessor/extension.rb
- resources/asciidoctor/spec/elastic_compat_preprocessor_spec.rb
This adds the concept of "MIGRATION warnings" that are specifically
around migrating to Asciidoctor. By default these warnings are only
enforced against the "latest" version of each book where "latest" is the
first version listed in the `branches` list. The idea is that we'd like
"modern" versions of the documentation to be fully Asciioctor
compatible but that we won't be able to do that overnight and that we
won't be able to modify very old documentation to be compatible and we
will forever rely on the compatibility layer in branches that are not
actively being developed.
This only adds a single `MIGRATION` warning, emitted when the start of a
code block doesn't match the end of a code block. These are very simple
to fix and we can fix them before migrating the book to Asciidoctor.
In …
> Introduce MIGRATION warnings

- conf.yaml
- doc_build_aliases.sh
Switches the PHP client's doc to being built from Asciidoctor. The
resulting html has quite a few changes spacing changes that aren't
impactful and a couple of small changes that look fine visually. There
are a few changes to auto-generated IDs that we've grown to expect from
asciidoctor. They seem fine to me. Here is the diff:
https://gist.github.com/nik9000/72113b441f682b116b7b41a2b78baed6
> Switch the PHP client to Asciidoctor

- conf.yaml
- doc_build_aliases.sh
This switches building the ruby client docs from AsciiDoc to
Asciidoctor. The html that it produces isn't 100% the same, but most the
differences aren't relevant. Here is a diff of the relevant stuff:
https://gist.github.com/nik9000/92e098ca9d9ce113f5d795ee1b0017ce
That diff seems like a net positive.
> Switch ruby client docs to asciidoctor

- conf.yaml
- doc_build_aliases.sh
Switches the community clients book in the Elasticsearch repo to
Asciidoctor. The generated html has some spacing differences but our
tuned html_diff tool doesn't think that there are any differences that
are impactful.
> Switch the community clients book to Asciidoctor

- conf.yaml
Removes the milestone 18 build and creates an MS 19 build
> Update Cloud MS build

- conf.yaml
This PR moves the Groovy API documentation from the Elasticsearch Clients page to the https://www.elastic.co/guide/en/elasticsearch/client/index.html to the "Legacy Documentation" section.
> Moves Groovy client to legacy documentation

- shared/versions.asciidoc
- shared/versions55.asciidoc
- shared/versions56.asciidoc
- shared/versions60.asciidoc
- shared/versions61.asciidoc
- shared/versions62.asciidoc
- shared/versions63.asciidoc
- shared/versions64.asciidoc
- shared/versions65.asciidoc
- shared/versions66.asciidoc
- shared/versions67.asciidoc
- shared/versions70.asciidoc
- shared/versions71.asciidoc
This PR adds the `prev-major-version` attribute to the shared versions files, so that it can be used in the Installation and Upgrade Guide (and any other books that need it).
> [DOCS] Adds shared prev-major-version attribute

- conf.yaml
- doc_build_aliases.sh
Switches the Infrastructure Monitoring Guide to Asciidoctor. There are a
few spacing changes that are noops in HTML and there are a few changes
that look like this:
```
-            <img alt="monitoring-architecture.png" src="monitoring-architecture.png"/>
+            <img alt="monitoring architecture" src="monitoring-architecture.png"/>
```
They switch the alt tag on an image from the name of the image to a
"more English" version of the name of the image. I'm not sure if this is
really an improvement because the alt tag is still being automatically
generated so it isn't going to be particularly descriptive. But I don't
*think* this is a problem either.
> Switch the Infra Monitoring Guide to asciidoctor

- conf.yaml
- doc_build_aliases.sh
Switches the groovy API for Elasticsearch to Asciidoctor. The html has a
few spacing differences but is otherwise the same.
> Switch the groovy API to Asciidoctor

- conf.yaml
- doc_build_aliases.sh
Switches the APM Agent for .NET's docs from the no-longer-maintained
AsciiDoc project to Asciidoctor. The only difference between the html
output is spacing which the browser ignores.
> Switch the APM Agent for .NET to Asciidoctor

- README.asciidoc
- integtest/html_diff
Remove the last "temporary workaround" in `html_diff` for issues
building the readme. I fix the readme by using `ifdef` to write
different source text for AsciiDoc vs Asciidoctor. This would be a bad
solution if these things were common in normal books, but the constructs
that need this are when you have snippets of asciidoc inside the
asciidoc. This is a thing that will probably only happen in the readme.
> self-test: remove last temporary workaround

- conf.yaml
- doc_build_aliases.sh
Switches the core of the documentation build infrasturcture for the APM
Agent for Java from the no-longer-living AsciiDoc project to the active
Asciidoctor project. The HTML differences are fairly small:
1. Empty table blocks no longer contain an `<p></p>`
2. Headings are now in a `<thead>` tag.
> Switch the APM Agent for Java to Asciidoctor

- conf.yaml
- doc_build_aliases.sh
This switches the Elasticsearch Python Client's stub book to
Asciidoctor. `html_diff` claims that the html is the same modulo
whitespace. This book is small because it points folks at the canonical
docs at `readthedocs.org`.
> Switch the ES Python Client to Asciidoctor

- shared/attributes.asciidoc
This PR updates the ccr, ccr-cap, ccs, and ccs-cap shared attributes so that they hyphenate the terms "cross-cluster search" and "cross-cluster replication".
> Hyphenates CCR and CCS attributes

- conf.yaml
Until https://github.com/elastic/docs/pull/701 gets merged, this is the correct URL to use for build the documentation.
/cc @spalger
> Fixed js repository url

- conf.yaml
Related to https://github.com/elastic/docs/pull/697
This PR updates the conf.yaml so that the Groovy API output is still going to https://github.com/elastic/built-docs/tree/master/html/en/elasticsearch/client/groovy-api
It also adds the "Legacy" tag to this book.
> Fix output path for Groovy API

- conf.yaml
- doc_build_aliases.sh
Switches the core of the process that builds the docs for the APM Agent
for Go from the no-longer-supports AsciiDoc to the supported
Asciidoctor. The html output is slightly different - mostly spacing
which is generally ignored by the browser. It *does* change the spacing
in front of the go source from a leading eight spaces to a leading tab.
These look the same to me in the browser but copy-and-pasting them comes
out slightly differently.
> Switch APM Agent for Go to Asciidoctor

- shared/attributes62.asciidoc
Related to https://github.com/elastic/stack-docs/pull/244
This PR copies the "cloud" attribute from https://github.com/elastic/docs/blob/master/shared/attributes.asciidoc to https://github.com/elastic/docs/blob/master/shared/attributes62.asciidoc so that it can be used in earlier releases too.
> Adds cloud to attributes62.asciidoc

- shared/attributes.asciidoc
Follow up to #688.
Adds `:dataframe-transform:   data frame transform` which is not obvious with the indenting changes
@hendrikmuhs any more we need? A CAPS version?
> Add ML data frame transform short cut

- lib/ES/Toc.pm
We chain the books that make the all of the docs together into a web
site by making tables of content that link the whole thing together.
We make these by building asciidoc files and then building them like
single-page books. This switches from building them with AsciiDoc to
building them with Asciidoctor.
> Build tables of contents with Asciidoctor

- conf.yaml
- doc_build_aliases.sh
Switches the core of the build for the APM Agent for Ruby docs from the
end-of-life AsciiDoc to the actively maintained Asciidoctor. The HTML
differences are mostly whitespace but there are two "real" differences:
1. The edit url for the section at `api.html#api-context` goes to
`index.asciidoc` in AsciiDoc and `api.asciidoc` in AsciiDoctor.
AsciiDoctor seems more right here.
2. Empty table cells do not have an empty paragraph tag in them.
> Switch APM Agent for Ruby to Asciidoctor

- conf.yaml
- doc_build_aliases.sh
Switches the docs build core for the APM Agent for RUM JavaScript from
the no-longer-supported AsciiDoc to the actively maintained Asciidoctor.
The generated HTML is the same modulo whitespace which the browser
ignores.
> Switch APM Agent for RUM JavaScript

- resources/asciidoctor/.rubocop.yml
- resources/asciidoctor/lib/elastic_compat_preprocessor/extension.rb
- resources/asciidoctor/lib/open_in_widget/extension.rb
- resources/asciidoctor/style/pretend_regexp_isnt_mutable.rb
In ruby regular expressions aren't frozen by default *but* they don't have
any methods to mutate them. You *can* still mutate them with standard ruby
monkey patching, but we find it more idiomatic to treat them as immutable
for style purposes.
> Ruby Style: Treat regexps as immutable

- shared/attributes.asciidoc
This PR adds attributes that can be used to link to specific versions of the Installation and Upgrade Guide from the upgrade instructions in the Elasticsearch Reference.
> Adds version-specific URLs for Installation and Upgrade Guide

- build_docs.pl
- integtest/Makefile
Adds a self-test that runs nginx and doesn't basic sanity checks on the
files it serves. This is nice to make sure that `--open` works but
*also* it should serve as another line of defence against making invalid
nginx config files. This is important as those nginx config files will
be used on the web site and we'd really prefer not to bring that down.
To get this to work consistently I have to drop the "don't run twice"
behavior of `build_docs.pl`. That behavior is implemented by checking
for a pidfile on startup. If the file is there it checks if `ps` for
that pid comes back with a process that looks like the running one. When
the perl process terminates naturally it destroys the file. This is
known to cause trouble when a server loses power and can't delete the
file and the process is …
> Self-Test: Run nginx

- integtest/Makefile
- integtest/minimal.adoc
- lib/ES/Util.pm
The `adoc` extension is fairly common instead for asciidoc files. Most
of our files use `asciidoc` but a few of them, notable
elasticsearch-hadoop, uses `adoc`. This fixes support for them and adds
a test for it.
> Asciidoctor: Support adoc files

- shared/attributes62.asciidoc
Related to https://github.com/elastic/docs/pull/657
CCS exists in the Elasticsearch Reference going back to version 5.3, so this PR adds the ccs and ccs-cap attributes to shared/attributes62.asciidoc too.
> Adds CCS attributes to earlier releases

- shared/attributes.asciidoc
APM Server's `7.x` documentation branch is going away. See https://github.com/elastic/apm-server/issues/1993 for more details. This PR allows us to cross doc link to `7.0` documentation from `7.x`.
> Add shared refs for APM Server 7.0

- conf.yaml
This PR removes APM's `7.x` documentation from the build process. See elastic/apm-server#1993 for more information.
> Remove apm 7.x branches

- resources/asciidoctor/lib/copy_images/extension.rb
- resources/asciidoctor/lib/elastic_compat_preprocessor/extension.rb
This makes some headaway into our usage of "magic $ variables" which are
so common in perl but discouraged in ruby. It doesn't remove all of
them, but it removes that ones that are simple to get at and aren't
already being addressed in another ongoing change.
> Asciidoctor: Remove some magic $ variable usage

- conf.yaml
- doc_build_aliases.sh
Switches the core of the docs build process from the
no-longer-maintained AsciiDoc to the actively-maintained Asciidoctor.
The resulting HTML is mostly the same but there are a few differences:
1. Spacing changes that the browser ignores
2. AsciiDoc adds `<p></p>` inside any empty table cell. Asciidoctor does
not.
3. The automatically generated alt text for one of the images is
different in Asciidoctor. I believe the Asciidoctor alt text is
marginally better but I don't think automatically generated alt text is
a good thing in general.
4. There is a particular table cell that seems to be changed like so:
```
-                ^2.0.0 || ^3.1.0
+                \^2.0.0 || ^3.1.0
```
I think we can probably change the table cell in the docs after merging
Asciidoctor.
5. One of the deprecation …
> Switch APM Agent for NodeJS to Asciidoctor

- resources/web/docs.js
curl -X HEAD behaves in an unexpected way; namely, it behaves as a GET request so it sits there waiting for Content-Length bytes to be sent, but since the method was HEAD the server would never send these bytes. This makes curl hang forever. It is unfortunate that common sense has not prevailed so this remains unchanged in curl to this day. Instead, curl has a built-in flag for sending a HEAD request and not expecting Content-Length bytes to sent. This is -I or --head. This commit fixes the copy-as-curl behavior with HEAD requests to use the correct form of sending a HEAD request.
Relates #110
Relates elastic/elasticsearch#40114
> Fix handling of copy-as-curl for HEAD requests

- conf.yaml
- doc_build_aliases.sh
Switches the core of the docs generation pipeline from the
no-longer-maintained AsciiDoc project to the actively-maintained
Asciidoctor project. The HTML that it produces isn't 100% the same but
it looks to only differ in three ways:
1. Spacing that the browser will ignore anyway.
2. AsciiDoc was producing `<p></p>` inside of empty table cells.
Asciidoctor does not.
3. In the 1.x docs there are some attribute references that do not
resolve and they are rendered differently by Asciidoctor. Either way,
they should probably be fixed in the 1.x branch of the docs.
> Switch Python APM Agent docs to Asciidoctor

- shared/settings.asciidoc
- shared/settings65.asciidoc
This PR adds a link to the cross cluster replication settings (https://www.elastic.co/guide/en/elasticsearch/reference/master/ccr-settings.html) in the X-Pack settings table (https://www.elastic.co/guide/en/elasticsearch/reference/master/settings-xpack.html) for 6.7 and later releases.
It also adds mention of the cluster update settings API and fixes some spacing in the table.
> Adds CCR link to shared settings

- conf.yaml
- doc_build_aliases.sh
Related to https://github.com/elastic/elasticsearch/pull/39379, which must be merged first.
This PR adds documentation for the Go client in https://www.elastic.co/guide/en/elasticsearch/client/index.html
This new client documentation is generated via the Asciidoctor build options.
> [DOCS] Adds Go client documentation

- shared/attributes.asciidoc
Related to https://github.com/elastic/docs/pull/688 and https://github.com/elastic/elasticsearch/pull/40232
This PR adds the term "data frame" to the list of shared attributes.
> Adds data frame attributes

- integtest/Makefile
- integtest/empty_table_cell.asciidoc
- integtest/html_diff
AsciiDoc spits out `<td><p></p></td>` for an empty table cell. Asciidoctor
spits out `<td></td>` which is just fine. This ignores the empty `<p>`
tags that are children of `<td>`.
> self-test: Ignore empty paragraphs inside of td

- conf.yaml
Changing the `current` branch from `release-ms-17` to `release-ms-19`.
> [DOCS] Switching ESS MS19 to current

- conf.yaml
- doc_build_aliases.sh
Switches the core of the docs build for the APM overview from the
unmaintained AsciiDoc to the actively maintained AsciiDoctor project. It
is marginally faster to build as well. The HTML output is the same
modulo some spacing differences and one real change to the tables on the
`install-and-run` page. The first element on the table gets the
"heading" formatting. Like this:
```
-                <a class="ulink" href="https://www.elastic.co/guide/en/apm/agent/js-base/current/intro.html" target="_top">
-                 Introduction
-                </a>
+                <span class="strong strong">
+                 <strong>
+                  <a class="ulink" href="https://www.elastic.co/guide/en/apm/agent/js-base/current/intro.html" target="_top">
+                   Introduction
+ …
```
> Switch APM Overview to Asciidoctor

- build_docs.pl
Sometimes we want to share the docs that we've built with firebase or a
similar too. I broke that a while back when I turns off `abs_url` when
you build with `--doc` inside docker because I *thought* `abs_url` was
only there to support the built in python web server that we use with
`--open` outside of docker. But it also supports sharing docs with
firebase.
Eventually we'd like something more automatic than firebase but firebase
is what we have right now....
> Fix sharing docs built with firebase

- doc_build_aliases.sh
A couple of the newer Beats are missing from the aliases.
> Add missing Beats aliases

- conf.yaml
- doc_build_aliases.sh
This PR adds the Elastic Common Schema (ECS) Reference to the list of docs available from the website
> Add ECS Reference to stack docs

- integtest/Makefile
- lib/ES/Util.pm
Adds an explicit error message if the "index" file is missing because
asciidoctor doesn't output anything in that case. It'll fail, but it
won't tell you *why* it failed.
> Explicit error message if index missing

- conf.yaml
- doc_build_aliases.sh
Related to https://github.com/elastic/beats/pull/11443
This PR enables the Installation and Upgrade Guide to re-use content from the https://github.com/elastic/beats repo.
> Add beats repo as resource for Installation and Upgrade Guide

- conf.yaml
- shared/versions67.asciidoc
**Do not merge until the 6.7 release**
* Updates current to `6.7`.
* Updates release state for `6.7` to `released`.
_Deploying with Azure Marketplace and Resource Manager (ARM) template_ remains at `6.6` as there is no `6.7` branch (confirmed with repo owner)
> Update current to 6.7

- README.asciidoc
- resources/asciidoctor/lib/elastic_compat_preprocessor/extension.rb
- resources/asciidoctor/lib/elastic_compat_tree_processor/extension.rb
- resources/asciidoctor/lib/extensions.rb
- resources/asciidoctor/lib/lang_override/extension.rb
- resources/asciidoctor/spec/elastic_compat_preprocessor_spec.rb
- resources/asciidoctor/spec/elastic_compat_tree_processor_spec.rb
Our backwards compatibility support for "OPEN IN CONSOLE"-style links did
not work with snippets followed by a callout list. That looks like this:
```
[source,js]
----
GET / <1>
----
// CONSOLE
<1> words go here
```
These is actually *super* common and I'm surprised I didn't catch it
before! This adds tests for it so it won't sneak through again.
The reason this didn't work is that our backwards compatibility worked by
transforming the `// CONSOLE` comment in `pass:[// CONSOLE]` and then
catching that when walking the tree. We do this in two passes because our
preprocessor works line by line and reading ahead can cause issues. So we
do the "action at a distance" in a tree processor where it is quite
simple.
The trouble is that the `pass:[// CONSOLE]` construct is *inline* so when
it is …
> Asciidoctor: BWC for // CONSOLE then callouts

- build_docs.pl
- integtest/Makefile
- lib/ES/Book.pm
- lib/ES/BranchTracker.pm
- lib/ES/Repo.pm
Now that we're using a combination of `--keep_hash --sub_dir` as pull
request tests we've hit some snags, namely that when we add new books or
new repos to existing books `--keep_hash` complained about those books.
This makes it so that new repos and new books are skipped if you use
`--keep_hash`. It also adds test cases for adding new repos to existing
books and adding new books *without* `--keep_hash`.
Note that this work spawned a fierce desire to replace `make` with `rspec`
that I'm tracking in #757. I think I'd like to add these tests and then have
a look at switching from `make` to `rspec`.
Closes #749
> Refine --keep_hash behavior for new things

- conf.yaml
This patch removes the capitalized version of the Go language — `GO` — and changes it to `Go`.
> Fix name of the Go client on index page

- conf.yaml
Needed to test our 2.2 docs this week before the release.
> Add 2.2 doc builds for ECE

- resources/asciidoctor/lib/copy_images/extension.rb
- resources/asciidoctor/spec/copy_images_spec.rb
- resources/asciidoctor/spec/spec_helper.rb
This copies images declared "inline". Asciidoctor doesn't give a good
way of hooking into these images so we have to scan for them when we
walk the tree. It isn't the best solution, but at least we don't have to
scan for them after the document is rendered! If we did that we wouldn't
get line number information when we can't find images....
Closes #730
> Asciidoctor: Copy images for inline image macro

- conf.yaml
- doc_build_aliases.sh
Per https://github.com/elastic/docs#chunking-in-the-right-place:
> By default, each part (= Part Title) and chapter (== Chapter Title) is "chunked" into a separate HTML file. However, for bigger books, such as the Elasticsearch reference docs, this results in enormous pages. These bigger books are also chunked at the first section level (=== Section One Title). 
The "Breaking changes" page in the Installation and Upgrade Guide is getting quite large as we add more products' information.
This PR proposes to add --chunk 1 to the Installation and Upgrade Guide, which will result in the following layout:
> Adds chunk level for Installation and upgrade guide

- conf.yaml
- doc_build_aliases.sh
This PR updates the conf.yaml to exclude the kibana and beats repos from the Installation and Upgrade Guide builds in 6.7 and earlier releases.  Those repos are only required when we added shared highlights and breaking changes in 7.0 and later releases.
It also adds a "docbldstkold" alias which omits the unnecessary --resource parameters.
Finally, it adds some comments in the aliases file, since we were missing descriptions of some of the aliases.
> Omits beats and kibana repos from old Installation and Upgrade Guides

- conf.yaml
This commit adds 6.7 Azure ARM template docs to the site documentation and makes it the current documentation.
> Add 6.7 Azure ARM template docs

- resources/asciidoctor/lib/care_admonition/extension.rb
- resources/asciidoctor/lib/change_admonition/extension.rb
- resources/asciidoctor/lib/edit_me/extension.rb
- resources/asciidoctor/lib/lang_override/extension.rb
- resources/asciidoctor/spec/spec_helper.rb
It looks like it is more idiomatic in ruby to avoid hash rockets where
possible. This drops *some* of them.
> Asciidoctor: Drop a few hash rockets

- resources/asciidoctor/lib/copy_images/copier.rb
Breaks up the method that we use for locating images to copy so it is
more readable. Hopefully. Rubocop identifies this method as being too
complex and long, so hopefully breaking it down into named, digestable
chunks helps.
> Asciidoctor: Break up method for readability

- resources/asciidoctor/spec/shared_examples/does_not_break_line_numbers.rb
This switches our single shared example to use more standard rspec,
adding contexts to make it clear what is being tested and switching from
the `convert` method to the `convert` context.
> Use more standard rspec for shared example

- conf.yaml
- doc_build_aliases.sh
This PR updates the conf.yaml and the build aliases such that the apm-server repo is a resource for the Installation and Upgrade Guide.  This enables us to use tagged regions to re-use content from the apm-server repo, such as the breaking changes and highlights.
> Adds apm-server repo as resource for Install Upgrade Guide

- conf.yaml
- doc_build_aliases.sh
This PR updates the conf.yaml and the build aliases such that the logstash repo is a resource for the Installation and Upgrade Guide. This enables us to use tagged regions to re-use content from the logstash repo, such as the breaking changes and highlights.
> Adds logstash repo as resource for Install Upgrade Guide

- conf.yaml
- doc_build_aliases.sh
This PR updates the conf.yaml and the build aliases such that the elasticsearch-hadoop repo is a resource for the Installation and Upgrade Guide. This enables us to use tagged regions to re-use content from the elasticsearch-hadoop repo, such as the breaking changes and highlights.
> Adds elasticsearch-hadoop repo as resource for Install Upgrade Guide

- shared/attributes.asciidoc
This PR adds the "esh" attribute to the list of shared attributes.
It is used in the breaking changes in https://www.elastic.co/guide/en/elasticsearch/hadoop/7.0/breaking-changes.html#breaking-changes-7.0 , which are in turn used in the Installation and Upgrade Guide (https://www.elastic.co/guide/en/elastic-stack/7.0/elastic-stack-breaking-changes.html)
> Adds shared attribute for Elasticsearch Hadoop

- conf.yaml
- doc_build_aliases.sh
Switches the Transport Client's docs from the no-longer-maintained
AsciiDoc project to the actively maintained Asciidoctor project. In the
process it speeds up building them by a factor of three.
> Switch the Transport Client docs to Asciidoctor

- conf.yaml
- doc_build_aliases.sh
Switches the ES-hadoop based docs from the unmaintained AsciiDoc backend
to the actively maintained Asciidoctor backend. This makes them 3x
faster to build.
> Switch es-hadoop docs to asciidoctor

- conf.yaml
- doc_build_aliases.sh
Switches the painless reference book from the no-longer-maintained
AsciiDoc backend to the actively-maintained Asciidoctor backend. In the
process this speeds up the build by a factor of three.
> Switch Painless reference to Asciidoctor

- conf.yaml
In preparation for the ECE 2.2.0 release, changed `current` to `2.2`.
> Switched ECE `current` to `2.2`

- conf.yaml
- doc_build_aliases.sh
Switches the Elasticsearch Java REST client's docs from being generated
by the no-longer-maintained AsciiDoc project to the maintained
Asciidoctor project. It is *much* faster:
```
AsciiDoc   : 0m48.358s
Asciidoctor: 0m10.436s
```
> Switch Java REST client to Asciidoctor

- resources/legacy_redirects.conf
Add redirects for renaming of Filebeat apache2 module to apache in 7.0.
> Add redirects for apache2 renaming in 7.0

- conf.yaml
- doc_build_aliases.sh
Related to https://github.com/elastic/stack-docs/pull/284
> Add gke-on-prem docs to conf.yaml and aliases

- conf.yaml
This PR shortens the name of the "Combining logs and metrics from Google Cloud’s Anthos GKE On-Prem with traditional on premises systems in the Elastic Stack" book on the documentation landing page.
> Renames Google Cloud Anthos book

- conf.yaml
Switches the core of the build for the legacy reporting docs from
AsciiDoc to Asciidoctor.
> Switch legacy reporting docs to Asciidoctor

- conf.yaml
Switches the core of the docs build for the legacy sense application's
documentation from the unmaintained AsciiDoc to the actively developed
Asciidoctor. The html produced is different only by spacing.
> Switch legacy sense documentation to Asciidoctor

- resources/asciidoctor/lib/elastic_compat_preprocessor/extension.rb
- resources/asciidoctor/spec/elastic_compat_preprocessor_spec.rb
Changes the invocation rules for legacy style admonition macros to only
invoke the block version if it is alone on a line. This more closely
mirrors the customizations that Elastic did to AsciiDoc.
> Asciidoctor: Change invocation rules for macros

- resources/asciidoctor/spec/edit_me_spec.rb
This replaces the large examples I started using with nested contexts
and smaller examples. It manages to remove most of the copy-and-paste
as well with two shared_examples.
> Use standard rspec for edit_me spec

- conf.yaml
- doc_build_aliases.sh
Switches the core of the docs build for the Elasticsearch client for
.net from the unmaintained AsciiDoc project to the actively maintained
Asciidoctor project.
> Switch .net client to Asciidoctor

- conf.yaml
Switches the core of the docs build for the legacy graph docs from the
unmaintained AsciiDoc project to the actively maintained Asciidoctor
project.
> Switch legacy graph docs to Asciidoctor

- conf.yaml
Switches the core of the documentation build from the unmaintained
AsciiDoc project to the actively developer Asciidoctor project.
> Switch legacy watcher documentation to Asciidoctor

- conf.yaml
- doc_build_aliases.sh
Switches the ES "Plugins and Integrations" book's documentation build
core from the unmaintained AsciiDoc project to the actively maintained
Asciidoctor project. It also speeds up building it by a factor of about
2.5.
> Switch ES plugins docs to Asciidoctor

- conf.yaml
- doc_build_aliases.sh
This PR updates the Stack Overview (https://www.elastic.co/guide/en/elastic-stack-overview/master/index.html) such that it's built via Asciidoctor.
Related to #606
> Switches Stack Overview to asciidoctor builds

- conf.yaml
The 6.0 branch no longer exists. Changing current to 6.5.x.
> Update current version of elasticsearch-php docs

- conf.yaml
- doc_build_aliases.sh
Switches the "deploying elasticsearch azure" docs from the unmaintained
AsciiDoc project to the actively maintained Asciidoctor project.
> Switch "deploying with ARM" to Asciidoctor

- conf.yaml
Adds the 5.7 branch and updates the current version to resolve a bad link in the 5.x Curator docs.
> Update Curator docs to 5.7

- build_docs.pl
- lib/ES/BaseRepo.pm
- lib/ES/Repo.pm
- lib/ES/TargetRepo.pm
This begins to use sparse checkout to speed up building `--all` docs. It
does so in the simplest way possible at this point: instead of checking
out the entire target repo before checking out other repos we checkout
all of the target repo *except* the built docs before checking out the
other repos. This allows us to read the "tracker" file from the built
docs repo to pick which hashes to use for the other repos. We then
checkout the built docs in parallel with the other repos.
The bulk of changed code is around breaking out handling of the
"target" repo into a new class `TargetRepo` and creating a `BaseRepo`
that is shared between `TargetRepo` and `Repo`.
This doesn't save *that* much time locally but I expect it'll be
somewhat more substantial in CI because CI tends to spend more time …
> Use sparse checkout to speed up building all docs

- conf.yaml
Switches the legacy shield docs from the unmaintained AsciiDoc project
to the actively maintained Asciidoctor project.
> Switch legacy shield docs to asciidoctor

- conf.yaml
Switches the legacy marvel docs from the unmaintained AsciiDoc project
to the actively maintained Asciidoctor project.
> Switch legacy marvel docs to asciidoctor

- resources/asciidoctor/spec/elastic_compat_preprocessor_spec.rb
Rewrites the rspec for the preprocessor's handling of care admonitions
to be more standard. Actually, it merges the testing of care admonitions
and change admonitions into a single `shared_examples`.
> Rewrite preprocessor rspec for care admonitions

- build_docs.pl
- integtest/spec/helper/repo.rb
- integtest/spec/single_book_spec.rb
When you build docs with `--doc` we attempt to figure out the "edit me"
url. If we can't find an "elastic" clone we would log a warning and move
on. The trouble is that this warning upsets the docs build unless you
pass `--lenient`. This change fixes the problem by instead using the
first remote that it finds if it can't find the Elastic remote. And if
it can't find *any* remotes then it uses `unknown` as the remote. This
prevents the warning.
Closes #845
> Allow building docs with an Elastic clone

- doc_build_aliases.sh
There are many of us who use the build aliases script, but many of the aliases still seem to be using the about-to-be-deprecated `build_docs.pl` build script rather than the newfangled and preferred `build_docs`. This PR fixes that. Tested to work with the ESS and ECE docs.
@nik9000 and @lcawl I assume we want this change, unless the build aliases script is also about to be deprecated?
> Switch build aliases script to use build_docs

- .gitignore
- .rubocop.yml
- integtest/Makefile
- resources/asciidoctor/Makefile
Locally this saves a few second on every build and is super simple to
turn on. It does nothing for CI.
> Enable rubocop cache

- resources/asciidoctor/.rubocop.yml
- resources/asciidoctor/spec/copy_images_spec.rb
- resources/asciidoctor/spec/elastic_compat_preprocessor_spec.rb
- resources/asciidoctor/spec/open_in_widget_spec.rb
Enables and fixes the redundant return cop. In one case I was able to
remove the entire method.
> Tests: Drop redundant returns

- build_docs.pl
- fetch_template.sh
- integtest/spec/helper/dsl/convert_single.rb
- lib/ES/Book.pm
- lib/ES/Template.pm
Now that we're not automatically fetching the template there isn't a
nead to store its md5 with every book. Instead we leave a note to users
that they'll have to manually force a rebuild after updating the
template. This saves us a few files which is nice but it allows us to
significantly simplify the code around up-to-date checking.
> Drop template.md5 file

- conf.yaml
- shared/versions71.asciidoc
This PR updates the conf.yaml to reflect the new 7.1 and 6.8 branches in each repo
> Adds 7.1 and 6.8 branches in documentation

- conf.yaml
This commit adds 7.0 to the ARM template docs, and makes them the default.
> Add 7.0 ARM template docs

- resources/asciidoctor/.rubocop.yml
- resources/asciidoctor/lib/copy_images/extension.rb
- resources/asciidoctor/lib/elastic_compat_preprocessor/extension.rb
- resources/asciidoctor/lib/elastic_include_tagged/extension.rb
- resources/asciidoctor/lib/scaffold.rb
- resources/asciidoctor/spec/copy_images_spec.rb
- resources/asciidoctor/spec/edit_me_spec.rb
- resources/asciidoctor/spec/elastic_compat_preprocessor_spec.rb
- resources/asciidoctor/spec/open_in_widget_spec.rb
Enables the line length cop on the asciidoctor customizations. I'd
entended to do this slowly while reworking other things but not having
this enabled has started getting in the way.
> Enable line length cop

- build_docs.pl
- integtest/spec/helper/repo.rb
- integtest/spec/single_book_spec.rb
- lib/ES/Util.pm
When you do `build_docs --doc ../foo/index.asciidoc` and `foo` is a git
worktree then we blew up. This prevents that.
Closes #833
> Fix build when pointed at a worktree

- integtest/spec/helper/book.rb
- integtest/spec/multiple_builds_spec.rb
- lib/ES/Repo.pm
When I added support for asciidoctor I mistakenly caused all books built
by asciidoctor to be considered out of date when there was *any* change
made to any repo that builds them, even if the changes were to unrelated
files.
When I fixed that I mistakenly caused remove asciidoctor-ness from
consideration in the up-to-date check entirely. Programing is like that,
I guess. This fixes that by explicitly checking if asciidoctor-ness
changed.
> Fix up-to-date check when switching asciidoctor-ness

- conf.yaml
This PR adds update the branch of [elastic/elasticsearch-php](https://github.com/elastic/elasticsearch-php) to 6.7.x. I just release v6.7.0 and I finally decided the right policy for branches and releases.
P.S. Sorry again for the previous PR!
> Update elasticsearch-php to branch 6.7.x

- integtest/Makefile
- integtest/spec/all_books_spec.rb
- integtest/spec/helper/dsl/convert_all.rb
- integtest/spec/helper/source.rb
This moves the "relative conf.yaml" test file from our Makefile to
rspec in an attempt to remove everything from the Makefile.
> Integtest: Move the relative conf test to rspec

- resources/asciidoctor/.rubocop.yml
- resources/asciidoctor/lib/edit_me/extension.rb
- resources/asciidoctor/spec/care_admonition_spec.rb
- resources/asciidoctor/spec/copy_images_spec.rb
- resources/asciidoctor/spec/edit_me_spec.rb
- resources/asciidoctor/spec/elastic_compat_preprocessor_spec.rb
- resources/asciidoctor/spec/elastic_compat_tree_processor_spec.rb
- resources/asciidoctor/spec/shared_examples/does_not_break_line_numbers.rb
- resources/asciidoctor/spec/spec_helper.rb
Removes the suppression of the `StringLiterals` cop and switches all
strings to the format the follows the cop: double quotes if using
interpolation or containing a single quote, single quotes otherwise. I
got this by running `bundle exec rubocop -a`.
> Drop StringLiterals cop suppression

- resources/asciidoctor/.rubocop.yml
- resources/asciidoctor/lib/copy_images/extension.rb
Removes the remaining "easy to fix" rubocop suppressions from the
asciidoctor extension code base.
> Remove remaining easy rubocop suppressions

- build_docs.pl
- integtest/spec/all_books_change_detection_spec.rb
- integtest/spec/all_books_spec.rb
- integtest/spec/helper/dest.rb
- integtest/spec/helper/dsl/convert_all.rb
- lib/ES/TargetRepo.pm
Adds support for specifying the branch to which to build docs in the
target repo. This will make release times smoother because we can
continue to build the docs but send them to the `staging` branch. It
*might* allow more fancy pull request testing by allowing us to send
pull requests to their own branch.
If the branch already exists we just check it out and build the docs
onto it and then push it. If it doesn't exist then things are a little
more complicated. First we check if the `master` branch exists. It won't
in an entirely fresh repo which we often use for testing. If it doesn't
exist we create an empty commit in the master branch to "anchor" it.
Once we're sure that the master branch exists we fork the new target
branch from the master branch.
Pushing the built docs gets a bit …
> Support --target_branch

- build_docs.pl
Today, building the docs emits the following warnings:
Scalar value @edit_urls{ $doc_toplevel } better written as $edit_urls{ $doc_toplevel } at /Users/davidturner/src/docs/build_docs.pl line 144.
Scalar value @edit_urls{ $resource_toplevel } better written as $edit_urls{ $resource_toplevel } at /Users/davidturner/src/docs/build_docs.pl line 150.
This commit implements these suggestions to suppress these warnings.
> Fix mysterious Perl warnings

- shared/versions72.asciidoc
This PR updates the `branch` attribute from 7.x to 7.2 in the shared `versions72.asciidoc` file.
> Changes 7.2 branch attribute

- conf.yaml
This will prevent folks from getting directed to the obsolete docs over the current docs. 
This does not set noindex on the Definitive Guide. We'll wait to do that until we've incorporated equivalent content into the ES docs.
@jonasll Need to verify that this will not prevent our site search from indexing these pages. Since we already set noindex on the Logstash Versioned Plugins doc, I think we're ok?
> Set noindex on the legacy docs to block Google from indexing

- build_docs.pl
- integtest/spec/all_books_change_detection_spec.rb
- lib/ES/TargetRepo.pm
Before this commit if you add `--target_branch` and the branch is *new*
then we pushed to it regardless of if there were changes. This felt nice
and consistent but we're going to end up with a lot of branches that
way.
> Only push to new target branches if there changes

- build_docs.pl
- integtest/spec/all_books_broken_link_detection_spec.rb
- integtest/spec/helper/book.rb
- integtest/spec/helper/dest.rb
- integtest/spec/spec_helper.rb
- lib/ES/BaseRepo.pm
- lib/ES/BranchTracker.pm
- lib/ES/Repo.pm
The docs build has three features when building all books:
1. If you specify `--keep_hash` we reuse the hash of the source repos
for every book that we've built before. This is useful for rebuilding
only the books that we converted to asciidoctor. Or in combination with
`--sub_dir`
2. If you specify `--sub_dir` we use a directory instead of a commit
hash from some source repo. This is mostly useful in combination with
`--keep_hash` because when you use those together your can rebuild the
docs as though you committed the directory that you are subsituting. It
makes for perfect pull request tests.
3. We automatically check all of the links, including links from some
typescript files in the kibana repo.
The trouble is that the kibana repo link checking process didn't
understand `--keep_hash` …
> Teach Kibana link checking about PR features

- Dockerfile
- build_docs
On Sles-12 and potentially other distros some extra stuff is
automatically mounted into `/run` making it impossible to remove them
and ultimately causing the build to fail as seen in https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch+pull-request+docbldesx/12978/console
```
/ # mount | grep /run
tmpfs on /run/secrets/credentials.d type tmpfs (ro,relatime)
tmpfs on /run/secrets/SUSEConnect type tmpfs (ro,relatime)
```
However it looks like only `/run/nginx` is actually being used so there
doesn't seen to be a need to mount and wipe the whole of `/run`
> Only mount and clean the /run/nginx directory

- conf.yaml
- doc_build_aliases.sh
This PR switches the [Elasticsearch Reference ](https://www.elastic.co/guide/en/elasticsearch/reference/master/index.html)to use asciidoctor.
It depends on fixes being backported in the Elasticsearch repo first: elastic/elasticsearch#41128
> Switches Elasticsearch Ref doc build to asciidoctor

- conf.yaml
Related to https://github.com/elastic/elasticsearch/pull/42731
This PR removes the master branch of the Groovy API documentation: 
https://www.elastic.co/guide/en/elasticsearch/client/groovy-api/master/index.html
> Remove master groovy client docs

- .dockerignore
- build_docs
- build_docs.pl
- integtest/spec/all_books_spec.rb
- integtest/spec/helper/book.rb
- integtest/spec/helper/dest.rb
- integtest/spec/helper/matcher/doc_body.rb
- integtest/spec/helper/matcher/have_same_keys.rb
- integtest/spec/helper/matcher/serve.rb
- integtest/spec/helper/preview.rb
- integtest/spec/preview_spec.rb
- integtest/spec/spec_helper.rb
- lib/ES/BaseRepo.pm
- lib/ES/TargetRepo.pm
- lib/ES/Util.pm
- preview/Dockerfile
- preview/preview.js
- preview/test.sh
- publish_docker.sh
This modifies build_docs.pl to support `--preview` which serves preview of
any branch of the `--target_repo`. It works by forking nginx to handle
the incoming traffic, pulling the target repo locally, and then forking
a nodejs process that can read directly from the git repo without
checking it out. You can test this locally with `./preview/test.sh`.
It picks the branch to preview by grabbing the first "chunk" of the
requested host. So if you run `./preview/test.sh` you should be able to
go to `master.localhost:8000/guide/index.html` to see the docs from the
master branch. When you first run `./preview/test.sh` it'll 503 but
*eventually* we'll have cloned the branch locally and we'll be able to
serve it.
`./preview/test.sh` works by booting building a docker image for the
preview and …
> Create a docker image for previewing

- build_docs.pl
We no longer use password-based authentication and so we no longer need
to clear the github credentials.
> Drop unused code

- conf.yaml
- doc_build_aliases.sh
Include SIEM Guide in elastic.co docs builds, and add to docs landing page.
> Add SIEM Guide to docs landing page

- conf.yaml
This milestone is going out to production today, so we need to add `release-ms-21` as `current` and pull `release-ms-20` from the builds.
@elastic/cloud-writers - need an approval.
> Update current for ESS to milestone 21

- conf.yaml
To restore the standard index page.
> Added chunk:1 for Elastic Cloud on Kubernetes

- README.asciidoc
The "For a local repo" section has been confusing people on Slack recently. You can't build all of the documentation with just the `--doc` parameter. 
This PR turns `doc_build_aliases.sh` into a link and makes it clear that some documentation books require more complex build commands.
> Update "For a local repo" section

- shared/attributes.asciidoc
This PR adds attributes that can be used to differentiate between the two main types of distributions listed on https://www.elastic.co/downloads/elasticsearch
These terms are sometimes used in the documentation to differentiate between environments where X-Pack is installed or not, so it would be nice to have uniform terminology.
> Adds shared attributes for distribution types

- conf.yaml
This PR adds the 7.x branch to the .NET client branches.
The 7.x .NET client is not quite yet GA, but we have released prereleases, so it'd be good to have supporting docs for these.
> Add 7.x branch to .NET client branches

- conf.yaml
This commit adds Azure Marketplace 7.1 to the docs and also updates the title to make it more succinct
> Add Azure Marketplace 7.1 to docs

- shared/api-ref-ex.asciidoc
Creates a first draft of the API reference template, using the Elasticsearch CCR [Create follower API](https://www.elastic.co/guide/en/elasticsearch/reference/master/ccr-put-follow.html) as an example.
Relates to #937
> [DOCS] Add API reference template example

- shared/api-definitions-ex.asciidoc
This PR creates a template for the pages that contain definitions for API objects. Similar to pages like https://www.elastic.co/guide/en/cloud-enterprise/current/definitions.html#AllocatorBuildInfo and https://www.elastic.co/guide/en/elasticsearch/reference/master/ml-job-resource.html
> Drafts a template for API object definitions

- resources/web/styles.css
* Changes font size of `<code>` text in a `<term>` to 16px. This ensures `<code>` text matches the size of other text in the `<term>`.
* Removes the blue text color from `<term>`s. Users sometimes mistake this formatting as a link. This bolds `<term>`s instead.
I'm not 100% convinced bolding is the best choice here so I'd love to hear feedback.
<details>
<summary>ES Glossary - Before</summary>
</details>
<details>
<summary>Create follower API Parameters - Before</summary>
</details>
<details>
<summary>ES Glossary - After</summary>
</details>
<details>
<summary>Create follower API Parameters - After</summary>
</details>
| OS                         | Chrome                    | Firefox                      |
| ----------------- | ------------------- | --------------------| 
| Mac OS …
> [DOCS] Changes the styles of terms in definition lists

- shared/api-ref-ex.asciidoc
- shared/attributes.asciidoc
This PR updates the API reference example to use attributes in its section headings, since our choices about those names might change and we don't want to have to correct all the pages that use out-dated labels.
> Updates API reference example with attributes

- conf.yaml
Last year, we switched to the `release-ms-nn` doc builds for `current`. At the time, we decided to keep `saas-release` around for a while to prevent breaking bookmarks and links for people; a header encourages people to move to current docs. We've now been operating under the new milestone release builds for some time and I think it's time to remove the old legacy `saas-release` docs after giving folks a heads-up in the next weekly update. 
Just today, I looked at a recent doc issue that referenced some docs from `saas-release`, but at this point they are at least six or seven months out of date. I think it's time to rip off the bandaid.
@elastic/cloud-writers please approve--we'll discuss tomorrow as well.
> Remove legacy saas-release from ESS doc builds

- shared/api-ref-ex.asciidoc
- shared/attributes.asciidoc
Adds an optional response codes section to the API reference template. I needed this section while migrating the index exists API to the template with elastic/elasticsearch#43546.
Also makes a few other changes for consistency:
- Simplifies the comment structure to use multiline comments.
- Adds missing punctuation in several places.
> [DOCS] Adds optional response codes section to API reference template

- conf.yaml
Add 7.2 to the Azure Marketplace documentation and make 7.2 the current version.
This PR should be merged only when Azure Marketplace version 7.2.0 goes live; will update here when that happens.
> Add 7.2 to Azure Marketplace docs

- conf.yaml
This PR updates the docs for elasticsearch-php client to 7.0 branch.
> Added 7.0 branch for elasticsearch-php

- shared/attributes.asciidoc
Adds an attribute for the 6.8 branch of the [Elastic Stack Installation & Upgrade Guide](https://www.elastic.co/guide/en/elastic-stack/6.8/index.html).
This attribute is helpful when instructing users how to upgrade from 6.8 to 7.0.
Relates to elastic/elasticsearch#43685
> Add attribute for 6.8 Elastic Stack Installation & Upgrade Guide

- conf.yaml
There are plans to refresh and redesign the documentation landing page. In the meantime, this PR adds an Observability heading and moves Observability solutions underneath that heading. With our current build script, I've found two different ways to accomplish this. ~I like option two, but I've included screenshots of option one as well.~ After chatting with Gil, option 1 seems like the best path forward.
Closes https://github.com/elastic/observability-dev/issues/70.
1. **Observability heading added to main doc page** https://www.elastic.co/guide/index.html
2. **Selecting APM brings you to a new APM subpage. From this page you can view Overview and Server docs.**
3. **Clicking on APM Agents brings you to the Agents subpage**
* Pro: All URLs remain the same
* Con: 3 clicks to actually view …
> Add observability header to doc landing page

- conf.yaml
This commit updates the .NET client documentation to make 7.x the current version.
> Update .NET client docs current to 7.x

- conf.yaml
Adds the Cloud milestone release 24 to the doc builds. Changing `current` will be done in a separate PR.
> Add Cloud release MS24

- shared/api-definitions-ex.asciidoc
- shared/api-ref-ex.asciidoc
- shared/attributes.asciidoc
This PR updates the API reference template as follows:
* adds an attribute for the "Properties" title
* removes float attributes from the template (so the "On this page" navigation works)
* uncomments the Response body since it's the only optional one we were commenting out that way
* changes the template to use "Examples" instead of "Example" by default
> More edits to the API template

- conf.yaml
This PR updates the conf.yaml file to start building the 7.3 branches of the documentation.
> Adds 7.3 branches to conf.yaml

- shared/attributes.asciidoc
This PR adds some shared attributes for data frame analytics.
Related to https://github.com/elastic/elasticsearch/pull/43875/files
NOTE: The dataframe-job attributes are commented out in this PR but if they're not used, they should be removed to avoid confusion.
> Updates data frame attributes

- resources/legacy_redirects.conf
The following page ceases to exist after 6.2:
https://www.elastic.co/guide/en/kibana/6.2/xpack-upgrade-assistant.html
Instead, the new URL is:
https://www.elastic.co/guide/en/kibana/6.6/upgrade-assistant.html
https://github.com/elastic/kibana/pull/40432 adds deleted pages up to 6.8. This PR creates the redirects thereafter.
> Adds redirect for upgrade assistant

- integtest/spec/single_book_spec.rb
- resources/website_common.xsl
We had a bug where links to floating titles (aka bridgeheads) would
include the `edit_me` link in its contents like this:
```
<a class="xref" href="chapter.html#floater" title="Floateredit">
Floater
<a href="https://github.com/elastic/docs/edit/master/index.asciidoc" class="edit_me" title="Edit this page on GitHub" rel="nofollow">
edit
</a>
</a>
```
Because this is invalid html it'd cause the `edit` button to float to
the top of the page, and, confusingly, take you to edit the source of
the *link target* rather than the current page. Madness.
This removes the extra link.
Closes #903
> Remove edit link from links to bridgeheads

- resources/legacy_redirects.conf
Related to https://github.com/elastic/elasticsearch/pull/43996
This PR creates a redirect for the URLs
https://www.elastic.co/guide/en/elasticsearch/reference/7.2/data-frame-transform-pivot.html
https://www.elastic.co/guide/en/elasticsearch/reference/7.3/data-frame-transform-pivot.html
https://www.elastic.co/guide/en/elasticsearch/reference/7.x/data-frame-transform-pivot.html
https://www.elastic.co/guide/en/elasticsearch/reference/master/data-frame-transform-pivot.html
... since they will cease to exist when the aforementioned PR is merged.
> Adds redirects for pivot resource

- shared/attributes.asciidoc
This PR adds shared attribute for `olscores` and `oldetection-cap`.
Related to https://github.com/elastic/elasticsearch/pull/43972
>  [DOCS] Adds outlier scores to the attributes list.

- conf.yaml
The legacy js client has accidentally been removed from the build in #934, this pr fixes that.
Ref: https://github.com/elastic/docs/pull/934/files#diff-4a701a5adb4359c6abf9b8e1cb38819fL354
Fixes: https://github.com/elastic/elasticsearch-js-legacy/issues/3
> Added legacy js client to the doc build

- shared/api-ref-ex.asciidoc
This PR hopefully addresses some confusion about the difference between the query and path parameter sections in the API reference template.
It's based on the descriptions in https://swagger.io/docs/specification/describing-parameters/
> Clarify query and path parameters in API template

- build_docs.pl
- integtest/spec/preview_spec.rb
- lib/ES/Util.pm
- preview/preview.js
- publish_docker.sh
Switches the PR preview infrastructure from buffering the entire file to
chunked transfer. This allows us to do two things:
1. Shrink the size of the node process significantly.
2. Handle large files.
> Switch preview to chunked transfer

- build_docs.pl
- conf.yaml
- integtest/spec/all_books_change_detection_spec.rb
- integtest/spec/helper/book.rb
- lib/ES/BranchTracker.pm
We keep information about which branches contribute to which books but
before this change we didn't automatically remove the metadata when
a branch is no longer involved in building a book we never cleared that
metadata. For the most part this just left lines in a YAML file that
aren't used except when we remove a branch from a book and then re-add
it. In that case since we only use the branch data to figure out if we
should rebuild a book we *wouldn't* start to build the book when it is
added back unless the branch that it is built from changes. This happened
to us recently so it makes sense to clean up these files automatically
so it never happens again.
Closes #973
> Automatically clean up book metadata

- shared/api-ref-ex.asciidoc
This PR updates the API reference template to change the location of the Required/Optional parameter qualifier (hopefully for the last time!).
I also modified the comment about the definitions list, since I think we should have some leeway for whether we create separate pages for all objects or not.  i.e. For small objects it might annoy users to be sent to a separate page.
> Updates to API template

- integtest/spec/preview_spec.rb
- preview/preview.js
When you request a directory on the public web site we redirect your
request to `{path}/index.html`. The preview *was* just serving that
index file instead. This sounds good but breaks relative links in the
`index.html` file. Sadly, we have some of those. This change teaches the
preview to do the same redirect as the public site.
> Preview: More closely mimick nginx on dir request

- build_docs.pl
- integtest/spec/all_books_spec.rb
- integtest/spec/helper/dest.rb
Adds an option to the build that causes it to comment that a preview of
the docs changes are available after it pushes a change. We'll use this
on the pull request builds to make it obvious where the previews are.
> Add an option to comment about a preview

- integtest/spec/all_books_change_detection_spec.rb
- lib/ES/TargetRepo.pm
Previously when you specified `--target_branch` we'd fork that branch
from master if it didn't exist and otherwise we'd build "on top" of that
branch. This isn't quite right for pull request testing. The trouble is
that you often want to merge master into your pull request branch. Doing
that introduces dependencies on other repos that touch the same books
you do. But if your target branch is old we'll reuse old commits from
that branch which might not have those dependencies. It can make a
somewhat simple PR totally fail to build if it sits for a week or two.
This change makes it so we always fork the `--target_branch` from the
master branch. We fork it from master even if it already exists. This
both fixes the "out of date" issue above and it better simulates when
merging the PR will be …
> Always fork from master when targeting a branch

- conf.yaml
Adds the new 0.9 branch to the docs build.
> Enable ECK doc build for 0.9

- README.asciidoc
- build_docs.pl
- conf.yaml
- doc_build_aliases.sh
- integtest/spec/all_books_spec.rb
- integtest/spec/helper/book.rb
- lib/ES/Book.pm
- lib/ES/Util.pm
- resources/asciidoctor/lib/edit_me/extension.rb
- resources/asciidoctor/spec/edit_me_spec.rb
Makes two changes to the generation of "edit" links for asciidoctor:
1. Prefers the longest matching repository. This helps when repository
is `logtstash` and another is `logstash-docs`.
2. Create a setting to enable overriding `edit_me` links using an
attribute. Historically we've overridden this attribute in cases where
it is no longer needed for Asciidoctor and overriden it *incorrectly*.
But there are some cases where we really do want ot override it.
Specifically for logstash. So this allows us to turn it on when we want
it.
> Edit me link improvements

- integtest/spec/helper/matcher/serve.rb
- integtest/spec/preview_spec.rb
- lib/ES/Util.pm
- package.json
- preview/preview.js
- preview/test.sh
- publish_docker.sh
I've found that it can be kind of annoying trying to find out which
files changed when looking up a docs preview. This adds a page at
`/diff` that contains links to all of the modified pages.
I used chunked transfer and stream parsing the result from git because
that felt like the right thing to do here but it did make the parsing a
bit more complex.
I also chose to use the `-z` flag when calling git because it emits a
format that isn't jumbled when files move. It has many ascii-nul
terminated records which means I couldn't really use any off the shelf
nodejs parsing libraries.
> Preview: Add a diff endpoint

- integtest/spec/preview_spec.rb
- preview/preview.js
Fixes two silly mistakes with the docs preview:
1. Removes a debugging output that I left in the path that handles
renames.
2. Handles empty diffs. Those should be rare, but we should produce
valid html when we have them.
> Docs preview: fix two silly mistakes

- preview/__test__/clean.test.js
- preview/clean.js
Our pattern for pull request branches is a little broad so sometimes
normal looking branches will match it and we'll *think* they are for a
pull request when they really aren't. This change makes it so that when
we can't find the pull request information for a branch we log a warning
and keep it open rather than crash. That seems sensible.
> Docs preview: Skip repos we don't own

- integtest/spec/preview_spec.rb
- lib/ES/Util.pm
The docs-preview service is never going to be the canonical place to
host docs and we're not going to set up canonical tags on it or
anything. This kindly asks search engines not to index it.
> Docs preview: Add a "go away" robots.txt

- conf.yaml
Changed `current` to `0.9` for the upcoming K8s alpha release (July 30).
> k8s - change current to 0.9

- shared/versions68.asciidoc
Increments the shared 6.8 attributes for the 6.8.2 release.
Will merge on release day.
> [DOCS] Bump 6.8 version attributes from 6.8.1 to 6.8.2

- shared/versions72.asciidoc
Increments the shared 7.2 attributes for the 7.2.1 release.
Will merge on release day.
> [DOCS] Bump 7.2 version attributes from 7.2.0 to 7.2.1

- README.asciidoc
- doc_build_aliases.sh
You now need to specify the `--target_repo` when building with the `--all` option and can use the `--sub_dir` option to pick up local changes. (So you can check for broken links *before* you merge!)
> Update build all instructions.

- conf.yaml
The exclude path will need to be updated again when the doc changes that caused the build to break are backported to other branches.
> Add xpack libbeat path

- resources/web/styles.css
Our table of contents and "on this page" section was using
`line-height: 26px` which looked fairly bad if the title broke to the
next line. This switches it to using `line-height: 1em` and uses
margin or padding to maintain the separation between items instead.
Closes #1006
> Style: Fix toc line spacing

- conf.yaml
- doc_build_aliases.sh
Following the pattern of other clients, I've taken the files [here](https://github.com/elastic/elasticsearch/tree/master/docs/ruby) and copied them into the `master` and `7.x` branches of the Ruby client repository.
This pull request add the metadata for building the Ruby client docs to the docs repo.
> Add ruby docs metadata to conf.yml

- conf.yaml
Version 5.0 of the APM Python Agent is now the current version
**Needs to be merged concurrently with https://github.com/elastic/apm-server/pull/2519**
Other related PRs: https://github.com/elastic/apm-server/pull/2520, https://github.com/elastic/apm-server/pull/2521
> Update APM Python Agent versioning

- conf.yaml
Changed to _new_ path for the PHP examples.
> Use updated path to PHP examples

- doc_build_aliases.sh
Corrects a copy/paste error from #1026.
I'd say this is a dependency for elastic/elasticsearch#45227
> Correct doc build alias for es ruby client

- conf.yaml
- doc_build_aliases.sh
Related to https://github.com/elastic/stack-docs/pull/456
This PR adds the beats repo as a dependency for the Stack Overview, so that we can pull content about monitoring Beats.
> Adds beats resource to Stack Overview

- conf.yaml
Reverts elastic/docs#1050 because this is breaking the doc build.
> Revert "Add 5.8 branch to Curator"

- conf.yaml
Adding Curator 5.8 again, as something weird happened with the build. It works for me on the same branch, and the error isn't a cross-doc link issue.
> Add Curator 5.8 again

- build_docs
- integtest/spec/all_books_spec.rb
- integtest/spec/helper/dest.rb
- lib/ES/TargetRepo.pm
This will be useful for tracking down "rogue" builds outside of our
primary build.
> Add the node name to the commit message

- build_docs
Catches the docker error message if port 8000 is already in use and adds
a more user friendly one below it.
Closes #739
> Improve error message if port 8000 taken

- resources/web/template.html
We had animated the scroll when you click on an ID or load a page with
an id to make sure we didn't cover up a "floating" pane at the top of
the page. We don't have such a pane anymore so we can fall back to the
browser's default behavior.
Closes #950
> Drop animated scrolling

- conf.yaml
This PR adds the 7.3 version of Azure Marketplace and ARM template to the docs, and marks as the current version.
It must be committed only after 7.3 is made available on the Azure Marketplace. I'll comment when this is the case.
> Add Azure Marketplace 7.3 to docs

- build_docs
Improves the error message when `git revparse --show-toplevel` doesn't
match the provided path. We might be able to "heal" these bad paths
later on when we have a better sense of how they can come about and
bet
> Improve error message when paths don't line up

- conf.yaml
With the release of `release-ms-25` imminent , we should update our doc builds to 
* change `current` to `release-ms-25 for both ESS and ECH (our newfangled Heroku docs); and
* remove `release-ms-24` from the doc builds
@elastic/cloud-writers I need one of you to review and approve, please.
> Change current to release-ms-25

- build_docs
Switching to two ports for `--open` broke our nice error message when
ports colide. This fixes it.
> Fixup error handling for new port

- resources/web/style/calloutlist.pcss
- resources/web/style/code.pcss
- resources/web/styles.pcss
We're going to be hacking on this code a fair bit in the future. This
*just* moves it and makes very little effort to simplify it.
> Move CSS for code and callouts into its own file

- conf.yaml
Starts pulling C# examples from the elasticsearch-net repo into the
Elasticsearch reference. They aren't visible by default but we'll be
able to switch to them eventually.
> Enable alternative examples from C#

- integtest/spec/helper/console_alternative_examples.rb
- integtest/spec/single_book_spec.rb
- lib/ES/Template.pm
- lib/ES/Util.pm
- resources/web/style/conum.pcss
- resources/web/styles.pcss
- resources/website_common.xsl
This switches the callout numbers from images to css-managed text. It is
still copy-and-paste safe.
> Switch callouts from images to css

- resources/web/style/code.pcss
We need to be pretty specific in order for code blocks to get the right
style because of the global `*` rule.
> Style: Fix up code blocks

- integtest/readme_examples/csharp/8a7e0a79b1743d5fd94d79a7106ee930.adoc
- integtest/readme_examples/js/8a7e0a79b1743d5fd94d79a7106ee930.adoc
- integtest/spec/all_books_spec.rb
- integtest/spec/helper/console_alternative_examples.rb
- integtest/spec/single_book_spec.rb
- resources/asciidoctor/lib/alternative_language_lookup/alternative.rb
- resources/asciidoctor/lib/alternative_language_lookup/listing.rb
- resources/asciidoctor/lib/scaffold.rb
- resources/asciidoctor/spec/alternative_language_lookup_spec.rb
- resources/asciidoctor/spec/resources/alternative_language_lookup/csharp/9e01493a85c06a5100ff712f6b3eead4.adoc
- resources/website_common.xsl
This changes the order of the html generated by alternative examples so
it is simpler to switch to different alternatives. Instead of the html
looking like:
```
default example
console widget
default callout list
alternative 1 example
alternative 1 callout list
alternative 2 example
alternative 2 callout list
```
It now looks like:
```
alternative 1 example
alternative 2 example
default example
console widget
alternative 1 callout list
alternative 2 callout list
default callout list
```
The advantage of this order is that it works with how we want to display
these examples: we always hide all but one of the examples and all but
one of the callout list and we want the order of shown things to always
be:
```
example
console widget
callout list
```
> Fix the ordering of alternative examples

- conf.yaml
Let's start on the translations!
> Switch CN PHP API to asciidoctor

- integtest/spec/helper/dsl/convert_all.rb
- integtest/spec/single_book_spec.rb
- lib/ES/Util.pm
We don't ship the original files so the source map fails to load anyway.
> Drop source maps from production web resources

- conf.yaml
Long time fan, first pull request to docs :-)
I'm in the process of releasing ECS 1.1.0, which has a live `1.1` branch, for docs adjustments.
> ECS 1.1.0 docs for release

- resources/web/docs_js/components/alternative_picker.jsx
We should probably be using the language string but we'll get there
eventually. For now, lets just make Python look a little nicer, shal we?
> Add python's pretty name to alternatives drop down

- resources/web/docs_js/components/alternative_switcher.js
- resources/web/docs_js/components/console_widget.jsx
- resources/web/style/alternative_picker.pcss
- resources/web/styles.pcss
This changes the console widget style so it looks better on mobile. It
1. Shrinks the link text slightly when the width shrinks. This is the
same shrinking that we have for the nav header and footer.
2. When there isn't enough space for the links they now wrap "inside"
themselves.
3. Switch the "bad language" warning from "not displayed" to "not
visible" to it takes up space all the time. This should prevent weird
stuff happening when it needs to be shown on mobile.
> Fix console widget style on mobile

- resources/web/docs_js/index.js
It was starting with Elasticsearch's port.
> Fix Copy as cURL's default port for kibana

- resources/asciidoctor/lib/alternative_language_lookup/listing.rb
Fix a warning emitted when including alternative snippet. It isn't
causing any failure but it is making debugging failures more difficult.
> Fix warning

- shared/api-ref-ex.asciidoc
- Adds a basic example to the intro section
- Adds additional guidelines for the intro and examples sections
We've heard from several folks that it's helpful to include a basic example at the top of API ref pages. This tries to address that feedback without adding new sections or headings.
> Add basic request example to API Reference Template

- resources/web/docs_js/__tests__/components/alternative_picker.test.jsx
- resources/web/docs_js/__tests__/components/alternative_switcher.test.js
- resources/web/docs_js/actions/settings.js
- resources/web/docs_js/components/alternative_picker.jsx
- resources/web/docs_js/components/alternative_switcher.js
When you pick an alternative language the page has to reflow because the
alternatives have different vertical size. This reflow looks like a big
"jump", especially when you pick the language lower down on the page.
This prevents the "jump" by storing the location of the picker before
the reflow, updating the styles to cause the reflow, grabbing the new
location, and then scrolling the window the difference between the new
and old location. This keeps the picker, which is usually right under
your mouse when you change the language, from jumping. This "feels"
smooth!
> Prevent jumping when you pick an alternative lang

- conf.yaml
- shared/versions74.asciidoc
This PR updates the conf.yaml file to start building documentation from the 7.4 branches in each repo.
It also updates the shared "branch" attributes from 7.x to 7.4.
> Adds 7.4 branches to documentation builds

- conf.yaml
- doc_build_aliases.sh
> Switch APM Server to Asciidoctor

- build_docs.pl
- conf.yaml
- integtest/spec/helper/dest.rb
- integtest/spec/helper/source.rb
- lib/ES/BaseRepo.pm
- lib/ES/Util.pm
Removes the `paths.repos` config entry from the conf file because we
rarely want to change it outside of tests. Adds a command line parameter
to change the path (`--reposcache`) and uses it in the tests.
This sort of accidentally fixes a problem where running `--self-test`
will trash the contents of `.repos/target_repo.git`, forcing subsequent
`--all` builds on the same machine to fetch it.
> Move the repos dir config to parameter

- Dockerfile
- build_docs.pl
- integtest/spec/all_books_change_detection_spec.rb
- integtest/spec/all_books_spec.rb
- integtest/spec/helper/dest.rb
- lib/ES/TargetRepo.pm
We generate `sitemap.xml` with an entry for every page in every
"current" book. Before this change we'd set the last modified time to
"now" for every single page, every time we rebuild the books. This
changes it so that we only change the last modified time when we modify
the file which is how you are supposed to use `sitemap.xml` anyway.
Beyond that, it sorts the entries in the sitemap before building it so
it doesn't "jump arround" on every commit.
These two combine to significantly shrink the size of small diffs which
should make working with the docs just a little bit faster.
Closes #684
> Shrink diffs for sitemap.xml

- build_docs.pl
- lib/ES/Util.pm
Before: 5m50.802s
After: 2m46.185s
Works by only building the web resources one time in the docker
container. In normal operation that means it'll build it every time
because we only use the docker container once. But we reuse the same
container over and over again for integration tests so this saves quite
a bit of time there. Parcel *does* have a cache that works well for us,
but it cuts the web resource compile time from 5 seconds to 1.5 seconds
milliseconds. Great, but 1.5 seconds can add up.
This also merges two parcel runs into one and lets parcel parallelize
the builds. This saves a few hundred milliseconds on the compile which
is nice. Less nice now that we only do it once for all the integration
tests, but still nice.
> Vastly speed up integration testing

- integtest/spec/all_books_change_detection_spec.rb
- lib/ES/BranchTracker.pm
We set a flag on the branch tracker whenever there are changes to one of
the branches that we use to build the docs. When we're done building the
docs we commit them if *either* the flag is set or the built resulted in
any changed files. We do this because we want to commit the branch
changes even if there aren't changed files so we know were to start from
on the next build.
This fixes a problem where the tracker would lie about there being
changes when there weren't any. In particular, the kibana link checking
would set the branch even if it hadn't changed and that triggered the
tracker to *think* that it had changes. That caused us to try and
`git commit` when there aren't actually any changes. This fixes that.
Previously this wasn't causing trouble because we would rebuild the
entire …
> Stop the tracker from lying about changes

- conf.yaml
- integtest/spec/helper/source.rb
- resources/web/template.html
Now that the web and docs teams are collaborating more closely we
don't really *need* to patch the template on startup. Instead we can put
all of our patches into the template file directly and everything is
just a little bit clearer.
> Merge template customization into template

- conf.yaml
Moved the docs folder from the elasticsearch repo to the perl client's repo.
Ref: https://github.com/elastic/elasticsearch-perl/pull/173
> Load Perl Client docs from the repo

- resources/web/template.html
This removes the marketo code from the docs template. This form's code will come in with the footer javascript, so we don't need it in the template anymore.
> Remove marketo code from docs template

- resources/web/template.html
This drops main.css from the elastic.co requests. 
Testing to see if this is possible yet.
> Drop main.css from elastic.co in favor of docs css

- integtest/spec/all_books_change_detection_spec.rb
- lib/ES/BranchTracker.pm
- lib/ES/Repo.pm
- lib/ES/Source.pm
When we added a new branch to the list of books last week we broke the
docs PR tests for books that were involved in more than one repo. The
build saw `--sub_dir` for *that* repo and no other history so it tried
to build those multi-source books with just the `--sub_dir`ed repo. This
didn't work because we were missing a ton of files.
This detects when `--sub_dir` is used for a new source and skips
building the book *unless* all of the sources are new *and*
`--sub_dir`ed. This means we'll still build, say, the Elasticsearch
reference on Elasticsearch PRs even if the book is new but we won't
build, say, the stack overview. So we lose test coverage here but in
exchange we don't fail builds.
The more paranoid option would be to "fail closed" and log a more
helpful message but fail the build …
> Skip new --sub_dirs unless all sources are present

- resources/web/style/code.pcss
We were getting a nice code style from main.css. This moves it into the
docs css.
> Restor code style from main.css

- resources/web/template.html
I don't think it has worked for a while and no one is complaining. We
always ended up with `currentlocale` as `undefined` because `/en` was
missing a trailing `/`.
With that picker gone we can also remove `jquery.cookie` because it was
the last thing to use it.
> Remove locale bouncer from template

- integtest/spec/single_book_spec.rb
- lib/ES/Template.pm
- lib/ES/Util.pm
This'd make it simpler for *anything* else to use the raw output by
normalizing docbooks quirks away.
> Slightly clean up raw output

- shared/versions/stack/5.5.asciidoc
- shared/versions/stack/5.6.asciidoc
- shared/versions/stack/6.0.asciidoc
- shared/versions/stack/6.1.asciidoc
- shared/versions/stack/6.2.asciidoc
- shared/versions/stack/6.3.asciidoc
- shared/versions/stack/6.4.asciidoc
- shared/versions/stack/6.5.asciidoc
- shared/versions/stack/6.6.asciidoc
- shared/versions/stack/6.7.asciidoc
- shared/versions/stack/6.8.asciidoc
- shared/versions/stack/7.0.asciidoc
- shared/versions/stack/7.1.asciidoc
- shared/versions/stack/7.2.asciidoc
- shared/versions/stack/7.3.asciidoc
- shared/versions/stack/7.4.asciidoc
- shared/versions/stack/7.x.asciidoc
- shared/versions/stack/master.asciidoc
Relates to https://github.com/elastic/docs/issues/804
This PR copies the version attribute files to a new folder and names them based on branch names. 
This will potentially enable us to pull the right filename using attributes provided by the build (see https://github.com/elastic/docs/pull/1147).
If we go ahead with the use of these files, the older copies of the version attribute files are redundant and can be removed after all books that use them have been updated to use the new files.
> Copies shared version attributes to new location

- conf.yaml
This PR alters the name of the "Kibana Reference" in the conf.yaml file.
This affects the title that appears in the following locations:
- https://www.elastic.co/guide/index.html
- https://www.elastic.co/guide/en/kibana/current/index.html
For example:
> Change Kibana Reference to Kibana Guide

- conf.yaml
With the change in https://github.com/elastic/elasticsearch-net/pull/4043 to write C# examples directly to asciidoc, rather than use an include:: element, the src/Examples directory in elastic/elasticsearch-net no longer needs to be referenced. This commit removes the reference.
> Remove .NET client src/Examples directory

- integtest/Makefile
- integtest/spec/all_books_spec.rb
- integtest/spec/helper/console_alternative_examples.rb
- integtest/spec/single_book_spec.rb
- lib/ES/Template.pm
- lib/ES/Util.pm
It is an input to the templating process so it should be in the `raw`
directory.
> Move alternatives_summary.json

- build_docs.pl
- integtest/spec/all_books_spec.rb
- integtest/spec/single_book_spec.rb
- lib/ES/Book.pm
- lib/ES/Toc.pm
- lib/ES/Util.pm
The `source_branch` attribute should be useful in resolving inter-book
links. We can get this *perfect* when we're running with `--all` because
every book already *has* a branch attribute. When we build with `--doc`
we have to guess. I've added some heuristics that I feal are likely to
guess right most of the time for most folks. I'm not too worried about
guessing wrong *sometimes* because, for the most part, that'll only
break interbook links and lots of folks don't check those locally
anyway. And because we have the pull request tests which run with
`--all` so they'll serve as an accurate backstop.
Relates to #804
> Add source_branch attribute

- build_docs
Fixes broken Parcel watcher when running it in a mounted volume in a Docker container using Docker for Mac.
See:
- https://github.com/docker/for-mac/issues/2216
- https://github.com/parcel-bundler/parcel/issues/2539#issuecomment-462946468
> Better Parcel watch support in Docker for Mac

- fetch_template.sh
- resources/web/README
We don't fetch the template from anywhere anymore. We maintain it in the
docs repo.
> Drop template fetch script

- resources/web/style/table.pcss
- resources/web/styles.pcss
Moves the styles for tables into their own file so it is a bit easier to
manage. Drops the stype for paragraphs inside tables because it isn't
being used.
> Move table styles into their own file

- shared/versions/stack/7.0.asciidoc
- shared/versions/stack/7.1.asciidoc
- shared/versions/stack/7.2.asciidoc
- shared/versions/stack/7.3.asciidoc
- shared/versions/stack/7.4.asciidoc
- shared/versions/stack/7.x.asciidoc
- shared/versions/stack/master.asciidoc
We need a way to link ECS versions to stack versions.  This PR adds an `ecs-version` attribute to our shared version files. 
Issue:
#804
Related PRs:
#1147 
#1148
> Add attribute for ecs-version to shared version files

- integtest/spec/preview_spec.rb
- preview/preview.js
Empty diffs aren't as common as we'd hoped! This changes the diff page
generation to add a line explaining that the diff is empty if it is
indeed empty. Without this the diff page just looks like a totally blank
page which is confusing.
> Warn if empty diff

- resources/web/template.html
When we're ready to enable it we'll fold it into the main javascript
file probably. But until then let's get it out of the template so it
doesn't take up extra space.
> Drop commented out APM from template

- shared/versions.asciidoc
- shared/versions55.asciidoc
- shared/versions56.asciidoc
- shared/versions60.asciidoc
- shared/versions61.asciidoc
- shared/versions62.asciidoc
- shared/versions63.asciidoc
- shared/versions64.asciidoc
- shared/versions65.asciidoc
- shared/versions66.asciidoc
- shared/versions67.asciidoc
- shared/versions68.asciidoc
- shared/versions70.asciidoc
- shared/versions71.asciidoc
- shared/versions72.asciidoc
- shared/versions73.asciidoc
- shared/versions74.asciidoc
- shared/versions75.asciidoc
This PR reverts https://github.com/elastic/docs/pull/1172 and updates them to point to the new shared version files until all the Cloud references can be fixed.
> Adds temporary redirects in out-dated shared version attribute files

- resources/web/docs_js/__tests__/components/alternative_picker.test.jsx
- resources/web/docs_js/components/alternative_picker.jsx
- resources/web/style/alternative_picker.pcss
- resources/web/styles.pcss
Just what it says on the tin.
I adjusted the `_AlternativePicker` component to be written as a class instead of a stateless component, in order to keep track of the hover state of a tooltip.
The rest was just CSS styling and animations that I borrowed from EUI, then adapted and tweaked to meet our specific use case.
Fixes #1113.
> Add tooltip when hovering over alt picker warning icon

- shared/attributes.asciidoc
Related to #1169 
This PR replaces the hard-coded ECS version number with an attribute that supports versioning.
DO NOT MERGE until all books using the hard-coded ECS attribute have been updated to include `//shared/versions/stack/{source_branch}.asciidoc` (or handled in product repo versioning)
* SIEM
*  ML
> Replace ecs version with attribute

- integtest/spec/single_book_spec.rb
- lib/ES/Util.pm
- resources/website-l10n.xsl
- resources/website_common.xsl
Drops some meta tags from the header. One is hard coded which seems
wrong. The other one isn't all that helpful.
> Drop some meta

- shared/versions/stack/README
- shared/versions/stack/current.asciidoc
This file will be useful for books that *generally* want to point the
current release of the stack. We'll update it when we release a new
version of the stack.
> Create "current" stack version file

- conf.yaml
These are very, very old but we'd still like to be able to build
them with Asciidoctor so we can drop support for AsciiDoc all together.
> Switch Japanese XPack docs to Asciidoctor

- shared/attributes.asciidoc
- shared/versions/stack/6.0.asciidoc
- shared/versions/stack/6.1.asciidoc
- shared/versions/stack/6.2.asciidoc
- shared/versions/stack/6.3.asciidoc
- shared/versions/stack/6.4.asciidoc
- shared/versions/stack/6.5.asciidoc
- shared/versions/stack/6.6.asciidoc
- shared/versions/stack/6.7.asciidoc
- shared/versions/stack/6.8.asciidoc
- shared/versions/stack/7.0.asciidoc
- shared/versions/stack/7.1.asciidoc
- shared/versions/stack/7.2.asciidoc
- shared/versions/stack/7.3.asciidoc
- shared/versions/stack/7.4.asciidoc
- shared/versions/stack/7.x.asciidoc
- shared/versions/stack/master.asciidoc
* Allows APM Server to take advantage of the new shared version file by adding `apm_server_version`
* ~Allows us to **finally** stop linking to `current` versions of all APM Agent documentation 🎉~ 
* ~Moves APM Agent version attributes to the shared version files.~
* Moves APM Agent attributes from the APM Server version file to the shared attributes file
> Add APM to shared versioning

- .dockerignore
- build_docs.pl
- integtest/spec/all_books_spec.rb
- integtest/spec/helper/book.rb
- integtest/spec/helper/console_alternative_examples.rb
- integtest/spec/helper/dsl/file_contexts.rb
- integtest/spec/helper/matcher/initial_js_state.rb
- integtest/spec/helper/repo.rb
- integtest/spec/preview_spec.rb
- integtest/spec/single_book_spec.rb
- integtest/spec/spec_helper.rb
- lib/ES/Book.pm
- lib/ES/Util.pm
- preview/Dockerfile
- preview/Makefile
- preview/__test__/git.test.js
- preview/git.js
- preview/preview.js
- preview/test.sh
- template/__test__/template.test.js
- template/cli.js
- template/template.js
This makes the preview service template html pages on the fly.
A few things had to happen to make this go:
1. Start writing everything that we need to render the tempelate on the
fly into built-docs, specifically the template and the language.
2. Only use the template if it is in the built-docs branch we're trying
to render. Branches without the template serve from the "html" directory
like we do in production.
3. Rework error handling for the git operations.
4. Move the git operations into their own file and unit test them.
5. Rework some other error handling after I found out the `.pipe`
doesn't propagate errors in node.
The performance cost of apply the template on the fly is something like
20 milliseconds which doesn't feel to bad because we're running six git
operations instead of …
> Template on the fly in preview

- integtest/spec/preview_spec.rb
- lib/ES/Util.pm
- preview/preview.js
- resources/web/air_gapped_template.html
This allows you to request the "air gapped" template from the preview
application by prefixing the branch name with `gapped_`. So you'd do
`http://gapped_master.docs-preview.app.elstc.co/guide` to see the master
branch with the air gapped template. It won't look good at all because
I've made no real effort to make it look right yet. That'll come in a
bit. For now, just seeing it is nice.
This also adds an air gapped template that drops some lines that
obviously aren't going to work properly when the docs are air gapped.
I've kept things like the favicon around because I believe we *should*
be able to make those work.
If you request the air gapped template from preview for a branch that
doesn't have a copy of the air gapped template then the request will
just 404.
Finally, I removed a few …
> Serve air gapped template from preview

- build_docs
- build_docs.pl
- integtest/Makefile
- integtest/spec/helper/dest.rb
- integtest/spec/helper/opened_docs.rb
- integtest/spec/single_book_spec.rb
- lib/ES/Util.pm
- preview/cli.js
- preview/core.js
- preview/preview.js
This applies the template on the fly when building docs locally. This is
useful for quickly iterating on the template. It also allows you to get
the air gapped template for the doc by requesting
`gapped.localhost:8000/guide`.
I implemented this by extracting the git logic for the preview service
into a "git core" and adding a new "fs core" which can serve documents
from the local filesystem. I like this particular implementation because
it gives us fewer things to test because almost everything is going
through the preview application.
It doesn't apply the template on the fly to `--all --open` because
*that* is supposed to be a more "production like" test. And, at least
for now, production uses nginx to serve static files locally.
> Apply template on the fly with --doc

- conf.yaml
Just changed 5.7 to 5.8 here. The 5.8 branch has been building stably for some time, so I don't think there should be any issues.
> Make Curator 5.8 the current release

- conf.yaml
Adds the `3.x` branch of the APM Node.js Agent to the documentation build.
When the branch is ready, we'll need to run the ci/docs test again with:
```
@elasticmachine, run elasticsearch-ci/docs rebuild
```
> Add APM Node.js 3.x documentation

- preview/Dockerfile
- preview/test.sh
- publish_docker.sh
This limits `git gc`'s memory usage. I chose a single thread because all
of the memory is per thread. I chose a small window size because I
[heard][so] that it isn't particularly useful. Even if it were, it'd make
the compressed result smaller which isn't currently super important to
us. I went with 500mb as the limit for the window because this seemed
more useful.
[so]: https://stackoverflow.com/a/27839473
> Limit git gc's memory usage

- integtest/spec/all_books_spec.rb
- resources/web/docs.js.licenses
- resources/web/lib/bootstrap/bootstrap.css
- resources/web/styles.css.licenses
- resources/web/styles.pcss
Adds bootstrap's css to our CSS which:
1. Prevents some of the "jumping" that happens on page load.
2. Allows the air-gapped template to work *much* better.
Follow-up work includes:
1. Step sending bootstrap's css to the docs as part of the header.
2. Figure out exactly what part of bootstrap we actually use.
> Add bootstrap css to our CSS

- integtest/spec/preview_spec.rb
- integtest/spec/single_book_spec.rb
- lib/ES/Util.pm
- preview/preview.js
- preview/test.sh
- publish_docker.sh
- template/template.js
Fix the table of contents in the preview and `--doc --open` modes.
Without this the table of contents just *doesn't* show up. With this we
continue to perform client side merging of the toc into the page.
Now that we're templating on the fly it is tempting to merge the toc at
template time, but that won't work in production because we're not
templating on the fly in production. Yet.
> Fix toc in preview

- resources/web/air_gapped_template.html
Drops our "best effort" for IE8 from the air gapped network template
because it requires access to the external web. We *could* bundle it but
it doesn't seem worth it for IE8.
Drops our `og:image` because that is used by facebook when linking to
the page. The air gapped docs aren't going to be linked to facebook
anyway. And that link is the last reference to www.elastic.co on the
template.
> Drop ie8 and social stuff from air gapped

- resources/legacy_redirects.conf
This PR adds redirects for transform content that was moved from the Stack Overview to the Elasticsearch Guide.  It also adds redirects for machine learning content that was moved from the Kibana Guide to the Stack Overview.
These redirects enable us to remove the matching "deleted pages" from the end of the books.
> Adds transform redirects

- .ci/publish_air_gapped_docs.sh
- .gitignore
- air_gapped/Dockerfile
- air_gapped/Dockerfile.dockerignore
- air_gapped/build.sh
- air_gapped/test.sh
- build_docs.pl
- integtest/spec/air_gapped_spec.rb
- integtest/spec/helper/dest.rb
- integtest/spec/helper/preview.rb
- integtest/spec/preview_spec.rb
- lib/ES/Util.pm
- preview/Dockerfile
- preview/cli.js
- preview/core.js
- preview/test.sh
Adds scripts to build a docker image with the air gapped docs. This
required a ton of changes that came before this, but this commits adds
the following features:
1. Adds a `--default-template` option to `preview/cli.js` which is used
when you don't specify a branch or the `gapped_` prefix.
2. Adds the `--gapped` option to the perl code handling previews which,
when specified, skips the initial fetch of the built docs, specifies the
`--default-template` to the preview, and skips the periodic fetches.
3. Adds a Dockerfile and scripts to build the docker image.
This project still isn't done because:
1. We need to add the infrastructure to publish the docker image.
2. We need to remove all external dependencies from the air gapped
template.
Probably more stuff I haven't thought of yet.
> Air gapped docs in a docker image

- air_gapped/Dockerfile
- air_gapped/build.sh
- preview/Dockerfile
- preview/test.sh
- publish_docker.sh
This should help to prevent
```
warning: There are too many unreachable loose objects; run 'git prune' to remove them
```
Related to #1214
> Configure preview's git gc

- integtest/spec/helper/dsl/convert_all.rb
- integtest/spec/single_book_spec.rb
- lib/ES/Util.pm
- package.json
- resources/web/air_gapped_template.html
- resources/web/template.html
Switches the template from serving the jquery from the public site to
serving it from the `/guide/static` which is served from the
`built-docs` repo. Also copies jquery.min.js into the `built-docs` repo.
I tried bundling `jquery` into `docs.js` but it made it much, much
bigger. That didn't seem worth it.
> Include jquery in built-docs

- integtest/spec/all_books_spec.rb
- integtest/spec/helper/dsl.rb
- integtest/spec/preview_spec.rb
- integtest/spec/single_book_spec.rb
- lib/ES/Util.pm
This should make it ever so slightly simpler to generate links to "the
docs".
> Redirect from the root the `/guide`

- build_docs.pl
- integtest/spec/air_gapped_spec.rb
- integtest/spec/all_books_broken_link_detection_spec.rb
- integtest/spec/helper/serving_docs.rb
- lib/ES/Util.pm
- preview/cli.js
- preview/core.js
I'd configured the air gapped docs so if you access them as
`localhost/blah` they'd always give you the master branch. But I still
allowed you to grab other branches with `foo.localhost/blah`. The
trouble with that is that folks will tend to want to have `.`s in the
hostname when they deploy it.
This locks the branch to always be `master` regardless of the host
header.
> Air gapped docs always serve master

- conf.yaml
This PR sets the current doc _pointer_ to the latest branch `7.2` of the client
> Point to latest PHP client doc

- build_docs.pl
- integtest/spec/helper/dest.rb
- integtest/spec/preview_spec.rb
If github is down or something, we really should just fail the pull, log
a message, and keep going. Before this PR we'd crash and k8s would
restart us. As nice as that is, we really ought to stay up.
> Preview: Survive git fetch failures

- air_gapped/Dockerfile
- air_gapped/build.sh
- preview/Dockerfile
- preview/test.sh
- publish_docker.sh
Adds optional credentials to Github repo URL if they exist. If they don't exist, the URL should be properly formatted without credentials.
> Add optional Github creds to built-docs

- shared/attributes.asciidoc
This PR adds attributes to make it easier to differentiate between Watcher transforms (https://www.elastic.co/guide/en/elasticsearch/reference/master/transform.html) and data transforms (https://www.elastic.co/guide/en/elasticsearch/reference/master/transforms.html).
> Adds shared attributes for Watcher transforms

- shared/settings.asciidoc
Restructuring Monitoring content for Logstash (https://github.com/elastic/logstash/pull/11033) resulted in a broken link in a deprecated topic. This PR removes the link.
> Remove broken link from a deleted topic

- resources/asciidoctor/.rubocop.yml
- resources/asciidoctor/lib/copy_images/extension.rb
- resources/asciidoctor/lib/edit_me/extension.rb
- resources/asciidoctor/lib/extensions.rb
- resources/asciidoctor/spec/edit_me_spec.rb
Switches the edit_me link implementation from a TreeProcessor to a
DelegatingConverter. This is nice because, eventually, we'll want to
generate the edit_me links differently if we're converting to html
instead of docbook. Converters are the place where we can make that
call.
Also I can remove some rubocop suppressions which is nice.
> Switch the edit_me link implementation

- integtest/.rubocop.yml
- integtest/spec/all_books_spec.rb
- integtest/spec/helper/dest.rb
- integtest/spec/helper/dsl/convert_all.rb
- integtest/spec/helper/shell_repo.rb
```
Before: 10m47.920s
After:   6m1.201s
```
The integration tests have felt slower to me so I did a little digging.
`top` told me that git was pretty busy during the integration tests and
it dawned on me that we put the fonts in the built-docs repo now and
they are pretty big.
This speeds up the tests by creating a "shell" repository before most
tests that already has the fonts in it and then clonging the "target"
repository from that shell before every test. That way we only have to
pay the cost of `git add`ing the font files one time.
> Speed up integration tests

- integtest/spec/single_book_spec.rb
- lib/ES/Util.pm
Before this commit we bundled executing `asciidoctor`, `xmllint`, and
`xsltproc` together, checking warnings after the whole process
succeedes. If any step in the process fails we'd log the errors for
*that* *step* and exit non-0. The trouble with this behavior is that
we'd throw out the warnings from the previous steps. This is especially
bad because the warnings from `asciidoctor` are *much* easier to debug
that errors from `xmllint`.
This commit causes us to check the warnings after each step. If there
are any warnings we log them and exit non-0. This is will effectively
prefer warnings from asciidoctor if there are any which should make
debugging problems like bad links *much* simpler.
> Check warnings from asciidoctor before next steps

- integtest/Makefile
It has some variables that are left over from when we were writing tests
in the Makefile directly. We don't need them any more.
> Clean integtest/Makefile

- build_docs.pl
- integtest/spec/all_books_change_detection_spec.rb
- lib/ES/DocsRepo.pm
- lib/ES/Repo.pm
It is important that changes to the docs repo don't trigger a rebuild
when `--keep_hash` is specified or else every time we change this
file we'll rebuild all books in every PR build. That is a waste of
time and a potential source of spurious errors.
This PR does exactly that: it adds tests that make sure we don't rebuild
and it makes a small change to the initialization fo the docs repo to
make the test pass.
> Make sure we don't rebuild at a bad time

- shared/attributes.asciidoc
Adds Asciidoc attributes for various uses of 'snapshot lifecycle management.'
The idea is to keep the docs DRY, reduce the likelihood of error, and make future updates easier if we decide to rename SLM to something else.
I largely followed the pattern used for ILM, but let me know if you'd like to see anything else.
This should also fix the current attribute in use in the SLM docs:
https://github.com/elastic/elasticsearch/blame/master/docs/reference/ilm/apis/slm-api.asciidoc#L44
> [DOCS] Add attributes for SLM

- integtest/Makefile
- integtest/html_diff
- lib/ES/Util.pm
- resources/asciidoctor/lib/extensions.rb
- resources/asciidoctor/lib/relativize_link/extension.rb
- resources/asciidoctor/spec/relativize_link_spec.rb
This adds an asciidoctor plugin to automatically relativize links with a
particular prefix and configures it with `https://www.elastic.co/
Closes #1029
> Automatically relativize links to elastic.co

- shared/versions/stack/6.5.asciidoc
- shared/versions/stack/6.6.asciidoc
- shared/versions/stack/6.7.asciidoc
- shared/versions/stack/6.8.asciidoc
- shared/versions/stack/7.0.asciidoc
- shared/versions/stack/7.1.asciidoc
- shared/versions/stack/7.2.asciidoc
- shared/versions/stack/7.3.asciidoc
- shared/versions/stack/7.4.asciidoc
- shared/versions/stack/7.x.asciidoc
- shared/versions/stack/master.asciidoc
Couple more changes per [this](https://github.com/elastic/observability-dev/blob/master/docs/apm/apm-documentation.md#updating-an-apm-agent-to-a-new-version).
This PR updates `3.x` to the current version of the APM Ruby Agent back to `6.5`.
> docs: update APM ruby current to 3.x

- README.asciidoc
- build_docs.pl
- integtest/Makefile
- integtest/spec/all_books_change_detection_spec.rb
- integtest/spec/all_books_sub_dir_spec.rb
- integtest/spec/helper/repo.rb
- lib/ES/BaseRepo.pm
- lib/ES/Repo.pm
- lib/ES/TargetRepo.pm
This adds a fancy interaction between `--sub-dir` and `--keep_hash` that
is meant to make sure we build *exactly* the right docs for pull
requests.
When we first deploy pull request builds we targeted them at the tip of
the pull request branch. This caused trouble because the tip of the pull
request branch was often behind the last successful build. Building the
docs against that would often cause spurious failure from out of date
links. Merging `master` into the PR branch usually fixed it but it was
annoying.
We fixed this problem by switching our target to the result of merging
the pull request branch into the target branch. This was *better*
because it had fewer spurious failures, but often caused us to think
that the docs changes were larger than they actually were because the
target …
> Fancy --sub_dir and --keep_hash

- integtest/spec/all_books_spec.rb
- integtest/spec/helper/dsl.rb
- integtest/spec/helper/matcher/redirect_to.rb
- integtest/spec/preview_spec.rb
- integtest/spec/spec_helper.rb
- preview/core.js
- preview/preview.js
This add support for parsing the redirects.conf file that we've been
including in every do build for a while. It is *technically* an nginx
config file but it is safe to treat it as a list of regex substitutions.
> Support redirects in preview

- shared/attributes.asciidoc
This PR adds a new attribute for the APM app documentation: `apm-app-ref`. Right now, this reference points to the Kibana docs. Over the next few weeks I'll slowly be moving APM Agent/Server links to this new attribute. Then, when the APM app documentation moves out of Kibana, I'll simply need to adjust this attribute to point to the right location.
FYI @gchaps @KOTungseth
> Add APM app attribute

- preview/__test__/buffer_itr.test.js
- preview/__test__/git.test.js
- preview/buffer_itr.js
- preview/core.js
The code that emits the `html` for our `diff` endpoint if pretty chatty
and we wrap it in a "buffering iterator" to save up chunks until they
are worth sending. It had a bug where it'd duplicate stuff. This fixes
that bug and adds tests.
> Fix some duplication problems in buffer itr

- conf.yaml
This adds an explicit dependency on the docs repo for all books build
from `stack-docs`. This will expose the `docs-root` attribute to those
books and automatically rebuild the books if any of those file change.
> Add explicit dependency on docs repo for some books

- conf.yaml
Another step in our effort to remove the unmaintained AsciiDoc in favor
of the actively maintained Asciidoctor.
> Move the swiftype placeholder to asciidoctor

- conf.yaml
- integtest/spec/all_books_spec.rb
- integtest/spec/helper/book.rb
- lib/ES/Book.pm
MIGRATION warnings are problems that we should fix in newer versions of
a book but aren't worth fixing in old versions of a book. But some books
are old and aren't going to be updated, probably ever. Those books
should just suppress their MIGRATION warnings all together. This allows
you to configure that.
> Allow explicit suppress of MIGRATION warnings

- integtest/Makefile
- integtest/spec/all_books_sub_dir_spec.rb
- lib/ES/Repo.pm
When an entire repo is included by the docs we were failing to properly
perform the merge. This fixes that.
> Improve --sub_dir --keep_hash for /

- air_gapped/Dockerfile
- air_gapped/build.sh
- build_docs.pl
- preview/Dockerfile
- preview/test.sh
- publish_docker.sh
Loading creds into the URI ends up making it way too easy to leak creds in logs and such. Switching to clone the repo via SSH, with the assumption that SSH creds will be available on the box.
> [docs-preview] Switch Github creds to use SSH

- shared/attributes.asciidoc
This PR adds an attribute for the following book in the list of shared URLs: https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/master/index.html
> Add shared URL for Elasticsearch Node.js client book

- shared/attributes.asciidoc
- shared/attributes62.asciidoc
This PR backports the new attributes that were added in https://github.com/elastic/docs/pull/1301 and adds a URL that points to the "current" version.
> More attributes for the Elasticsearch node.js client documentation

- shared/versions/stack/7.5.asciidoc
This PR adds a shared version attribute file for the 7.5 branch of the documentation.
> Adds 7.5 version attributes

- conf.yaml
- shared/versions/stack/6.6.asciidoc
- shared/versions/stack/6.7.asciidoc
- shared/versions/stack/6.8.asciidoc
- shared/versions/stack/7.0.asciidoc
- shared/versions/stack/7.1.asciidoc
- shared/versions/stack/7.2.asciidoc
- shared/versions/stack/7.3.asciidoc
- shared/versions/stack/7.4.asciidoc
- shared/versions/stack/7.x.asciidoc
- shared/versions/stack/master.asciidoc
Updates `current` links for the APM Node.js Agent.
> [docs] Update current for APM Node.js Agent

- build_docs
When a book fails to build we try to list the latest commits from each
of the sources of the book. When one of the sources of that book is the
docs repo *and* the docs repo was cloned with `--reference` then we were
failing to list the source and crashing. This fixes that by mounting the
`--reference`d repo.
> Fix error reporting when book depends on docs

- integtest/spec/all_books_spec.rb
- lib/ES/Repo.pm
We helpfully tried to decode utf8 when we to a `git log`. The trouble
with this is that we've *already* decoded those characters so this blows
up.
> Don't choke on utf8 in logs

- integtest/spec/air_gapped_spec.rb
- integtest/spec/helper/matcher/redirect_to.rb
- integtest/spec/preview_spec.rb
- lib/ES/Util.pm
- preview/core.js
- preview/preview.js
When you make a request to a location outside of the `guide` we should
redirect to `www.elastic.co` *unless*:
1. We have the file (then we should just send it to you).
2. You made the request for air gapped docs (we should 404).
This implements that by adding a `try_files` block to the `/` arm of our
nginx config which forwards requests for missing files right into the
preview application. The preview application checks if you are asking
for the air gapped deploy or not and performs the redirect or not.
Relates to #1300
> Redirect slightly more

- build_docs.pl
- integtest/spec/all_books_spec.rb
- integtest/spec/single_book_spec.rb
- lib/ES/Book.pm
- lib/ES/Toc.pm
- lib/ES/Util.pm
I don't particularly like building different books with `--all` vs
`--doc`, but in this case it seems like it is the best solution....
We want to relativize links to `www.elastic.co` because it prevent
linking off into "nowhere" when you use the docs in a air gapped
network. And it makes it less likely that you'll accidentally get linked
to production when browsing the docs preview. On the other hand, when
you are building docs with `--doc` the URL space looks nothing like when
you build all the docs so links into the docs that aren't already part
of the book aren't going to resolve properly if we relativize them.
So, this does what I don't really want to do but think is probably the
right thing to do anyway: it only relativizes the links if you build
all of the books and skips it if you …
> Only relativize links build with --all

- conf.yaml
Asciidoc is unmaintained. It is time to get everything off of it.
> Switch Kibana's CN book to asciidoctor

- conf.yaml
It is time to drop AsciiDoc support. It hasn't been maintained for a
long, long time.
> Switch kr X-Pack docs to Asciidoctor

- conf.yaml
Add explicit dependencies on the files in the docs repo that logstash
uses so that when they change we automatically rebuild the docs.
> Explicitly depend on shared docs in logstash

- conf.yaml
It is time to retire AsciiDoc. It hasn't been maintained in a long time.
> Switch Korean translation of kibana to Asciidoctor

- shared/attributes.asciidoc
- shared/attributes62.asciidoc
We should prefer https for the security and because our link relativizer
only does the job for https.
> Switch all attribute links to https

- conf.yaml
It is time to retire AsciiDoc because it is no longer maintained.
> Switch Japanese Kibana docs to Asciidoctor

- conf.yaml
AsciiDoc is unmaintained and we should drop support for it.
> Switch uptime docs to Asciidoctor

- conf.yaml
> Switch the Korean ES reference to Asciidoctor

- air_gapped/Dockerfile
- air_gapped/build.sh
- integtest/spec/preview_spec.rb
- lib/ES/Util.pm
- preview/test.sh
- publish_docker.sh
Adds a `/liveness` endpoint which returns a 200 strait from nginx so it
will be considered "alive" very, very soon.
> Create dedicated livenss endpoint

- conf.yaml
With the versioned link switch to ECE 2.4, we need this PR to enable Cloud PR tests to pass.
Required by https://github.com/elastic/cloud/pull/42356.
> Add ECE 2.4 doc builds

- conf.yaml
Adds explicit paths for shared attributes and versions used by the Beats documentation.
> Make doc repo dependencies explicit in Beats documentation

- conf.yaml
> Switch the Japanese ES reference to Asciidoctor

- conf.yaml
> Switch Japanese Logstash reference to Asciidoctor

- conf.yaml
> Switch Korea Logstash reference to Asciidoctor

- conf.yaml
APM didn't make it into the 7.5 branch PR (https://github.com/elastic/docs/pull/1304). @lcawl I'm guessing you're doing some sort of find and replace for `master, 7.x, 7.4`. APM won't appear in that search because we don't build the `7.x` branch.
> Build 7.5 branch for APM documentation

- conf.yaml
This PR must be merged immediately after the next APM Ruby Agent release. It will fix the doc build before it has enough time to break.
> Add ruby changelog for 3.x

- conf.yaml
AsciiDoc is deprecated and we have to drop support for it.
> Switch the Chinese Definitive Guide to Asciidoctor

- conf.yaml
With the production release of `release-ms-28` early this coming week, let's get our doc builds ready. 
**DO NOT MERGE UNTIL MS 28 GOES OUT**
> Update ESS and Heroku doc builds to use release-ms-28

- conf.yaml
> Switch cloud's heroku docs to asciidoctor

- conf.yaml
- integtest/.rubocop.yml
- integtest/spec/air_gapped_spec.rb
- integtest/spec/helper/dest.rb
- integtest/spec/helper/dsl/convert_all.rb
- integtest/spec/helper/dsl/convert_single.rb
- integtest/spec/preview_spec.rb
- integtest/spec/single_book_spec.rb
A while back I started migrating my calls to "convert" documents in the
integration tests from a single method into a fluent builder style
because we've grown so many parameters for the conversion. This finishes
that migration.
> Finish a ruby migration

- shared/attributes.asciidoc
We're splitting the logging and metrics guides. Let's get the attributes
in first so we can build everything else a little more cleanly.
> Add new attributes for the upcoming guides

- resources/asciidoctor/.rubocop.yml
- resources/asciidoctor/lib/extensions.rb
- resources/asciidoctor/lib/open_in_widget/extension.rb
- resources/asciidoctor/spec/elastic_compat_preprocessor_spec.rb
- resources/asciidoctor/spec/open_in_widget_spec.rb
I've been wanting to remove our fairly complex `TreeProcessorScaffold`
for a while now because it mirror's Asciidoctor's `Conveter` except it
doesn't properly handle attributes. This migrates `open_in_widget` off
of the scaffold to a converter. This also has the advantage of giving a
clear path to implement the converter if we target html instead of
docbook, which we'd very much like to do.
> Simplify open_in_widget

- shared/attributes.asciidoc
I know, linking to current is (generally) evil, but I want to be able to link to the instructions/compose file for installing the latest available Docker images.
> Add attribute for current version of the Stack Getting Started

- conf.yaml
- doc_build_aliases.sh
- shared/attributes.asciidoc
Changes required as a result of splitting Infrastructure Monitoring Guide into separate Logs and Metrics guides.
This is part of a multi-repo change (see elastic/observability-dev#98). DO NOT PUSH UNTIL EVERYTHING IS READY.
> [DOCS] Split Infrastructure Monitoring guide into separate Logs and Metrics docs.

- conf.yaml
The current version of the stack is 7.4 but we don't have a 7.4 version
of those books.
> Flip the current version of the new books to 7.5

- shared/attributes.asciidoc
We planned to do these attributes updates as part of #1312 but we split
them out to speed up the deploy. This adds them back.
> Cleanup attributes after docs split

- conf.yaml
This patch adds the Go to the list of alternative languages to choose from in the documentation.
> Add go-elasticsearch to the list of alternative languages

- conf.yaml
With the release of ECE 2.4 imminent, let's prepare to point `current` to `2.4`. 
@elastic/cloud-writers could one of you approve, please? 
*** DO NOT MERGE UNTIL ECE 2.4 GOES GA ***
> Change current for ECE to 2.4

- resources/web/style/table.pcss
This prevent super-wide tables from escaping their containers and ending
up under the nav.
Closes #1237
> Don't allow tables to escape

- conf.yaml
This PR adds version 7.4  to the Azure Marketplace docs and sets 7.4 as the current version
> Update Azure Marketplace docs to 7.4

- build_docs
- publish_docker.sh
I hadn't used it when I first migrated the docs build to docker because
it was slower when the image was already cached. But it is now a little
faster for me. And it is the future of the docker project. And it gives
more features which we will use eventually.
> Switch to docker's buildkit everywhere

- Dockerfile
This *massively* shrinks our docker images, most importantly, the air
gapped docs image:
```
-rw-------. 1 manybubbles manybubbles 1.1G Oct 31 17:16 /home/manybubbles/Downloads/air_gapped_after.tar
-rw-------. 1 manybubbles manybubbles 1.6G Oct 31 17:09 /home/manybubbles/Downloads/air_gapped_before.tar
```
It does so by using the "multi-stage builds" feature from docker's
buildkit. It allows you to create multiple docker images in the same
Dockerfile and copy parts each image into another. We use that to build
images that *just* install dependencies and then we copy those
dependencies from those images into a "final" image.
> Shrink docker images

- resources/web/style/table.pcss
It turn out that tables that don't have a title don't have a
`table-contents` class. They have an `informaltable` class intead.
:shrug: This prevents those sorts of table from escaping under the nav
as well.
> Prevent informal table from escaping

- integtest/spec/all_books_change_detection_spec.rb
- integtest/spec/helper/book.rb
- lib/ES/Book.pm
- lib/ES/Repo.pm
- lib/ES/Source.pm
- lib/ES/Toc.pm
Replaces the mechanism that we used track the Asciidoctor migration with
a new mechanism that we will use to track the "direct to html"
migration.
> Track direct-to-html conversions

- conf.yaml
- doc_build_aliases.sh
Drop the `asciidoctor` flag from `conf.yaml` and `doc_build_aliases.sh`.
It isn't needed any more.
> Drop explicit asciidoctor

- Dockerfile
Drops python 2 from the Docker image. We don't need it any more!
> Drop python2

- build_docs.pl
- lib/ES/Toc.pm
- lib/ES/Util.pm
- template/template.js
This adds the option to generate html directly from asciidoctor for
single page books with `--direct_html`. Right now no books use this but
we'd like to migrate all of them too it once we're sure the output looks
good for them!
Relates to #743
> Add the option to skip docbook for single page

- template/__test__/template.test.js
The template tests were missing a `return` which meant that the
assertion didn't trigger. That assertion started failing and we didn't
know! This fixes the `return` and the failing assertion.
> Fix a test bug in template

- air_gapped/Dockerfile
- build_docs.pl
- preview/Dockerfile
`--target_repo` has been required with `--all` for a while now, but we
only ever really call it with
`--target_repo git@github.com:elastic/built-docs.git`. We typically use
`--target_branch` for experimentation. So let's just assume `built-docs`
unless someone passes `--target_repo`.
> Default to built-docs repo

- Dockerfile.dockerignore
- preview/Dockerfile.dockerignore
Our "normal" docker image was including context files needed for the
`preview` docker image because I didn't know how to make separate
`.dockerignore` files for each `Dockerfile`. I know now. So this fixes
up the main `.dockerignore` file.
> Speed up building "normal" docker image

- .ci/test.sh
- Makefile
- build_docs
- common.mk
- integtest/Makefile
- preview/Makefile
- resources/asciidoctor/Makefile
- resources/web/Makefile
- template/Makefile
Previously we ran make inside of our docker container. Long ago this was
important because we did complex things in make. We don't any more
though because that was a stygian nightmare. This flips the `Makefile`s
so *they* run docker. This is nice because:
1. It is now possible to `cd` into any directory you like and run `make`
to run the tests.
2. We can use different docker images for different tests. We *don't* do
that right now, but we certainly *can* do that with this change in the
future.
This routes all execution of docker through the `build_docs` script,
which is nice because docker requires a bunch of command line options to
properly run the scripts, particularly in the integration tests. It'd
be nice if we could limit those options to just the tests that need
them, but that is a …
> Invert Makefile control

- resources/asciidoctor/lib/chunker/extension.rb
- resources/asciidoctor/lib/extensions.rb
- resources/asciidoctor/spec/chunker_spec.rb
- resources/asciidoctor/spec/spec_helper.rb
We'd very much like to avoid having to use docbook to generate our HTML
because it is slow and difficult to customize. This creates the
beginnings of an Asciidoctor plugin that emulates docbook's chunking.
The plan is to enable it on the perl side with a command line flag and a
flag in conf.yaml in a follow up change.
Relates to #1390.
> Emulate docbook chunking

- conf.yaml
Adds processor doc files so we can move them to a directory within the code modules.
~Currently only covers Packetbeat. I will copy to other beats after @nik9000 confirms that this approach will work.~ done
~This PR must be merged after https://github.com/elastic/beats/pull/14488~ done
> Add processor doc folders to the conf.yaml

- build_docs.pl
- lib/ES/Util.pm
- resources/asciidoctor/lib/chunker/extension.rb
This hooks the `chunker` extension added in #1390 to the docs build when
you do a multi-page book with `--direct_html`. Important: it crashes!
But I'll fix it with mostly ruby hacking and this is more perl stuff and
it is fairly selef contained. So I figure I should fix it in a follow up
change.
> Progress building chunked docs

- integtest/spec/all_books_sub_dir_spec.rb
- lib/ES/Repo.pm
When a source contained `*` the merging logic used by `--sub_dir
--keep_hash` would cause git errors because it attempted to name a
branch with a `*` in the name. This fixes that error so the `*`s work.
> Fix bug when source contains *

- shared/attributes.asciidoc
This PR defines a shared attribute for `ctransform-cap`, since it is used by
https://www.elastic.co/guide/en/elasticsearch/reference/current/transform-limitations.html
> Adds missing shared attribute for transforms

- integtest/spec/all_books_sub_dir_spec.rb
- lib/ES/Repo.pm
There is a place where we treat * as though it were in a glob when it
*really* is in a git pathspec. Also, we treat it as though it'll only
make a single directory. That isn't going to work with some changes
beats is making. This fixes both of those things.
> Fix support for * in pathspecs

- Dockerfile
- Makefile
- build_docs
- integtest/Makefile
- package.json
- preview/Makefile
- resources/asciidoctor/Makefile
- resources/web/Makefile
- template/Makefile
This shrinks the build, preview, and air gapped images by moving the
test dependencies out of them. This is also nice because changing test
dependencies won't cause us to have to rebuild the production images.
The cost is that it'll be a little slower to run the tests the first
time. This isn't a problem locally, but will slow down CI. We can
mostly mitigate that in a follow up change though.
Before:
```
-rw------- 1 manybubbles manybubbles 1.1G Nov 12 19:06 air_gapped_with_test.tar
```
After:
```
-rw------- 1 manybubbles manybubbles 930M Nov 12 19:01 air_gapped_no_test.tar
```
> Shrink production images

- .ci/test.sh
- build_docs
- integtest/spec/all_books_spec.rb
- integtest/spec/spec_helper.rb
- preview/__test__/clean.test.js
- preview/__test__/git.test.js
Fixes a fairly esoteric error that you get when you do
```
./build_docs --keep_hash --sub_dir blah:blah:blah
```
without `--push`.
It fixes it by *always* passing the git username and email to the docker
image all the time. It also cleans up the tests a little bit in the ways
that that change implies.
> Fix fairly strange error

- Dockerfile
This adds a docker image for the diff tool. We used to be able to use
the regular build image for it but now that we stripped all the test
stuff out of it we'll need a named image for it.
Expect like, real tests and stuff for it to come in at some point. It is
an "expert" tool mostly used for migration, but it is important that it
works.
> Keep the diff tool working

- resources/web/style/heading.pcss
We don't depend on the aktiv-grotesk font any more but we still declare
that headings should have it. That causes them to look radically
different on different platforms. We should just use Inter like we do
with anything else.
> Switch headings to Inter

- conf.yaml
Do not merge until *after* https://github.com/elastic/beats/pull/14571 and https://github.com/elastic/beats/pull/14570 are merged.
docs CI will fail until the dependencies are meged.
> Remove 7.x and 7.5 from excludes for processor refactoring

- .ci/clean_preview_branches.sh
- .ci/packer_cache.sh
- .ci/test.sh
- build_docs
- preview/build.sh
Builds the testing docker images during the packer cached step of the
process that builds the images that run the docs build. So *usually*
we'll be able to use the cached copy. Which speeds up the tests.
> Speed up tests

- conf.yaml
- integtest/spec/all_books_spec.rb
- integtest/spec/helper/book.rb
- integtest/spec/helper/book_conf.rb
- lib/ES/Book.pm
We've wanted for a while to mark old versions of books as "noindex" and,
probably, to remove the `edit_me` links from them. This creates a config
entry for `conf.yaml` to mark branches as "live". If this list is
specified then everything *not* in the list will be marked as `noindex`.
In the future we might remove the edit links from it was well.
This applies that config change to the installation and upgrade guide,
just to apply it to something for testing. I think we'll want to apply
it to most books eventually.
> Create a "live" branches config for books

- integtest/html_diff
- lib/ES/Util.pm
- resources/asciidoctor/lib/chunker/extension.rb
- resources/asciidoctor/lib/docbook_compat/extension.rb
- resources/asciidoctor/lib/extensions.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
- resources/asciidoctor/spec/spec_helper.rb
Creates a plugin to "work like" Elastic's docbook customizations. The
idea here is to replace docbook with as close to 0 diffs as possible.
But in some cases, that isn't worth it. So this also alters `html_diff`
to start to normalize all of the diffs that we don't care about. Right
now there is only one, but I'm sure we'll have a hand full.
The actual asciidoctor plugin munges the header and title into the
correct form with string manipulation. I don't feel *too* bad about that
because:
1. It is in the grand tradition of bubble gum and duct tape that holds
all of the important bits of the internet together.
2. We'll be able to *remove* it piece by piece once we're done. It'll be
*much* easier to visually verify that removing each piece is safe if we
can do it one by one.
3. Further work …
> Create docbook workalike plugin

- conf.yaml
Configures which branches are "live" for book that are versioned with
the stack.
> Configure "live" branches for stack books

- integtest/spec/all_books_sources_spec.rb
- integtest/spec/helper/book_conf.rb
- integtest/spec/helper/source.rb
- integtest/spec/spec_helper.rb
The integration tests used a lot of code to properly generate yaml that
the docs build could parse, mostly because the docs build used an old
yaml parser that had a few bugs. But we recently upgraded the yaml
parser and it looks like it doesn't have the bugs any more! So this
replaces the "by hand" yaml generation with ruby's built in `.to_yaml`
which is much simpler to do.
> Clean up yaml generation in tests

- conf.yaml
- doc_build_aliases.sh
- integtest/html_diff
- integtest/spec/all_books_change_detection_spec.rb
- integtest/spec/helper/book.rb
- integtest/spec/helper/book_conf.rb
- lib/ES/Book.pm
- lib/ES/Util.pm
- resources/asciidoctor/lib/docbook_compat/doc_munging.rb
- resources/asciidoctor/lib/docbook_compat/extension.rb
- resources/asciidoctor/lib/edit_me/extension.rb
- resources/asciidoctor/lib/extensions.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
- resources/asciidoctor/spec/edit_me_spec.rb
- template/__test__/template.test.js
- template/template.js
This improves our plugin for direct html generation in Asciidoctor to
the point where the diff for the perl client's docs is empty. Now, that
isn't as big a feat as it sounds because:
1. Most of the perl client's docs are on CPAM so the docs we actually
build are pretty small.
2. I pull a few tricks with `html_diff` to ignore a few changes that
don't *look* like they make any visual difference to me.
Even with those two caveates, this is pretty good progress. It switches
the perl client to direct html, because, well, I did all the work to
make sure the diff is empty.
> Improve direct html generation

- conf.yaml
This PR updates the docs for [elasticsearch-php](https://github.com/elastic/elasticsearch-php) 7.4 branch.
> Update the PHP docs

- conf.yaml
Full details in https://github.com/elastic/docs/pull/1421 & https://github.com/elastic/docs/issues/1419. To summarize:
> We've wanted for a while to mark old versions of books as "noindex" and,
probably, to remove the `edit_me` links from them. This creates a config
entry for conf.yaml to mark branches as "live".
This PR sets _live_ branches for the APM agents. Specifically, it marks only `master` and the `current` version of each agent as _live_. @lreuven (or maybe @axw?) can you confirm there are no other branches that should also be marked as _live_?
> Add "live" branches for APM agents

- conf.yaml
- doc_build_aliases.sh
Related to https://github.com/elastic/stack-docs/pull/693
This PR removes references to the Kibana,  Beats, and X-Pack Elasticsearch repos from the Stack Overview, since those dependencies are no longer required.
> Removes unnecessary repos from Stack Overview

- shared/notices/README.txt
- shared/notices/page_header-EOL.html
- shared/notices/page_header-OOM.html
The default banner for versions older than the current version does not distinguish between versions that are still being actively maintained and versions that are out of maintenance or EOL. 
Changes that we've been discussing around our backporting policy, "live" docs, and sunsetting old versions mean we need to more clearly communicate to readers when they are looking at a version that is OOM or EOL. 
The intent is that these boilerplate messages will be set on a per-version basis for stack docs that have reached OOM or EOL. Going forward, we'll need some process for adding the notices as versions age.
**Out of maintenance notice:** 
**EOL notice:**
Relates to: https://github.com/elastic/docs/issues/1407, https://github.com/elastic/docs/issues/1419, …
> Boilerplate for EOL/OOM notices.

- resources/asciidoctor/lib/chunker/extension.rb
- resources/asciidoctor/spec/chunker_spec.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Improves the docbook chunking emulation by generating proper headers for
the pages. This allows the templating system to work for them so
now multi-page books at least won't crash with `--direct_html`.
> Improve docbook chunking emulation

- build_docs.pl
- integtest/spec/single_book_spec.rb
When you build docs with `--doc` and the source files don't live in a
git repo with an Elastic remote we log a line about how we can't find
the Elastic remote. We really only need the remote to build edit urls
so if we don't find it then it is *probably* ok because we just use the
first remote. The edit urls are less realistic but that isn't a big
deal usually.
This modifies the message we log to make it clear that it is just about
the edit links.
> Improve error messsage when no elastic remote

- build_docs.pl
- conf.yaml
- extra/README
- extra/docs_landing.html
- extra/kibana_landing.html
- integtest/spec/all_books_spec.rb
- integtest/spec/helper/book.rb
- integtest/spec/helper/book_conf.rb
- integtest/spec/helper/source.rb
- lib/ES/Book.pm
- lib/ES/Toc.pm
- lib/ES/Util.pm
This adds the perl plumbing for "extra" HTML that is added to the table
of contents after it is rendered. This *probably* won't be enough
for #1338 but it is a good start.
> Plumbing for "extra" HTML in TOCs

- conf.yaml
This PR adds the alternative examples to the cloud docs. Currently only the SaaS book is currently subjected, as the display is still in PoC.
/cc @nik9000 & @russcam
> Added the alternative examples for Cloud

- integtest/spec/helper/dest.rb
- integtest/spec/single_book_spec.rb
- lib/ES/Util.pm
We'd very much like to retire docbook, but we use its "docinfo" feature
quite a bit to add extra text to the header of the title page of a few
of our books. Asciidoctor *has* a "docinfo" feature but we can't use it
to emulate docbook's docinfo because the asciidoctor adds the text to
the `<head>` tag while docbook adds it below the `<h1>` tag. This change
causes us to look for files names `-extra-title-page.html` to find text
to add just below the `<h1>`.
> Create a substitute for docinfo in direct html

- README.asciidoc
Replace it was Asciidoctor stuff where needed.
> Drop asciidoc stuff from the README

- resources/asciidoctor/lib/docbook_compat/convert_document.rb
- resources/asciidoctor/lib/docbook_compat/convert_lists.rb
- resources/asciidoctor/lib/docbook_compat/convert_outline.rb
- resources/asciidoctor/lib/docbook_compat/extension.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
This modifies the docbook_compat plugin to add the table of contents to
the same location that docbook adds it and to generate it in the same
style that docbook uses. It only works for a single level, but that
should be fine for now. We'll improve it in further work.
> Handle single-level TOCs in direct html

- conf.yaml
- doc_build_aliases.sh
This replaces the xmllint/xslt steps with the ruby implementation we've
been working on. It is generally much faster and much easier to
customize.
> Convert all single page books to direct html

- conf.yaml
Adds path statements to get asciidoc source files from directories under libbeat/outputs/docs.
Prep work for more refactoring of libbeat.
> Add libbeat/outputs dirs to conf.yaml

- .docker/asciidoctor_2_0_10.patch
- lib/ES/Util.pm
- resources/asciidoctor/lib/chunker/extension.rb
- resources/asciidoctor/lib/docbook_compat/convert_document.rb
- resources/asciidoctor/spec/chunker_spec.rb
`--direct_html`'s chunking was broken in two ways:
1. It'd only chunk when the section level matched the chunk level
exactly. It is supposed to chunk when it is less than or equal to the
level. This does that.
2. It wasn't using the standard table of contents mechanism to build the
table of contents. Which is trouble because our fancy table of contents
rendering code wasn't kicking in *and* because the table of contents was
getting scattered across the chunked pages. This fixes that too.
> Fix direct_html chunking

- resources/asciidoctor/lib/chunker/extension.rb
- resources/asciidoctor/spec/chunker_spec.rb
Docbook generates a `<link rel="home"` in the header. We should do so
too, if just to line up with docbook.
> Add home link to direct html

- lib/ES/Util.pm
- resources/asciidoctor/lib/docbook_compat/convert_document.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Handles subtitles in `--direct_html` the same way that we handle them in
docbook.
> Handle subtitles in direct_html

- README.asciidoc
- resources/web/docs_js/__tests__/utils.test.js
- resources/web/docs_js/components/console_widget.jsx
- resources/web/docs_js/index.js
- resources/web/docs_js/localization.js
- resources/web/docs_js/utils.js
- resources/web/style/console_widget.pcss
- resources/website_common.xsl
Adds "Copy as cURL" links for Elastic Cloud SAAS and Elastic Cloud
Enterprise.
Also removes the "langStrings" passed into the curl building code. We
don't need it.
> Add Copy as cURL links for Cloud and ECE

- shared/api-ref-ex.asciidoc
This PR adds a comment to the API reference template. It recommends that we use "api" in the page title and anchor for consistency and SEO purposes.
> Adds API reference ID recommendation

- README.asciidoc
Two examples in the README are displaying inconsistently with the rest
because the blocks are missing the Asciidoc "source" attribute.
Add the missing attribute lists above the blocks to fix their
presentation.
**Before:**
**After:**
> Fix presentation of 2 examples in README

- integtest/html_diff
- resources/asciidoctor/lib/docbook_compat/convert_lists.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
This makes `--direct_html`'s ordered lists look visually the same as
docbook's ordered lists by removing the extra `<p`> tags on the entries
and adding docbook's standard classes. Docbook adds some extra "stuff"
to the lists which `--direct_html` doesn't even after this change but it
doesn't make a visual difference so we normalize those differences away
with `html_diff`.
> Normalize direct_html's ordered lists

- resources/asciidoctor/lib/chunker/extension.rb
- resources/asciidoctor/lib/docbook_compat/convert_document.rb
- resources/asciidoctor/spec/chunker_spec.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
This disables the "header" parts of `--direct_html`'s "subpages". These
pages only really *want* the contents of the subpage, not the
"titlepage" that comes with a "full" book.
> Disable headers in direct_html subpages

- resources/asciidoctor/lib/docbook_compat/convert_document.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Our docbook extensions wrap the table of contents in ``
and `` to make some manipulation by the docs build
simpler. This adds those comments to the when generating the html
directly from Asciidoctor.
> Wrap toc in comments in direct_html

- integtest/html_diff
- resources/web/style/img.pcss
`--direct_html` emits images wrapped in `<span class="image">` while
docbook emits them as `<span class="inlinemediaobject">`. This updates
the style so they both render the same and updates the `html_diff` tool
so we ignore that difference.
> Handle the direct_html's different image class

- resources/asciidoctor/lib/docbook_compat/convert_links.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Fixes an infinite loop that in the direct_html code that comes up when
you like to an inline anchor. These are *fairly* common and were causing
the Elasticsearch reference not to build with `--direct_html`.
> Fix a direct_html crash on link to inline anchor

- resources/asciidoctor/lib/chunker/extension.rb
- resources/asciidoctor/lib/chunker/extra_docinfo.rb
- resources/asciidoctor/lib/chunker/find_related.rb
- resources/asciidoctor/spec/chunker_spec.rb
- test
Adds the `<link rel="home"`, `<link rel="up"`, `<link rel="pre"`,
and `<link rel="next"` tags to the header for direct_html.
> Generate related links for direct_html

- resources/asciidoctor/lib/docbook_compat/convert_document.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Drops a wrapper `<div>` that declares that we're converting a `book` or
an `article` for subpages produced by `--direct_html`. This lines them
up *much* better with docbook.
> Drop wrapper div in subpages

- shared/attributes.asciidoc
This PR adds a shared attribute for ":wikipedia:", since it is used in at least one page:
https://www.elastic.co/guide/en/elasticsearch/reference/master/setting-up-authentication.html
Preview: http://docs_1465.docs-preview.app.elstc.co/guide/en/elasticsearch/reference/master/setting-up-authentication.html
> Adds shared attribute for wikipedia

- conf.yaml
I noticed that we don't have descriptive text for ecctl, which was probably my omission. This PR fixes that.
> Add descriptive text for ecctl title

- resources/asciidoctor/lib/chunker/extension.rb
- resources/asciidoctor/lib/chunker/extra_docinfo.rb
- resources/asciidoctor/lib/chunker/find_related.rb
- resources/asciidoctor/lib/chunker/link.rb
- resources/asciidoctor/lib/chunker/nav.rb
- resources/asciidoctor/lib/docbook_compat/convert_document.rb
- resources/asciidoctor/spec/chunker_spec.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Adds the `navheader` and `navfooter` elements to the output of
`--direct_html`.
> Add navheader and navfooter to direct_html

- integtest/html_diff
Docbook wraps `<em>` tags in `<span class="emphasis">`. Asciidoctor
doesn't. We don't need the it. This ignores it as part of the diffs.
> Ignore difference between <em> rendering

- integtest/html_diff
Docbook links with `<a class="link"` when linking from one page of a book
to another. Asciidoctor emits `<a class="link"`. Both look fine. This
ignores the difference.
> Ignore direct_html's different link class

- resources/asciidoctor/lib/docbook_compat/convert_listing.rb
- resources/asciidoctor/lib/docbook_compat/extension.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Asciidoctor doesn't *quite* render callout lists the same way that
docbook does. So we have to overwrite that too!
> Fix callout lists in direct_html

- resources/asciidoctor/lib/chunker/extension.rb
- resources/asciidoctor/spec/chunker_spec.rb
This fixes up the destination of the links producted by `--direct_html`
so they include the page that contains thing being linked to.
> Fixup cross references in direct_html

- integtest/spec/helper/dsl/convert_single.rb
- integtest/spec/helper/dsl/file_contexts.rb
- integtest/spec/single_book_spec.rb
- resources/asciidoctor/lib/chunker/extension.rb
- resources/asciidoctor/lib/docbook_compat/convert_document.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
`--direct_html` was producing incorrect `<title>`s on subpages. But it
worked in the unit tests! I tracked down the fix to us overwriting the
wrong attribute to force the subpage's title. But again, no luck testing
it in the unit tests.
So this starts testing direct_html in an integration test and adds all
of the right things to catch this.
> Fix title on direct_html's subpages

- integtest/spec/all_books_change_detection_spec.rb
- lib/ES/Book.pm
Adds the version drop down to the raw docs so they show up in the
preview. It'd be nice if the templating system did this on the fly, but
that is a problem for another day. This is a simple solution that fixes
the preview so we can keep doing other things.
> Add version drop downs to raw

- resources/asciidoctor/lib/chunker/breadcrumbs.rb
- resources/asciidoctor/lib/chunker/extension.rb
- resources/asciidoctor/lib/chunker/link.rb
- resources/asciidoctor/spec/chunker_spec.rb
Adds the breadcrumbs at the top of the page to `--direct_html`.
> Add breadcrumbs to direct_html

- resources/asciidoctor/lib/chunker/nav.rb
- resources/asciidoctor/spec/chunker_spec.rb
It turns out that docbook doesn't add the `index.html` as a "prev" page
in docbook's nav even though it *does* add it as `<link rel="prev"`.
Funny thing, that. Anyway, this makes us line up with docbook.
> Drop index from direct_html's nav

- resources/asciidoctor/lib/docbook_compat/convert_outline.rb
- resources/asciidoctor/lib/docbook_compat/extension.rb
- resources/asciidoctor/spec/chunker_spec.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
This enables rendering subsections in the table of contents in a way
that mimicks docbook. In doing so it fixes a crash when trying to
convert chunked books that have subsections caused by the chunker not
seeing the subsections in the toc. This adds them so it is happy.
> Render deep toc in --direct_html

- resources/asciidoctor/lib/docbook_compat/convert_links.rb
- resources/asciidoctor/spec/chunker_spec.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Stops us from ignoring explicit link text like `<<target,override text>>`
on cross references in direct_html. I was so concerned with getting he
text right in the complex cases I didn't do the obvious case where it is
specified....
> Fix override text on xref in direct_html

- resources/asciidoctor/lib/docbook_compat/convert_lists.rb
- resources/asciidoctor/lib/docbook_compat/convert_open.rb
- resources/asciidoctor/lib/docbook_compat/extension.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
List items always have text and *sometimes* have complex content. If the
list item has complex content then docbook wraps the text in
`<p class="sempara>`. We should do that too for compatibility.
> Improve list rendering in direct_html

- integtest/spec/all_books_spec.rb
- lib/ES/Book.pm
Removes non-live versions from the version drop downs. We still publish
the non-live versions but we don't want to point folks to them
accidentally.
Closes #1431
> Remove non-live versions from the drop downs

- README.asciidoc
The Elastic doc toolchain migrated from the original Python Asciidoc
to Asciidoctor, a re-implementation in Ruby (tracked in #505).
During the migration, the README referenced both Asciidoc and
Asciidoctor. After the migration, #1414 removed all references to the
original Asciidoc and standardized the README on Asciidoctor. However, I
found one lingering reference to the days when both tools were being
used.
Remove a reference to the obsolete `--asciidoctor` command line option
and a note about Asciidoc vs Asciidoctor.
> Remove lingering Asciidoc (Python) reference from README

- conf.yaml
~Blocked by https://github.com/elastic/apm-agent-java/pull/948~.
> APM Agent Java: Build changelog on 1.x

- integtest/spec/all_books_spec.rb
- lib/ES/Book.pm
We use perl code to hack the book's title into the table of contents.
Because we like it there. *Technically* we could use an Asciidoctor
customerization to do it in direct_html but in the spirit of keeping the
changes as small as possible I've just fixed the perl code to tolerate
direct_html output.
> Tolerate direct_html's toc

- integtest/spec/all_books_spec.rb
- lib/ES/Book.pm
- resources/web/docs_js/utils.js
This adds an "other versions" link to the versions drop downs if we
stripped any versions from the drop down because they aren't "live". We
remove non-"live" versions from the drop down because we don't want
folks accidentally picking up an old version and because the list just
gets too long with all the versions listed. But we still publish all the
old versions in case some unfortunate soul is stuck on that version.
This adds an "other versions" option to the versions drop down so those
folks can find their version.
> Add "other versions" link to versions drop down

- integtest/html_diff
- resources/asciidoctor/lib/docbook_compat/convert_lists.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Docbook adds `class="simpara"` all over the place but we don't use the
class. So this ignores it in our diff generater and drops it from the
`--direct_html` implementation.
> Drop simpara from direct_html

- resources/asciidoctor/lib/docbook_compat/extension.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
When an admonition has blocks inside it docbook doesn't wrap them all in
a `<p>` tag. But when it is doesn't have blocks and just has some text
then it *does* wrap the text in the `<p>` tag. So do that too.
> Fix direct_html's complex admonitions

- resources/asciidoctor/lib/docbook_compat/convert_table.rb
- resources/asciidoctor/lib/docbook_compat/extension.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Asciidoctor's default able implementation doesn't line up with
docbook's. So we're going to have to customize it! This adds a very
basic table implemenation that works for the getting started books. And
probably quite a few others. But it is only a start! Tables can get
pretty intricate. We'll get there.
> Add basic table implementation to direct_html

- integtest/html_diff
- resources/web/style/img.pcss
When we make a screenshot `--direct_html` emits a different class. It is
pretty simple to update the css to pick that class up. Much simpler than
making `--direct_html` emit the docbook classes. So this updates the
styles to render the new class and the html diff tool to ignore the
difference in classes.
> Update styles for direct_html's screenshots

- integtest/html_diff
Cleans up the html diff implementation's class handling a little:
1. Change one last class for screenshots
2. Always sort the class list. This came up when handling screenshots
but feels pretty generate.
3. Always remove empty class lists. This came up a while ago but feels
like something I should handle more generally.
> Clean up html diff classes some more

- conf.yaml
As titled, https://github.com/elastic/elasticsearch-js/pull/1011 contains all the doc examples.
Which one should I merge first?
> Added elasticsearch-js doc examples configuration

- lib/ES/Util.pm
- resources/asciidoctor/lib/chunker/extra_docinfo.rb
- resources/asciidoctor/lib/docbook_compat/convert_document.rb
- resources/asciidoctor/lib/docbook_compat/extra_docinfo.rb
- resources/asciidoctor/lib/docbook_compat/munge_body.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
We use "extra" header elements on the page to convey things like "this
version is out of date" or "this version has yet to be released".
`--direct_html` was ignoring those extra headers. This adds support for
it.
> Add extra header support to direct_html

- lib/ES/Util.pm
- resources/asciidoctor/lib/docbook_compat/convert_document.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Implements the `noindex` flag in direct html which causes us to add a
header to the page that asks robots not to index or follow the page.
Docbook has this so we should too.
> Implement noindex in direct_html

- resources/web/style/docbook.pcss
- resources/web/style/list.pcss
Sometimes docsbook spits out `<p>` tags with `class="simpara"` and
sometimes it doesn't. I can't quite figure out the rules, but I'd like
it not to matter. And it *mostly* doesn't. There was just one css rule
that used `simpara` and of course it wasn't commented. But I've reverse
engineered it: it is designed to make lists that directly follow
paragraphs that are *inside* of `<dd>` or `<li>` closer to the
paragraph. Without it the lists look "lonely" and separate from the
paragraph.
So I replaced it with a css rule that explicitly looks for `<dd>` and
`<li>`.
> Replace "simpara" style with one more explicit

- lib/ES/Util.pm
- resources/asciidoctor/lib/chunker/breadcrumbs.rb
- resources/asciidoctor/lib/chunker/extension.rb
- resources/asciidoctor/lib/chunker/extra_docinfo.rb
- resources/asciidoctor/lib/chunker/link.rb
- resources/asciidoctor/lib/docbook_compat/convert_document.rb
- resources/asciidoctor/spec/chunker_spec.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Docbook adds the version of the book to some title attributes on some
links. This teaches `--direct_html` to add them there too.
> Add version to some titles in direct_html

- integtest/html_diff
- resources/asciidoctor/lib/docbook_compat/convert_lists.rb
- resources/asciidoctor/lib/docbook_compat/extension.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Implement docbook compatibility for direct_html's description lists.
This should be enough to convert our glossary to direct_html.
This also removes the double trailing new lines from `</p>`. Asciidoctor
already seems to add a newline for those.
This also cleans up a bug in list rendering that I encountered while
doing real world testing of the description lists: if you form an
ordered list with `1.` instead of `.` then it wasn't getting the
override. This fixes that.
This looks to be enough to unblock #1494.
> Fix compatibility for direct_html's dl

- shared/attributes.asciidoc
The :xpack-ref: shared attribute is defined in https://github.com/elastic/docs/blob/master/shared/attributes.asciidoc such that it equates to the Stack Overview.  This helped avoid broken links when the Stack Overview was first created.
However, there are places in the Cloud documentation where we need to be able to refer to old books as well as new ones. This PR sets the :xpack-ref: attribute to the final 6.2 version for the X-Pack Reference book so those old references can still work.
> Differentiate X-Pack Reference and Stack Overview

- integtest/html_diff
- resources/web/style/img.pcss
`--direct_html` produces html for images with titles that is fairly
different than what docbook makes. But with a little CSS this makes them
*look* the same. And with a little more python code this makes the diff
tool ignore the changes to the html.
> Clean up direct_html difference in titled images

- integtest/html_diff
There were some cases where we Asciidoctor and Docbook don't agree on
the classes on links. Those classes don't make and visual difference so
this ignores them. We actually already *tried* to ignore them, but we
didn't do it all the time.
> Be slightly less picky in normalizing links

- resources/asciidoctor/lib/chunker/extension.rb
- resources/asciidoctor/lib/chunker/footnotes.rb
- resources/asciidoctor/spec/chunker_spec.rb
- resources/web/docs_js/index.js
Asciidoctor allows you to make footnotes and we use them. This makes
sure that they end up on the same page as they are declared. Without it
the footnotes end up on the "index" page which is super confusing.
NOTE: I'm note really making an effort to make this line up perfectly
with docbook's output. These *should* be rare enough that I can verify
them by hand. We really don't use *that* many footnotes.
> Properly chunk footnotes in direct_html

- resources/asciidoctor/lib/docbook_compat/extension.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
This fixes the wrapper class on level 3 sections in direct html.
Required for #1495.
> Properly handle level 3 sections in direct html

- resources/asciidoctor/lib/docbook_compat/convert_table.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
This adds support for complex content inside of tables like lists and
things to `--direct_html`. Without this change complex content would
cause us to crash!
Required for #1505
> Handle complex content in tables in direct_html

- resources/asciidoctor/lib/docbook_compat/convert_listing.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
When a code listing has a title docbook wraps it in `<p><strong>`. So
should we.
> Render listing titles in direct_html

- resources/asciidoctor/lib/docbook_compat/convert_dlist.rb
- resources/asciidoctor/lib/docbook_compat/convert_lists.rb
- resources/asciidoctor/lib/docbook_compat/extension.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
This adds docbook-style horizontal dlist support to direct_html.
Required for #1506.
> Add support for horizontal dlists to direct_html

- resources/asciidoctor/lib/docbook_compat/convert_lists.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
This fixes how we handle two level lists in `--direct_html` so they are
rendered in a docboook compatible way.
> Handle two level lists in direct_html

- resources/asciidoctor/lib/docbook_compat/extension.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
You can add a title to admonitions with
```
[WARNING]
.Title goes here
--
Content goes here
--
```
This makes direct_html produce the same output as docbook for those
titles.
Required for #1506.
> Support title on admonitions in direct_html

- integtest/html_diff
Docbook spits out empty `<p>` tags sometimes. I'm not sure why. But I'm
95% sure we don't want them. Sure enough that we can ignore them in the
diff and clean them up if anyone complains later.
> Ignore empty <p> when comparing direct_html

- integtest/html_diff
When I built the diff for logstash I discovered a few small tweaks I
could make to the diff algorithm:
1. Totally ignore any "type" attributes on `ul` and `li` because we
override the type in css.
2. Ignore "double wrapping" of `<code>` tags that docbook can sometimes
make.
Required for #1512
> Tweak diff algorithm for direct_html

- resources/asciidoctor/lib/docbook_compat/convert_listing.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
When you declare a code listing without a language docbook renders it
quite differently than one *with* a language. This makes direct_html do
the same.
> Fix rendering of no lang listings in direct_html

- resources/asciidoctor/lib/chunker/convert_outline.rb
- resources/asciidoctor/lib/chunker/extension.rb
- resources/asciidoctor/lib/docbook_compat/convert_outline.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Docbook uses the `role=exclude` mechanism to exclude pages from the
table of contents. This makes direct_html do the same.
> Don't include "role=exclude" entries from the toc

- resources/asciidoctor/lib/docbook_compat/extension.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
We've customized docbook to add a spec "tag" to the title of pages that
are marked with `role=xpack`. This implements that customization in
direct_html. It was way, way, way, way easier than the docbook
customization.
> Add support for xpack tag in direct_html

- resources/asciidoctor/lib/docbook_compat/extension.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
It is possible to declare an id for a paragraph like so:
```
[[foo]]
Words in the paragraph.
```
Docbook renders this like:
```
<p><a id="foo"></a>Words in the paragraph</p>
```
So we should too.
> Render ids for paragraphs in direct_html

- conf.yaml
With the release of 7.5.0, the 7.4.x branches passed their maintenance date:
https://www.elastic.co/support/eol
This retires the 7.4 branch from the list of "live" Stack release branches in our docs.
I believe this is our first time doing this so let me know if we want to formalize the process a bit more. I see benefits in both keeping the branch around longer _or_ updating the list as part of release (or shortly after).
Appreciate any feedback!
> Retire 7.4 from the live stack releases

- README.asciidoc
- resources/asciidoctor/lib/docbook_compat/convert_outline.rb
- resources/asciidoctor/lib/docbook_compat/extension.rb
- resources/asciidoctor/lib/docbook_compat/titleabbrev_handler.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
In docbook we can abbreviate the title of a section in the table of
contents by doing something like this:
```
== Intro to XYZ
++++
<titleabbrev>Intro</titleabbrev>
++++
Words.
```
This is *very* docbook. `++++` mean "pass this output directly to the
generated doc" and `<titleabbrev>` is a docbook element.
This change adds support for abbreviating a title of a section in the
table of contents when using `--direct_html` using the following syntax:
```
[id=intro_to_xyz,titleabbrev=Intro]
== Intro to XYZ
Words.
```
It is both shorter and more AsciiDoc friendly. It isn't compatible with
docbook though.
This change *also* adds support for identifying the docbook-style title
abbreviate commands when running with `--direct_html` and having those
set the title abbreviation. In other words: you …
> Add support for abbreviated titles in direct_html

- integtest/html_diff
- resources/asciidoctor/lib/chunker/breadcrumbs.rb
- resources/asciidoctor/lib/chunker/link.rb
- resources/asciidoctor/lib/chunker/nav.rb
- resources/asciidoctor/lib/docbook_compat/extension.rb
- resources/asciidoctor/spec/chunker_spec.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
- resources/asciidoctor/spec/edit_me_spec.rb
Docbook adds "Appendix A." to the front of the title for and appendix.
And references to that apendix. We should do the same. Except we can't
*quite* get it. We do, instead "Appendix A:". This is close enough.
> Handle title captions in direct_html

- resources/asciidoctor/lib/docbook_compat/convert_listing.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
This adds support for `id`s on listing block and adds a missing `.` to
the end of the title.
> Improve listing blocks in direct_html

- resources/asciidoctor/lib/docbook_compat/extension.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Docbook bumps the `<h` tag levels in level 0 section and their children.
But *not* the their grand children. Which is strange. But we're
emulating docbook. So this does that too. Oh yeah, and only "bar" level
0 sections count. If you make a level 0 section an appendix then no bumping.
> Implement strange h level bumping in direct_html

- resources/asciidoctor/lib/docbook_compat/convert_admonition.rb
- resources/asciidoctor/lib/docbook_compat/extension.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Our custom "experimental" and "beta" admonitions have default text if
you don't supply any. This adds that default text to direct_html and
cleans up the tests around admonitions a bit, including adding tests for
our custom admonitions.
> Support default admonition text in direct_html

- integtest/html_diff
direct_html renders partintro blocks slightly differently than docbook
but they aren't visually distinct so we can ignoree that difference.
This teaches the html_diff tool to ignore it.
> Ignore difference in direct_html's partintro

- integtest/html_diff
- resources/asciidoctor/lib/docbook_compat/convert_table.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Docbook wraps tables with titles differently than tables without. This
adds that wrapping to direct_html.
> Handle tables with titles in direct_html

- integtest/spec/all_books_spec.rb
- lib/ES/Book.pm
This removes the `edit` links from versions of books that aren't "live"
because, for the most part, we don't want folks opening PRs against
them. I mean, we'd *prefer* folks open PRs against the master branch,
but that isn't really a simple thing to do when fixing docs so we're
pretty happy with whatever. But we'd really prefer PRs to target live
branches.
> Remove edit links form non-live versions

- resources/asciidoctor/lib/docbook_compat/convert_outline.rb
- resources/asciidoctor/lib/docbook_compat/titleabbrev_handler.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
This reworks `<titleabbrev>` handling in direct_html so it works for
link targets as well. It turns out asciidoctor has a built in thing for
this called `reftext`. So we just use it.
> Rework titleabbrev handling in direct_html

- resources/asciidoctor/lib/docbook_compat/convert_table.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Docbook handles `[width=50%]` on tables by adding the width to the
`<table>` tag. So we should too, just to be even.
> Handle "width" in tables in direct_html

- integtest/spec/all_books_spec.rb
- lib/ES/Book.pm
- resources/web/docs_js/index.js
- resources/web/docs_js/utils.js
- resources/web/style/toc.pcss
When you click the "other versions" option it used to take you to the
version link farm page. While it is nice to get all the versions this
loses the one of the nice behaviors of the versions drop down, namely
that it checks if the page you are on exists in the target version and
drops you right on that page if it does.
This change stops it from sending you to the link farm and instead
un-hides another drop down that contains *all* of the versions.
Relates to #1419 and #1536.
> Refine "other versions" behavior

- conf.yaml
Reverts elastic/docs#1535. It was a mistake.
> "Re-adds the MS31 build to ESS and Heroku books""

- integtest/html_diff
direct_html renders examples slightly differently than docbook but they
don't make any visual difference. So we ignore the difference.
> Ignore difference between examples in direct_html

- resources/asciidoctor/lib/chunker/extension.rb
- resources/asciidoctor/lib/docbook_compat/extra_docinfo.rb
- resources/asciidoctor/spec/chunker_spec.rb
* Pass the *caption* of the title into subpages. This adds things like
"Appendix A:" to the front of pages for the appendix.
* Remove the title-separator from subpages so their `<title>` renders
properly. Now we only use the separator for the *main* page.  Without
this `Appendix A: Foo` would get rendered as `Appendix A` because the
`Foo` part would be considered a subtitle.
> Fix two connected issues with title in direct_html

- resources/asciidoctor/lib/care_admonition/extension.rb
- resources/asciidoctor/lib/docbook_compat/convert_admonition.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Elastic's admonition extensions can be used inline with something like:
```
The foo is experimental::[some warning text].
```
This adds support for that to direct_html.
> Handle inline admonitions in direct_html

- resources/asciidoctor/lib/docbook_compat/titleabbrev_handler.rb
- resources/asciidoctor/lib/scaffold.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
You can use an attribute in a `titleabbrev` like so:
```
++++
<titleabbrev>{security}</titleabbrev>
++++
```
The `{security}` thing *should* get replaced with the attribute value.
This does that in direct_html and solves a *ton* of problems converting
logstash (#1512).
> Handle attributes in `titleabbrev` in direct_html

- resources/asciidoctor/lib/docbook_compat/convert_links.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
When you make a cross reference to a section who's title contains html
we were generating invlid html. For example, a link to this:
```
[[foo]]
== `foo`
```
Would come out with `<a title="<code ....>foo</code>"`. That ain't
right. This strips the html which is *super* helpful for converting
logstash (#1512).
> Clean xref title in direct_html

- resources/asciidoctor/lib/docbook_compat/convert_links.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
When you reference something like
```
== Section heading
This
[[privileges-list-cluster]]
page has moved.
```
direct_html *was* producting an empty string for the default text while
docbook was using the section heading as the default text. This fixes up
direct_html to match docbook.
> Fix ref text for inline anchors in direct_html

- resources/asciidoctor/lib/docbook_compat/convert_links.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
When you link to a section that doesn't have a title at all we crashed!
Crash bad! No crash! This skips the `title` tag if the section we link
to doesn't have a title.
> Handle missing titles in direct_html

- resources/asciidoctor/lib/docbook_compat/extension.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
direct_html's implementation of `[sidebar]` produced an "empty" title if
the sidebar didn't have a title but docbook skipped it. This skips the
title to line up with docbook.
> Support title-less sidebar in direct_html

- integtest/spec/all_books_spec.rb
- lib/ES/Book.pm
I added "out of date" to the version drop down if you are on a page for
a non-live version of the docs but it turns out we're adding a heading
to the docs that says exactly that so this is duplicate information and
it can be confusing.
> Drop "out of date" from version drop down

- resources/asciidoctor/lib/docbook_compat/convert_table.rb
- resources/asciidoctor/lib/docbook_compat/convert_table_cell.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Adds support for `colspan` and `rowspan` to direct_html's tables.
> Add support for colspan and rowspan to direct_html

- resources/asciidoctor/lib/docbook_compat/convert_listing.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
When the title of a listing ends in a `:` we shouldn't add a `.` to it
because docbook doesn't and because it looks silly.
> Don't add . to title ending in : in direct_html

- integtest/html_diff
- resources/asciidoctor/lib/docbook_compat/convert_quote.rb
- resources/asciidoctor/lib/docbook_compat/extension.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Docbook renders attributed quotes radically differenly than asciidoctor.
This gets direct_html to look like docbook.
> Support quotes in direct_html

- resources/asciidoctor/lib/docbook_compat/convert_dlist.rb
- resources/asciidoctor/lib/docbook_compat/convert_table.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
"horizontal" style descriptions lists with a title need to be rendered
*just* like a table with a title. This does that, mostly by leaning on
the table rendering code.
This is required for logstash (#1512).
> Handle horizontal dlist with title in direct_html

- resources/asciidoctor/lib/docbook_compat/convert_paragraph.rb
- resources/asciidoctor/lib/docbook_compat/extension.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Adds support for titles on paragraphs to direct_html. These are written
like:
```
.Title
Paragraph body.
```
> Handle titles on paragraphs in direct_html

- resources/asciidoctor/lib/care_admonition/extension.rb
- resources/asciidoctor/lib/change_admonition/extension.rb
- resources/asciidoctor/lib/docbook_compat/convert_admonition.rb
- resources/asciidoctor/spec/care_admonition_spec.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
- resources/asciidoctor/spec/elastic_compat_preprocessor_spec.rb
This handles change admonitions and cleans up the care admonitions to
look like the change admonitions. For the most part that means moving
the "default text" of the care admonitions into the care admonition
extension itself. This will change the generated docbook xml but it
*shouldn't* change the resulting html.
> Handle change admonitions in direct_html

- resources/asciidoctor/lib/docbook_compat/convert_table.rb
- resources/asciidoctor/lib/docbook_compat/convert_table_cell.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Asciidoctor supports explicitly setting the format on table cell so we
should respect that in direct_html. This sets up direct_html to mimic
how it all turns out in docbook.
> Support more table formatting in direct_html

- integtest/html_diff
- resources/asciidoctor/lib/change_admonition/extension.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
This fixes some small errors with direct_html's handling of inline
change admonitions that came up because I didn't have a great example to
compare against when I wrote them. I found an example though! This adds
a missing space between some classes, adds some more text to the
message, and fixes up the diff tool to ignore a small diff that isn't
visible.
> Clean up direct_html's inline change admonitions

- resources/asciidoctor/lib/docbook_compat/convert_table.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Adds support for specifying he id on a table in a docbook compatible way
to direct_html. Required by the painless reference (#1562).
> Support ids on tables in direct_html

- lib/ES/Book.pm
This updates the default notice for versions older than current. With this change, we do not have to override the default notice in every OOM version, but we *will* have to override it for the maintenance version of the previous minor (currently 6.8).
That's simpler than having to do that for every OOM version, so I think it's a win. At some point, we could automatically apply the correct notice to "live" versions that aren't current and eliminate even  that manual step.
> Revised  default notice for older versions.

- resources/asciidoctor/lib/chunker/extension.rb
- resources/asciidoctor/lib/chunker/extra_docinfo.rb
- resources/asciidoctor/lib/docbook_compat/convert_document.rb
- resources/asciidoctor/lib/docbook_compat/convert_links.rb
- resources/asciidoctor/lib/docbook_compat/extension.rb
- resources/asciidoctor/lib/strip_tags.rb
- resources/asciidoctor/spec/chunker_spec.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
If a page has extra html in the title we shouldn't add it to a
`title=""` tag because it'd be invalid. This stips it.
> Strip html from titles in direct_html

- resources/asciidoctor/lib/docbook_compat/convert_dlist.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
This implements glossary style dlists in direct_html which is required
to convert the Elasticsearch reference (#1566).
> Implement glossary style dlists in direct_html

- integtest/html_diff
Fixes a bug in the diff tool that causes it to crash when there is an
anchor tag inside a table without an id. Ooops.
> Fix error in diff tool

- Dockerfile
- integtest/html_diff
This ignores `<span class="quote">` in the direct_html diffs. They don't
render differently and Asciidoctor doesn't make them so I don't believe
they are worth looking at.
> Ignore funny quote in direct_html diff

- resources/asciidoctor/lib/docbook_compat/convert_admonition.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Adds support for ids on admonitions to direct_html in a way that lines
up with docbook. Required for the plugins and integrations guide
(#1564).
> Support ids on admonitions in direct_html

- resources/asciidoctor/lib/chunker/extension.rb
- resources/asciidoctor/spec/chunker_spec.rb
Strips html from the `<link>` tag in the headings generated by direct
html. *and* squeezes extra spaces out of the titles as a side effect.
Required for .NET client (#1575).
> Clean up html in meta links in direct_html

- Dockerfile
We need at least 1.21.1 to fix
https://blog.npmjs.org/post/189618601100/binary-planting-with-the-npm-cli
. apt-get doesn't let us say "more than 1.21.1" so we have to pin it
*to* 1.21.1.
> Force updating to a new version of yarn

- resources/asciidoctor/lib/docbook_compat/convert_listing.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
When you write a callout list with duplicate entries we'd previously
duplicate a bunch of the callouts in strange ways. Both docbook and
direct_html had different, strange renderings. This changes direct_html
to have a fairly sane rendering. Say you write this, like we do in the
Elasticsearch reference:
```
"tokens" : [ {
"token" : "detail",
"start_offset" : 0,
"end_offset" : 8,
"type" : "<ALPHANUM>",
"position" : 0,
"keyword" : false <1>
}, {
"token" : "output",
"start_offset" : 9,
"end_offset" : 15,
"type" : "<ALPHANUM>",
"position" : 1,
"keyword" : false <1>
} ]
```
The duplicate `<1>` elemenets now get a single callout which looks sort
of like:
```
<1> Output only "keyword" attribute, since specify "attributes" in
the request.
```
This is *much* cleaner than how docbook does it and …
> Improve rendering of callout lists in direct_html

- resources/asciidoctor/lib/docbook_compat/convert_sidebar.rb
- resources/asciidoctor/lib/docbook_compat/extension.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Adds support for rendering the id on a sidebar in a docbook-like way to
direct_html.
> Support id on sidebar in direct_html

- shared/notices/README.txt
- shared/notices/page_header-OOM.html
- shared/notices/page_header-maintenance.html
Updated the boilerplate notices to match with the changes discussed in https://github.com/elastic/docs/issues/1419 and https://github.com/elastic/docs/pull/1528.
> [DOCS] Revised notices.

- integtest/html_diff
Ignores two tags from in the html_diff. One of them docbook adds but
we don't need and another one asciidoctor adds that we're ok with it
adding.
> Ignore unneeded tags in diffs for direct_html

- resources/asciidoctor/lib/docbook_compat/convert_lists.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
This makes direct_html's rendering of the titles for ordered and
unordered lists line up with docbook's rendering.
> Fixup the list titles in direct_html

- resources/asciidoctor/lib/docbook_compat/convert_table.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
We add the title of a table to the table's `summary` tag to line up with
docbook. Docbook also strips the html out of the summary because if you
don't do that you can generate invalid html. This makes direct_html
strip the html as well.
> Clean html from the table summary in direct_html

- integtest/html_diff
Docbook outputs `align=middle` and `align=center` for images but that is
how images look for us by default anyway and asciidoctor doesn't produce
those attributes. So this ignores them.
> Ignore some defaults in direct_html comparison

- resources/web/template.html
This adds a `<meta name="robot"` tag specifically for site search so we
*always* crawl the site, even if we've instructed other robots not to.
We'll use site search's customization to downplay the results for old
docs rather than excluding them entirely.
Here are the docs for the robots tag we use:
https://swiftype.com/documentation/site-search/crawler-configuration/meta-tags#swiftbot
> Add a robots tag for Elastic Site Search

- conf.yaml
- doc_build_aliases.sh
direct_html is faster and more customizable. We're switching all of our
docs to it.
> Switch cloud-on-k8s docs to direct_html

- resources/asciidoctor/lib/docbook_compat/convert_table.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Apparently docbook only uses the formal "table" wrapper when there is a
title and uses the informal "informaltable" wrapper even when the table
has an id. direct_html was using the formal wrapper when it *either* had
an id or a title. This fixes that.
Required by the Elaticsearch reference (#1566).
> Make direct_html tables a little more docbook

- resources/asciidoctor/lib/chunker/extra_docinfo.rb
- resources/asciidoctor/spec/chunker_spec.rb
We have `<link rel="next"` and `prev` and `up`, all of which have the
title of the target section. If the titles of those sections have a
quote in them we were emitting invalid html. This fixes that by escaping
the quotes as `&quot;`.
> Escape quotes in direct_html sibling links

- integtest/html_diff
Ignores the difference between `<p class="exclude exclude">` (docbook's
output) and `<p>` (asciidoctor's output). The `exclude` role doesn't
have any visual effect. And duplicate classes *never* have any visual
effect.
Required by the Elasticsearch reference (#1566).
> Ignore a few more differences in direct_html

- integtest/html_diff
- resources/asciidoctor/lib/docbook_compat/convert_floating_title.rb
- resources/asciidoctor/lib/docbook_compat/convert_inline_quoted.rb
- resources/asciidoctor/lib/docbook_compat/convert_quote.rb
- resources/asciidoctor/lib/docbook_compat/extension.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Sometimes we declare the xpack tag inline like so:
```
[float]
=== [xpack]#Foo#
```
This renders the xpack tag in those cases.
> Support inline xpack declaration in direct_html

- resources/asciidoctor/lib/docbook_compat/convert_admonition.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Docbook puts ids *inside* the title of an admonition if there is a
title. This does that too.
> Move id for admonitions in direct_html

- resources/asciidoctor/lib/docbook_compat/convert_links.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
When we link to an appendix we docbook adds `Appendix A,` to the text.
This makes direct_html do that too.
> Decorate link to appendix in direct_html

- conf.yaml
Since we don't intend to update these docs, we don't want folks to open PRs against them.
Related to: https://github.com/elastic/docs/pull/1533
> Set Legacy & translated docs to private to remove edit links.

- conf.yaml
> Switch legacy watcher reference to direct_html

- integtest/html_diff
- resources/asciidoctor/lib/docbook_compat/convert_example.rb
- resources/asciidoctor/lib/docbook_compat/extension.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Formal examples were rendering their titles in a docbook incompatible
way. This fixes that.
> Fix examples in direct_html

- resources/asciidoctor/lib/docbook_compat/convert_paragraph.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
Docbook copies the `role` on paragraphs into the class. This implements
that in direct_html.
Required for beats.
> Support roles on paragraphs in direct_html

- integtest/html_diff
Docbook doesn't add a `px` that direct_html does add. We're quite happy
to have the `px` but we don't need to see it on every time that gets it.
Thus, we ignore it in `html_diff`.
> Ignore missing px in direct_html diff

- conf.yaml
Updates the Beats documentation to pull output doc source in 7.x and 7.5 from libbeat/outputs
> Update exclude paths for output docs

- resources/asciidoctor/lib/docbook_compat/clear_cached_titles.rb
- resources/asciidoctor/lib/docbook_compat/convert_admonition.rb
- resources/asciidoctor/lib/docbook_compat/extension.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
When a section or a floating title doesn't have an id asciidoctor
generates one. When that section includes an admonition it *was*
included in the generated id. Docbook also generates ids but doesn't
include the admonition, which makes a ton of sense. So this modifies
direct_html not to generate the admonition into the id. *how* we do that
is a little complex because of the extension points that asciidoctor
gives us:
1. If we're generating an admonition inside of a section that doesn't
yet have an id then return an empty string. This should make the
admonition a noop when generating the title used to generate the
automatic id and *only* then. All other times the section has an id.
2. Before actually converting the document to html we clear that cached
copy of the generated title. Now that …
> Drop admonitions from generated ids in direct_html

- resources/asciidoctor/lib/docbook_compat/convert_floating_title.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
direct_html's floating titles were rendering classes *outside* of the
tag. Oops. This fixes that.
> Fix a bug in direct_html' floating titles

- integtest/spec/all_books_spec.rb
- integtest/spec/helper/console_alternative_examples.rb
- integtest/spec/single_book_spec.rb
- resources/asciidoctor/lib/docbook_compat/convert_listing.rb
- resources/asciidoctor/lib/open_in_widget/extension.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
- resources/asciidoctor/spec/open_in_widget_spec.rb
This adds support for examples in alternative languages to direct_html.
The alternative examples plugin works by adding a bunch of extra
listings and callout lists to the parse tree. This makes sure that they
are all converted properly, including updating the integration test for
them to work with `--direct_html`.
> Support alternative examples in direct_html

- resources/asciidoctor/lib/copy_images/copier.rb
- resources/asciidoctor/lib/copy_images/extension.rb
- resources/asciidoctor/spec/copy_images_spec.rb
This fixes our image copier to properly copy images referenced by
`imagesdir`. We *were* copying the images correctly be we weren't
copying them to the right spot. This is because our image copier does a
`find | grep <path>` to find the image for compatibility with the old
`a2x` utility that we used to build the asciidoc before asciidoctor. We
just weren't getting the paths right.
Here is some documentation for the attribute:
https://asciidoctor.org/docs/user-manual/#setting-the-location-of-images
> Fix support for imagesdir

- resources/asciidoctor/lib/docbook_compat/convert_admonition.rb
- resources/asciidoctor/lib/docbook_compat/convert_document.rb
- resources/asciidoctor/lib/strip_tags.rb
- resources/asciidoctor/spec/docbook_compat_spec.rb
This removes admonitions from the `<title>` and `title=""` tags. It does
this by hacking it out with regexes which is pretty lame, but
asciidoctor doesn't give us another extension point.
> Drop admonitions from titles

- Dockerfile
- integtest/spec/single_book_spec.rb
When attempting to switch some Chinese books we were getting errors that
looked like:
```
cli/options.rb:87:in `encode': "\xE8" from ASCII-8BIT to UTF-8
```
This was caused by ruby thinking that the cli was in ascii instead of
utf8 but perl encoding stuff in utf8. Ruby was doing that, helpfully,
because the shell's locale *was* `POSIX` because that is the default in
minideb if you don't run `locale-gen`.
So, interestingly, the fix for this is in the `Dockerfile`. We have to
enable the `en_US.UTF-8` locale. Now ruby reads the CLI as UTF-8.
> Fix locale errors in direct_html

- conf.yaml
The ECK project needs to change the "current" version to a new branch.
Thank you
> Add ECK 1.0-beta branch, make it the current

- conf.yaml
This PR exclude `1.0-beta` from `shared/versions/stack/7.x.asciidoc`
> Exclude ECK 1.0-beta from shared/versions/stack/7.x.asciidoc

- conf.yaml
- doc_build_aliases.sh
We're moving to a more sustainable way of maintaining current Docker image info for ECE that requires pulling from the `master` branch of the elastic/cloud-assets repo. This PR makes the necessary doc build updates.
> Add cloud-assets to conf.yaml and build aliases for ECE

- integtest/spec/all_books_change_detection_spec.rb
- integtest/spec/all_books_spec.rb
- integtest/spec/helper/book.rb
- integtest/spec/preview_spec.rb
- lib/ES/Util.pm
Switch the "all books" integration tests to direct_html now that almost
all of the books have switched.
> Switch "all books" integ tests to direct_html

- README.asciidoc
- resources/web/style/video.pcss
- resources/web/styles.pcss
Adds documentation on how to use videos and a little style.
Closes #995
> Explicitly support video

- resources/asciidoctor/spec/chunker_spec.rb
Drops some "funny" `gsub` calls from the chunker test in favor of being
more explicit.
> Clean up the chunker test

- conf.yaml
- doc_build_aliases.sh
- shared/attributes.asciidoc
Related to https://github.com/elastic/stack-docs/pull/734
This PR adds a machine learning book to the conf.yaml and adds the "docbldml" build alias.
At this time, the machine learning content also appears in the Stack Overview, since we want to transition gradually to avoid broken links.
Preview:
* http://docs_1662.docs-preview.app.elstc.co/guide/index.html
* http://docs_1662.docs-preview.app.elstc.co/guide/en/machine-learning/index.html
* http://docs_1662.docs-preview.app.elstc.co/guide/en/machine-learning/master/index.html
* http://docs_1662.docs-preview.app.elstc.co/guide/en/machine-learning/7.x/index.html
* http://docs_1662.docs-preview.app.elstc.co/guide/en/machine-learning/7.5/index.html
* http://docs_1662.docs-preview.app.elstc.co/guide/en/machine-learning/7.4/index.html
* …
> Adds machine learning book to builds

- Makefile
- integtest/spec/spec_helper.rb
- resources/asciidoctor/spec/spec_helper.rb
- resources/test/Makefile
- resources/test/matcher/file_exist.rb
This moves the `file_exist` matcher into a place so the Asciidoctor
plugin unit tests and the integration tests can share it.
> Share a test utility

- conf.yaml
With `release-ms-31` going out soon, it's time to get ready to switch the docs builds. 
@elastic/cloud-writers can I get an LGTM for this, please?
> Switch ESS and Heroku docs to MS 31

- conf.yaml
> Drop unused line from conf.yaml

- resources/asciidoctor/.rubocop.yml
- resources/asciidoctor/lib/elastic_compat_preprocessor/extension.rb
- resources/asciidoctor/lib/elastic_compat_tree_processor/extension.rb
- resources/asciidoctor/lib/elastic_include_tagged/extension.rb
This fixes all of the remaining rubocop warnings in our code and removes
the suppresions. The last suppression is for the docbook45 converter
which mostly comes from Asciidoctor's code base and we're in the process
of removing it.
> Fix remaining rubocop

- integtest/spec/helper/dsl.rb
- integtest/spec/helper/dsl/file_contexts.rb
- integtest/spec/spec_helper.rb
- resources/asciidoctor/spec/chunker_spec.rb
- resources/asciidoctor/spec/spec_helper.rb
- resources/test/dsl/file_context.rb
Moves `file_context` into a shared space because we use it in both the
unit tests and integration tests.
> Unify some test dsl

- README.asciidoc
- build_docs.pl
- integtest/spec/all_books_change_detection_spec.rb
- integtest/spec/helper/console_alternative_examples.rb
- lib/ES/Book.pm
- lib/ES/Toc.pm
- lib/ES/Util.pm
- resources/asciidoctor/lib/docbook_compat/titleabbrev_handler.rb
This removes support for building docs without direct_html. You no
longer need to specify `--direct_html` on the command line or
`direct_html` in conf.yaml for it ot build with direct_html.
This doesn't drop the configuration from conf.yaml or the change
tracker or all of the files that we need to build with docbook. We'll do
that in a followup.
> Only build with `--direct_html`

- resources/web/style/table.pcss
Switches the overflow strategy for tables from "always scroll" to
"scroll if needed".
> Vanish ugly grey bars unless needed

- Dockerfile
We don't depend on dockbook any more so we don't need its dependencies.
> Drop docbook dependencies from docker

- lib/ES/Book.pm
Changing the default "old version" banner until @nik9000 merges a change to enable a different default for live versions older than current (actively maintained versions).
Once we rebuild, this will replace the erroneous out of maintenance message on the Cloud docs. OOM stack docs will also get the "milder" message until Nik's fix is merged and this is reverted, but we're okay with that.
> Temporarily change the default banner text for old versions.

- lib/ES/Book.pm
- lib/ES/Repo.pm
- lib/ES/Source.pm
Removes all of the "change tracking" code for `--direct_html`. It is the
default now.
> Remove change tracking code for direct_html
