conf.yaml
This includes:
* New guide for Topbeat
* Version bump for Packetbeat
* New developer guide (in the libbeat repo)
=> Added new entries for the Beats release 1.0.0-beta3

conf.yaml
Adds branches 1.5 and 2.0 for Logstash
=> Add branches for Logstash docs

conf.yaml
Adds the Filebeat book, for now master only.
=> Added filebeat book

conf.yaml
Don't merge it just yet, please. We'll do it shortly before the release.
=> Added Beats docs version 1.0.0-rc1

conf.yaml
We're planning to merge this one tomorrow when we do the repository merges.
Hopefully will result in less of "the Beats team has broken the docs build".
=> Merging the Beats in a single repository

conf.yaml
The repo structure is changing per #1022.
=> Updated paths for x-plugins docs to match the repo reorg.

conf.yaml
Do not merge this PR until the PRs in https://github.com/elastic/beats/issues/970 are also merged.
@clintongormley I don't want this change merged until after the Beats team has reviewed and approved the PRs that restructure the Beats doc.
=> Change chunk level for Beats doc

conf.yaml
New minor version means documentation update.
=> Add Curator 3.5 to the documentation

conf.yaml
It is not the current release, but it needs to be published.
=> Add Curator 4.0

conf.yaml
=> Added Metricbeat to the website

conf.yaml
Changing the current release version to 4.0
=> Curator 4.0 release

conf.yaml
Relates to https://github.com/elastic/elasticsearch/pull/19618
=> Add Java REST client docs

conf.yaml
=> Make 4.1 the current branch of Curator

conf.yaml
@debadair @pickypg Please review. 
Here's what the landing page will look like. I'm just throwing something out there for discussion.
=> Add stack upgrade docs

conf.yaml
=> Add Curator 4.2

conf.yaml
We need to start building the alpha4 docs for Elastic Cloud Enterprise, so switch current to `1.0.0-alpha4` and update the branches.
=> Update conf.yaml for ECE alpha4

conf.yaml
Add 5.1 branches. (Also adds 5.x and 5.0 for the stack upgrade docs).
=> Add 5.1 branches to the doc build

conf.yaml
@debadair @clintongormley I added the 5.2 branches + Heartbeat, our newest Beat. I tried it locally and seems to work fine. Can you review the change, please?
=> Add Heartbeat and the 5.2 branch

lib/ES/Book.pm, resources/asciidoc-8.6.8/lang-zh.conf, resources/web/docs.js, resources/website-l10n.xsl
This change refer to this discussion:
https://github.com/elastic/website-www.elastic.co/issues/1365#issuecomment-272875891
Hi, @clintongormley , please help to review. :)
=> Translate misc files into Chinese

conf.yaml
=> Add 5.0 branch for Curator

conf.yaml
This pull request updates the X-Pack Reference section of the elastic/docs/conf.yaml to include the x-pack-kibana repository in its builds.
=> [DOCS] Add x-pack-kibana to conf.yaml for X-Pack Reference

conf.yaml
This PR attempts to re-add the "docs/en" in the conf.yaml for the X-Pack Reference doc builds
=> [DOCS] Re-add docs/en for X-Pack

conf.yaml
=> Update Curator current to 5.0

conf.yaml
Should fix the broken doc build.
=> fix doc build

conf.yaml
Changes required for the 1.0.1 ECE release planned this week, and to reapply the changes previously committed under #189.
=> Add 1.0.1 branch, reapply changes from #189

README.asciidoc
=> Add section that describes how to set short titles for the TOC

conf.yaml
This pull request adds a new "Elasticsearch and X-Pack" book for (temporary?) testing purposes as we investigate where best to build this type of integrated content.
=> [DOCS] Create separate ES+Xpack book for testing

conf.yaml
Add Auditbeat docs to the build
=> Add Auditbeat docs to the build

conf.yaml
Master will become 7.0, 5.x will become 5.6, and we're branching 6.0 and 6.x
=> Branch 6.0 and 5.6 and bump master to 7.0

conf.yaml
Add directory paths to the root folder for each beat to pick up the reference.yml file example.
=> Update conf.yaml to include root dir of each beat

resources/website-l10n.xsl
Improve Japanese templates in website-l10n.xsl
=> Improve Japanese templates

conf.yaml
=> Add Curator 5.2 branch

conf.yaml
and update the location of the APM Server reference docs.
=> Add the APM Getting started guide

conf.yaml
=> Set 5.3 to current for Curator

conf.yaml
ECE 1.1 will GA November 14. This is its doc branch.
=> Add ECE 1.1 branch

conf.yaml
This PR updates the "current" values from 5.6 to 6.0.
=> [DOCS] Change current from 5.6 to 6.0 in conf.yaml

conf.yaml
=> Update ES-PHP current to 6.0

conf.yaml, shared/attributes.asciidoc
This is a possible method to integrate the various product glossaries.  It's a work in progress.
=> [DOCS] Added glossary book

shared/versions61.asciidoc
This PR updates the version from 6.1.0 to 6.1.1 in preparation for the next documentation release.
=> [DOCS] Updated versions to 6.1.1

conf.yaml
Initial docs in https://github.com/elastic/apm-agent-ruby/pull/33
=> Add configuration for the Ruby APM Agent docs

conf.yaml
=> add APM Frontend JavaScript agent docs

shared/settings.asciidoc, shared/settings61.asciidoc
Updated the X-Pack settings tables to include links to the APM UI settings.
=> [DOCS] Added APM settings

conf.yaml
=> Add apm frontend agent 0.x branch

shared/versions61.asciidoc
Update version to 6.1.3 for the release today.
=> Update version to 6.1.3

shared/versions56.asciidoc
Update version to 5.6.7 for the release today.
=> Update version to 5.6.7

README.asciidoc, conf.yaml, doc_build_aliases.sh
This PR is related to https://github.com/elastic/logstash/pull/9078
It updates the conf.yaml and doc_build_aliases.sh to reflect the changed location of the Logstash Reference's index.asciidoc.
=> [DOCS] Update Logstash doc build

README.asciidoc
=> Escape raw versions of replacement characters in README

conf.yaml
=> Update current docs for APM agents in preparation for 6.2

build_docs.pl
Resolves issue https://github.com/elastic/docs/issues/161
@nik9000 Is this sufficient to address your concern? I don't see an actual error...just keeps restarting. I don't want to mess too much with my keychain, tho, so maybe my testing is not thorough enough. Here's what the output looks like: first when I enter the wrong credentials, and then when I enter no password.
In the spirit of the existing text, I've tried to keep the messages short.
=> Improve error message for auth failure

shared/attributes.asciidoc, shared/attributes62.asciidoc
This PR adds attributes for the forum URLs, which are currently used in the X-Pack Reference.
=> [DOCS] Added forum attributes

lib/ES/Template.pm, resources/web/docs.js, resources/web/styles.css, resources/website_common.xsl
This was added in a similar format to the already existing code, though I did some minor cleaning up to better understand it. It still references Sense, which I am not sure if we can remove that. If we no longer build docs referencing Sense examples, then we should.
This code could really benefit from a more thorough cleanup or possible rewrite in the future.
Also fixed Copy as cURL commands to include the hostname configured through the settings.
=> Adds formatting support for Kibana APIs

conf.yaml, doc_build_aliases.sh, shared/attributes.asciidoc
This PR updates the documentation build commands in the  doc_build_aliases.sh and the conf.yaml once the files have moved to their new location.
=> [DOCS] Update documentation build commands

conf.yaml
This PR adds the new 6.3 branches to the documentation builds by updating the conf.yaml
=> [DOCS] Adds 6.3 branches to conf.yaml

conf.yaml
Also added the repo for the Kibana ref translation, but it's not ready to add to the build yet.
=> Added Chinese translation of the PHP guide. Closes #315

doc_build_aliases.sh
We have some images in a new shared folder that might require this PR.
=> Add shared folder for Cloud docs

shared/versions.asciidoc
Adds attributes for logstash, elasticsearch, and kibana to allow for greater granularity for package names in installation instructions.
=> Add version attributes for logstash, elasticsearch, and kibana

conf.yaml
Added missing changelog to sources
=> [APM} Add CHANGELOG to sources

doc_build_aliases.sh
Correct and clarify instructions for setting GIT_HOME
=> [DOCS] Fix instructions for using build alias file.

shared/attributes.asciidoc
=> Add attribute for APM Ruby agent

conf.yaml
This PR adds the new 6.4 branches to the conf.yaml
=> [DOCS] Adds 6.4 branches to conf.yaml

conf.yaml
=> [APM] use Real User Monitoring in the title

conf.yaml
Mostly a cosmetic change, this PR just re-adds some spaces that got removed earlier today.
=> Re-add some spaces for Cloud

conf.yaml
This PR updates the conf.yaml in preparation for the 6.4.0 release
=> [DOCS] Updated current to 6.4

shared/versions64.asciidoc
This PR updates the shared version information that is used by a subset of the 6.4.0 documentation.
=> [DOCS] Updates release state for 6.4.0

conf.yaml
NOTICE: Only to be published after 6.4 release.
=> [APM] RUM JS agent add version branch 1.x

conf.yaml
=> Revert "Add 6.x to APM UI docs"

conf.yaml
Add 0.5 branch for apm-agent-go, for upcoming release.
=> [APM] Add apm-agent-go 0.5 branch

conf.yaml
Corresponding to change in elastic/apm-server#1342
=> include apm-server changelogs in build

conf.yaml
=> only include apm-server changelogs in build for master branch, for now

doc_build_aliases.sh
Related to https://github.com/elastic/docs/pull/425
This PR adds the "docbldaz" alias to build the new book.
=> [DOCS] Adds docbldaz alias

conf.yaml, conf.yaml_latest
=> update APM section title

conf.yaml
This PR updates the conf.yaml to include the new 6.5 branches.
=> [DOCS] Adds 6.5 branches to the documentation 

conf.yaml
This is for the pending Curator 5.6 release.
=> Adding Curator 5.6

conf.yaml, shared/versions65.asciidoc
This PR updates the conf.yaml such that the 6.5 branches are "current".
=> Updates current in conf.yaml

conf.yaml, shared/attributes.asciidoc
Also added an attribute for linking to the doc.
=> Added standalone ES SQL ODBC Driver Doc

shared/versions65.asciidoc
TO BE MERGED 1 HOUR BEFORE RELEASE
=> Bump versions for 6.5.1

shared/attributes.asciidoc
First step in implementing elastic/apm/issues/19.
Starting small so I don't 🌋💣 everything.
=> add new apm server attribute

build_docs.pl
Fixes some inconsistent indentation that are bothering me.
=> Fix some indentation

conf.yaml
This PR adds the new 6.6 branches to the conf.yaml
=> [DOCS] Adds 6.6 branches to conf.yaml

conf.yaml
Adding the MS15
Relates to [#23010](https://github.com/elastic/cloud/issues/23010) and https://github.com/elastic/cloud/issues/23585
=> Update Cloud builds

resources/asciidoctor/lib/elastic_compat_preprocessor/extension.rb, resources/asciidoctor/spec/elastic_compat_preprocessor_spec.rb
Asciidoc will match any line that starts with `----` and only contains
`-` as a code block fence. Asciidoctor will do that for the *start* of
the code block fence, but the *end* of the code block fence must match
the start fence perfectly. Asciidoc has no such check. It is generally
good practice for them to match so they usually do, but they don't
always. So we normalize them on load, logging a warning if we have to do
it so the author of the docs can fix them at their leisure.
This comes up enough in the Elasticsearch reference that the reference
fails to render about half with through without this fix. With this fix
it still fails to render, but for some other, hopefully unreleated
reason.
=> Asciidoctor: Fix mismatched code block fencing

conf.yaml
This PR updates "current" field to 6.6
=> Updating current to 6.6

README.asciidoc
This PR updates the readme so that it's clearer that authorization is required to build the full set of documentation.
=> [DOCS] Clarify authorization requirement

conf.yaml
Changing ESS (Cloud) build to MS15
=> Change Cloud current

conf.yaml
=> [APM] RUM JS agent add version branch 3.x

conf.yaml
Updated `current` to `2.1`.
**Do not merge until 2.1.0 is a go**
=> [DOCS] Changed current to 2.1

conf.yaml
Changed the current branch from 2.0 to 2.1
=> Changed current to 2.1

conf.yaml
=> [APM] RUM JS agent set current version branch to 3.x

conf.yaml, doc_build_aliases.sh
We've got a new APM Agent in the family! 🎂 👶 🍾 
Ran a `build --all` locally without any problems.
=> Add APM .NET Agent to doc build

conf.yaml
=> Add APM 6.7 branch

conf.yaml
This PR adds the 7.0 and 7.x branches to the conf.yaml so that we can start building those branches
=> Adds 7.0 and 7.x branches

build_docs.pl
Drops the branch switching and self updating behavior from
`build_docs.pl` because we don't need it now that we're building the
docs using our standard build process.
Closes #575
=> Drop self-updating

resources/asciidoctor/.rubocop.yml, resources/asciidoctor/lib/edit_me/extension.rb, resources/asciidoctor/lib/elastic_compat_tree_processor/extension.rb, resources/asciidoctor/lib/elastic_include_tagged/extension.rb, resources/asciidoctor/spec/change_admonishment_spec.rb, resources/asciidoctor/spec/copy_images_spec.rb, resources/asciidoctor/spec/edit_me_spec.rb, resources/asciidoctor/spec/elastic_compat_preprocessor_spec.rb
Removes some rubocop suppressions and fixes the warnings that they find
without changnig any behavior.
=> Asciidoctor: Enable some more rubocop rules

conf.yaml
Looks like there are some items that cropped up that warrant a Milestone 18 doc build after all. So, as a first step, let's add a build and then we can haggle about ze details. 😸
=> Add Milestone 18 to ESS builds

shared/attributes.asciidoc
This PR adds shared attributes that can be used to differentiate between machine learning jobs that perform anomaly detections vs data frame analytics.
=> Adds shared attributes for ML jobs

resources/asciidoctor/lib/elastic_compat_preprocessor/extension.rb
Its been recommended to me that I should make all of my regexes constants
if possible. This grabs a few of them.
=> Asciidoctor: Make some regexes constants

shared/versions66.asciidoc
This PR updates the shared versions attribute file for 6.6.2.
=> Updated versions66.asciidoc for 6.6.2

shared/versions56.asciidoc
This PR updates the shared version attributes for the 5.6.16 release.
=> Updates version attributes for 5.6.16

build_docs.pl
This tidies the list of command line options so they are always in
alphabetical order within their three groups.
=> Sort command line options

conf.yaml, shared/versions70.asciidoc
This PR updates the conf.yaml and shared version attributes for 7.0.0-rc1
=> Updates attributes and conf for 7.0.0-rc1

shared/attributes.asciidoc
We need an attribute for the new ECS book. Woot! Woot!
=> Add attribute for ECS docs

conf.yaml
Updated conf.yaml to start building the docs for ESS MS20.
=> [DOCS] Updated conf.yaml for ESS MS20

shared/attributes.asciidoc
=> Fix ecs url

conf.yaml, shared/versions70.asciidoc
This PR updates the conf.yaml and shared version attributes for 7.0.0-rc2
=> Updates attributes and conf for 7.0.0-rc2

shared/versions67.asciidoc
This PR updates the shared version attributes for 6.7.1.
=> Updates attributes for 6.7.1 release

resources/asciidoctor/.rubocop.yml, resources/asciidoctor/spec/spec_helper.rb
Turns on the ExtraSpacing cop and removes two spaces to make it happy.
=> Asciidoctor: Fix extra spacing

resources/asciidoctor/lib/copy_images/copier.rb, resources/asciidoctor/lib/copy_images/extension.rb, resources/asciidoctor/lib/elastic_compat_preprocessor/extension.rb, resources/asciidoctor/lib/elastic_include_tagged/extension.rb
Drops the hash rockets that are not already being covered by #775.
=> Asciidoctor: Drop hash rockets

conf.yaml, shared/versions70.asciidoc
This PR updates the conf.yaml and shared versions70.asciidoc file for 7.0.0
=> Updates current to 7.0.0 in conf.yaml

shared/attributes.asciidoc
Well, turns out I need 63. Sooooo here's where we're at
=> add beats ref 60 and 63

conf.yaml, doc_build_aliases.sh
Switches the curator docs from the unmaintained AsciiDoc project to the
Asciidoctor project.
=> Switch curator docs to Asciidoctor

conf.yaml
Changes the ESS `current` branch to `release-ms-20`.
=> Changes ESS `current` to `release-ms-20`

resources/asciidoctor/.rubocop.yml, resources/asciidoctor/spec/change_admonition_spec.rb, resources/asciidoctor/spec/spec_helper.rb
Removes a few cop suppressions and fixes that failures.
=> Asciidoctor: Enforce more cops

conf.yaml
only conf.yaml has been edited in this PR.  I am unsure how to test this, as there is no index.asciidoc in the docs repo and I do not see an alias to build the top level menu.  
Thanks,
Dan
=> fixed branding noted in issue 847

shared/versions70.asciidoc
This PR update the shared version attributes for 7.0.1.
=> Updates attributes for 7.0.1 release

shared/versions68.asciidoc, shared/versions72.asciidoc
This PR adds shared version attributes for 6.8.0 and 7.2.0
=> Adds 6.8.0 and 7.2.0 version attributes

shared/attributes.asciidoc
This PR adds a shared attribute for the Elastic subscriptions page.
=> Add attribute for subscriptions URL

shared/versions68.asciidoc, shared/versions71.asciidoc
This PR updates the release-state attributes in advance of 6.8 and 7.1 releases.
=> Updates docs release state for 6.8 and 7.1

conf.yaml
This PR updates "current" to 7.1 for the appropriate books.
=> Updates current documentation version

resources/asciidoctor/Makefile, resources/asciidoctor/spec/copy_images_spec.rb
Found when running through the tests during ruby guild meeting.
=> Small typo fixes

shared/versions73.asciidoc
This PR adds a new file that contains version attributes for use by the 7.x branches
=> Adds 7.3 version attributes

conf.yaml
This PR adds the new 7.2 branches to the conf.yaml so that we can start building documentation for that version.
=> Adds 7.2 branches to conf.yaml

shared/attributes.asciidoc
This PR adds shared attributes for the terms "Elastic Cloud" and "Elasticsearch Service", as well as ESMS and data frames so they can be used consistently across the library.
=> Adds cloud and ESS attributes

conf.yaml, integtest/spec/all_books_spec.rb, integtest/spec/helper/book.rb, lib/ES/Source.pm, resources/asciidoctor/lib/edit_me/extension.rb, resources/asciidoctor/spec/edit_me_spec.rb
Adds support for disabling edit_me links by setting a source to
`private`.
=> Support disabling edit_me for some sources

conf.yaml, doc_build_aliases.sh
Related to [#992](https://github.com/elastic/cloud-on-k8s/pull/992).
Removed the `single:1` to get 2 single pages.
=> Remove single: 1

shared/attributes.asciidoc
For context, see also elastic/elasticsearch#42288
=> Add dataframe-analytics attribute for Data Frame Analytics high-level REST client documentation

doc_build_aliases.sh
To restore the standard index page.
=> Added chunk:1

shared/attributes.asciidoc
Adds new attribute for SIEM Guide
=> Add attribute for Siem Guide

conf.yaml
Change the order of branch appearance, to have `master` as the current branch.
=> Move master branch to appear as current

conf.yaml
Blocks indexing and changes title
=> Set noindex values

conf.yaml
=> k8s - revert back `current` to `0.8`

shared/versions68.asciidoc
This PR updates the shared version attributes for the 6.8.1 release.
=> Updates shared version attributes

shared/api-ref-ex.asciidoc
This PR updates the API reference template.
=> Updates to the API template

conf.yaml, shared/versions72.asciidoc
* Updates current to `7.2` in `conf.yaml`
* Changes `release-state` to `released` in `versions72.asciidoc`
=> docs: update 7.2 to current and released

conf.yaml
=> Changes to conf.yaml for secops

shared/versions74.asciidoc
This PR creates a new shared version attributes file.
=> Adds new shared attributes for 7.4

conf.yaml
**Do not merge until MS 24 is confirmed that it builds**
=> Changing Cloud current to MS 24

shared/attributes.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/43402
This PR adds shared attributes related to the data rollups feature.
=> Adds shared attributes for rollups

shared/api-ref-ex.asciidoc
Related to https://github.com/elastic/docs/issues/937#issuecomment-509778517
This PR updates the format of the "Required/Optional" qualifier in the API template.
=> Change layout of parameters in API template

conf.yaml
Builds the 7.3 documentation for APM
=> Add APM 7.3 branch

resources/web/styles.css, resources/web/template.html
This PR is to add a dynamic nav and footer to the docs for the upcoming site redesign.
=> Add new main nav and footer for 2019 redesign

conf.yaml
=> Add 7.x to exclusion list

resources/web/template.html
This adds a `Docs` link as a subnav to fix https://github.com/elastic/docs/issues/993
=> Add Docs link subnav

conf.yaml
This PR fixes the issue reported by @debadair in https://elastic.slack.com/archives/C0JF80CJZ/p1564004725053400.
=> Fix conf.yaml indentation for Cloud section

conf.yaml
Does not set 2.3 to current, that will be done in a separate PR
=> Adds the Cloud 2.3 build

conf.yaml
Relates to https://github.com/elastic/cloud/issues/36252.
=> Switch current for ECE to 2.3

conf.yaml
=> Remove 7.x from exclusion list

shared/attributes.asciidoc
This PR adds a couple of attributes to the shared attributes list related to the evaluate data frame analytics API.
=> Adds evaluate data frame analytics API related attributes

conf.yaml
=> Remove 7.x from exclude branch

resources/web/styles.css
Space out the lines in the TOC slightly more so they don't run together
quite so much.
Closes #1035
=> Space TOC lines a bit more

conf.yaml
=> Add 5.8 branch to Curator

conf.yaml
Merge this PR after merging https://github.com/elastic/beats/pull/13172.
=> Add x-pack/libbeat/docs to paths

resources/web/style/admonishment.pcss, resources/web/style/util.pcss, resources/web/styles.pcss, resources/website_common.xsl
Converts inline admonishments into "component" style html using the
guidelines laid out here:
http://nicolasgallagher.com/about-html-semantics-front-end-architecture/
=> Convert inline admonishments to components

resources/web/style/calloutlist.pcss, resources/web/style/code.pcss
These look a little more like what we're going for.
=> Update code and callout style

resources/web/styles.pcss
Make sure we switch to the pointer and don't underline.
=> Correct style on gear icon

resources/web/style/list.pcss, resources/web/styles.pcss
It'll make our life simpler to have the styles grouped. This doesn't
simplify the rules, just moves them.
=> Extract list styling into its own file

shared/versions73.asciidoc
=> Bump shared version to 7.3.1

conf.yaml
The PR adds the code snippets for the ES Python Client for the following doc pages:
* Index API
* Get API
* Delete API
* Getting Started
=> Python Client - code snippets

resources/web/style/heading.pcss
We'd intended to do this a long time ago.
Relates to #1081.
=> Switch headings to aktiv grotesk

resources/web/styles.pcss
This should prevent us from modifying the header and footer.
=> Style: Move the * rule into guide

conf.yaml
This PR is equivalent to https://github.com/elastic/docs/pull/1088 and adds documentation examples for the Ruby client.
/cc @estolfo
=> Ruby Client - code snippets

lib/ES/Book.pm
I broke them, but only when a new book is coming in.
=> Fix problem with PR builds

conf.yaml
These don't do anything anymore. I'm not sure what they did to be
honest.
=> Drop unused config lines

resources/web/template.html
=> Fix footer div tag

integtest/spec/helper/dest.rb, lib/ES/Repo.pm, lib/ES/Source.pm
Returning a string sometimes and a number other times upsets perl.
=> Fix perl warning

shared/attributes.asciidoc
This PR expands the attributes list by adding the regression analysis related attributes.
Related issue: https://github.com/elastic/ml-team/issues/203
=> Adds regression analysis related attributes to the attributes list

build_docs.pl, lib/ES/Template.pm
Now that we have control over the template file directly we really don't
need to support any kind of fancy configuration for it. This drops that.
See #1115
=> Drop ability to configure template

build_docs.pl, conf.yaml, integtest/spec/helper/source.rb
The build wouldn't work properly if we set them to anything else.
=> Drop remaining path customizations

resources/web/style/rtpcontainer.pcss, resources/web/style/settings_modal.pcss, resources/web/style/this_page.pcss, resources/web/styles.pcss
Moves the styles for the settings_modal, this_page, and rtpcontainer
into their own files so that we can find things a little easier.
=> Continue to group styles

integtest/spec/helper/dsl/file_contexts.rb, integtest/spec/single_book_spec.rb, lib/ES/Template.pm, resources/web/template.html
Drops the template munging code and makes the changes that it made
directly in the template file. This seems sensible now that we own the
template.
=> Drop template munging

lib/ES/Template.pm
That init method used to be super important but now it is so simple we
can just inline it with the constructor.
=> Remove Template.pm's "funny" init method

shared/versions68.asciidoc
This PR updates the shared version attributes file for the 6.8.3 release.
=> Updates shared version attributes for 6.8.3

resources/web/template.html
This would remove the js linked from elastic.co.
=> Drop static scripts being loaded from elastic.co

lib/ES/Template.pm, lib/ES/Util.pm
Moves the autosense extraction code from the templating process into the
book building process so templating is even simpler!
=> Move autosense extraction from template

preview/test.sh, publish_docker.sh
We'd like to pick up the "go away" robots.txt.
=> Prepare to release a new version of preview

resources/web/template.html
I *think* these aren't used any more. I can't find them, at least.
=> Drop m-shortcut styles

resources/web/template.html
=> Drop jquery cookie

resources/web/styles.pcss
These are managed by the header and footer itself. For the most part
this doesn't actually change anything visually because the header and
footer *already* manage it.
=> Drop styles that leak into the header and footer

shared/attributes.asciidoc
This PR changes `data frame transform` and its variations to `transform` and its respective variations in the attributes list.
=> Changes data frame transforms to transforms in the attributes

resources/web/template.html
Drops two misleading comments from the template and an empty meta tag.
=> Drop comments and empty meta from template

shared/attributes.asciidoc
This PR adds shared attributes for capitalized rollup terminology.
=> Adds more shared attributes for rollups

preview/__test__/git.test.js
The tests relied on `HEAD` which isn't really *there* for intake builds.
=> Fix up tests for git

integtest/spec/helper/console_alternative_examples.rb, lib/ES/Util.pm, resources/asciidoctor/lib/alternative_language_lookup/report.rb, resources/asciidoctor/spec/alternative_language_lookup_spec.rb, template/template.js
So it'll be easier to parse.
Closes #1135
=> Switch the alternatives report to json

conf.yaml
=> Turn on asciidoctor build for Beats documentation

doc_build_aliases.sh
Switches alias file to use asciidoctor.
=> Update aliases to build beats in asciidoctor

preview/test.sh, publish_docker.sh
=> Release new version of the docs preview application

resources/web/air_gapped_template.html, resources/web/template.html
=> Template: remove slick.js

resources/web/air_gapped_template.html, resources/web/template.html
=> Drop bootstrap.js

.ci/publish_air_gapped_docs.sh, air_gapped/build.sh, air_gapped/test.sh
Modifies the ci script for the air gapped docker image to push it.
=> Push air gapped docker image

integtest/spec/all_books_broken_link_detection_spec.rb, lib/ES/LinkCheck.pm
Just alter the regular expression to pick them up.
=> Link check relative links

.ci/test.sh
Adds a ci script to run the tests so we have the flexibility of changing
how we run the tests if we want to.
=> Add ci script to run tests

air_gapped/Dockerfile, air_gapped/build.sh, preview/test.sh, publish_docker.sh
Got a couple new changes from @nik9000 in here that we'd like to benefit from on the next deploy of the docs preview app.
=> Bump preview Docker image to version 11

shared/versions/stack/current.asciidoc
=> 7.4 is current now

conf.yaml
1.2 branch should now be current
=> ECS 1.2.0 release.

build_docs.pl, lib/ES/BaseRepo.pm
We haven't supported it for a while. We rely on git over ssh for this.
=> Drop the user option

conf.yaml
We've released a new major version 🎉
=> Add 3.x branch to Ruby APM Agent

conf.yaml
For https://github.com/elastic/apm-agent-nodejs/pull/1435.
=> [docs] Add APM CHANGELOG.asciidoc

air_gapped/Dockerfile, air_gapped/build.sh, build_docs.pl, preview/Dockerfile, preview/test.sh, publish_docker.sh
Putting optional env vars in the Dockerfile `CMD` was breaking the Helm chart deployment. Moving the logic into the code.
My first time committing production Perl!
=> GitHub user via code

conf.yaml
This adds the 1.0 branch to the docs build for ECK
=> ECK add 1.0 branch to docs

integtest/Makefile
=> Revert mistake

conf.yaml
This PR adds the beta version to `current`.
=> Add 1.0 to current

conf.yaml
This PR adds the 7.5 branches to the conf.yaml to start building the documentation for those branches.
=> Adds 7.5 branches to documentation

resources/legacy_redirects.conf
This PR removes or updates some X-Pack Reference redirects.
=> Updates X-Pack Reference redirects

conf.yaml, doc_build_aliases.sh
=> Convert the definitive guide to asciidoctor

conf.yaml
Adds APM Ruby changelog for `master` and `2.x`
=> docs: Add ruby changelog

shared/versions/stack/6.8.asciidoc
=> [DOCS] Bump docs for 6.8.4 release

shared/versions/stack/7.4.asciidoc
=> [DOCS] Bump docs for 7.4.1 release

shared/versions/stack/6.8.asciidoc, shared/versions/stack/7.4.asciidoc
=> Doc version bumps for  6.8.4 and 7.4.1 releases

conf.yaml, doc_build_aliases.sh
Moves the second to last book to Asciidoctor!
=> Switch cloud saas docs to Asciidoctor

shared/attributes.asciidoc
Adds new, data frame analytics related attributes to the pool.
:classification:
classification
:classification-cap:
Classification
:classanalysis:
classification analysis
:classanalysis-cap:
Classification analysis
=> Adds new data frame analytics related attributes

shared/discontinued.asciidoc
Adds shared file for defining "discontinued" statements for inclusion in multiple books.
@debadair Is this what you had in mind?
=> Add shared file for discontinued features

conf.yaml
For https://github.com/elastic/apm-agent-dotnet/issues/572.
=> Add APM .NET Changelog -- master

resources/web/template.html
Updates text and CTA's for the rtp container.
https://github.com/elastic/website-www.elastic.co/issues/4928
=> Update rtp container content

build_docs
Drops sending the Dockerfile into the docker build process. It isn't
required.
=> Clean up leftover

build_docs
One that I don't see locally, but other folks do. I'm not sure that this
fixes it but it is worth a shot!
=> Fix a NO SUCH FILE bug

conf.yaml
For https://github.com/elastic/apm-agent-python/issues/616.
=> Add APM Python Changelog -- master

conf.yaml
These work properly with git to find the files we need. Hopefully.
=> Switch beats paths to "pathspec"s

conf.yaml
Closes https://github.com/elastic/apm-agent-python/issues/616.
=> Add APM Python Changelog -- 5.x

shared/versions/stack/6.8.asciidoc
DO NOT MERGE THIS PR UNTIL RELEAESE DAY
=> Updates version numbers

doc_build_aliases.sh, lib/ES/Util.pm, resources/asciidoctor/lib/docbook_compat/convert_document.rb, resources/asciidoctor/lib/docbook_compat/convert_links.rb, resources/asciidoctor/lib/docbook_compat/extension.rb, resources/asciidoctor/spec/docbook_compat_spec.rb
Improves the docbook_compat plugin to properly render most of the single
page books. Not *all* of them are perfect, but they are getting there!
=> Further improve docbook workalike

integtest/spec/air_gapped_spec.rb, integtest/spec/all_books_spec.rb, integtest/spec/helper/book.rb, integtest/spec/preview_spec.rb, integtest/spec/single_book_spec.rb, lib/ES/Toc.pm
This should marginally speed up the build and it is another step to
getting us off of docbook.
=> Switch version tables of contents to direct_html

resources/asciidoctor/lib/docbook_compat/convert_document.rb
Instead of adding the tags with regex manipulation add them by
overriding docinfo. This is the same mechanism that the chunked users to
get `<link rel="home"` into the head and it is *much* cleaner.
=> Clean up direct_html's dc meta tags

conf.yaml
~Blocked by https://github.com/elastic/apm-agent-java/pull/944~
=> APM Agent Java: Build changelog on master

conf.yaml
Getting ready for the next ECS release.
Please don't merge this PR, let @webmat do it :-)
=> Update the conf for the upcoming ECS 1.3 release

conf.yaml, doc_build_aliases.sh
I've picked this fairly small and self contained book to be the first
multi page book to switch to direct html *because* it is simple.
=> Switch the Anthos book to direct html

conf.yaml, shared/versions/stack/7.5.asciidoc, shared/versions/stack/current.asciidoc
DO NOT MERGE THIS PR UNTIL RELEASE DAY
=> Updates release state and current branches

resources/asciidoctor/spec/edit_me_spec.rb
It turns out that edit_me urls in the logstash plugin reference weren't
being generated quite right. I dug into it and found out that html5
fixes it which is lovely, if a little strange. This adds tests to make
sure it *stays* fixed.
=> Add some tests for a mysterious condition

conf.yaml
~Blocked by https://github.com/elastic/apm-agent-go/pull/682~
=> [APM] Build Go release notes to documentation [master]

air_gapped/build.sh
I believe I broke it while trying to clean things up back in
October.....
=> Fix the name of the air gapped docs image

conf.yaml
Just adding the build, leaving current as MS28 for now.
=> Adds the MS31 build to ESS and Heroku books

conf.yaml
Reverts elastic/docs#1500 as it's breaking the doc build.
=> Revert "Adds the MS31 build to ESS and Heroku books"

conf.yaml, doc_build_aliases.sh
=> Switch the java rest client to direct_html

resources/asciidoctor/lib/docbook_compat/convert_table_cell.rb, resources/asciidoctor/spec/docbook_compat_spec.rb
It turns out that asciidoctor can do most of the job for us. Also, I
have to do something with paragraphs to fix errors I found while
converting ecs (#1559).
=> Rework table cell rendering in direct_html

conf.yaml, doc_build_aliases.sh
=> Switch the transport client docs to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch the es ruby client to direct_html

conf.yaml, doc_build_aliases.sh
Direct html is faster and more customizable. It is the future!
=> Switch the painless book to direct_html

conf.yaml
=> Switch logstash VPR to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch the .net client to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch the ES plugins doc to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch the php client to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch es hadoop docs to direct_html

conf.yaml, doc_build_aliases.sh
direct_html is faster and more customizable. We're converting all of our
docs to it.
=> Switch the curator docs to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch js client's docs to direct_html

shared/attributes.asciidoc
This PR adds two new attributes to the shared attributes asciidoc file in connection with a new machine learning feature: inference.
=> [DOCS] Adds inference related attributes

conf.yaml, doc_build_aliases.sh
=> Switch the groovy api to direct_html

conf.yaml
=> Switch legacy infrastructure guide to direct_html

conf.yaml
=> Switch legacy reporting reference to direct_html

conf.yaml
=> Switch graph to direct_html

conf.yaml
=> Switch marvel to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch metrics docs to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch logging guide to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch libbeat docs to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch siem docs to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch uptime docs to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch the beats developer guide to direct_html

conf.yaml, doc_build_aliases.sh
direct_html is the future! The definitive guide is the past....
=> Switch the definitive guide to direct_html

conf.yaml, doc_build_aliases.sh
direct_html is the future! The xpack reference is a thing of the past.
=> Switch the legacy xpack reference to direct_html

conf.yaml
=> Switch Japanese translations to direct_html

conf.yaml
=> Switch Korean translations to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch elasticsearch reference to direct_html

conf.yaml
=> Switch shield to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch journalbeat to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch functionbeat to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch auditbeat to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch heartbeat to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch metricbeat to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch winlogbeat to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch filebeat docs to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch packetbeat to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch RUM apm agent to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch python apm agent to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch ruby apm agent to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch the nodejs agent to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch .NET apm agent to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch Java apm agent to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch go apm agent to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch apm getting started docs to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch apm server to direct_html

conf.yaml
=> Switch Chinese translations to direct_html

conf.yaml, doc_build_aliases.sh
`--direct_html` is faster and more customizable. It is the future.
=> Switch cloud's heroku docs to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch cloud's saas docs to direct_html

conf.yaml, doc_build_aliases.sh
=> Switch cloud enterprise docs to direct_html

conf.yaml, doc_build_aliases.sh
direct_html is fater and more cutomizable. It is the future!
=> Switch kibana to direct_html

conf.yaml
=> Switch topbeat reference to direct_html

integtest/spec/helper/dsl/convert_single.rb, integtest/spec/single_book_spec.rb
Now that most of the books are on direct_html we should probably switch
the tests.
=> Switch the single book tests to direct_html

conf.yaml
Please let @webmat merge at the appropriate time for this release, as usual <3
=> Release ECS 1.4

resources/web/style/rtpcontainer.pcss
Update CSS for RTP Cloud Promo in `rtpcontainer.pcss` for this ticket https://github.com/elastic/website-www.elastic.co/issues/5058
=> Update CSS for RTP Cloud Promo to match design system

conf.yaml, doc_build_aliases.sh
direct_html is faster and more customizable.
=> Switch ecs to direct_html

conf.yaml
=> Drop direct_html from conf.yaml

integtest/spec/single_book_spec.rb
=> Drop direct_html flag from single book tests

build_docs.pl
Since we don't depend on docbook we don't need to set up the environment
for xml any more.
=> Drop environment customization for xml

integtest/spec/all_books_spec.rb, integtest/spec/helper/book.rb, integtest/spec/helper/book_conf.rb, integtest/spec/helper/dest.rb, integtest/spec/helper/dsl/convert_single.rb
It is now the default so there is no need to test it explicitly.
=> Drop remaining tests for direct_html

shared/versions/stack/master.asciidoc
I need this for https://github.com/elastic/beats/pull/15497
=> Update the ECS version in master to 1.4

shared/versions/stack/7.x.asciidoc
=> Update ecs_version to 1.4 in 7.x branches

conf.yaml, shared/versions/stack/7.6.asciidoc
This PR opens the 7.6 branch of the docs and adds a shared version attribute file to it.
=> Creates 7.6 version of the docs

shared/attributes.asciidoc
This PR adds a shared attribute for the machine learning Data Visualizer.
=> Adds shared attribute for Data Visualizer

README.asciidoc, resources/asciidoctor/lib/docbook_compat/convert_lists.rb, resources/asciidoctor/spec/docbook_compat_spec.rb
These are supported by asciidoctor but we broke them. This fixes that.
Closes #1713
=> Support TODO checkboxes

conf.yaml
Preview: http://docs_1724.docs-preview.app.elstc.co/guide/en/workplace-search/current/index.html
=> Add Workplace search docs to the build.

README.asciidoc
This PR provides information about the documentation build checks that exist in most Elastic repos.
=> Adds PR checks to readme

conf.yaml
This PR adds the shared attributes file to the PHP API book.
=> Adds shared attributes to PHP API book

conf.yaml
Forgot to add the statements to ALL THE THINGS.
=> Add x-pack processor paths to all beats books

conf.yaml
This PR updates the Azure ARM template current version to 7.6
=> Update Azure ARM template current version to 7.6

conf.yaml
As usual, please let @webmat do the merge at the proper time :-)
=> ECS 1.5.0 release

shared/attributes.asciidoc
This PR adds two new attributes related to feature importance to the shared attributes list.
=> [DOCS] Adds feature importance attributes

shared/api-ref-ex.asciidoc
This PR updates the comments in the API reference template to recommend collapsible sections for large or nested objects.  It also mentions two APIs that currently deal with this issue in different ways.
=> Adds collapsible sections to API template

shared/versions/stack/6.8.asciidoc, shared/versions/stack/7.6.asciidoc
=> Bump doc versions

conf.yaml, shared/attributes.asciidoc
Add new shared attributes for future Elastic Endpoint docs.
=> [Security]: Add security shared attributes. Remove extra guide

conf.yaml, shared/attributes.asciidoc
=> [Endpoint]: Add shared attributes repo to security docs config

conf.yaml
Please do not merge, just opening this for approval so I can merge it on release day (anticipated 28/4)
=> Make ECK 1.1 the current branch

README.asciidoc
Fixes #1750, fixes #1751, fixes #1752, fixes #1753
=> Fix typos in README.

conf.yaml, shared/versions/stack/7.8.asciidoc
CC @lcawl 
CI is expected to fail until all repos have added their 7.8 branches.
=> [DOCS] Add 7.8 branches to Stack docs

README.asciidoc
=> Remove outdated info about edit links

conf.yaml
Merging #1795 created a regression to something fixed in #1818
=> Fix duplicate variable in conf.yaml

conf.yaml
This patch updates the ecctl config to include the master branch and the branch from latest release.
=> Update conf.yaml with new ecctl branches

conf.yaml
=> [Security]: Rename Endpoint Guide to Security Guide

conf.yaml
Remove the second book added in #1843 while waiting for a redirect to be created.
=> Remove legacy endpoint book

conf.yaml
This commit updates the Azure Marketplace documentation
to 7.7
=> Update Azure Marketplace to 7.7

shared/versions/stack/7.7.asciidoc
=> Bumps docs version to 7.7.1

shared/versions/stack/6.8.asciidoc
=> Bumps docs version to 6.8.10

shared/attributes.asciidoc, shared/versions/stack/master.asciidoc
Need these changes to get the reworked highlights pages working.
=> Add bare version of the ES ref attr & update ES master version.

conf.yaml, shared/versions/stack/7.8.asciidoc, shared/versions/stack/current.asciidoc
DO NOT MERGE THIS PR UNTIL RELEASE DAY
Updates for the 7.8 release.
[Preview](https://docs_1868.docs-preview.app.elstc.co/guide/index.html)
=> 7.8 release updates

shared/versions/stack/7.9.asciidoc
This PR adds a new shared versions file in preparation for the creation of new branches.
=> Adds shared version file

shared/attributes.asciidoc
This PR creates a shared attribute for links to this book: https://www.elastic.co/guide/en/security/master/index.html
=> Adds security-guide attribute

shared/versions/stack/7.10.asciidoc
Updates the 7.x versions file to reference 7.10.
Creates a 7.10 versions file.
=> Add 7.10 attributes

shared/attributes.asciidoc, shared/legacy-attrs.asciidoc
We're going to change the URLs of these books, so it helps to have them in one place.
=> Add attributes for legacy books

conf.yaml
When I created this file in #1919, I forgot to add it to the books that would depend on it.
=> Add legacy attrs to book sources

conf.yaml
=> Add more kibana sources

shared/attributes.asciidoc
This PR adds an attribute for the File Data Visualizer, which is referenced in both Machine Learning and Kibana documentation and is a component that might be moved or renamed in the future.
=> Adds shared attribute for File Data Visualizer

shared/attributes.asciidoc
This PR adds shared attributes for more of the Kibana apps and UIs.
=> Adds more Kibana apps to shared attributes

shared/versions/stack/6.8.asciidoc
This PR updates the shared version attributes to 6.8.12.
-- Please do not merge this PR until release day! --
=> Update versions to 6.8.12

conf.yaml, shared/versions/stack/7.9.asciidoc, shared/versions/stack/current.asciidoc
This PR updates "current" to 7.9 and changes it from "unreleased" to "released".
--Do not merge this PR until the day of the release!--
=> Update current for 7.9.0 release

conf.yaml
Do not merge until ECS release day :-)
cc @ebeahan
=> Make ECS 1.6 current

shared/attributes.asciidoc
=> [DOCS] Add "elastic-sec" to list of attributes

conf.yaml
=> Update to ms45

build_docs.pl
If the local git project has multiple remotes from preferred
organizations, we should attempt to use one that matches the basename
of the working (mounted) directory. This repo is more likely to be the
preferred upstream repo
=> Prefer remote repos that match the local dir name

.ci/publish_preview.sh
=> Update Docker Push URL for preview image

conf.yaml
Updates `current` and branches to point to MS-46 Cloud docs
=> Release docs for Cloud release MS-46

shared/versions/stack/7.x.asciidoc
=> Bump 7.x.asciidoc file to 7.11.

resources/web/template.html
This adds the Optimizely snippet to Docs template.
=> GH6990 - Add Optimizely code to Docs pages

conf.yaml
This PR adds the conf.yaml doc build changes required for ECE 2.7.
=> Update build for ECE 2.7.0 release.

conf.yaml
This PR changes ms-47 references to ms-48 for the ESS release.
=> [ESS Release MS-48] Update docs for release - MS-47 -> MS-48

shared/versions/stack/7.11.asciidoc
Adds shared versions for 7.11.0
=> Add 7.11 version attributes

shared/versions/stack/7.x.asciidoc
Update 7.x.asciidoc shared file to point to 7.12
=> Update 7.x shared version to point to 7.12

conf.yaml
Update `&stacklive` variable in conf.yaml
=> Update stacklive variable

integtest/spec/all_books_broken_link_detection_spec.rb, lib/ES/LinkCheck.pm
For new people and those less familiar with the broken links messages,
it's not always clear which page has the broken link, and which page the
link is pointing to. Hopefully this clears it up!
=> Clarify message on broken links

.gitignore
https://marketplace.visualstudio.com/items?itemName=cfgweb.vscode-perl
=> Ignore .vstags file created by VSCode Perl extension

conf.yaml
For https://github.com/elastic/beats/pull/23344.
=> Add filebeat/docs dependency to Functionbeat Ref

shared/versions/stack/6.8.asciidoc
--DO NOT MERGE THIS PR UNTIL RELEASE DAY --
Update shared version attributes to 6.8.14
=> Update version for 6.8.14 docs release

conf.yaml
Preparing the release of ECE 2.8
=> Update current of ECE to 2.8

shared/attributes.asciidoc
Related to https://github.com/elastic/elasticsearch/pull/68964
This PR adds a shared attribute for the feature name.
=> Add attribute for operator privileges

doc_build_aliases.sh
It's actually a function, though ;-)
=> Add build alias for logstash plugin reference

shared/versions/stack/6.8.asciidoc
--DO NOT MERGE THIS PR UNTIL RELEASE DAY --
Updates 6.8 version to 6.8.15
=> Update version for 6.8.15

conf.yaml
Updates things for the ECE/ECCTL release next week - https://github.com/elastic/dev/issues/1648
@karencfv I'm not sure about the ECCTL branch, it doesn't exist yet but I'm guessing that happens on release day?
=> Update branch mapping for ECE 2.9.0 and ECCTL 1.3

conf.yaml, shared/versions/stack/7.12.asciidoc, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
Update apm-agent-dotnet current version to 1.9.
=> docs: apm-agent-dotnet 1.9

shared/versions/stack/7.12.asciidoc
=> Bumps the docs versions from 7.12.0 to 7.12.1

conf.yaml, shared/versions/stack/7.12.asciidoc, shared/versions/stack/7.13.asciidoc, shared/versions/stack/current.asciidoc
=> Change current branch to 7.13

shared/versions/stack/6.8.asciidoc
=> Update 6.8 version to 6.8.16

shared/versions/stack/7.13.asciidoc
=> Bump docs version to 7.13.1

conf.yaml, doc_build_aliases.sh, shared/attributes.asciidoc, shared/versions/stack/7.13.asciidoc, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
updating conf.yml to include iOS agent docs. 
This PR is intended for a 7.14 release.
=> added ios agent

shared/versions/stack/7.13.asciidoc
Updates the versions from `7.13.1` to `7.13.2`. 
=> Updates versions to 7.13.2

shared/attributes.asciidoc
This PR adds a shared attribute for "ML", to align with other acronyms in this list.
=> Add ML to shared attributes

conf.yaml
This PR changes current to MS 58 for ESS.
=> Update branch version to MS-58

conf.yaml
This PR changes current to MS 59 for ESS.
=> Change current to MS 59

shared/versions/stack/7.13.asciidoc
=> Update 7.13 version to 7.13.3

shared/versions/stack/6.8.asciidoc
=> Update 6.8 version to 6.8.17

shared/attributes.asciidoc
=> Adds shared attribute for the Swimlane connector

conf.yaml, shared/versions/stack/7.13.asciidoc, shared/versions/stack/7.14.asciidoc, shared/versions/stack/7.x.asciidoc, shared/versions/stack/master.asciidoc
Bump the version to the latest release, 1.11
=> Bump apm-agent-dotnet version

shared/versions/stack/7.13.asciidoc
=> 7.13.4 version bump

conf.yaml
This PR changes current to MS 60 for ESS.
=> Change current to MS 60

shared/versions/stack/6.8.asciidoc
=> Update 6.8 version to 6.8.18

conf.yaml, shared/versions/stack/7.13.asciidoc, shared/versions/stack/7.14.asciidoc, shared/versions/stack/current.asciidoc
=> Change current branch to 7.14 

shared/versions/stack/master.asciidoc
=> Bumps version to 8.0.0-alpha1

shared/versions/stack/main.asciidoc
This PR copies the contents of https://github.com/elastic/docs/blob/master/shared/versions/stack/master.asciidoc in to a main.asciidoc file for testing purposes.
=> Copies master branch attributes to main

conf.yaml
This PR changes current to MS 61 for ESS.
=> ESS - Change current to MS 61

conf.yaml, shared/versions/stack/7.15.asciidoc
We can merge this after all repos publish a 7.15 branch, and CI jobs succeed.
=> Add 7.15 docs branch

conf.yaml
Update for ECE 2.11.0 release. This replaces PR #2162.
=> Add ECE 2.11 and ECCTRL 1.5

shared/versions/stack/7.14.asciidoc
As the title states.
**DO NOT MERGE UNTIL RELEASE.**
=> 7.14.1 version bump

conf.yaml, doc_build_aliases.sh, shared/attributes.asciidoc
This PR:
* adds the new Javal client book to the `conf.yml` file
* modifies `docs_build_aliases.sh`
* modifies `shared/attributes`.
=> Adds new Java High-level Client book to conf.yml

shared/versions/stack/6.8.asciidoc
=> Change 6.8 docs version to 6.8.19

shared/versions/stack/7.14.asciidoc
Increments version for the 7.14.2 release
=> 7.14.2 version bump

conf.yaml, shared/versions/stack/7.14.asciidoc, shared/versions/stack/7.15.asciidoc, shared/versions/stack/current.asciidoc
=> Change current docs branch to 7.15

shared/versions/stack/7.15.asciidoc
Bumps version for the 7.15.0 release
=> 7.15.1 version bump

build_docs.pl, integtest/spec/all_books_broken_link_detection_spec.rb
=> Disable Kibana link checking

shared/attributes.asciidoc
This PR introduces two attributes to the list:
* `data-sources-caps`. Resolves to Data Views. 
* `data-sources-cap`. Resolves to Data views.
=> Adds attribute to data views

shared/versions/stack/8.0.asciidoc, shared/versions/stack/master.asciidoc
As the title states.
DO NOT MERGE UNTIL RELEASE.
=> Updates the 8.0 attributes file to 8.0.0-beta1

shared/versions/stack/7.15.asciidoc
Bumps version for the 7.15.2 release
=> 7.15.2 version bump

shared/attributes.asciidoc
Resolves https://github.com/elastic/docs/issues/2287.
=> Adding attribute for ServiceNow

resources/web/template.html
Removes unused script reference which is generating many 404s.
=> Remove unused script ref

shared/versions/stack/8.0.asciidoc, shared/versions/stack/master.asciidoc
=> Bump 8.x `prev-major-last` to 7.17

shared/attributes.asciidoc
This PR adds a variable for the "natural language processing" feature.
=> Adds NLP to shared attributes

conf.yaml
This adds the ECK 1.9 branch to the build list.
=> Add ECK 1.9

conf.yaml, doc_build_aliases.sh
Depends on https://github.com/elastic/enterprise-search-php/pull/8
=> Add docs for the Enterprise Search PHP client

shared/attributes.asciidoc
Adds a new ess attribute with a shorter message for more specific contexts
=> Add attribute for ess messaging

shared/attributes.asciidoc
This PR introduces two attributes to the list:
* `data-source-caps`. Resolves to `Data View`.
* `data-source-cap`. Resolves to `Data view`.
=> Adds attributes for data views

shared/versions/stack/8.0.asciidoc
Updating version attributes for 8.0.0-rc1
=> [DOCS]8.0.0-rc1 version attributes

shared/versions/stack/6.8.asciidoc, shared/versions/stack/7.16.asciidoc
=> [DOCS] Bump version for 7.16.3 and 6.8.23

shared/attributes.asciidoc
Cleaning up some tech debt by removing this old conditional.
=> Remove temp APM conditional

conf.yaml
This PR changes `*mapMainToMaster` to `*mapMasterToMain`
=> Fixes .net book generation

conf.yaml
Neutral name branch for `elastic/beats`
Requires https://github.com/elastic/beats/pull/29710
=> Rename master to main for Beats project

shared/versions/stack/8.0.asciidoc
Updating version attributes for 8.0.0-rc2.
=> [DOCS] 8.0.0-rc2 version attributes

conf.yaml
Adds the branch for the ECK 2.0 release.
=> Add ECK 2.0 branch

shared/attributes.asciidoc
Add a shared attribute `{integrations-server}`
=> add Integrations Server shared attribute

shared/versions/stack/8.0.asciidoc
=> Bump doc versions for 8.0.1

conf.yaml
Adds the branch for the ECK 2.1 release.
=> Add ECK 2.1 branch.

conf.yaml, shared/attributes.asciidoc, shared/versions/stack/8.0.asciidoc, shared/versions/stack/8.1.asciidoc, shared/versions/stack/current.asciidoc
=> Bump version to 8.1

shared/versions/stack/8.1.asciidoc
=> Bump doc versions for 8.1.1

shared/versions/stack/8.2.asciidoc
Creates a new /stack/versions/8.2.asciidoc file based on master.asciidoc
=> Add 8.2.0 version attributes

shared/versions/stack/7.17.asciidoc
=> [DOCS] Bumps docs version to 7.17.2

shared/versions/stack/8.1.asciidoc
=> Bump doc versions for 8.1.2

shared/attributes.asciidoc
* Lowercases `agent` in shared APM attributes
* Adds two attributes for` APM agent` and `APM Server`
=> Update APM shared attributes

shared/versions/stack/7.17.asciidoc
=> Bumps docs version to 7.17.3

shared/versions/stack/8.1.asciidoc
=> Bumps docs version to 8.1.3

shared/versions/stack/7.17.asciidoc
=> Bumps docs version to 7.17.4

shared/versions/stack/8.2.asciidoc
=> Bump doc versions for 8.2.1

shared/versions/stack/8.2.asciidoc
=> Bump docs version to 8.2.2

shared/attributes.asciidoc
=> [DOCS] Adds new endpoint-cloud-sec attribute.

shared/versions/stack/8.2.asciidoc
Do not merge until day of release.
=> Bump version to 8.2.3

conf.yaml
@chriscressman Please review this with a fine-tooth comb 🔎
- Issue: https://github.com/elastic/enterprise-search-team/issues/1989#issuecomment-1160713989
- Tied to stub page creation. CI will fail until 👉  exists I expect?: https://github.com/elastic/enterprise-search-pubs/pull/2522
=> Add Ent Search Node.js client to `conf.yaml`

shared/attributes.asciidoc
This PR adds an attribute for the "ServiceNow ITOM" product, which is referenced from pages such as https://www.elastic.co/guide/en/kibana/master/servicenow-itom-action-type.html
=> Add attribute for ServiceNow ITOM connector

shared/versions/stack/7.17.asciidoc
Do not merge until day of release.
=> Bumps version to 7.17.5

conf.yaml
=> 8.3 to current for ecs release

conf.yaml
=> Revert "Switch from master to main for elasticsearch repo"

conf.yaml
Preview: https://docs_2459.docs-preview.app.elstc.co/guide/index.html
=> Moved StackGS to Legacy Docs

shared/attributes.asciidoc
For https://github.com/elastic/apm-aws-lambda/issues/209.
=> Add APM AWS Lambda extension attr

shared/versions/stack/8.3.asciidoc
Do not merge until day of release.
=> Bumps version to 8.3.2

conf.yaml
Related to https://github.com/elastic/dev/issues/2020
=> Update conf.yaml for ECE 3.3.0 release

conf.yaml
Relates to https://github.com/elastic/elasticsearch/issues/76950
=> Switch from master to main for elasticsearch docs

shared/versions/stack/8.3.asciidoc
Do not merge until day of release.
=> Bumps version to 8.3.3

conf.yaml
New section on landing page: https://docs_2481.docs-preview.app.elstc.co/guide/index.html
New book: https://docs_2481.docs-preview.app.elstc.co/guide/en/elastic-platform-security/current/index.html
=> Add platform security guide

shared/versions/stack/8.4.asciidoc
Creates the `/stack/versions/8.4.asciidoc` file based on `master.asciidoc`
=> Add 8.4.0 version attributes

.rubocop.yml, conf.yaml, integtest/spec/all_books_spec.rb, lib/ES/Book.pm, schema.yaml
Fail if there is a branch in the 'live' list that is not also in the 'branches' list.
=> Verify that all 'live' branches actually exist

extra/docs_landing.html
=> Add what's new link to top of landing page

shared/attributes.asciidoc
This will help referring to these books from other documentation
=> Add attributes for various client library URLs

conf.yaml, doc_build_aliases.sh
For https://github.com/elastic/apm-mutating-webhook/issues/37.
=> add `elastic/apm-mutating-webhook` to the build

shared/versions/stack/7.17.asciidoc
=> Bump version to 7.17.6

conf.yaml
Merge on the release day - Aug 24
Related to https://github.com/elastic/dev/issues/2073
=> ECE - change current to 3.4.0

conf.yaml
Please do not merge. Please let the ECS team merge this at the appropriate time.
=> Updating ECS current for the 8.4 release

shared/versions/stack/8.5.asciidoc
This PR adds a new version attributes file
=> Add 8.5 version attributes file

resources/web/style/openapi.pcss, resources/web/styles.pcss
This PR is a first draft of a new stylesheet related to auto-generated API output
Relates to https://github.com/elastic/kibana/issues/137240
=> Add stylesheet for generated APIs

shared/attributes.asciidoc
This PR adds versioning to the shared attributes for the Welcome guide, since it will soon have multiple versions.
=> Add attributes for versioned welcome book

resources/web/docs_js/index.js, resources/web/template.html
Once the preview build finishes, this can be tested at https://docs_2525.docs-preview.app.elstc.co/guide/index.html
=> Add GA4 tracking information

conf.yaml
Bump the public notes to ms-80
=> Ms-80 release notes

shared/versions/stack/8.4.asciidoc
This PR updates the shared version attributes for an upcoming release
NOTE: This PR must not be merged until the appropriate release day
=> Update 8.4 version attributes

conf.yaml
For https://github.com/elastic/apm-aws-lambda/pull/328.
=> docs: add AWS changelog

conf.yaml
=> Updated master to main for enterprise-search-php and elasticsearch-php

conf.yaml
This PR adds the 7.17 branch to the Welcome Guide.
=> Add 7.17 branch to welcome guide

shared/versions/stack/7.17.asciidoc
This PR should not be merged until release day.
=> Update version details in 7.17.asciidoc

conf.yaml
=> Update current docs for ESS ms-82 release

conf.yaml
In preparation for the ECE 3.5..0 release
=> Deploy docs for ECE 3.5.0

resources/web/docs_js/index.js
Read these values from cookies; they will have been set elsewhere on elastic.co.
=> Include User ID and hashed IP in Google Analytics

extra/docs_landing.html
Relates to https://github.com/elastic/docs/pull/2547#issuecomment-1294047555
This PR updates the Elastic Stack information that sits behind the twistie on the docs landing page with the diagram and text from https://github.com/elastic/tech-content/pull/240
=> Update Elastic Stack information

resources/web/template.html
This snuck in as part of #2525
=> Remove Byte order mark

shared/attributes.asciidoc
Relates to https://github.com/elastic/kibana/issues/142776
=> Add Opgsgenie attribute

shared/versions/stack/8.6.asciidoc, shared/versions/stack/master.asciidoc
Relates to https://github.com/elastic/docs/pull/2565
=> Add version attributes for 8.6

conf.yaml, doc_build_aliases.sh, shared/attributes.asciidoc, shared/versions/stack/8.5.asciidoc, shared/versions/stack/master.asciidoc
* Closes https://github.com/elastic/docs/issues/2564
* For https://github.com/elastic/apm-agent-android/issues/28
=> add apm-agent-android to doc build

conf.yaml
Pointing the docs to the new release.
Release issue: https://github.com/elastic/ecctl/issues/599
=> Update config.yaml with new ecctl release 1.9

shared/versions/stack/7.17.asciidoc
This PR updates the shared version attributes for the 7.17 branch of the documentation.
*Do not merge until release day*
=> Update 7.17 version

extra/docs_landing.html
=> Updates SIEM card title

shared/attributes.asciidoc
Corrects [URL **path**](https://www.elastic.co/guide/en/enterprise-search-clients/enterprise-search-node/current/index.html)
=> Update Ent Search node attribute

conf.yaml
=> Add ingest architecture docs to build

conf.yaml
Make Curator 8.0 the current branch and add it to the list of branches.
(I made sure I pushed the fixes into the 8.0 branch this time 🙄)
=> Add Curator 8 docs

resources/asciidoctor/lib/chunker/breadcrumbs.rb, resources/asciidoctor/spec/chunker_spec.rb, resources/web/docs_js/index.js, resources/web/style/nav.pcss
=> Add dropdown for APM and ECS logging books

resources/asciidoctor/lib/chunker/breadcrumbs.rb
Follow up to https://github.com/elastic/docs/pull/2619.
=> Link APM/ECS breadcrumbs to first page

build_docs.pl, lib/ES/LinkCheck.pm
This reverts commit 698f9dd1d35bf365ceaa9356a5748e53ee3d07ac.
=> Revert "Test Elasticsearch's links (#2631)"

resources/web/air_gapped_template.html
For https://github.com/elastic/docs/issues/2640
=> attempt to fix air-gapped docs

extra/docs_landing.html
Updates the onboarding terminology on the Welcome to Elastic Docs page for 8.7.
Closes https://github.com/elastic/tech-content/issues/307
=> Updates the onboarding terminology for 8.7

conf.yaml, doc_build_aliases.sh
Required for https://github.com/elastic/observability-docs/pull/2854
=> add new dependency to obs-docs guide

shared/attributes.asciidoc
We are introducing new documentation for data lifecycle management (DLM) and we would like to have similar macros like we have for ILM.
Part of: https://github.com/elastic/elasticsearch/issues/93596
=> Add DLM related attributes

conf.yaml, shared/versions/stack/master.asciidoc
=> Adding ECS 8.8 for FF

conf.yaml, shared/versions/stack/8.8.asciidoc, shared/versions/stack/master.asciidoc
- Creates a new `/shared/versions/stack/8.8.asciidoc` file copied from `8.7.asciidoc`
- Updates the `master.asciidoc` to show the next version (8.9)
- Updates `conf.yaml` to include the 8.8 branch
=> Adds 8.8 to conf.yaml and the 8.8.0 attributes

extra/docs_landing.html
This will sync the landing page card with updated title proposed in https://github.com/elastic/tech-content/pull/329
=> Update title of Observability GS guide

conf.yaml, shared/versions/stack/8.7.asciidoc, shared/versions/stack/8.8.asciidoc, shared/versions/stack/current.asciidoc
Bumps the Docs version to 8.8.
=> Bumps version to 8.8

conf.yaml
Please do not merge. Please let the ECS team merge this at the appropriate time.
=> Updating ECS current for the 8.8 release

conf.yaml
This PR adds 8.9 branches to the conf.yaml file.
=> Update conf.yaml for 8.9 branches

conf.yaml, shared/versions/stack/master.asciidoc
Related: https://github.com/elastic/security-team/issues/7248
=> Prepare for ECS 8.10.0 release

conf.yaml
This PR adds a main branch to the `clients-team` repo in the conf.yml file of the docs build system.
=> Switch to main branch for clients-team in docs build

conf.yaml
Update docs to reference latest released `ecctl` version.
Release issue: https://github.com/elastic/ecctl/issues/608
=> ecctl 1.10 release: Update conf.yaml

.buildkite/pipeline.yml, .buildkite/scripts/build-docs.sh
=> Add Warn Broken Links build option

.buildkite/preview_cleaner_pipeline.yml, catalog-info.yaml
=> Add preview cleaner pipeline

shared/versions/stack/7.17.asciidoc, shared/versions/stack/8.10.asciidoc
=> Bump to 8.10.3 and 7.17.14

.buildkite/air_gapped_pipeline.yml, catalog-info.yaml
=> Add build air-gapped pipeline-132

.buildkite/air_gapped_pipeline.yml, .buildkite/preview_cleaner_pipeline.yml, .buildkite/scripts/clean_preview_branches.sh, .buildkite/scripts/publish_air_gapped_docs.sh, .buildkite/scripts/retry.sh, air_gapped/build_bk.sh, catalog-info.yaml, preview/clean.js
=> Migrate build air-gapped job 132

.buildkite/air_gapped_pipeline.yml, air_gapped/build_bk.sh
=> fix air-gapped env #132

.buildkite/pull-requests.json
=> add json file for pr bot #136

.buildkite/pr_main_mr_test.yml
=> add pr and merge condition to run a job #130

conf.yaml
Release issue: https://github.com/elastic/ecctl/issues/624
=> Update conf.yaml for `ecctl` 1.11.0 release

conf.yaml, shared/versions/stack/8.10.asciidoc, shared/versions/stack/8.11.asciidoc, shared/versions/stack/current.asciidoc
=> Release 8.11.0

extra/docs_landing.html
DO NOT MERGE UNTIL 15-NOV 8AM ET 
Adds serverless docs to the landing page.
=> Adds serverless to landing page

.github/CODEOWNERS
this should help with the PR review process as we're cranking quite a few
=> Add migration taskforce to code owners until BK migration is over

shared/versions/stack/8.11.asciidoc
=> Bump the docs to version 8.11.2

shared/versions/stack/7.17.asciidoc
=> Bump docs version to 7.17.16

shared/versions/stack/8.11.asciidoc
=> Bump the docs to version 8.11.3

conf.yaml, shared/versions/stack/8.12.asciidoc
=> Add 8.12 branch

.buildkite/scripts/compare_bk_jenkins_branches.sh
=> Set metadata

conf.yaml
For https://github.com/elastic/obs-docs-projects/issues/216
=> Move APM Guide docs to observability-docs repo

conf.yaml
ecctl release issue: https://github.com/elastic/ecctl/issues/637
=> Update conf.yaml for ecctl 1.12.0 release

.buildkite/build_pipeline.yml, .buildkite/build_pr_pipeline.yml, .buildkite/hooks/pre-command
=> Use bigger instance type for the full doc rebuild

extra/docs_landing.html
This PR adds cards for ECE and ECK on the Deploy tab of the landing page.
https://docs_bk_2890.docs-preview.app.elstc.co/guide/index.html
=> Add ECE and ECK to deploy tab on landing page

extra/docs_landing.html
This PR changes the labe on the tab from "Products" to "Platform"
=> Rename products tab

extra/docs_landing.html
This PR adds "Get started" links to the Solution cards on the landing page.
=> Add Solution get started links

.buildkite/build_pr_pipeline.yml, .buildkite/scripts/build_pr.sh, .buildkite/scripts/build_pr_commit_status.sh
This reverts commit 85d05d98a51b1c48ca5be1dbfd4a3c3781f6a5cf.
Reverting #2904 in an attempt to fix the BK builds on the elastic/docs repository.
=> Revert "Pass the --update-head-ok to fetch for PRs out of main (#2904)"

.buildkite/pull-requests.org-wide.json, conf.yaml, doc_build_aliases.sh, resources/asciidoctor/lib/chunker/obs_breadcrumbs.rb, shared/attributes.asciidoc, shared/versions/stack/7.17.asciidoc, shared/versions/stack/8.10.asciidoc, shared/versions/stack/8.11.asciidoc, shared/versions/stack/8.12.asciidoc, shared/versions/stack/8.5.asciidoc, shared/versions/stack/8.6.asciidoc, shared/versions/stack/8.7.asciidoc, shared/versions/stack/8.8.asciidoc, shared/versions/stack/8.9.asciidoc, shared/versions/stack/master.asciidoc
Content in https://github.com/elastic/ecs-logging-go-zerolog/pull/10
=> Add ecs-log-zerolog

.buildkite/pull-requests.org-wide.json
Note - it's hard to understand the change in the diff, but I did a sort of all the repos and consolidated all of them in the top configuration block.
=> Run CI for all PR changes for now - to enable Buildkite PR status check

catalog-info.yaml
=> Build every 1.5 hours

catalog-info.yaml
=> Clean-up the ci-docs-migration-taskforce team

catalog-info.yaml
=> Add employees perms to rebuild doc PR

resources/web/docs_js/utils.js
Contributes to https://github.com/elastic/docs/issues/2966
=> Updates utils.js by adding `PATCH` support

shared/versions/stack/8.13.asciidoc
=> Bumps the docs version to 8.13.1

shared/versions/stack/8.13.asciidoc
=> Bumps the docs version to 8.13.2

shared/versions/stack/7.17.asciidoc
=> Bumps the docs version to 7.17.20

build_docs.pl
The Elasticsearch reference docs links file formatted in json. That format makes extraction of links complicated, both on the docs side, and also in Elasticsearch needing to parse json. This commit adds support for a new tab delimited txt file where the Elasticsearch reference docs will move to.
relates elastic/elasticsearch#105813
=> Add support for Elasticsearch tab delimited links file

shared/versions/stack/7.17.asciidoc
=> Bumps the docs version to 7.17.21

shared/versions/stack/8.13.asciidoc
=> Bump the docs version to 8.13.4

conf.yaml, shared/versions/stack/8.13.asciidoc, shared/versions/stack/8.14.asciidoc, shared/versions/stack/current.asciidoc
=> Bump current to 8.14

README.asciidoc, resources/web/template.html
This PR updates a date in the licensing details that are added to each page.
=> Update license details

shared/versions/stack/8.14.asciidoc
=> Bump the docs version to 8.14.1

shared/versions/stack/7.17.asciidoc
=> Bumps the docs version to 7.17.22

shared/attributes.asciidoc
This PR updates the list of attributes to align with what's used in Serverless and to add some more generic management terms.
=> Add Stack management terms

lib/ES/Util.pm
=> Fixes failing test

shared/versions/stack/8.14.asciidoc
=> Bump the docs version to 8.14.2

shared/versions/stack/8.14.asciidoc
=> Bump the docs version to 8.14.3

conf.yaml, shared/versions/stack/8.14.asciidoc, shared/versions/stack/8.15.asciidoc, shared/versions/stack/current.asciidoc
=> Bumps current to 8.15.0

renovate.json
This repository doesn't gain any value from using Renovate, so we can be super clear that we want to opt out.
=> Explicitly opt out of Renovate

shared/versions/stack/8.15.asciidoc, shared/versions/stack/master.asciidoc
This PR adds version-specific API URL attributes for https://www.elastic.co/docs/api/doc/kibana
=> [DOCS] Add API URL attributes

shared/versions/stack/8.15.asciidoc
=> Bump the docs version to 8.15.1

shared/versions/stack/8.x.asciidoc
This PR adds a 8.x.asciidoc file with variables/attributes appropriate for that upcoming branch.
=> Add 8.x branch attributes

shared/versions/stack/7.17.asciidoc
=> Bump the docs version for 7.17.24

shared/versions/stack/8.15.asciidoc
=> Release 8.15.2

shared/attributes.asciidoc
This PR adds a variable/attribute related to [TheHive connector](https://www.elastic.co/guide/en/kibana/master/thehive-action-type.html)
=> Add variable for TheHive connector

conf.yaml
Adds new ecctl release to the docs (https://github.com/elastic/ecctl/issues/665)
=> Add new ecctl version 1.14.0

shared/versions/stack/8.15.asciidoc
=> Bumps the docs version to 8.15.3

conf.yaml
This PR changes the `live` and the `current` branches of the .NET book.
=> Changes current and live for .NET client book

shared/versions/stack/7.17.asciidoc
=> Bumps the docs version 7.17.25

shared/attributes.asciidoc
This PR adds a shared attribute for https://www.elastic.co/docs/api/doc/cloud-enterprise
=> Add api-ece variable

shared/versions/stack/8.15.asciidoc
=> Bump the docs version to 8.15.4

shared/versions/stack/8.16.asciidoc
Wait for confirmation from @dtylerElastic before merging.
Reverts elastic/docs#3118
=> Revert "Bumps the doc version to 8.16.1"

shared/versions/stack/8.15.asciidoc
=> Bump the docs version to 8.15.5

shared/versions/stack/7.17.asciidoc
=> 7.17.26 version bump

conf.yaml, shared/versions/stack/8.16.asciidoc, shared/versions/stack/8.17.asciidoc, shared/versions/stack/current.asciidoc
=> Bumps current to 8.17

conf.yaml
⚠️  Do not merge until https://github.com/elastic/search-ui/pull/1097 is merged and the changes are live on the [production site](https://www.elastic.co/guide/en/search-ui/current/overview.html). ⚠️
=> Start indexing search ui book

shared/versions/stack/8.16.asciidoc
=> Bumps the docs version to 8.16.2

shared/versions/stack/7.17.asciidoc
=> Bumps the docs version to 7.17.27

shared/versions/stack/8.16.asciidoc
Relates to https://github.com/elastic/dev/issues/2960
=> docs version bump to 8.16.3

shared/versions/stack/8.17.asciidoc
Relates to https://github.com/elastic/dev/issues/2961
=> docs version bump to 8.17.1

conf.yaml, doc_build_aliases.sh
Builds content needed for new docs IA
**PREVIEW:** https://docs_bk_3159.docs-preview.app.elstc.co/guide/en/ingest-overview/current/ingest-intro.html
=> Add ingest overview content set

shared/versions/stack/8.16.asciidoc
=> Bump the docs version to 8.16.4

shared/versions/stack/7.17.asciidoc
=> Bump the docs version to 7.17.28

shared/versions/stack/8.17.asciidoc
=> Bumps Docs to 8.17.3

shared/versions/stack/8.17.asciidoc
=> Bumps docs version to 8.17.3

shared/versions/stack/8.16.asciidoc
=> Bumps Docs to 8.16.5

shared/versions/stack/8.16.asciidoc
=> Bump the docs version to 8.16.6

shared/versions/stack/8.17.asciidoc
=> Bumps the docs version to 8.17.5

shared/versions/stack/8.17.asciidoc
Docs release issue: https://github.com/elastic/dev/issues/3137
=> 8.17.6 docs version bump

shared/versions/stack/8.18.asciidoc
=> Bump the docs version to 8.18.1

shared/versions/stack/8.17.asciidoc
=> Bumps version to 8.17.8

shared/versions/stack/8.17.asciidoc
=> Bumps version to 8.17.9

shared/versions/stack/8.19.asciidoc, shared/versions/stack/master.asciidoc
=> bump 8.19 to 8.19.1

shared/versions/stack/8.19.asciidoc
=> Bumps the docs version from 8.19.2 to 8.19.3

shared/versions/stack/8.18.asciidoc
=> Bumps the docs version from 8.18.6 to 8.18.7

shared/versions/stack/8.18.asciidoc
Doc release ticket: https://github.com/elastic/dev/issues/3314
=> Bump doc version to 8.18.8
